### PR TITLE
Adds word wrap functionality

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This addresses https://github.com/ansible/awx/issues/5895#issuecomment-600801479

PF issue filed https://github.com/patternfly/patternfly-react/issues/3938

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
9.2
```

##### ADDITIONAL INFORMATION
Screen Shot 2020-03-19 at 12 47 46 PM

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by dsesami** [comment]
Can we wrap these little breadcrumbs:
Screenshot from 2020-03-24 11-22-12

**Review by dsesami — APPROVED** [review]
breadcrumbs are pf-dependent, so im approving this and putting an issue in PF.

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
:middle_finger: :middle_finger: :middle_finger: regate :middle_finger: :middle_finger: :middle_finger:

**Pull request merged**
