### PR TITLE
Rename Automation Insights to Automation Analytics.

### PR DESCRIPTION
**Pull request by wenottingham**
Fix user-facing code, don't worry about settings names.

### CODE REVIEW

**Comment by wenottingham** [comment]
recheck

**Comment by wenottingham** [comment]
recheck

**Comment by jlmitch5** [comment]
I went through and found a few other references to insights that bubble up as strings to the user.  I believe this is all (aside from the "insights" credential name, and the insights settings.py var names, but that's a lot more in the weeds than user-facing strings).

https://github.com/ansible/awx/blob/devel/awx/ui/client/src/inventories-hosts/hosts/host.form.js#L115
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/inventories-hosts/inventories/insights/plan-filter.js#L10
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.form.js#L125
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/inventories-hosts/inventories/related/hosts/related-host.list.js#L99
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/inventories-hosts/inventories/standard-inventory/inventory.form.js#L51
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/inventories-hosts/inventory-hosts.strings.js#L27
https://github.com/ansible/awx/blob/devel/awx/ui/client/src/license/license.partial.html#L193

**Comment by wenottingham** [comment]
All the inventory ones are about the Insights integration for pulling playbooks from Red Hat Insights... they can stay.

**Review by AlexSCorey — APPROVED** [review]
Looks good to me.

**Pull request merged**
