### PR TITLE
Remove redundant available_instances field

### PR DESCRIPTION
**Pull request by rooftopcellist**
##### SUMMARY
Replaces: https://github.com/ansible/awx/pull/8703

Remove unneeded field.  

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
Nice!  If you throw this through an integration run and things look ✅, I'd say :shipit:!

**Comment by rooftopcellist** [comment]
Integration passed!  _merging_

**Comment by rooftopcellist** [comment]
regate

**Comment by rooftopcellist** [comment]
recheck

**Pull request merged**
