### PR TITLE
Restore UI license checker

### PR DESCRIPTION
**Pull request by wenottingham**
https://github.com/ansible/awx/commit/27219d34eb92fc63495237cc722836688b5264d8 removed the license checker for UI dependencies as part of removing the UI. We actually still need it, just pointed at the new UI.

This brings it back, and updates it to do so. It also removes no longer needed license files.

It doesn't *pass* yet, as I haven't added licenses for the new UI dependencies in this PR. Hi @jakemcdermott.

### CODE REVIEW

**Comment by jakemcdermott** [comment]
:+1: :+1:

**Comment by jakemcdermott** [comment]
https://github.com/ansible/awx/issues/8647

**Comment by unlikelyzero** [comment]
No QA

**Comment by ryanpetrello** [comment]
@jakemcdermott @wenottingham what's the status of this PR?

**Comment by wenottingham** [comment]
Needs updated with the actual UI license text files.

**Comment by unlikelyzero** [comment]
@wenottingham what's the status on this one

**Comment by wenottingham** [comment]
Needs UI engineering to add the missing license files.

**Comment by wenottingham** [comment]
@jakemcdermott assorted script-ish license fetching done, plz review.

**Review by jakemcdermott — APPROVED** [review]

**Pull request merged**
