### PR TITLE
Add shortcut for running integration tests

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
I was just about to lose my mind over the workflow to run a single integration target for the AWX collection.

My position here is that developers should never have to change directories to run tests. So far, `ansible-test` forces that. Even if you disagree on that point, it won't let me turn off the cows (I refuse to uninstall cowsay), or [customize junit data](https://github.com/ansible/ansible/issues/68365).

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - AWX collection

##### AWX VERSION
```
9.3.0
```

##### ADDITIONAL INFORMATION
You could also say that `make test_ansible_integration` suffers from a critical shortcoming that it won't take a parameter for the test. I'd rather address the other problems at the same time.

I went through several iterations of `include_role`, `include_tasks`, and adhoc calling the role. There's no way to get that to work with collections _if_ the role does not use the FQCN task names (which is not an option for us). Some options (such as PATH customizations) get as far as _trying_ to run the task but failing on import. We use relative imports, and I wasn't interested enough to test FQCN imports, because that's also not an option for us. This, also, really seems like it should be an Ansible core issue, but it's a significant effort to nail down expectations and articulate one of those particular scenarios.

example:

```
$ ansible-playbook awx_collection/tools/integration.yml -e test=tower_role
[WARNING]: You are running the development version of Ansible. You should only run Ansible from "devel" if you are modifying the Ansible engine, or trying out features under
development. This is a rapidly changing source of code and can become unstable at any point.
[WARNING]: provided hosts list is empty, only localhost is available. Note that the implicit localhost does not match 'all'

PLAY [localhost] ********************************************************************************************************************************************************************

TASK [Include all targets] **********************************************************************************************************************************************************
skipping: [localhost] => (item=demo_data) 
skipping: [localhost] => (item=tower_inventory) 
skipping: [localhost] => (item=tower_job_cancel) 
skipping: [localhost] => (item=tower_host) 
skipping: [localhost] => (item=tower_role) 
skipping: [localhost] => (item=tower_credential) 
skipping: [localhost] => (item=tower_job_launch) 
skipping: [localhost] => (item=tower_job_list) 
skipping: [localhost] => (item=tower_user) 
skipping: [localhost] => (item=tower_project_manual) 
skipping: [localhost] => (item=tower_job_template) 
skipping: [localhost] => (item=tower_settings) 
skipping: [localhost] => (item=tower_team) 
skipping: [localhost] => (item=tower_notification) 
skipping: [localhost] => (item=tower_inventory_source) 
skipping: [localhost] => (item=tower_job_wait) 
skipping: [localhost] => (item=tower_label) 
skipping: [localhost] => (item=tower_credential_type) 
skipping: [localhost] => (item=tower_send) 
skipping: [localhost] => (item=tower_organization) 
skipping: [localhost] => (item=tower_group) 
skipping: [localhost] => (item=tower_project) 
skipping: [localhost] => (item=tower_receive) 
skipping: [localhost] => (item=tower_workflow_template) 
skipping: [localhost] => (item=demo_data/tasks) 
skipping: [localhost] => (item=demo_data/tasks/main.yml) 
skipping: [localhost] => (item=tower_inventory/tasks) 
skipping: [localhost] => (item=tower_inventory/tasks/main.yml) 
skipping: [localhost] => (item=tower_job_cancel/tasks) 
skipping: [localhost] => (item=tower_job_cancel/tasks/main.yml) 
skipping: [localhost] => (item=tower_host/tasks) 
skipping: [localhost] => (item=tower_host/tasks/main.yml) 
skipping: [localhost] => (item=tower_role/tasks) 
skipping: [localhost] => (item=tower_credential/tasks) 
skipping: [localhost] => (item=tower_credential/tasks/main.yml) 
skipping: [localhost] => (item=tower_job_launch/tasks) 
skipping: [localhost] => (item=tower_job_launch/tasks/main.yml) 
skipping: [localhost] => (item=tower_job_list/tasks) 
skipping: [localhost] => (item=tower_job_list/tasks/main.yml) 
skipping: [localhost] => (item=tower_user/tasks) 
skipping: [localhost] => (item=tower_user/tasks/main.yml) 
skipping: [localhost] => (item=tower_project_manual/tasks) 
skipping: [localhost] => (item=tower_project_manual/tasks/create_project_dir.yml) 
skipping: [localhost] => (item=tower_project_manual/tasks/main.yml) 
skipping: [localhost] => (item=tower_job_template/tasks) 
skipping: [localhost] => (item=tower_job_template/tasks/main.yml) 
skipping: [localhost] => (item=tower_settings/tasks) 
skipping: [localhost] => (item=tower_settings/tasks/main.yml) 
skipping: [localhost] => (item=tower_team/tasks) 
skipping: [localhost] => (item=tower_team/tasks/main.yml) 
skipping: [localhost] => (item=tower_notification/tasks) 
skipping: [localhost] => (item=tower_notification/tasks/main.yml) 
skipping: [localhost] => (item=tower_inventory_source/tasks) 
skipping: [localhost] => (item=tower_inventory_source/tasks/main.yml) 
skipping: [localhost] => (item=tower_job_wait/tasks) 
skipping: [localhost] => (item=tower_job_wait/tasks/main.yml) 
skipping: [localhost] => (item=tower_label/tasks) 
skipping: [localhost] => (item=tower_label/tasks/main.yml) 
skipping: [localhost] => (item=tower_credential_type/tasks) 
skipping: [localhost] => (item=tower_credential_type/tasks/main.yml) 
skipping: [localhost] => (item=tower_send/tasks) 
skipping: [localhost] => (item=tower_send/tasks/main.yml) 
skipping: [localhost] => (item=tower_organization/tasks) 
skipping: [localhost] => (item=tower_organization/tasks/main.yml) 
skipping: [localhost] => (item=tower_group/tasks) 
skipping: [localhost] => (item=tower_group/tasks/main.yml) 
skipping: [localhost] => (item=tower_project/tasks) 
skipping: [localhost] => (item=tower_project/tasks/main.yml) 
skipping: [localhost] => (item=tower_receive/tasks) 
skipping: [localhost] => (item=tower_receive/tasks/main.yml) 
skipping: [localhost] => (item=tower_workflow_template/tasks) 
skipping: [localhost] => (item=tower_workflow_template/tasks/main.yml) 
included: /Users/alancoding/Documents/tower/awx_collection/tests/integration/targets/tower_role/tasks/main.yml for localhost

TASK [Generate names] ***************************************************************************************************************************************************************
ok: [localhost]

TASK [Create a User] ****************************************************************************************************************************************************************
changed: [localhost]

TASK [assert] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Add Joe to the update role of the default Project] ****************************************************************************************************************************
changed: [localhost] => (item=present)
changed: [localhost] => (item=absent)
[DEPRECATION WARNING]: This module is being moved to a different collection. Instead of awx.awx it will be migrated into awx.tower_cli. This feature will be removed in version 3.7.
 Deprecation warnings can be disabled by setting deprecation_warnings=False in ansible.cfg.

TASK [assert] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Create a workflow] ************************************************************************************************************************************************************
ok: [localhost]

TASK [Add Joe to workflow execute role] *********************************************************************************************************************************************
changed: [localhost]

TASK [assert] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

TASK [Delete a User] ****************************************************************************************************************************************************************
changed: [localhost]

TASK [assert] ***********************************************************************************************************************************************************************
ok: [localhost] => {
    "changed": false,
    "msg": "All assertions passed"
}

PLAY RECAP **************************************************************************************************************************************************************************
localhost                  : ok=11   changed=4    unreachable=0    failed=0    skipped=0    rescued=0    ignored=0   
```
(this is with AWX devel)

### CODE REVIEW

**Comment by squidboylan** [comment]
I'm a little worried about providing a way to run tests that isnt `ansible-test` because we might end up debugging why things work in one place and not the other. We could instead run `ansible-test` in the faux-install location

**Comment by AlanCoding** [comment]
> We could instead run ansible-test in the faux-install location

There are 2 problems with this - there is no location for the faux-install. That location _is_ the awx_collection folder, which is symlinked to `~/.ansible/collections/ansible_collections/awx/awx`. That's the folder you run from, so you're right back to the source folder. Second problem, even you write more complicated hacks to attempt this, `ansible-test` just flatly doesn't work with symlinks.

**Comment by AlanCoding** [comment]
@squidboylan I added a parameter

https://github.com/ansible/awx/blob/08bd445caff0df26c86bfcafcbf6f2c3fbe89561/Makefile#L409

So the use case here is `make test_collection_integration COLLECTION_TEST_TARGET=demo_data`. I'm still not fully happy with this, but it's better than nothing, closing this b/c there is too much in flight.

**Comment by AlanCoding** [comment]
https://gist.github.com/AlanCoding/2adb1590489912233117aa572b44b85a

**Pull request closed without merging**
