### PR TITLE
Do not remove edges from other inventory sources

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Our "SYNC ALL" functionality in inventories has been plagued with significant cross-inventory-source interference problems.

This attempts to institute the most basic rules of non-interferences within the logic for building relationships (edges) group-to-groups (parent/child) and groups-to-hosts.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
3.0.0
```

##### ADDITIONAL INFORMATION
Steps:

 - Take a large AWS account
 - create 4 groups, all within different regions
 - SYNC ALL in the UI

Inspect the line for "group-group and group-host deletions"

After this change, I get 0 relationships modified. Before this change, I got a whole lot of relationships modified.

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
Man, this was really hairy - thanks for digging into this and understanding this problem.

**Review by matburt — APPROVED** [review]

**Review by chrismeyersfsu — APPROVED** [review]
Approved, but my spidey sense is tingling for same-named groups in the same inventory but different inventory sources.

**Comment by AlanCoding** [comment]
> Approved, but my spidey sense is tingling for same-named groups in the same inventory but different inventory sources.

I was about half-way through a reply disagreeing with you, but then I saw it.

I got groups from `self.all_group.all_groups.keys()`, but I got hosts from `self.inventory_source.hosts.values_list('pk', flat=True)`.

The difference is extremely subtle, but we really need to exercise the utmost caution here. The groups it is using is the set of _new_ groups, whereas the set of hosts is the _old_ set of hosts.

The logic for inventory updates loading into database can be separated into several distinct stages, and this is very unambiguously in the stage where it deletes old data which was not returned from `ansible-inventory`.

~For these purposes, we need to filter hosts & groups based on what was present in the **old** data.~

~Just like we shared a common query with `_delete_hosts`, we need to consolidate the `self.inventory_source.groups.all()` query with the `_delete_groups` method. The pattern should be very clear once I get it in. Otherwise we might try to delete relationships with non-existent children.~

I wrote all that, but I was wrong again! Do you see it? Why did using the new data ever seem sensible? Because of the order of operations of the deletion stage.

```python
        if self.overwrite:
            self._delete_hosts()
            self._delete_groups()
            self._delete_group_children_and_hosts()
```

If a group was present in the old data, but not present in the new data then it should be obvious that `_delete_groups` already deleted that group by the time that we're at this method.

Confusingly, this means that it might not actually matter whether we use the old hosts & groups or the new hosts & groups. I do agree that it's much harder to follow if I use the old values for hosts, but new values for groups. I think I did so as a matter of convenience. Groups only have names, whereas the unique identifier for hosts could be name or instance_id, or both (no really, I'm actually not sure in the case of conflicts). By using old values, the primary key becomes the host unique identifier, and that's that.

So even though it would be a non-functional change, I do agree that it would be better to switch to using the **old** values for the group pk set.

**Comment by AlanCoding** [comment]
I really thought about this a lot - I think I don't want to change this after all.

Groups and hosts are just different here, because we do group accounting based on names, and this doesn't jive how we do it in other places. The new vs. old values should behave the same, and we can't do this based off the old values without additional queries.

**Pull request merged**
