### PR TITLE
record the receptor unit ID on the job record for debugging purposes

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/8641

image

### CODE REVIEW

**Comment by AlanCoding** [comment]
This won't be in the actual job environment, will it?

**Comment by AlanCoding** [comment]
I think I've confirmed that (via https://github.com/ansible/test-playbooks/pull/153)

My thought was that a new `UnifiedJob` field would be a less confusing way to present that. Aside from system jobs, workflow jobs, and approval jobs, I think that all job types should have this non-blank.

**Comment by ryanpetrello** [comment]
@AlanCoding it won't, no.  This JSON blob was just a convenient place to store the data without having to resort to a new column on a table that tends to be very large (schema changes on this table tend to be quite expensive).

If you all don't like this approach, that's fine, though.  I figured this PR was a cheap way to get us what we needed for debugging.

**Review by shanemcd — APPROVED** [review]
We will eventually probably need this in its own database column, but I think this is fine for now.

**Pull request merged**
