### PR TITLE
Roll back PF deps upgrade to re-enable select input typing.

### PR DESCRIPTION
**Pull request by kialam**
##### SUMMARY

Roll back previous PF update.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
19.4.0
```

### CODE REVIEW

**Review by AlexSCorey — APPROVED** [review]
Looks good to me.

**Review by nixocio — APPROVED** [review]

**Comment by nixocio** [comment]
Lets make sure that visual tests and e2e are 🟢. I triggered visual and e2e test run earlier today.

**Comment by akus062381** [comment]
question- would this fix not address the problem with adding labels in the WFJT creation form?

**Comment by nixocio** [comment]
> question- would this fix not address the problem with adding labels in the WFJT creation form?

This fix should address the problem reported on https://github.com/ansible/awx/issues/11224

**Comment by akus062381** [comment]
@nixocio @kialam I just want to make sure, because I am still seeing the error adding labels in WFJT. But if this PR is not meant to address that problem, please let me know.

**Comment by kialam** [comment]
@akus062381 this PR _should_ restore that functionality. I tested it locally before putting up the PR:
wf_tags

**Review by akus062381 — APPROVED** [review]

**Review by tiagodread — APPROVED** [review]

**Review by InnocentK — APPROVED** [review]
Looks good

**Comment by tiagodread** [comment]
For some reason, running e2e tests from awx is not working I triggered a manual run and here was the result for functional tests https://dashboard.cypress.io/projects/ui2mq7/runs/9874/overview

**Pull request merged**
