### PR TITLE
Do not translate FR variables in notifications

### PR DESCRIPTION
**Pull request by rverchere**
Signed-off-by: Rémi VERCHERE <remi.verchere@axians.com>

##### SUMMARY

`{{ job_friendly_name }}` variable should not be translated in FR

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
awx: 14.0.0
```

##### ADDITIONAL INFORMATION
Just a quick translation fix ;)

### CODE REVIEW

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
The post failure was fixed by https://github.com/ansible/zuul-config/pull/92

**Comment by ryanpetrello** [comment]
Hey @rverchere, thanks for this.  We actually manage the generation of these files via a system that tracks the translation strings as the source of truth, so we'll have to update it there. I'll reach out to the folks in charge of that and let them know.

cc @docschick @rooftopcellist @rh-tchuang

**Comment by rverchere** [comment]
> Hey @rverchere, thanks for this. We actually manage the generation of these files via a system that tracks the translation strings as the source of truth, so we'll have to update it there. I'll reach out to the folks in charge of that and let them know.
> 
> cc @docschick @rooftopcellist @rh-tchuang

Hi, no problem. How can I help for translation, any contribution guide for this ?
Thanks!

**Pull request closed without merging**
