### PR TITLE
Add Rocket.Chat notification type

### PR DESCRIPTION
**Pull request by theblazehen**
##### SUMMARY
Add Rocket.Chat notification type

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
# make VERSION
awx: 1.0.4.98
```

### CODE REVIEW

**Comment by wenottingham** [comment]
Any chance you could add tests for this?

**Comment by theblazehen** [comment]
@wenottingham I may be missing something, but I've based this on the Mattermost code, and there doesn't appear to be any tests there?

**Comment by wenottingham** [comment]
Yeah, we probably should have asked for tests when that one was merged too. Alas. 

I'm just leery of things that we won't catch when they break.

**Comment by theblazehen** [comment]
@wenottingham It appears as if the one test failed due to a networking issue, `https://rpm.nodesource.com/pub_6.x/el/7/x86_64/repodata/repomd.xml: [Errno 14] curl#35 - "TCP connection reset by peer"`, is it possible to run it again?

**Comment by ryanpetrello** [comment]
Hey @theblazehen, the easiest way is to force push an amended commit.

```
~ git commit --amend --no-edit
~ git push -f origin devel
```

**Review by ryanpetrello — APPROVED** [review]
Once the tests pass, the Python bits of this get a 👍 from me; I'll find somebody to review the UI code, too.

Thanks for writing tests, and for contributing this!

**Review by mabashian — COMMENTED** [review]
UI changes look good to me

**Review by matburt — APPROVED** [review]

**Pull request merged**
