### PR TITLE
stop hard-coding the awx version in the isolated development environment

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/296

### CODE REVIEW

**Comment by AlanCoding** [comment]
Verified brutally:

```
$ docker start tools_isolated_1
tools_isolated_1
$ echo "__version__ = '`python setup.py --version`'" | docker exec -i tools_isolated_1 /bin/bash -c "cat > /venv/awx/lib/python2.7/site-packages/awx.py"
$ docker exec -i tools_isolated_1 /bin/bash -c "echo 'import awx;print awx.__version__' | /venv/awx/bin/python"
1.0.0
```

However, I do still have a concern. The latest tag is 1.0.1, and my source tree is up to date. You might want to hold off for a second, and I will get the server running and cross-check against the UI and /ping/ endpoint.

**Review by matburt — APPROVED** [review]
lgtm

**Comment by AlanCoding** [comment]
Ping reports

```
1.0.0-718-g5924571
```

For the controller node, so given that the versions before the `-` match, this should check out.

Also, I realized I needed to do:

```
git fetch tags
```

That causes the version to be bumped when doing `python setup.py --version`. However, the heartbeat, ping, and config endpoints have still not updated, and I don't know why.

**Comment by AlanCoding** [comment]
ok, restarting bumped me to 1.0.1, so that's why. It was just stale in-memory.

**Review by AlanCoding — APPROVED** [review]

**Comment by matburt** [comment]
celery doesn't (usually) successfully restart itself with changed files :/

**Comment by ryanpetrello** [comment]
Well, the reason @AlanCoding needed to restart was that the *new* tag didn't automatically trigger the process that installs the awx egg/package - that only happens when you run the make target and start the containers (which is probably good enough - the package version number doesn't change *that* often, and I think it's reasonable to expect you'd have to restart the containers to see that change take effect).

**Pull request merged**
