### PR TITLE
tools/scripts/firehose.py: capture all job ids, attach events to all jobs ids and distribute the events

### PR DESCRIPTION
**Pull request by mcharanrm**
##### SUMMARY

There are 3 changes made to improve the following things

1. Create the no.of event rows given on the command line. 
2. Add events to all the Jobs
3. Distribute the events over the days delta.
4. Remove command line options --jobs, --events, --hours-delta
5. Add new command line options --jobs-per-hour, --events-per-job 
```
#Total events = days_delta * 24 * jobs/h * events/j
#Defaults = 1 Billion events, 31 days

#events/day = 32258064.51612903
#events/hour = 1344086.0416666667 =~ 1M + events per hour 
#events/job = 1344.087 Assuming 1000 jobs in a Hour 
#events/job = 13440.87 Assuming 100 jobs in a Hour
```

##### ISSUE TYPE

 - Feature Pull Request

I happened to see more events are created (8000 events instead of 100) during my testing. we are always returning event rows in the multiples of 1000 when `self.rows > 1` instead of returning `self.rows`.

```
        elif self.rows >= 1 and self.rows < 1000:
            event_rows = self.rowlist[random.randrange(len(self.rowlist))] * self.rows
            self.rows -= self.rows
            return event_rows
```

> 2. Add events to all the Jobs

Previously we generate all the jobs and capture last job id. And then we attach all the events to last job id. With the change we capture all the job ids and attach certain no.of events to all the job ids

```
       created, jt_pos = make_batch(min(jobs, batch_size), jt_pos)
        created, jt_pos, ujs_pk = make_batch(min(jobs, batch_size), jt_pos)
        print('took {}'.format(time() - s_loop))
        i += 1
        jobs -= batch_size
    return created
        created_job_ids += ujs_pk
    print('Creted Job IDS: {}'.format(created_job_ids))
    #return created
    return created_job_ids
```

> 3. Distribute the events over the days.

Previously we generate all the events on a particular day. And if we wanted to create events for multiple days, a `bash for loop` was used. Due to that, drop and create indexes code block will be repeated for multiple times. Changes made in such a way that it drop indexes and constraints of `main_jobevent` table before attaching events and repeat the process of attaching new event rows couple of times and reattach the indexes and constraints back to `main_jobevent` at the end.

##### TEST EXECUTION
```
[<test-host>]# ./firehose.py --jobs-per-hour 1 --events-per-job 100 --days-delta 1
removing indexes and constraints
DROP INDEX IF EXISTS main_jobevent_created_idx
DROP INDEX IF EXISTS main_jobevent_job_id_parent_uuid_idx
DROP INDEX IF EXISTS main_jobevent_host_id_idx
DROP INDEX IF EXISTS main_jobevent_job_id_end_line_idx
DROP INDEX IF EXISTS main_jobevent_job_id_brin_idx
DROP INDEX IF EXISTS main_jobevent_job_id_uuid_idx
DROP INDEX IF EXISTS main_jobevent_job_id_event_idx
DROP INDEX IF EXISTS main_jobevent_job_id_start_line_idx
ALTER TABLE main_jobevent DROP CONSTRAINT IF EXISTS main_jobevent_verbosity_check
inserting 1 job(s)
running batch 1, runtime 1.1920928955078125e-06
took 0.047708988189697266
Creted Job IDS: [3807]
attaching 100 events to job 3807
generating unique start/end line counts
2021-02-19T14:48:30.382628
inserting 1 job(s)
running batch 1, runtime 5.0067901611328125e-06
took 0.022481918334960938
Creted Job IDS: [3808]
attaching 100 events to job 3808
generating unique start/end line counts
2021-02-19T14:48:32.231270
inserting 1 job(s)
running batch 1, runtime 5.4836273193359375e-06
took 0.019299745559692383
Creted Job IDS: [3809]
attaching 100 events to job 3809
generating unique start/end line counts
2021-02-19T14:48:34.079990
inserting 1 job(s)
running batch 1, runtime 5.245208740234375e-06
took 0.019356966018676758
Creted Job IDS: [3810]
attaching 100 events to job 3810
generating unique start/end line counts
2021-02-19T14:48:35.923016
inserting 1 job(s)
running batch 1, runtime 5.245208740234375e-06
took 0.018933534622192383
Creted Job IDS: [3811]
attaching 100 events to job 3811
generating unique start/end line counts
2021-02-19T14:48:38.250596
inserting 1 job(s)
running batch 1, runtime 5.245208740234375e-06
took 0.024649381637573242
Creted Job IDS: [3812]
attaching 100 events to job 3812
generating unique start/end line counts
2021-02-19T14:48:40.458194
inserting 1 job(s)
running batch 1, runtime 6.4373016357421875e-06
took 0.02432560920715332
Creted Job IDS: [3813]
attaching 100 events to job 3813
generating unique start/end line counts
2021-02-19T14:48:42.307213
inserting 1 job(s)
running batch 1, runtime 5.0067901611328125e-06
took 0.018409013748168945
Creted Job IDS: [3814]
attaching 100 events to job 3814
generating unique start/end line counts
2021-02-19T14:48:44.179888
inserting 1 job(s)
running batch 1, runtime 5.9604644775390625e-06
took 0.018113374710083008
Creted Job IDS: [3815]
attaching 100 events to job 3815
generating unique start/end line counts
2021-02-19T14:48:46.064803
inserting 1 job(s)
running batch 1, runtime 5.245208740234375e-06
took 0.018368959426879883
Creted Job IDS: [3816]
attaching 100 events to job 3816
generating unique start/end line counts
2021-02-19T14:48:47.895369
inserting 1 job(s)
running batch 1, runtime 5.7220458984375e-06
took 0.023639202117919922
Creted Job IDS: [3817]
attaching 100 events to job 3817
generating unique start/end line counts
2021-02-19T14:48:49.911893
inserting 1 job(s)
running batch 1, runtime 5.4836273193359375e-06
took 0.018483400344848633
Creted Job IDS: [3818]
attaching 100 events to job 3818
generating unique start/end line counts
2021-02-19T14:48:51.754557
inserting 1 job(s)
running batch 1, runtime 5.9604644775390625e-06
took 0.022894859313964844
Creted Job IDS: [3819]
attaching 100 events to job 3819
generating unique start/end line counts
2021-02-19T14:48:54.069882
inserting 1 job(s)
running batch 1, runtime 5.4836273193359375e-06
took 0.024121522903442383
Creted Job IDS: [3820]
attaching 100 events to job 3820
generating unique start/end line counts
2021-02-19T14:48:56.253730
inserting 1 job(s)
running batch 1, runtime 5.4836273193359375e-06
took 0.01886773109436035
Creted Job IDS: [3821]
attaching 100 events to job 3821
generating unique start/end line counts
2021-02-19T14:48:58.090876
inserting 1 job(s)
running batch 1, runtime 6.67572021484375e-06
took 0.01830005645751953
Creted Job IDS: [3822]
attaching 100 events to job 3822
generating unique start/end line counts
2021-02-19T14:48:59.909731
inserting 1 job(s)
running batch 1, runtime 7.62939453125e-06
took 0.018251419067382812
Creted Job IDS: [3823]
attaching 100 events to job 3823
generating unique start/end line counts
2021-02-19T14:49:01.968200
inserting 1 job(s)
running batch 1, runtime 5.245208740234375e-06
took 0.018181800842285156
Creted Job IDS: [3824]
attaching 100 events to job 3824
generating unique start/end line counts
2021-02-19T14:49:04.152043
inserting 1 job(s)
running batch 1, runtime 5.9604644775390625e-06
took 0.023064613342285156
Creted Job IDS: [3825]
attaching 100 events to job 3825
generating unique start/end line counts
2021-02-19T14:49:06.168388
inserting 1 job(s)
running batch 1, runtime 5.7220458984375e-06
took 0.0180203914642334
Creted Job IDS: [3826]
attaching 100 events to job 3826
generating unique start/end line counts
2021-02-19T14:49:08.214632
inserting 1 job(s)
running batch 1, runtime 5.9604644775390625e-06
took 0.018720626831054688
Creted Job IDS: [3827]
attaching 100 events to job 3827
generating unique start/end line counts
2021-02-19T14:49:10.427800
inserting 1 job(s)
running batch 1, runtime 5.4836273193359375e-06
took 0.0250699520111084
Creted Job IDS: [3828]
attaching 100 events to job 3828
generating unique start/end line counts
2021-02-19T14:49:12.720686
inserting 1 job(s)
running batch 1, runtime 6.198883056640625e-06
took 0.018234729766845703
Creted Job IDS: [3829]
attaching 100 events to job 3829
generating unique start/end line counts
2021-02-19T14:49:14.767415
inserting 1 job(s)
running batch 1, runtime 4.76837158203125e-06
took 0.018674135208129883
Creted Job IDS: [3830]
attaching 100 events to job 3830
generating unique start/end line counts
2021-02-19T14:49:17.100879
2021-02-19T14:49:17.101059
restoring indexes and constraints (this may take awhile)
CREATE INDEX main_jobevent_created_idx ON public.main_jobevent USING btree (created)
CREATE INDEX main_jobevent_job_id_parent_uuid_idx ON public.main_jobevent USING btree (job_id, parent_uuid)
CREATE INDEX main_jobevent_host_id_idx ON public.main_jobevent USING btree (host_id)
CREATE INDEX main_jobevent_job_id_end_line_idx ON public.main_jobevent USING btree (job_id, end_line)
CREATE INDEX main_jobevent_job_id_brin_idx ON public.main_jobevent USING brin (job_id)
CREATE INDEX main_jobevent_job_id_uuid_idx ON public.main_jobevent USING btree (job_id, uuid)
CREATE INDEX main_jobevent_job_id_event_idx ON public.main_jobevent USING btree (job_id, event)
CREATE INDEX main_jobevent_job_id_start_line_idx ON public.main_jobevent USING btree (job_id, start_line)
ALTER TABLE main_jobevent ADD CONSTRAINT main_jobevent_verbosity_check CHECK (verbosity >= 0)
2021-02-19T14:49:24.779358
```

We are suppose to see 2400 events but 2496 events is results of using `num_events = math.ceil(events / num_procs)`. If we use `math.floor(events / num_procs)` we end up insert 96 events less than the actual. 

```
awx=> select min(id),max(id) from main_jobevent where job_id = 3806;
   min   |   max   
---------+---------
 3740889 | 3740992
(1 row)

awx=> select min(id),max(id),count(*) from main_jobevent where job_id > 3806;
   min   |   max   | count 
---------+---------+-------
 3740993 | 3743488 |  2496

```

### CODE REVIEW

**Comment by kdelee** [comment]
On a qualitative level, I like all the changes made -- especially distributing the events over the jobs, and then distributing the jobs over days/hours.

Using the defaults of:

```
#Total events = days_delta * 24 * jobs/h * events/j
#Defaults = 1 Billion events, 31 days

#events/day = 32258064.51612903
#events/hour = 1344086.0416666667 =~ 1M + events per hour 
#events/job = 1344.087 Assuming 1000 jobs in a Hour 
#events/job = 13440.87 Assuming 100 jobs in a Hour
```

Can you get a timing on how long it takes to run that and mention what type of system you run it on? (e.g. size of disk of DB and cpu/mem stats on the tower instance)

**Comment by mcharanrm** [comment]
Hello @kdelee , Sure i will run it with default values (1B events) and will update you.

**Comment by jladdjr** [comment]
This just now came up on my radar, sorry for missing this. @mcharanrm if you have any future PRs like this definitely feel free to cc me or put me down as a reviewer.

**Comment by jladdjr** [comment]
Right now I'm trying to chase down two issues (https://github.com/ansible/awx/issues/9412 and https://github.com/ansible/awx/issues/9258) in order to get a build into QE's hands so can't take a look at this right this second. Looks like @kdelee has already made a pass, though.

**Comment by ryanpetrello** [comment]
@jladdjr @mcharanrm do we think we're still gonna go down this path, or do the route of generating actual data over time w/ playbook runs?

**Comment by jladdjr** [comment]
We were wanting to work with more live / realistic data for this feature. I've been leaning toward sticking with that approach (but if we think there's value in updating the firehose, think we could still do that).

**Pull request merged**
