### PR TITLE
Project admin manual SCM Type creation bug fix

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

There was a bug in tower where project admin was not allowed to create a project with manual SCM type. This was because, the project base dir was only set from `settings.PROJECTS_ROOT`, if the user role was either admin or auditor. This has been updated by also allowing it to set when user is a project admin.

##### ISSUE TYPE

 - Bugfix Pull Request
 
##### COMPONENT NAME

 - API
 
##### AWX VERSION

```
awx: 3.0.1
```

##### ADDITIONAL INFORMATION

Before:

image

After:

image

```

```

### CODE REVIEW

**Comment by ghost** [comment]
@mabashian this PR solves the creation issue of the project, however, while trying to edit the same project, it will not show the `PROJECT BASE PATH`.

image


This is because, the base path is only shown to super users. If you can make changes to [this part of the code](https://github.com/ansible/awx/blob/devel/awx/ui/client/src/projects/edit/projects-edit.controller.js#L56) to something like: 

```
if (Authorization.getUserInfo('is_superuser') === true || has_project_admin_permissions())
```

it might solve the problem.

**Comment by mabashian** [comment]
@vismay-golwala https://github.com/ansible/awx/pull/3460/commits/b3947660750da39aadb986163c9f2066ab8cd119 should address UI concerns

**Comment by ghost** [comment]
Thanks @mabashian. Let’s wait for reviews.

**Comment by shanemcd** [comment]
regate

**Review by Spredzy — APPROVED** [review]
Tested and worked

**Review by ryanpetrello — APPROVED** [review]

**Pull request merged**
