### PR TITLE
Creation of tower_inventory_script module

### PR DESCRIPTION
**Pull request by sean-m-sullivan**
##### SUMMARY
Creation of tower_inventory_script module

I noticed that the collection lacked an inventory script module, and wanted to cut my teeth at creating one. 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - Collection

##### AWX VERSION
```
awx: 11.2.0
```

##### ADDITIONAL INFORMATION
new_name parameter does not work, tested it, compared code to other modules, may need to be removed.

### CODE REVIEW

**Comment by wenottingham** [comment]
My concern is that this is a deprecated feature, so I'm a bit leery of having a module in the collection that may be out of date soon.

**Comment by sean-m-sullivan** [comment]
I am looking at that now. Part of this was learning how to make a module. Do still see inventory scripts in 3.7. 

My gut opinion is that modules/updates should be tied to their respective tower/awx releases. What this means for the future of the collection as it applies to Tower/AWX and support of the collection, is something to be considered.

**Comment by wenottingham** [comment]
Storing the custom scripts (or plugins) in a SCM project. It's a much better way to manage them regardless.

**Comment by sean-m-sullivan** [comment]
True, I was just looking at that, Closing this. Thanks.

**Pull request closed without merging**
