### PR TITLE
fix: invalid response type on post request

### PR DESCRIPTION
**Pull request by pb82**
##### SUMMARY

Fix the 500 response when sending an unauthenticated `POST` request to `/api/controller/login`. Using a django `JsonResponse` avoids the error.

Verified by running this on OpenShift with Gateway.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API

##### AWX VERSION

```
2.5
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by relrod — APPROVED** [review]
Approving, but: @AlanCoding might know if there's a more DRF-ey way to do this with `@api_view` or the like. But this looks simple enough to me and fixes the fatal.

**Comment by relrod** [comment]
Actually: It might be nice to have a regression test for this (just mocking out is_proxied_request and calling the endpoint)

**Comment by pb82** [comment]
@relrod I'm working on a test for this :+1:

**Review by djyasin — APPROVED** [review]
Approving current changes- I wasn't sure if the test work was happening elsewhere.

**Comment by PabloHiro** [comment]
Would add tests for this one, feels self-contained enough :pray:

**Comment by pb82** [comment]
@djyasin @PabloHiro thanks, I'll add the tests in this PR

**Review by relrod — APPROVED** [review]

**Pull request merged**
