### PR TITLE
Adds smart inventory button on host list

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #7700 

smart_inv

Note that I filed https://github.com/ansible/awx/issues/8890 while working on this PR.  If you attempt to create a filter that does not match one of these: https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/Lookup/HostFilterLookup.jsx#L74-L109 then the tag _will not show up_ in the host filter field.  The value is still there and you can save.  You can also see the value inside the modal.

The Smart Inventory button is disabled until a search is performed.  The button is hidden from users that don't have the ability to create a host as was the case in the old UI.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by tiagodread** [comment]
Hey @mabashian do you mind rebasing this one?

**Comment by tiagodread** [comment]
@mabashian some feedback:

- ~Smart host filter fields empty and disabled after searching hosts by description:~

smart1

- ~I cant open the Smart host filter modal when the search term doesn't match because the button is disabled:~

smart

I found these two items above because i didn't know that I need fill an Organization first, to be able to click on **Smart host filter lookup button** This is not intuitive, in the old UI the users were able to see this help text:

image

We are missing this helper text in the ui_next

- Smart inventory button on kebab after advanced search:

image

**Comment by tiagodread** [comment]
@mabashian Smart inventory button on kebab after advanced search:

image

**Comment by mabashian** [comment]
@tiagodread ok I fixed the styling of that button.  The options are getting chopped off at certain resolutions.  I think this is an issue for PF though since we use their Toolbar component under the hood:

Screen Shot 2021-01-15 at 2 54 43 PM

**Review by tiagodread — APPROVED** [review]
Tests covered by https://github.com/ansible/tower-qa/pull/5867

**Pull request merged**
