### PR TITLE
Hide max hosts field on org form

### PR DESCRIPTION
**Pull request by nixocio**
Also, simplify the usage of context API to read the value of `me`
parameter.

Hide max hosts field on org form.

See: https://github.com/ansible/awx/issues/4950

### CODE REVIEW

**Comment by unlikelyzero** [comment]
I'll starting some tests for this tomorrow

**Comment by nixocio** [comment]
I decided to refactor, `OrganizationAdd`, and `OrganizationEdit` - how we are reading the `me` parameter. To avoid nested context APIs. I used the `useConfig` hook inside the `OrganizationForm`.  Open to suggestions.

**Review by jlmitch5 — APPROVED** [review]
very nice!

**Comment by unlikelyzero** [comment]
@nixocio shouldn't we have a tooltip on the Details view?

Also
maxhosts

**Comment by nixocio** [comment]
@unlikelyzero, I will take a look.

**Comment by unlikelyzero** [comment]
Moving those two bugs into separate tickets to address outside of this PR
https://github.com/ansible/awx/issues/8556
https://github.com/ansible/awx/issues/8557

**Pull request merged**
