### PR TITLE
Fix extra requests when creating WorkFlowJobTemplate

### PR DESCRIPTION
**Pull request by nixocio**
Fix extra requests when creating WorkFlowJobTemplate.

I used useRef to store the el - div, but it was becoming more complex to do the clean up. The useState solved the issue. 

See: https://github.com/ansible/awx/issues/11442

### CODE REVIEW

**Comment by nixocio** [comment]
I triggered the e2e tests.

**Comment by keithjgrant** [comment]
It feels weird putting an element in state here... is that an example you found somewhere? Why does it fix the issue?

Most examples I've seen of portals use an existing element in the DOM... Maybe instead of useState and adding/removing the div from the DOM, we can pass in a unique id prop and get a `div` by id (creating it if it's not found) and use that?

**Comment by nixocio** [comment]
@keithjgrant the solution involving `useRef` would be. Main issue is the `el` is being recreated over and over.

With useRef the clean up is a bit more complex. See: https://stackoverflow.com/questions/67069827/cleanup-ref-issues-in-react

Good article about portals and hooks: https://www.jayfreestone.com/writing/react-portals-with-hooks/

```js
import { useEffect, useRef } from 'react';
import ReactDOM from 'react-dom';

function AppendBody({ children }) {

  const el = useRef(document.createElement('div'));

  useEffect(() => {
    let elRefValue = null;
    if (el.current) {
      elRefValue = el.current;
    }
    document.body.appendChild(el.current);
    return () => {
      if (elRefValue) {
        document.body.removeChild(elRefValue);
      }
    };
  }, []);

  return ReactDOM.createPortal(children, el.current);
}

export default AppendBody;
```

**Review by keithjgrant — APPROVED** [review]

**Review by tiagodread — APPROVED** [review]

**Comment by tiagodread** [comment]
The broken tests related to this branch is also failing on origin/devel @nixocio feel free to merge it, I'll be working on these failures

**Pull request merged**
