### PR TITLE
Fix the Slack notification back end so it works.

### PR DESCRIPTION
**Pull request by craigcalef**
##### SUMMARY
Make the Slack notification backend work.

I have tested this on my Ansible Tower installation using the AMI build
and a bot token for Slack.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME

- Notification/Slack

##### AWX VERSION

```
AMI Description
Ansible Tower 3.2.2 on CentOS 7 x86_64
```

##### ADDITIONAL INFORMATION
Create a Slack notification in Ansible Tower.  Hit 'test'.  Get nothing.  Apply this fix.  Notifications now start working.

### CODE REVIEW

**Comment by shanemcd** [comment]
This was recently resolved by https://github.com/ansible/awx/pull/1003 which will make its way into a future version of Tower. In the future if you are having issues with Tower you should contact your support rep.

**Comment by shanemcd** [comment]
I was mistaken when I linked to the above PR. That resolved another unrelated issue. Nonetheless, this will be fixed in Tower 3.2.3.

**Comment by ewjoachim** [comment]
So, do you know when it will be fixed in AWX ?

**Comment by wenottingham** [comment]
It should already be fixed since https://github.com/ansible/awx/commit/aa469d730ea825119d2d5536e8255ab4632c7829

**Pull request closed without merging**
