### PR TITLE
Read in and use the Sat port if applicable for Subscriptions

### PR DESCRIPTION
**Pull request by rooftopcellist**
##### SUMMARY
Use port from rhsm.conf for subscription setup.  

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by rooftopcellist** [comment]
I just rebased, the PR checks should work now.

**Comment by rooftopcellist** [comment]
regate

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
