### PR TITLE
Inventory File field and playbook field are both now type ahead.

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This addresses:
1) #9043 
2) Makes Playbook drop down on the JT Form a type ahead component
3) prevents 'Custom Details` from rendering when Source field in the Inventory Source form is blank or when Custom is selected.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2021-01-20 at 3 24 16 PM
Screen Shot 2021-01-20 at 3 21 26 PM
Screen Shot 2021-01-20 at 3 21 03 PM

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by unlikelyzero** [comment]
@AlexSCorey will this need to be rebased to include the changes made to the credential typeahead component?

**Comment by ryanpetrello** [comment]
Hey.

@AlexSCorey

Hey.

**This is awesome.**

**Comment by tiagodread** [comment]
@AlexSCorey some feedback after use this feature:

1. allow users to send manual type in
2. allow users to scroll when the list is too large
3. close the list after clicking 
4. add IDs to the list items

**Review by tiagodread — APPROVED** [review]
Verified that the user can:

- type and select a playbook
- type and select an inventory file
- type in and create an entry for a existing file even if not visible in the list

**Comment by barkely128** [comment]
Umm, has this been merged in the new 17.1.0 release? I just updated my AWX all happy that I'll finally be able to use my yaml hosts files for different environments from a single git folder, only to find out I still can't type the names manually.

**Comment by AlexSCorey** [comment]
@barkely128 No it hasn't been merged into the newest release.  Feel free to pull down this PR, though and use it that way.

**Comment by christiangfeller** [comment]
It's not fixed. I am still not able to edit manaully the inventory file field. 
Installed AWX 17.1.0 on OpenShift.

**Comment by barkely128** [comment]
> It's not fixed. I am still not able to edit manaully the inventory file field.
> Installed AWX 17.1.0 on OpenShift.

As a workaround you can use f12 in Chrome and Firefox to manually edit the field's name and most importantly - value.
Not pretty, but it works and I managed to setup my 2 inventories, which lie in a single git folder. If you've checked the boxes to update it after project sync, then you should be able to live without doing this too often.

**Comment by christiangfeller** [comment]
> > It's not fixed. I am still not able to edit manaully the inventory file field.
> > Installed AWX 17.1.0 on OpenShift.
> 
> As a workaround you can use f12 in Chrome and Firefox to manually edit the field's name and most importantly - value.
> Not pretty, but it works and I managed to setup my 2 inventories, which lie in a single git folder. If you've checked the boxes to update it after project sync, then you should be able to live without doing this too often.

Thank you @barkely128 
it works with this f12 workaround

**Pull request merged**
