### PR TITLE
Update Kind Docs

### PR DESCRIPTION
**Pull request by thedoubl3j**
##### SUMMARY

Update some formatting as well as updating some commands that I found along the way while testing on fedora. 

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Docs

##### AWX VERSION

```
awx: 21.5.1.dev74+gabca78a893
```

##### ADDITIONAL INFORMATION

Also changed image URLs as they are not coming from GH but rather quay.

### CODE REVIEW

**Review by jbradberry — APPROVED** [review]

**Review by gundalow — APPROVED** [review]
Great to see docs updated when people run though them, thanks.

**Comment by fosterseth** [comment]
@thedoubl3j thanks!

the `kind.md` and `minikube.md` have a lot of overlap. Personally I'd rather see a single document with both kind and minikube instructions. Otherwise I fear things will go stale in one or the other as we add more instructions.

however, if we plan to add more k8s cluster targets (like k3s), then having separate documents might be best.

**Comment by thedoubl3j** [comment]
@fosterseth I am not opposed to condensing down into one. I know a lot of what was in the minikube one made it over into this one (some of which i was going to fix in another PR) but I am not against. can't speak on the future cluster targets but happy to go either way.

**Review by fosterseth — APPROVED** [review]

**Comment by TheRealHaoLiu** [comment]
@fosterseth i dont think we need to be DRY with the docs 

i would prefer being succinct and context specific

**Pull request merged**
