### PR TITLE
Handles workflow node schema inventory

### PR DESCRIPTION
**Pull request by db0**
##### SUMMARY

This makes the workflow_job_template handle the inventory passed to nodes in the schema properly

This is handled fine in workflow_job_template_node, but since workflow_job_template is using its own function, this functionality is missing. I simply copied the same approach from workflow_job_template_node and tested that it is working in my installation

Related #12720
##### ISSUE TYPE

Bug

##### COMPONENT NAME

Collection

##### AWX VERSION

```
I am using the Ansible Automation Platform 2.2.0 from RedHat, not AWX
```

Bug, Docs Fix or other nominal change

### CODE REVIEW

**Review by sean-m-sullivan — APPROVED** [review]
LGTM,

**Comment by john-westcott-iv** [comment]
Thanks for your contribution. We have put this in our backlog to get tested and merged in. While you are waiting for the testing process please feel free to reach out to us on Matrix in the #ansible-awx channel.

**Comment by sean-m-sullivan** [comment]
@john-westcott-iv think this got lost in the backlog, just pinging to see about putting in qa teams queue

**Comment by jay-steurer** [comment]
@db0 Could you rebase the PR? Thanks!

**Comment by db0** [comment]
@jay-steurer done

**Review by jay-steurer — APPROVED** [review]

**Comment by jay-steurer** [comment]
Verified by QE. Merging it.

**Pull request merged**
