### PR TITLE
docs: Update security.rst

### PR DESCRIPTION
**Pull request by ro4i7**
##### SUMMARY

Misc revision for auditor role only.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - Docs

##### AWX VERSION

```

```

### CODE REVIEW

**Comment by ro4i7** [comment]
@tvo318 please check this

**Comment by ro4i7** [comment]
@tvo318 please check this

**Review by AlanCoding — APPROVED** [review]

**Comment by tvo318** [comment]
@ro4i7 - This does not resolve https://github.com/ansible/awx/issues/14517 since there are no alt texts added to the following lines: 70, 83, 89, and 357.

Also, please amend your final commit to do the DCO signoff per the [Contributor's Guide guidelines](https://ansible.readthedocs.io/projects/awx/en/latest/contributor/work_items.html#things-to-know-prior-to-submitting-revisions)? To do this: 
1. Do a ``git commit --signoff``
2. Then push the new commits to your branch

Thanks again for your valuable contributions!

**Review by tvo318 — CHANGES_REQUESTED** [review]
Please see https://github.com/ansible/awx/pull/14540#issuecomment-1747658557

**Comment by tvo318** [comment]
I'll approve and merge these changes as-is but issue https://github.com/ansible/awx/issues/14517 will be resolved with a separate PR.

**Review by tvo318 — APPROVED** [review]

**Pull request merged**
