### PR TITLE
Modernize Python 2 code to get ready for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
This PR replaces #98 which in turn replaced #50 

Make the minimal, safe changes required to convert the code to be syntax compatible with both Python 2 and Python 3. There would definitely be __more work required__ to complete the port of the code to Python 3 but this is a minimal, safe first step.

1. Run: `futurize --stage1 -w **/*.py`

See Stage 1: "safe" fixes http://python-future.org/automatic_conversion.html#stage-1-safe-fixes

$ `pip install future`
$ `git checkout -b modernize-python2-code`
$ `futurize --stage1 -w **/*.py`  # done in zsh for ** globbing
$ `git commit --all -m "Modernize Python 2 code to get ready for Python 3"`
$ `git push --set-upstream origin modernize-python2-code`

2. Replace a ur'string' with an r'string' in `awx/main/redact.py`
3. Start testing on Python 3 in allow_failures mode in `shippable.yml`

### CODE REVIEW

**Comment by cclauss** [comment]
@matburt Could you please review this?

**Comment by matburt** [comment]
Hey @cclauss it looks good... I'm just holding off on merging until we do a larger 2 -> 3 upgrade

**Comment by cclauss** [comment]
Understood.  I have been watching that one as well.  Best of luck with everything.

**Review by sandrobonazzola — APPROVED** [review]

**Comment by matburt** [comment]
I'm going to close this, the code has diverged a lot and a larger effort is needed

**Comment by ryanpetrello** [comment]
FYI, we've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which runs under python3.6.  This version of awx also supports python2 _and_ python3 virtualenvs when running Ansible playbooks.

**Pull request closed without merging**
