### PR TITLE
Fix DETAILS link in WF viz not working until after job has ran

### PR DESCRIPTION
**Pull request by kialam**
- Make additional GET request if we need in order to surface the job type so that we can properly redirect the user to the detail page.

##### SUMMARY

Related #2606 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 2.1.0
```

### CODE REVIEW

**Review by jlmitch5 — APPROVED** [review]
Looks good!

**Comment by AlanCoding** [comment]
hey, I'm having some trouble with this, here is an example of workflow nodes of a workflow job with a running job inside it:

https://gist.github.com/AlanCoding/b74095a6723a8134c8d99fb18f5eb1f3

It returns the type here. I don't envision any scenario where it has the "job" entry in summary fields and doesn't have type.

Indeed, it seems that I can't reproduce issue #2606 at all. I've tried with a running job, and then with a workflow job that has a running job. In both cases I don't have any trouble with the click through.

**Comment by ryanpetrello** [comment]
I'm also having trouble reproducing #2606.

**Comment by AlanCoding** [comment]
Okay, I _am_ able to reproduce this now. You have to create a workflow with 3 root nodes, all of the same JT, and don't allow simultaneous, so 1 goes into running status and other 2 remain pending. Links don't work.

UI makes a request to get the nodes at a point-in-time when the nodes had not yet spawned. Some timing details:

Time of GET request to get the nodes

Thu, 08 Nov 2018 19:46:38 GMT

Time of first "pending" websocket message:

14:46:46.359

That's a delta of about 2 seconds. Still, this point to an API bug. The UI code here is a band aid that will work in most situations, but will still fail in the event of split JTs.

Still... split JTs links in workflows, in pending status, as a root node, given a particular timing window is hit... it's an awful narrow bug to be spending more time on right now.

**Review by AlanCoding — APPROVED** [review]

**Comment by kialam** [comment]
FWIW I was able to reproduce by simply launching a sliced job.

**Pull request merged**
