### PR TITLE
Do not allow EE to modify Org

### PR DESCRIPTION
**Pull request by nixocio**
Do not allow EE to modify Org.

See: https://github.com/ansible/awx/issues/9769
Also: https://github.com/ansible/awx/pull/9874

### CODE REVIEW

**Comment by nixocio** [comment]
Running e2e tests.

**Review by jakemcdermott — APPROVED** [review]

**Comment by nixocio** [comment]
I will have to update this PR upon discussion here: https://github.com/ansible/awx/pull/9874#discussion_r611766817

**Comment by nixocio** [comment]
@tiagodread @jakemcdermott updated with the latest API changes.

* One can not reassign a Globally available EE to an Org
* One can not reassign an EE that belongs to Org A to Org B
* One can reassign an EE that belongs to Org A to null - to be globally available.

**Comment by nixocio** [comment]
recheck

**Review by tiagodread — APPROVED** [review]
Added some tests in 6236

**Pull request merged**
