### PR TITLE
Deprecate tower modules

### PR DESCRIPTION
**Pull request by thedoubl3j**
##### SUMMARY

Deprecate tower_* modules and update plugin_routing with warning message. The symlinks have been removed as it was needed to properly deprecate the modules. Users who are currently using `tower_*` modules should experience no interruption in use aside from getting the warning message as the redirects were already in place and were not touched. 

Do note that there are other failing sanity tests that are not introduced via this change but are not related to this change. 

related #13186 

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Collection

##### AWX VERSION

```
awx: 21.5.1.dev424+g293bb9f656
```

##### ADDITIONAL INFORMATION

redirect remains in tact if old name is used. 

```
ansible-doc --playbook-dir=$PWD awx.awx.tower_ad_hoc_command_cancel 2>/dev/null | head -1
> AWX.AWX.AD_HOC_COMMAND_CANCEL    (collections/ansible_collections/awx/awx/plugins/modules/ad_hoc_command_cancel.py)
```

### CODE REVIEW

**Review by john-westcott-iv — APPROVED** [review]

**Review by john-westcott-iv — CHANGES_REQUESTED** [review]
We should probably add something to tools/roles/template_galaxy/templates/README.md.j2

**Review by sean-m-sullivan — APPROVED** [review]
LGTM

**Comment by john-westcott-iv** [comment]
We might have to be a little fluid with the version in the README. 21.10.0 has been released so it won't be until 21.11.0 (assuming we merge w/in the next three weeks).

**Review by john-westcott-iv — APPROVED** [review]
Approval with the assumption we will fix the version in the README before merging.

**Comment by thedoubl3j** [comment]
can't update readme until QE sign off so no merging until then.

**Review by AlanCoding — APPROVED** [review]

**Review by jay-steurer — APPROVED** [review]

**Comment by jay-steurer** [comment]
Verified by QE

**Comment by AlanCoding** [comment]
@thedoubl3j sorry to do this to you again, but could you rebase and see if the sanity tests are passing? Reason is that I remember some of our test ignore rules being related to the fact that these files are unnecessary. As you fix that issue, we might get new errors due to the ignore rule becoming unnecessary, and I just want to see.

**Comment by thedoubl3j** [comment]
@AlanCoding tested locally with 2.14 and it passed successfully. including the tail of the stdout (where the error report usually is) the forced update is the rebase
```
Running sanity test "shellcheck"
Running sanity test "symlinks"
Running sanity test "use-argspec-type-path"
Running sanity test "use-compat-six"
Running sanity test "validate-modules"
Running sanity test "yamllint"
WARNING: Reviewing previous 1 warning(s):
WARNING: Ignoring tests in "test/" in favor of "tests/".
WARNING: Reviewing previous 1 warning(s):
WARNING: Ignoring tests in "test/" in favor of "tests/".
```

**Comment by AlanCoding** [comment]
Perfect! The api-test failure looks like flake, and the operator failure is something many people are experiencing, as the Galaxy server is having downtime.

**Review by AlanCoding — APPROVED** [review]

**Comment by thedoubl3j** [comment]
Holding this PR until we determine which release version it will go into

**Pull request merged**
