### PR TITLE
remove extra and trailing slashes from e2e url settings

### PR DESCRIPTION
**Pull request by jakemcdermott**
##### SUMMARY
- remove extra and trailing slashes from e2e url settings

### CODE REVIEW

**Review by unlikelyzero — APPROVED** [review]
ok great. I'd still like to keep the FAQ section going

**Review by dsesami — APPROVED** [review]
LGTM, but does that normalizer replace any amount of extra slashes?

**Comment by jakemcdermott** [comment]
@dsesami Yep, it should. among the test strings I tried:

```
console.log(normalizeURL('https://localhost/foo/bar//fiz:8043//'));
// https://localhost:8043
```

edit also: 
```
console.log(normalizeURL('http://localhost//foo/bar///fiz/bar:3000/'));
// http://localhost/foo/bar/fiz/bar:3000
```

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
recheck

**Pull request merged**
