### PR TITLE
Display 'System' for user role resource name when summary_fields.resource_name not present

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #7816 

Screen Shot 2020-11-23 at 12 32 04 PM

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
:+1:

**Comment by unlikelyzero** [comment]
@mabashian is there a way to filter for 'System' in this way?

**Comment by tiagodread** [comment]
> @mabashian is there a way to filter for 'System' in this way?

@unlikelyzero it’s possible

search

**Review by tiagodread — APPROVED** [review]
Verified that the user can see System when summary_fields.resource_name is empty and it’s possible search for System.

Added a ui test in 5822

**Pull request merged**
