### PR TITLE
Change openshift vars path.

### PR DESCRIPTION
**Pull request by jmferrer**
##### SUMMARY
Fix OpenShift vars path in documentation.

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME
 - Installer

Depends-On: ansible/zuul-jobs#27

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Review by ryanpetrello — CHANGES_REQUESTED** [review]
@jmferrer can you put this back?

```
The default resource requests per-pod requires:

 > Memory: 6GB
 > CPU: 3 cores
```

Otherwise, thanks for the filename update.

**Comment by ryanpetrello** [comment]
recheck

**Comment by jmferrer** [comment]
@ryanpetrello , I removed the block because the resource requests is per-deployment instead of per-pod. I restored it and changed per-pod to per-deployment.
I am happy to help you so thank to you.

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
