### PR TITLE
Remove dead projects code

### PR DESCRIPTION
**Pull request by jakemcdermott**
##### SUMMARY
Project schedules are currently [deffined inline](https://github.com/ansible/awx/blob/devel/awx/ui_next/src/screens/Project/Project.jsx#L222) in the top-level component so this code isn't actually used.

### CODE REVIEW

**Review by mabashian — APPROVED** [review]

**Comment by mabashian** [comment]
regate

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
regate

**Pull request merged**
