### PR TITLE
make current_user ck secure and httponly

### PR DESCRIPTION
**Pull request by rooftopcellist**
##### SUMMARY
Makes the `current_user` cookie secure and httponly when set.  

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Review by jakemcdermott — CHANGES_REQUESTED** [review]
I went over this one earlier today with @rooftopcellist 

We picked up an e2e failure on this pr due to the side navigation bar not loading in the UI - further inspection showed us that that the navbar code is failing to initialize when the client attempts to access a cookie that is no longer defined.

Once we clear that up I think this should be ready for another look.

**Comment by rooftopcellist** [comment]
@jakemcdermott I have since made the `current_user` cookie secure, not httponly.  ~It looks like the e2e tests are still not happy though.  This may not work without the UI changes mentioned in the [related issue](https://github.com/ansible/tower/issues/1653)..~

^^ didn't build correctly, kicking off e2e again

**Comment by rooftopcellist** [comment]
Update: `current_user` was being set by the UI as well, and needed to also selectively set it as secure.  running e2e again

**Review by jlmitch5 — APPROVED** [review]

**Review by jakemcdermott — APPROVED** [review]

**Comment by unlikelyzero** [comment]
Can we test the following:
- Openshift integration
- TLS+HAProxy + Integration

**Review by jladdjr — APPROVED** [review]

**Comment by rooftopcellist** [comment]
@unlikelyzero that makes sense.  @unlikelyzero and I agreed on merging this, then to test this out.

**Pull request merged**
