### PR TITLE
remove awxkit logic for working around an old stdout handling bug

### PR DESCRIPTION
**Pull request by ryanpetrello**
related: https://github.com/ansible/awx/issues/200

### CODE REVIEW

**Review by kdelee — APPROVED** [review]
:shipit:

**Comment by ryanpetrello** [comment]
More context on the commit where we actually removed this in AWX:

0b30e7907b5d63cd2940174e33f3403e3a6c508f

**Review by jladdjr — APPROVED** [review]

**Comment by jladdjr** [comment]
zuul is seeing an unrelated failure:
```
_________________________ test_get_custom_venv_choices _________________________
[gw0] linux -- Python 3.6.8 /venv/awx/bin/python3
Traceback (most recent call last):
  File "/awx_devel/awx/main/tests/unit/utils/test_common.py", line 201, in test_get_custom_venv_choices
    assert sorted(common.get_custom_venv_choices()) == [bundled_venv]
AssertionError: assert ['/venv/ansib...tmp3yq3_vx5/'] == ['/venv/ansible/']
  Left contains more items, first extra item: '/venv/tmp3yq3_vx5/'
  Use -v to get the full diff
============= 1 failed, 2443 passed, 10 skipped in 336.66 seconds ==============
make: *** [test] Error 1
command terminated with exit code 2
```

**Comment by jladdjr** [comment]
recheck

**Pull request merged**
