### PR TITLE
Api issue float

### PR DESCRIPTION
**Pull request by nixocio**
Add SURVEY_TYPE_MAPPING to constants, and replace usage in a couple of
files.

See: https://github.com/ansible/awx/issues/8460

### CODE REVIEW

**Comment by AlanCoding** [comment]
This doesn't make any functional changes yet, right? So this just needs to be adopted in another file to address the issue.

**Comment by nixocio** [comment]
@AlanCoding, no functional changes. Exactly.

**Comment by AlanCoding** [comment]
huh, well then it seems surprising that the test would be passing, because that covers what the issue reported.

**Review by AlanCoding — APPROVED** [review]
I was going too fast earlier, I see this adds the int type to the `'float'` question type, this looks good.

**Review by InnocentK — APPROVED** [review]
Great job!

**Comment by InnocentK** [comment]
I verified that the above failing test is not caused by this work so its good to go

**Pull request merged**
