### PR TITLE
Make rrule plugins return a list with 1 element

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Connect https://github.com/ansible/awx/issues/13417

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - API

### CODE REVIEW

**Comment by AlanCoding** [comment]
Seems suspicious that all the checks passed...

**Comment by john-westcott-iv** [comment]
Is there a reason we are looking to do this? Seems like it could "break" existing integrations.
@sean-m-sullivan are you using these lookup plugins anywhere?

**Comment by sean-m-sullivan** [comment]
I am not using this in a lot of places, but have the same concern as John. However on looking at the underlying issue, we need to conform to sanity standards, and return the right thing

**Comment by AlanCoding** [comment]
> Is there a reason we are looking to do this?

The current behavior will become an error in a future version of Ansible core.

I guess you could argue that we don't fix it until Ansible core releases a version that breaks it. In that case the question is whether you care more about compatibility with older core versions, or with newer core versions.

**Comment by dmzoneill** [comment]
Marking as blocked/draft until it Ansible core breaks behaviour, per @AlanCoding feedback

**Comment by AlanCoding** [comment]
Replaced by https://github.com/ansible/awx/pull/15625

**Pull request closed without merging**
