### PR TITLE
Add VariablesField YAML/JSON validation

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Validates YAML or JSON syntax in the variables field on blur. Prevents formik from submitting the form while this error is present.

addresses #8906, #8907

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2021-03-15 at 11 31 19 AM

### CODE REVIEW

**Comment by keithjgrant** [comment]
NOTE: this relies on the browser's JSON parser and our YAML library's parser for error messages, so I don't think there's a viable strategy for translation here 😕

**Review by nixocio — APPROVED** [review]

**Comment by unlikelyzero** [comment]
@keithjgrant can you ensure that these strings are i18n'd ?

**Comment by one-t** [comment]
Hey, @keithjgrant - I found that this validates there are no duplicate keys for YAML, but it does not prevent saving JSON with repeated values.
image

**Comment by keithjgrant** [comment]
> Hey, @keithjgrant - I found that this validates there are no duplicate keys for YAML, but it does not prevent saving JSON with repeated values.

@one-t Hm. Technically, that is valid JSON (and most standard JSON validators will accept it. e.g. https://codebeautify.org/jsonvalidator). I talked a bit with @ryanpetrello and @chrismeyersfsu about this... we don't think the old UI checked for this, so it's not necessary for feature parity. It would also be pretty difficult to implement, since the browser's native JSON parser (and basically every other JSON parser lib) quietly accept duplicate keys.

**Review by jakemcdermott — APPROVED** [review]

**Comment by one-t** [comment]
regate

**Pull request merged**
