### PR TITLE
Fixes workflow vis edit save failure

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
See https://github.com/ansible/awx/issues/13275

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by AlexSCorey** [comment]
related https://github.com/ansible/tower/pull/6231

**Review by vidyanambiar — COMMENTED** [review]
@AlexSCorey I'm unable to reproduce this issue on the devel branch. Here are my steps. Am I missing something? Thanks!

https://user-images.githubusercontent.com/43621546/207876523-0ac3cba6-8873-4a36-aead-58095097cc77.mov

**Review by akus062381 — APPROVED** [review]

**Comment by AlexSCorey** [comment]
@vidyanambiar I don't remember off the top of my head.  Maybe this comment can help https://github.com/ansible/awx/issues/12782#issuecomment-1233095718

**Comment by akus062381** [comment]
@AlexSCorey I can't recreate it in devel either. only 4.2. I am thinking that only the backport PR is necessary?

**Comment by akus062381** [comment]
@AlexSCorey should we close this?

**Pull request closed without merging**
