### PR TITLE
Add support for Bitbucket Data Center webhooks

### PR DESCRIPTION
**Pull request by puiterwijk**
##### SUMMARY
This adds support for receiving webhooks from Bitbucket Data Center, and adds support for posting build statuses back.

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - UI
 - Other

##### ADDITIONAL INFORMATION
Note that this is very explicitly only for Bitbucket Data Center. The entire webhook format and API is entirely different for Bitbucket Cloud.

### CODE REVIEW

**Comment by relrod** [comment]
refs https://github.com/ansible/awx/issues/5209

**Comment by puiterwijk** [comment]
For information: I tested this with a local installation of Bitbucket Data Center 8.15.1, and it worked with both new pushes and PRs (both new, updated, merged).
The build status also worked and displayed correctly, including the link back to the job.

**Comment by djyasin** [comment]
Hello @puiterwijk! One of our CI checks is failing, specifically the api-test. Here is the error we are encountering:
`awx/main/tests/functional/test_credential.py::test_default_cred_types`

Is this something you can fix on your end? Please let us know if you need additional information!

**Comment by puiterwijk** [comment]
Hi @djyasin, thanks for the heads-up!
I just pushed a change that should fix this test failure, sorry about that.

**Comment by djyasin** [comment]
Hi @puiterwijk, thank you so much for making that change! It does appear that the tests are passing now. Would you mind rebasing for us once more? Once that is done we can get this merged in. Thank you so much!

**Comment by puiterwijk** [comment]
> Hi @puiterwijk, thank you so much for making that change! It does appear that the tests are passing now. Would you mind rebasing for us once more? Once that is done we can get this merged in. Thank you so much!

Done.

**Comment by djyasin** [comment]
Thank you so much! I will get this merged in now!

**Review by djyasin — APPROVED** [review]

**Pull request merged**
