### PR TITLE
Remove accidentally committed log files

### PR DESCRIPTION
**Pull request by wenottingham**

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Should we add something to `.gitignore`?

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
...or perhaps improve on https://github.com/ansible/awx/blob/devel/.gitignore#L52 ?

**Review by AlanCoding — APPROVED** [review]

**Comment by AlanCoding** [comment]
I'm going to investigate the test failure, since I'm pretty sure it's not related to the changes here.

**Comment by AlanCoding** [comment]
Replicated failures locally, yep, we've seen this before:

https://github.com/ansible/ansible/pull/23001/files#diff-9264ccbd90fd51c6ef3911846933c686L9

old:

```python
from ansible.inventory import Inventory
```

new:

```python
from ansible.inventory.manager import InventoryManager
```

These changes happened a while ago, but the test system is just now picking up the new version of Ansible apparently.

**Pull request merged**
