### PR TITLE
Provide a distinct column name for inventory_name in unifiedjob analy…

### PR DESCRIPTION
**Pull request by rooftopcellist**
…tics csv

##### SUMMARY
Follow-up for https://github.com/ansible/awx/pull/7965

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Review by rebeccahhh — COMMENTED** [review]
:+1: thanks @rooftopcellist

**Review by rebeccahhh — APPROVED** [review]

**Comment by elyezer** [comment]
Can we hold merging this so I can do some checks?

**Review by elyezer — APPROVED** [review]
LGTM

**Comment by elyezer** [comment]
Finished the checks and I think this is ready to be merged.

**Pull request merged**
