### PR TITLE
Send real client remote address in TACACS+ authentication packet

### PR DESCRIPTION
**Pull request by pax0s**
##### SUMMARY
Addresses #1797, to add the client IP when authenticating in TACACS+
The client IP is extracted from one of the following header in the request in this order: x-forwarded-for, remote-addr.
If none of those are found it is behaving like previously (no value is passed and the default client flag is used)

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - API

### CODE REVIEW

**Comment by fosterseth** [comment]
Hi! thank you for this contribution, we are still going over the PR and will let you know next steps

**Comment by john-westcott-iv** [comment]
@ekougs et. al. Would this change have any ill affect on people using TACAC+ for auth already without passing this through?

**Comment by TheRealHaoLiu** [comment]
Hi @ekougs thanks for your contribution!

are you on Ansible's chat server? https://matrix.to/#/#awx:ansible.com

our team is not as familiar with TACACS+ it would be wonderful we can chat with you about it.

(there might be a rare IRL angry spud plushy in it for you 😉 )

**Comment by TheRealHaoLiu** [comment]
also @ekougs would u mind addressing the linting error by running `make black`

```
would reformat awx/sso/tests/unit/test_tacacsplus.py

Oh no! 💥 💔 💥
1 file would be reformatted, 799 files would be left unchanged.
make: *** [Makefile:250: black] Error 1
ERROR: InvocationError for command /usr/bin/make black (exited with code 2)
___________________________________ summary ____________________________________
ERROR:   linters: commands failed
```

**Comment by pax0s** [comment]
Hi all.
@john-westcott-iv. Yes there is a risk as the connection parameters will change depending on headers which may already be present. I'll check if I can do some integration tests.
@TheRealHaoLiu I don't really know the TACACS auth mechanism so as I mentioned I'll recheck the lib behaviour.
BTW I fixed the formatting error and pushed it.

**Comment by john-westcott-iv** [comment]
If there is a risk of breaking existing functionality we could make this a toggle on the TACACS+ config page and only send the client IP if that toggle is on.

**Comment by pax0s** [comment]
Hi all and sorry for the long silence but I have been busy lately.
I'll have a look on how to create the config then. An opt-in seems the right way to ensure it is not breaking the existing integrations.
I am still looking how to do some relevant testing though.

**Comment by pax0s** [comment]
I tried to have a look at https://github.com/ansible/tacacs_plus/blob/master/tests/test_tacacs_plus.py but did not find anything I could reuse for an integration test. It seems like the remote address is sent as-is so the implementation should be fine.

I also added the configuration to enable it if needed. It will be disabled by default though.

**Comment by pax0s** [comment]
Hi @TheRealHaoLiu, @john-westcott-iv, is the feature still wanted?
I didn't have any feedback since my last submission.

**Comment by john-westcott-iv** [comment]
I looked at this PR today and I am good with what its doing but we need to fix the tests and rebase. The conflict is pretty straight forward. For the test, I think if you change from a `ChoiceField` to a `BooleanField` in `awx/ui/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.js` it might fix the failing tests:
```
diff --git a/awx/ui/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.js b/awx/ui/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.js
index dc176c7c5c..d9ab437774 100644
--- a/awx/ui/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.js
+++ b/awx/ui/src/screens/Setting/TACACS/TACACSEdit/TACACSEdit.js
@@ -12,6 +12,7 @@ import useModal from 'hooks/useModal';
 import useRequest from 'hooks/useRequest';
 import { SettingsAPI } from 'api';
 import {
+  BooleanField,
   ChoiceField,
   EncryptedField,
   InputField,
@@ -116,7 +117,7 @@ function TACACSEdit() {
                   name="TACACSPLUS_AUTH_PROTOCOL"
                   config={tacacs.TACACSPLUS_AUTH_PROTOCOL}
                 />
-                <ChoiceField
+                <BooleanField
                   name="TACACSPLUS_REM_ADDR"
                   config={tacacs.TACACSPLUS_REM_ADDR}
                 />
```

**Comment by john-westcott-iv** [comment]
Closing in favor of #14077

**Pull request closed without merging**
