### PR TITLE
DNM: Build cache testing

### PR DESCRIPTION
**Pull request by shanemcd**
The flow will need to be:

- Pre-pull image you want to use
- Re-tag as image:$(COMPOSE_TAG)
- COMPOSE_TAG=mytag make docker-compose-build

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by ryanpetrello** [comment]
https://media1.giphy.com/media/pd9fLHjcdvQLS/giphy.gif?cid=790b7611718b5c799b2946b42d01aace6c95a8b9de16b1bc&rid=giphy.gif

**Comment by ryanpetrello** [comment]
image

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Pull request closed without merging**
