### PR TITLE
Show Error if No Execution Environment is Found on Project Sync or Job Run [duplicate PR]

### PR DESCRIPTION
**Pull request by beeankha**
##### SUMMARY

Addressing issue https://github.com/ansible/awx/issues/10118

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API

##### AWX VERSION

```
19.0.0
```

### CODE REVIEW

**Comment by beeankha** [comment]
Now, when running a Project Sync without any EEs, the following error shows up in the UI (disregard comment snippets):

Screenshot from 2021-05-07 16-44-02

And for Job Template runs without an EE:

Screenshot from 2021-05-07 16-44-42

**Review by jbradberry — APPROVED** [review]

**Comment by beeankha** [comment]
recheck

**Comment by beeankha** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Pull request closed without merging**
