### PR TITLE
Second attempt at converting tower_job_template

### PR DESCRIPTION
**Pull request by john-westcott-iv**
##### SUMMARY

Replacement for #6353

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - Collection

##### AWX VERSION

```
awx: 10.0.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]
Awesome, I'm good with everything here, if we can get the current tests to pass, then I'd push for a merge

**Comment by AlanCoding** [comment]
One failure from integration tests here:

```
  TASK [tower_job_launch : Create a project for testing extra_vars] **************
  changed: [testhost]
  
  TASK [tower_job_launch : Create a Job Template for testing extra_vars] *********
  fatal: [testhost]: FAILED! => {"changed": false, "msg": "Unable to create job_template AWX-Collection-tests-tower_job_launch-jt2-zCxjCaWsmqIUzFsq: {u'extra_vars': [u'Not a valid string.']}"}
```

https://github.com/ansible/awx/blob/e9a48cceba328ce5d448063116558ee17ac9f60c/awx_collection/tests/integration/targets/tower_job_launch/tasks/main.yml#L73-L83

**Comment by AlanCoding** [comment]
think this just needs something like this:

https://github.com/ansible/awx/blob/e9a48cceba328ce5d448063116558ee17ac9f60c/awx_collection/plugins/modules/tower_workflow_template.py#L198-L201

**Review by beeankha — APPROVED** [review]
I've locally run the integration test playbook, etc., everything looks good to go as long as tests pass!

**Comment by beeankha** [comment]
recheck

**Comment by beeankha** [comment]
recheck

**Comment by AlanCoding** [comment]
still has that yaml lint error

```
2020-03-31 21:07:12.507802 | static | linters run-test: commands[1] | yamllint -s .
2020-03-31 21:07:16.894664 | static | ./awx_collection/tests/integration/targets/tower_job_template/tasks/main.yml
2020-03-31 21:07:16.894799 | static |   23:1      error    trailing spaces  (trailing-spaces)
2020-03-31 21:07:16.894849 | static |   152:12    error    trailing spaces  (trailing-spaces)
2020-03-31 21:07:16.894909 | static |   164:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895002 | static |   171:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895064 | static |   186:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895122 | static |   193:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895180 | static |   208:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895238 | static |   215:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895316 | static |   225:21    warning  truthy value should be one of [false, true]  (truthy)
2020-03-31 21:07:16.895375 | static |   235:21    warning  truthy value should be one of [false, true]  (truthy)
```

once that is cleared up, should be good for merge

**Comment by beeankha** [comment]
regate

**Pull request merged**
