### PR TITLE
Add relaunch against failed hosts

### PR DESCRIPTION
**Pull request by nixocio**
Add relaunch against failed hosts

See: https://github.com/ansible/awx/issues/8670

image

Job Output

image

Job Details
image

### CODE REVIEW

**Comment by unlikelyzero** [comment]
We currently have some stubs in this area but we know that they're not complete.

1. Need to make sure it's responsive
2. Should only see if user has permissions to launch (i.e. auditor should not see button)
3. Displayed on Jobs Detail Page
4. Displayed on Job result Output Page
5. Displayed on Jobs List Page
6. Test that it can launch on all
7. Test that it can launch only on Failed Hosts

Need to add visual test for component

Not add regression tests but check that:
1. Works with expanded and collapsed view
2. Should re-use original POL parameters
3. Check to see if it appears on Slice Job Templates and Workflow Templates

**Review by jakemcdermott — APPROVED** [review]

**Comment by one-t** [comment]
Hey, @nixocio - this is currently not displaying the relaunch on failed hosts option on the details page and the output page. It's only available in the jobs list view. Should that be covered by this PR?

**Comment by nixocio** [comment]
Hey @one-t, I will add those changes on this PR as well. Thanks.

**Comment by unlikelyzero** [comment]
@nixocio is this ready for test again?

**Comment by nixocio** [comment]
> @nixocio is this ready for test again?

yes, I already talked with @one-t.

**Comment by one-t** [comment]
regate

**Comment by kannurkars** [comment]
how to get this feature/bugfix in 17.1,0 (i cannot upgrade to 18 or 19).

**Comment by wenottingham** [comment]
You would have to perform a backport/build yourself - we do not backport bugfixes to older releases upstream.

**Pull request merged**
