### PR TITLE
Adds edit icon to the OrganizationTeams list 

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This addresses #7412 .  

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2020-06-25 at 1 18 45 PM

### CODE REVIEW

**Review by jlmitch5 — APPROVED** [review]
looks good!

**Review by dsesami — APPROVED** [review]
Looks great!

**Comment by dsesami** [comment]
regate

**Comment by dsesami** [comment]
reopening to try to trigger zuul

**Pull request merged**
