### PR TITLE
Fixes failing test

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This is meant to fix a failing test in zuul
##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Comment by shanemcd** [comment]
recheck

**Review by jlmitch5 — APPROVED** [review]
awesome stuff!

**Comment by AlexSCorey** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by AlexSCorey** [comment]
recheck

**Review by shanemcd — APPROVED** [review]

**Comment by shanemcd** [comment]
regate

**Comment by shanemcd** [comment]
regate

**Pull request merged**
