### PR TITLE
Change unicode() --> six.text_type() for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
__unicode()__ was removed in Python 3 because all str are Unicode so this PR:
* Changes all calls to __unicode()__ into calls to [__six.text_type()__](https://pythonhosted.org/six/#six.text_type)
* Change all instances of __(str, unicode)__ to [__six.string_types__](https://pythonhosted.org/six/#six.string_types)
* Change remaining instances of __unicode__ to [__six.text_type__](https://pythonhosted.org/six/#six.text_type)

### CODE REVIEW

**Comment by ryanpetrello** [comment]
If you don't mind, please squash these into a single commit with `git rebase` now that tests are passing.

**Comment by cclauss** [comment]
OK...  squashed.  #1186 also needs a review if you please.

**Review by cchurch — CHANGES_REQUESTED** [review]
Per https://pythonhosted.org/six/#six.u, `six.u` should be used in place of `u` in front of string literals, and `six.text_type` is the equivalent of `unicode` in Python 2 and `str` in Python 3 (https://pythonhosted.org/six/#six.u). `six.u()` is not equivalent to `unicode()`.

**Comment by cclauss** [comment]
@cchurch You are correct!! I misunderstood before.  Thank you...

Please review these new changes.

**Comment by cclauss** [comment]
@ryanpetrello @cchurch Your thoughts on this PR and #1186 ?

**Review by cchurch — APPROVED** [review]

**Pull request merged**
