### PR TITLE
don't attempt to recover special QUIT messages in the worker pool recovery code

### PR DESCRIPTION
**Pull request by ryanpetrello**
when `--reload` is sent to the dispatcher, it sends a special `QUIT`
message to each worker in the pool so that it will exit gracefully at
the next opportunity (i.e., when it has finished its currently running
task)

when a worker process exits unexpectedly, the dispatcher attempts to
recover its queued messages and sends them to another worker in the
pool; in this scenario, we should _never_ re-enqueue these special
`QUIT` messages (because the intended process worker doesn't _need_ to
exit, it's already gone)

To reproduce this race condition:

1.  Launch an adhoc that does `sleep 60`
2.  Run `awx-manage run_dispatcher --reload` to enqueue a `QUIT` message
    into the worker's queue
3.  Find the pid of the worker running the `sleep 60` and `SIGKILL` it.
4.  Observe that the dispatcher attempts to requeue the `QUIT` message and
    logs a confusing error.

Depends-On: https://github.com/ansible/zuul-jobs/pull/27

### CODE REVIEW

**Comment by ryanpetrello** [comment]
kudos to @AlanCoding for discovering and helping me diagnose this one:

screen shot 2018-10-15 at 12 23 26 pm

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Review by AlanCoding — APPROVED** [review]
looks very reasonable and should address the traceback

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
regate

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
