### PR TITLE
Fix quoting and indentation for management Pod annotations

### PR DESCRIPTION
**Pull request by hjkatz**
##### SUMMARY

This was missed as part of #8758 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
16.0.0
```

### CODE REVIEW

**Comment by hjkatz** [comment]
@shanemcd Could I have a hand re-triggering the `ansible/gate` check? This still exists in 17.0.1 and requires a manual change on our end to deploy the management Pod to k8s.

**Comment by ryanpetrello** [comment]
@hjkatz sorry for the delay on reviewing this PR - we've in the process of replacing the k8s installer in `devel` (https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/bCjSDn0eBQAJ https://github.com/ansible/awx/tree/devel/tools/docker-compose) and thus the next major release of AWX with an operator (https://github.com/ansible/awx-operator), so I suspect this PR is obsolete now.

**Comment by hjkatz** [comment]
Until the time comes where the awx-operator is the recommended way of installing AWX, could we please have this PR merged so we can upgrade/install as needed with the AWX versions y'all release?

**Comment by ryanpetrello** [comment]
@hjkatz,

The next release of AWX will be the operator-based install method - `./installer` doesn't exist in the AWX `devel` source tree anymore at this point.

**Pull request closed without merging**
