### PR TITLE
Update variables as returned by useRequest

### PR DESCRIPTION
**Pull request by nixocio**
Update variables to be consistent with variables returned by useRequest.

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
Nice find - Let's merge once we verify the unit tests and e2e are green.

**Comment by nixocio** [comment]
I will take a better look into those unit-tests failures, they seem to be a bit more interesting that I foresaw.

**Comment by nixocio** [comment]
Last change fixed unit-tests, currently running e2e tests using github actions.

e2e tests were 🟢

**Comment by unlikelyzero** [comment]
@nixocio 🟢

**Pull request merged**
