### PR TITLE
Don't unnecessarily expand YAML expressions

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Prevents variables fields from expanding YAML expressions when possible:
* In the detail view, the user may toggle to JSON (seeing the data structure fully expanded), but toggling back to YAML will continue to display the original un-expanded value with expressions intact
* In edit mode, this works the same way, UNLESS the user edits the value while in JSON mode.

Addresses #7506

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
yaml-expand

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
> In edit mode, this works the same way, UNLESS the user edits the value while in JSON mode.

:+1: This seems like the best way forward

code lgtm!

**Review by chrismeyersfsu — APPROVED** [review]

**Comment by one-t** [comment]
For this one, we'll definitely need to have a couple OUIA IDs added:

* close button for modal
* YAML and JSON buttons (preferably different between the expanded modal and the details/edit page)

**Comment by one-t** [comment]
@keithjgrant can you rebase/resolve this merge conflict? Once that's done I'll run my tests again and then merge.
Thanks!

**Comment by keithjgrant** [comment]
> @keithjgrant can you rebase/resolve this merge conflict? Once that's done I'll run my tests again and then merge.
> Thanks!

I've rebased locally and am sorting through some resulting bugs in how this feature interacts with the field validation changes that recently merged

**Comment by keithjgrant** [comment]
> I've rebased locally and am sorting through some resulting bugs in how this feature interacts with the field validation changes that recently merged

@one-t Good to test!

**Comment by one-t** [comment]
regate

**Pull request merged**
