### PR TITLE
Adds inventory sources notifications list

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This addresses #6590  and adds support for Inventory Source Notification List

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2020-06-01 at 12 08 33 PM

### CODE REVIEW

**Comment by AlexSCorey** [comment]
recheck

**Review by jlmitch5 — APPROVED** [review]
looking great!

**Review by dsesami — CHANGES_REQUESTED** [review]
Can we add a header to the type of notification? Like Type: Slack or **Type** Slack I see on other pages?
Screenshot_20200602_155123

**Review by dsesami — APPROVED** [review]
the actual views for the notifications aren't implemented yet, but the list looks good now. :+1:

**Pull request merged**
