### PR TITLE
Expose the known privilege escalation methods in the API config view

### PR DESCRIPTION
**Pull request by jbradberry**
##### SUMMARY
This PR exposes the list of built-in privilege escalation methods in the API, so that the UI and/or other clients can make use of them to provide hints for the user.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION

```
awx: 3.0.0
```

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by AlanCoding** [comment]
The schema change job didn't pick up any changes?

@ryanpetrello what is needed to get it to "see" the config endpoint? Could we get that by writing a simple test? Even if it did something completely unimpressive it would be lovely to have it on record in the schema artifacts.

**Comment by ryanpetrello** [comment]
@AlanCoding I wonder if the Swagger doc doesn't generate `/api/v2/config/` for some reason.

**Comment by ryanpetrello** [comment]
Looks like it should:

https://github.com/ansible/awx/blob/058e2c0d812d54220d2018465db32f3643903e4b/awx/main/tests/docs/test_swagger_generation.py#L111-L119

https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/System_Configuration/System_Configuration_config_list

**Comment by ryanpetrello** [comment]
@AlanCoding Check out the CI logs:

https://ansible.softwarefactory-project.io/logs/47/3147/46020379aadac6607f8d8587c8f2ee442034063a/check/tox-awx-detect-schema-change/5a06ca0/job-output.txt.gz

```
2019-02-04 16:57:47.287625 | static |   /awx_devel/awx/api/swagger.py:27: UserWarning: ApiV1ConfigView.get_serializer() raised an exception during schema generation. Serializer fields will not be generated for GET /api/{version}/config/.
2019-02-04 16:57:47.287685 | static |     .format(self.view.__class__.__name__, method, path))
```

(...and others...)

I'll take a look at that shortly.

**Pull request merged**
