### PR TITLE
Collect information on inventory sources

### PR DESCRIPTION
**Pull request by wenottingham**
Also remove one minor query from smart inventory collection that will
never return anything.

For https://github.com/ansible/tower/issues/3839

### CODE REVIEW

**Comment by chrismeyersfsu** [comment]
@wenottingham sounds like we may need to increment some version number because of schema change?

**Comment by chrismeyersfsu** [comment]
This seems ok from a database query time prospective. The number of inventories I would image people having would be < 1,000 and number of inventory sources per-inventory relatively low.

**Comment by wenottingham** [comment]
> @wenottingham sounds like we may need to increment some version number because of schema change?

We've already bumped this version once this release without shipping the change to customers. We can bump it again if needed, but don't *have* to.

**Review by chrismeyersfsu — APPROVED** [review]

**Comment by wenottingham** [comment]
@chrismeyersfsu i rebased & pushed

**Pull request merged**
