### PR TITLE
Add workflow to tower_role module

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Does https://github.com/ansible/awx/issues/6279

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
9.3.0
```

##### ADDITIONAL INFORMATION
As simple as it gets.

Didn't have it before, probably because the modules pre-dated workflows.

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
Seems pretty reasonable to me.

cc @john-westcott-iv @beeankha @squidboylan for approval.

**Comment by squidboylan** [comment]
It would be nice to have an integration test for this before merging, I can probably look into how we should do that

**Comment by AlanCoding** [comment]
That shouldn't be a huge problem because we have a file going for it

https://github.com/ansible/awx/blob/8668f2ad4692161f62a47f3517f165de10cb9d8b/awx_collection/tests/integration/targets/tower_role/tasks/main.yml

Actually, I might not have ran full integration for this yet, so I'll see about adding the example to the integration tests and running that.

**Comment by AlanCoding** [comment]
I'm not feeling as good about this integration test as I thought I would. I tried with this:

```yaml
- name: Add Joe to workflow execute role
  tower_role:
    user: joe
    role: execute
    workflow: test-role-workflow
    state: present
  register: result

- assert:
    that:
      - "result is changed"

- name: Add Joe from the workflow execute role, no-op
  tower_role:
    user: joe
    role: execute
    workflow: test-role-workflow
    state: present
  register: result

- assert:
    that:
      - "result is not changed"
```

And it didn't work. The second task had a status of changed.

But there's a problem with fixing this... that's a tower-cli bug, and no one is touching that. It's something we can return to, but we didn't test it before, and I'm pretty sure that it's a pre-existing issue.

So this adds basic use, but it's kind of low value. If I was going to go about that false changed status, then I would go straight for the unit tests.

**Comment by squidboylan** [comment]
@AlanCoding if you add that test that should do `result is not changed` and change it to `result is changed` when we fix that bug we'll remember to update that test because it will fail. However yeah i agree that we dont need to get that right since we'll fix it with our module conversions and the cli is EOL

**Comment by AlanCoding** [comment]
I would rather file an issue than add a test like that https://github.com/ansible/awx/issues/6324

**Review by squidboylan — APPROVED** [review]

**Comment by AlanCoding** [comment]
regate

**Pull request merged**
