### PR TITLE
Make minimal changes to remove Python 3 syntax errors

### PR DESCRIPTION
**Pull request by cclauss**
Ready for review: Some essential changes to prepare for Python 3.

```
$ pip install future
$ futurize --stage1 -w **/*.py
$ git commit --all -m "futurize --stage1 -w **/*.py"
$ git push --set-upstream origin futurize-stage-1
```

### CODE REVIEW

**Comment by matburt** [comment]
I'm totally fine with you doing this, but can you please rewrite the commit message to more accurately describe what's going on, see this section of the contributing doc:

https://github.com/ansible/awx/blob/devel/CONTRIBUTING.md#submitting-pull-requests

**Comment by matburt** [comment]
It'd also be good to check in on the shippable run failure.

**Comment by manishas** [comment]
hello, someone just pinged us about the shippable.yml issue.

One problem is that the `matrix` section isn't indented properly.... it should be at the same level as `env`:

```
env:
  - AWX_BUILD_TARGET=test
  - AWX_BUILD_TARGET=ui-test-ci
  - AWX_BUILD_TARGET="flake8 jshint"

matrix:   
  allow_failures:
    - python: "3.6"
```

Can you try this and let us know if it works?

**Comment by cclauss** [comment]
@manishas When it is "properly" indented like 41c110b, it does not work.  When it is not indented like both 361a909 and 88fe4ce, then it does work.  This is the opposite of what http://docs.shippable.com/platform/tutorial/workflow/shippable-yml/ demonstrates.

**Comment by manishas** [comment]
@cclauss  the document you pointed to is new and unfortunately has a bug showing wrong indentation.. I'll fix that.. 

Please refer to this for now: http://docs.shippable.com/ci/yml-structure/

Looks like your latest build is working with the right indentation.

**Comment by matburt** [comment]
Thanks for the work @cclauss, we still need you to rewrite/flatten the commits a bit see my message from before.

**Comment by matburt** [comment]
ping, otherwise we can close this and open a new one.

**Comment by cclauss** [comment]
Closing in favor of #163

**Comment by ryanpetrello** [comment]
FYI, we've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which runs under python3.6.  This version of awx also supports python2 _and_ python3 virtualenvs when running Ansible playbooks.

**Pull request closed without merging**
