### PR TITLE
Implement item copy feature

### PR DESCRIPTION
**Pull request by jangsutsr**
##### SUMMARY
Relates #283. Please use acceptance docs as a reference for review.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
awx: 1.0.1.204
```

### CODE REVIEW

**Comment by AlanCoding** [comment]
Last round of comments from me here. Final impressions from the code are:

 - the call arguments of the deep copy task really are very complex, with the sub_obj list in particular, this takes work to walk back to get its structure
 - recursive `copy_model_obj` and different return types - I would prefer to have the dual uses of the method actual refactored into 2 different methods
 - hard-coded lists of fields to copy or not copy - this is not as bad as I imagined because it's mainly for m2m things, but it's hard to know this from its name
 - the permission checking inside of the task - I have a hard time imagining peaceful outcomes for when the acting user lacks permission to a sub-component of the deep copy

None of these impressions are enough to block the moving of this feature, so I'm ready to get it moving.

For the acceptance criteria, I would like to submit for consideration the following additional actions for consideration, I would like to pass these onto @voidspace 

 - copying project shouldn't trigger project update
 - copying smart inventory should copy host filter and no hosts
 - copying a WFJT should also copy the credentials of nodes (needs issue)
 - copying as an org admin should work
 - copying as someone who doesn't have permission should give 403 for all resources
 - copying a JT with encrypted survey defaults
 - copying a credential correctly re-encrypts inputs

**Review by AlanCoding — APPROVED** [review]

**Comment by wenottingham** [comment]
> copying project shouldn't trigger project update

Why not? (for the new project only)

**Comment by AlanCoding** [comment]
You know the scm revision of the new project, it should be the same as the old one. That should be enough for subsequent syncs to work correctly. It'll have to clone the repo source tree into a new location for the copied project, that's what we want.

**Comment by wenottingham** [comment]
OK, makes sense.

**Pull request merged**
