### PR TITLE
init awx tower modules

### PR DESCRIPTION
**Pull request by chrismeyersfsu**

### CODE REVIEW

**Comment by piroux** [comment]
Is there a plan to convert the Ansible modules from `tower_cli` to the new `awxkit` sdk ?

**Comment by ryanpetrello** [comment]
@piroux we haven't decided exactly what we're going to do there (`awxkit` vs, say, `requests`), but we do plan to remove `tower-cli` usage at some point.

**Comment by AlanCoding** [comment]
Here is an old attempt to replace tower_cli or requests https://github.com/ansible/ansible/pull/48649

That is a viable approach, but it would take a lot of work.

There's also the matter of the parameter spec no longer matching up with the API, and the awxkit won't solve anything related to this anymore.

The elephant in the room for this porting right now is testing. I think it may be a near-term agenda item for me to return to these and see what kind of local testing I can do with them, maybe adding that to CI, and then open the door to convert the old tests to something more manageable.

**Comment by AlanCoding** [comment]
FYI, here is the version of this branch with relative imports:

https://github.com/ansible/awx/compare/devel...AlanCoding:awx_modules_rel

I hope to rebase and compare to what the migration tool gives me on a fresh attempt. I want to continue allowing merges into core for a little bit.

**Comment by AlanCoding** [comment]
I also realize that this does not include the tower inventory plugin right now. It seems that it should, otherwise, what's the point of collections?

**Comment by AlanCoding** [comment]
I've updated that last branch I linked to with the module after fully re-exporting it with the tool now. I wanted to be sure that I'm not missing any content that was here before which didn't come from the tool. Now everything has been accounted for.

the process I used is now documented in this branch over in the content collector:

https://github.com/ansible/content_collector/compare/master...AlanCoding:alan_migration

This won't run out-of-the-box for anyone, but it gives enough detail to be sure that you replicate the exact thing that I did.

Now, with it established how to re-generate the output from the tool, and the correctness of it, I'm going to go ahead and close this with the intent of opening a new PR with the alterations I have in mind.

**Comment by AlanCoding** [comment]
Moving to new branch with the history + tower inventory plugin.

https://github.com/ansible/awx/compare/devel...AlanCoding:awx_modules_merge

Next up will be working on opening up some testing structure.

**Comment by AlanCoding** [comment]
Welp, also missed https://github.com/ansible/ansible/blob/devel/lib/ansible/plugins/doc_fragments/tower.py

**Pull request closed without merging**
