### PR TITLE
open source awxkit

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by unlikelyzero** [comment]
I'm going to leave this to people more familiar with towerkit to review

**Review by kdelee — APPROVED** [review]
:shipit: expect more PRs from me to `awx`! :rocket:

**Review by matburt — APPROVED** [review]
This is an absolutely monumental amount of work, and nicely laid out here in the AWX source tree.

**Comment by piroux** [comment]
I am trying to understand the scope of this PR, which is quite big to digest for an outsider.

In the `awxkit/README.md`, I found :
```
Python library that backs the provided `awx` command line client.
```

From its `pages` sub-modules, I understand that it redefines all AWX objects in order to interact though the HTTP API
https://github.com/ansible/awx/pull/4451/files#diff-06ee91b3a50623f1464c8ca42b2fdf4b
https://github.com/ansible/awx/pull/4451/files#diff-f7ddb7c4c5525818c5373136c4940693R269

I feel that there is a lot of overlapping with the `tower-cli` project, so does it mean that `awxkit` is going to replace it ?

**Comment by matburt** [comment]
This is indeed intended to be the replacement for tower-cli

**Pull request merged**
