### PR TITLE
Moooore dashboard

### PR DESCRIPTION
**Pull request by kdelee**
##### SUMMARY

More cleanup in the grafana dashboard, making it work with multiple nodes and adding some organizational rows.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - Other

### CODE REVIEW

**Comment by AlanCoding** [comment]
No screenshot???

**Comment by rebeccahhh** [comment]
@AlanCoding we should have marked this as a draft, screenshots incoming though :)

**Comment by rebeccahhh** [comment]
The alert view in Grafana when _not_ firing:
alert not firing
The alert view in Grafana when pending:
alert pending
The alert view in Grafana when firing:
alert firing

**Comment by kdelee** [comment]
image
we also updated the dashboard to have foldable sections

**Review by AlanCoding — APPROVED** [review]

**Comment by fosterseth** [comment]
I'm enjoying the evolution of this dashboard, awesome work

**Review by fosterseth — APPROVED** [review]

**Review by jbradberry — APPROVED** [review]

**Pull request merged**
