### PR TITLE
[hop node] fix failing ci checks on feature_hop-node branch

### PR DESCRIPTION
**Pull request by djyasin**
##### SUMMARY

Realted #14220

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Other

##### AWX VERSION

```
22.3.1
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by djyasin** [comment]
Tests that need to be fixed on the feature branch:

- [x] api-test
- [ ] api-swagger
- [x] api-schema
- [ ] ui-lint
- [ ] ui-test-screens
- [x] awx_collection sanity

**Comment by djyasin** [comment]
> Tests that need to be fixed on the feature branch:
> 
> * [x]  api-test
> * [x]  api-swagger
> * [x]  api-schema
> * [ ]  ui-lint
> * [ ]  ui-test-screens
> * [x]  awx_collection sanity

I believe api-schema is expected to fail since we made migration changes.

**Comment by AlanCoding** [comment]
It is bizarre that the diff in https://github.com/ansible/awx/pull/13904/files doesn't show the changes that this reverts...

Looking at https://github.com/ansible/awx/pull/13904/commits, I actually see such a commit already landed https://github.com/ansible/awx/pull/13904/commits/db69f4b4def1e15e9342dbbd1662640bf5048efd

I'm still not sure what's going on, I would say you might want to try rebasing the feature branch.

**Comment by djyasin** [comment]
> It is bizarre that the diff in https://github.com/ansible/awx/pull/13904/files doesn't show the changes that this reverts...
> 
> Looking at https://github.com/ansible/awx/pull/13904/commits, I actually see such a commit already landed [db69f4b](https://github.com/ansible/awx/commit/db69f4b4def1e15e9342dbbd1662640bf5048efd)
> 
> I'm still not sure what's going on, I would say you might want to try rebasing the feature branch.

Thank you, Alan! I went ahead and rebased!

**Review by AlanCoding — APPROVED** [review]

**Review by thedoubl3j — APPROVED** [review]
sanity fix, lgtm

**Review by fosterseth — APPROVED** [review]

**Pull request merged**
