### PR TITLE
Updates PF dependency

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This updates the PF dependency.  Will be using the visual regression tests on this 1 to help catch things.

##### ISSUE TYPE
Dependency upgrade

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by AlexSCorey** [comment]
recheck

**Comment by unlikelyzero** [comment]
@AlexSCorey can you rebase on devel?

**Comment by AlexSCorey** [comment]
@unlikelyzero just updated

**Comment by AlexSCorey** [comment]
recheck

**Review by mabashian — APPROVED** [review]

**Comment by tiagodread** [comment]
Hey @AlexSCorey if the ui tests pass, we can merge this

**Review by tiagodread — APPROVED** [review]
Tests covered by https://github.com/ansible/tower-qa/pull/5707

**Pull request merged**
