### PR TITLE
add proxy support

### PR DESCRIPTION
**Pull request by snahelou**
##### SUMMARY

Add proxy support for Docker build. 

##### COMPONENT NAME
 - Installer

##### ADDITIONAL INFORMATION
Implementation of https://github.com/ansible/awx/issues/118

### CODE REVIEW

**Review by ghost — COMMENTED** [review]
no_proxy variable would be great as well, wouldn't it?

**Comment by snahelou** [comment]
Yes. It's done. 

Regards

**Review by matburt — APPROVED** [review]

**Comment by matburt** [comment]
Thanks for this!

**Comment by ghost** [comment]
Nice men i had the same idea for friday :) ! 
Thx

**Comment by ghost** [comment]
Please add those vars also in this section: https://github.com/ansible/awx/blob/devel/INSTALL.md#inventory-variables

**Pull request merged**
