### PR TITLE
added proxy settings to docker runtimes

### PR DESCRIPTION
**Pull request by st0ne-dot-at**
##### SUMMARY
added proxy settings to docker runtimes

##### ISSUE TYPE
Feature Pull Request/Bugfix Pull Request

##### COMPONENT NAME
 - Installer

##### AWX VERSION

```
1.0.0.551
```

### CODE REVIEW

**Review by matburt — CHANGES_REQUESTED** [review]
From a sheer cleanliness perspective I think it might be better to `|default(omit)`

**Comment by st0ne-dot-at** [comment]
@matburt : done

**Review by matburt — APPROVED** [review]
lgtm

**Comment by matburt** [comment]
fyi... it doesn't look like you've configured your github account properly as your commits aren't recognized:

image

It's no big deal to me, but it may be to you. I'll go ahead and merge this PR.

**Pull request merged**
