### PR TITLE
remove the x icon on the session timeout modal (it doesn't work)

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by ryanpetrello** [comment]
image

**Review by mabashian — APPROVED** [review]

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by ryanpetrello** [comment]
regate

**Comment by ryanpetrello** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Pull request merged**
