### PR TITLE
Bump react scripts to 5.0

### PR DESCRIPTION
**Pull request by nixocio**
Bump react scripts to 5.0

I was not able to run those commands inside the container to ensure version, but I verified my dev env, and I used the following versions:

after 
```npm ci```

I ran 

```npm install --save-dev --save-exact react-scripts@5.0.0```

```

(base) ➜  ui git:(ui_rs5) node -v
v14.18.3
(base) ➜  ui git:(ui_rs5) npm -v
7.24.2
```
See: https://github.com/ansible/awx/issues/11543

### CODE REVIEW

**Comment by tiagodread** [comment]
@nixocio all the brokent tests is related to notification templates, they might be the same issue

**Comment by nixocio** [comment]
@tiagodread 
> @nixocio all the brokent tests is related to notification templates, they might be the same issue

There is a newer run after I pushed some changes. The newer results did not update the link above.

[cypress](https://dashboard.cypress.io/projects/ui2mq7/runs/11570/overview?actions=%5B%5D&browsers=%5B%5D&groups=%5B%5D&isFlaky=%5B%5D&modificationDateRange=%7B%22startDate%22%3A%221970-01-01%22%2C%22endDate%22%3A%222038-01-19%22%7D&orderBy=EXECUTION_ORDER&oses=%5B%5D&specs=%5B%5D&statuses=%5B%5D&testingTypesEnum=%5B%5D)

**Review by AlexSCorey — APPROVED** [review]
@nixocio and I spoke offline and agree that many of the `eslint-disable...` comments can probably be addressed pretty easily but a separate issue will be filed to address them at a later date.

**Comment by nixocio** [comment]
This PR is affected by https://github.com/patternfly/patternfly-react/issues/5650, but the work around in place is not solving the problem.

**Comment by nixocio** [comment]
@tiagodread, I fixed the discrepancy from dev/production builds and started a new run for e2e tests. Ready to be reviewed again.

**Comment by tiagodread** [comment]
Assigning myself since I'm pairing along with @nixocio on this one

**Review by tiagodread — APPROVED** [review]
Since all e2e tests are green and all screenshots hasn't any large isse, we can go ahead and merge this one

**Pull request merged**
