### PR TITLE
fix a permissions bug for credentials specified at JT launch time

### PR DESCRIPTION
**Pull request by ryanpetrello**
hat tip to @alancoding for spotting this one

### CODE REVIEW

**Comment by AlanCoding** [comment]
Did we ever test this case for providing inventory?

**Comment by ryanpetrello** [comment]
@AlanCoding it's possible inventory suffers a _similar_ bug (i.e., if you manually specify an unauthorized inventory primary key in the launch payload that's already set on `JT.inventory`); I haven't tested to confirm (nor does this PR address it if it is a bug)

This PR *definitely* solves a bug in our handling of launch-time credentials in this regard.

**Comment by ryanpetrello** [comment]
@cchurch I've also tossed in fixes for a few of your more notable perf. suggestions on my original multi-credential PR

**Comment by AlanCoding** [comment]
> it's possible inventory suffers a similar bug (i.e., if you manually specify an unauthorized inventory primary key in the launch payload that's already set on JT.inventory); I haven't tested to confirm (nor does this PR address it if it is a bug)

Both cases were probably pre-existing before the multi-credential change. Because it has some impact on the user experience, I want to make an issue and hand it off to QE. I'll wind up moving this code around with the saved launch configurations soon.

**Review by AlanCoding — APPROVED** [review]

**Pull request merged**
