### PR TITLE
Replace known py3 virtualenv invocations with `python -m venv`

### PR DESCRIPTION
**Pull request by wenottingham**
##### SUMMARY

This allows not having an additional dependency on a separate virtualenv package for py3.

##### ISSUE TYPE
 - Feature Pull Request

### CODE REVIEW

**Comment by shanemcd** [comment]
Some context... we use `virtualenv` everywhere because the `venv` module does not use / respect `no-global-site-packages.txt`. If we do this, we'll need to add a step that uses the appropriate config file entry.

https://stackoverflow.com/a/40972692

**Comment by shanemcd** [comment]
We'll need to figure this out regardless because newer versions of `virtualenv` also use a config file. We're currently pinning to `>20`

**Comment by wenottingham** [comment]
> We'll need to figure this out regardless because newer versions of `virtualenv` also use a config file. We're currently pinning to `>20`

We don't appear to be pinning in AWX at the moment, although I think I can see why.

**Comment by wenottingham** [comment]
This is messy.

**Pull request closed without merging**
