### PR TITLE
Update Mesh.js to allow for running AWX at non-root path (URL prefixing)

### PR DESCRIPTION
**Pull request by rakesh561**
Update Mesh.js to allow for running AWX at non-root path (URL prefixing)

##### SUMMARY
This is in regards to issue #13824.PR allow's for running AWX at non-root path.
Updated /api/v2 to api/v2 in job_events.js as other files seems to be following pattern api/v2/
##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API
 - UI

### CODE REVIEW

**Comment by rakesh561** [comment]
Any FeedBack ?

**Comment by fosterseth** [comment]
@mabashian I still see a lot of `/api/v2` references in the source code, so I'm wondering if there are other places we'd want to make similar changes to allow supporting AWX at non-root url path.

**Comment by mabashian** [comment]
@fosterseth @rakesh561 I think this makes sense.  The only other place where I saw a leading `/` was this line: https://github.com/ansible/awx/blob/devel/awx/ui/src/api/models/Root.js#L7

All of the other instances are in tests/test data files

@rakesh561 if you can make the change in Root.js as well and rebase your PR we can probably get it merged in.

**Comment by rakesh561** [comment]
@mabashian thank you for the help.Did the requested changes also rebased the branch

**Comment by rakesh561** [comment]
I see some failures do i need to change some thing in the code ?

**Review by fosterseth — APPROVED** [review]

**Comment by fosterseth** [comment]
@rakesh561 merged! thanks for your contribution on this

**Pull request merged**
