### PR TITLE
Updates to workflow node details link

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link https://github.com/ansible/awx/issues/2936 

This PR changes the link from a svg text element to a foreignObject wrapping an `<a href>` element.  This will allow users to open this link in a new tab.  I also double checked to make sure that the link was being updated as soon as the job is available so clicking on it while the job is running should be functioning.

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by mabashian** [comment]
~~Update: this does not fix https://github.com/ansible/awx/issues/2935~~

Update: this does fix #2935

It fixes is in an undesirable way though.  The UI makes a GET request on the workflow nodes endpoint when the page first renders in order to build the graph.  Since we make that request so early, `summary_fields.job.type` does not yet exist for any of the nodes.  This field is great for loading the graph _after_ the workflow is finished running but doesn't really help us while it's running.  To get around this, I've added logic to make a GET request on a node whenever a socket message comes in and we notice that we don't have the job type that we need to build the details link.  It would be _really_ nice if the api could pass us this flag in the socket message.  That would save us from having to perform any GET requests in order to build the correct link.  If this is not possible then we can stick with the solution at hand but I'm concerned about it's impact on performance especially on really large split jobs where lots of socket messages could be coming in really early.

An alternative (UI only) solution would be for us to set up a dedicated route that would act like a switch.  We would point the user to that URL and pass the unified_job_id and that route would perform the GET and then redirect the user to the appropriate place.  This would allow us to support #2936 without having to make a bunch of GET requests.  If adding the type to the socket message is not an option then I'd definitely be willing to consider this as an alternative.

@AlanCoding I'd be curious to hear your thoughts on this subject.  

There's a lot of relevant dialogue around this same topic here: https://github.com/ansible/awx/issues/2465

**Comment by jakemcdermott** [comment]
@AlanCoding @mabashian 

This is the dedicated route approach discussed above: https://github.com/mabashian/awx/pull/2/files.

The idea here is we setup a dedicated route that fetches the unified job and conditionally redirects to the appropriate viewer based on job type. We then link to this route from the workflow job viewer for all playbook job nodes.

It's admittedly a bit of a hack but it seems to work well-enough.  If we want to take this approach we can pull one or both of these commits into this PR for #2935.

wflink

**Comment by AlanCoding** [comment]
I need to catch up more fully on Monday, but if adding `type` to summary_fields somewhere can help the UI out, I find this very reasonable to expect of the API, we just need to formalize what schema we intend to change and when we will do it.

**Comment by jakemcdermott** [comment]
~@AlanCoding sounds good - if we can do it that way it'd be preferable~

edit: out of date - we ended up going with https://github.com/ansible/awx/pull/2938#issuecomment-447519724 for various reasons

**Review by marshmalien — APPROVED** [review]
Tested this locally. LGTM 👍

**Review by dsesami — APPROVED** [review]
seems good on a local build, approved

**Comment by unlikelyzero** [comment]
Verified the following:

- Workflow node Details link can be opened while the job is running and the user is navigated to the job events page for a JT, Project Sync and Inventory Sync
- Workflow node details link can be opened after the job is run and the user is navigated to the completed job events page for a JT, Project Sync and Inventory Sync
- Workflow node details link can be right clicked to open up another tab.
- Workflow node details link can be opened after the job is finished for failed JT and Project Sync jobs

Light Regression Testing:

- Workflow Node Creation flow.
- Pan, Home, and Zoom functionality
- Firefox ESR tested

**Comment by kialam** [comment]
re-gate

**Comment by shanemcd** [comment]
regate

**Comment by unlikelyzero** [comment]
zuul plz

**Comment by kialam** [comment]
Regate

**Pull request merged**
