### PR TITLE
basestring to six.string_types for Python 3

### PR DESCRIPTION
**Pull request by cclauss**
__basestring__ was removed in Python 3 in favor of __str__ so this PR replaces all instance of __basestring__ with __six.string_types__.

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
👍 assuming tests pass

**Comment by cclauss** [comment]
@ryanpetrello I can not make sense of the Shippable log

**Comment by wenottingham** [comment]
@cclauss transient build error pulling from EPEL.  *Should* be unrelated.

**Comment by cclauss** [comment]
In Shipable, is there a way to rerun the failing test?

**Comment by shanemcd** [comment]
```
$ git commit --amend --no-edit
$ git push -f remote branch
```

**Review by AlanCoding — APPROVED** [review]

**Comment by ryanpetrello** [comment]
FYI, we've just released a new version of awx (https://github.com/ansible/awx/releases/tag/3.0.0) which runs under python3.6.  This version of awx also supports python2 _and_ python3 virtualenvs when running Ansible playbooks.

**Pull request merged**
