### PR TITLE
Retry chromium download in zuul

### PR DESCRIPTION
**Pull request by jakemcdermott**
##### SUMMARY
¯\_(ツ)_/¯

### CODE REVIEW

**Comment by jakemcdermott** [comment]
retry

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Review by keithjgrant — APPROVED** [review]

**Pull request merged**
