### PR TITLE
Removes references to current_user 

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
Removes current_user data from the cookie on the api and remove references to it on the UI side.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API
 - UI

### CODE REVIEW

**Comment by AlexSCorey** [comment]
kicking off e2e test

**Comment by AlexSCorey** [comment]
Needs QE manual testing.  Go through reproduction test and confirm bug is fixed.

**Review by mabashian — APPROVED** [review]
Looks good to me.  I did some manual testing with different users and timeout scenarios and it works like I would expect it to.

**Review by AlanCoding — APPROVED** [review]
I don't have any comments on the UI side, but this needed to be done. Thanks for getting that taken care of.

**Review by keithjgrant — APPROVED** [review]

**Pull request merged**
