### PR TITLE
Add organization to execution environments list/details

### PR DESCRIPTION
**Pull request by nixocio**
Add organization to execution environments list/details.

See: https://github.com/ansible/awx/issues/7886
Also: https://github.com/ansible/awx/issues/8171

List:

image

Details:

image

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@dsesami to quick review without delay

**Review by jakemcdermott — COMMENTED** [review]
The lists lgtm, let's get this rebased first and I think this'll be ready for some testing.

**Comment by nixocio** [comment]
@jakemcdermott, PR rebased.

**Review by mabashian — APPROVED** [review]

**Comment by dsesami** [comment]
assigning to tiago and john as part of handoff

**Comment by unlikelyzero** [comment]
@nixocio We are not going to review EE PRs in QE until we get the backfill

**Comment by nixocio** [comment]
recheck

**Comment by nixocio** [comment]
regate

**Comment by jakemcdermott** [comment]
recheck

**Pull request merged**
