### PR TITLE
make the callback receiver more robust to duplicate UUIDs from ansible

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Review by matburt — APPROVED** [review]

**Review by AlanCoding — APPROVED** [review]

**Comment by ryanpetrello** [comment]
I've had trouble tangibly reproducing this, but it's at least something that people have seen in practice:

https://github.com/ansible/awx/issues/3761

Specifically: https://github.com/ansible/awx/issues/3761#issuecomment-495384872

**Comment by ryanpetrello** [comment]
regate

**Comment by ryanpetrello** [comment]
regate

**Comment by jakemcdermott** [comment]
recheck

**Pull request merged**
