### PR TITLE
Refactors and redesigns workflow approval to impove UX

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
Addresses #12512.  Moves approve, deny, cancel buttons to be in the row items instead of in the toolbar.  This puts us more inline with UXD recommendations

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by mabashian** [comment]
@AlexSCorey I noticed that after I approved a workflow the approve and cancel buttons got greyed out but the deny button was still enabled.  It's showing the correct tooltip.

Screen Shot 2022-07-29 at 3 03 02 PM

The same thing happens in reverse if I deny an approval, the approve button remains enabled but with a tooltip saying that it's already been denied.

**Comment by mabashian** [comment]
@AlexSCorey I think there's something funny going on with cancelling an approval:

workflow_approval_cancel

The same thing happens when trying to delete from the workflow approval detail.

**Comment by kialam** [comment]
I don't see the wf approval details page refresh after clicking the "Cancel" button. This could be a local issue on my end. @akus062381 @InnocentK @jay-steurer are you able to reproduce the issue as well?
nipkwE94Hk

**Comment by kialam** [comment]
This compiler warning should be fixed before merging:

```
src/components/JobCancelButton/JobCancelButton.js
  Line 32:8:  React Hook useCallback has a missing dependency: 'onCancelWorkflow'. Either include it or remove the dependency array. If 'onCancelWorkflow' changes too often, find the parent component that defines it and wrap that definition in useCallback  react-hooks/exhaustive-deps
```

**Review by kialam — APPROVED** [review]
Good to merge once warnings are fixed.

**Pull request merged**
