### PR TITLE
Convert SchedulesList, WorkflowApprovalList to tables

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Converts SchedulesList and WorkflowApprovalList components to use PaginatedTable

addresses #6189 

schedules-table

approvals-table

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by AlexSCorey** [comment]
@keithjgrant found this issue in your PR, though it doesn't appear in your screen shots.  Can you confirm whether it's actually an issue?
Screen Shot 2021-01-13 at 1 32 30 PM

**Comment by keithjgrant** [comment]
@AlexSCorey That came up in a previous PR as well (when no header cell is given), though it didn't occur in my screenshot above. I suspect there's a particular version of PF that causes this, but I'll have to investigate whether it's a newer version that does it, or if this is a bug they have fixed on their end recently.

**Comment by tiagodread** [comment]
Hey @keithjgrant we're missing the actions <thead> here:

image

**Review by tiagodread — APPROVED** [review]
Ok, this worked as expected for schedules/workflowApproval and for schedules tab as well. I'm fixing some e2e broken tests in https://github.com/ansible/tower-qa/pull/5934

**Pull request merged**
