### PR TITLE
Set React to Strict Mode

### PR DESCRIPTION
**Pull request by nixocio**
Set React to Strict Mode.

See: https://reactjs.org/docs/strict-mode.html

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by dsesami** [comment]
@nixocio to close this out, can you run yolo + cypress against this branch? let me know if you need help knowing what flags to set. If it's green we can +1, if there are test issues let me know and we can look together.

**Comment by nixocio** [comment]
For future reference: I ran the cypress + yolo against this branch and since we are currently using dev mode to run the CI, `strict mode + npm start causes a ClosedChannelException and general freakout in CI` - by @dsesami . Thus closing this one.

**Comment by nixocio** [comment]
It was re-evaluated the output of jobs, re-opened this one.

**Comment by dsesami** [comment]
@nixocio is this still in needs_test or is there further work to be done?

**Comment by nixocio** [comment]
@dsesami, as soon as you say it's ok, let's merge this PR.

**Pull request merged**
