### PR TITLE
Update UI build system

### PR DESCRIPTION
**Pull request by gconsidine**
* Faster build times
* Smaller bundle sizes
* Adjust paths
* Cleanup npm dependencies
* Remove unneded Grunt tasks

Comparison:

Item | Old | New
------------ | ------------- | -------------
Build Time (dev) | 1m15.4s | 23.5s
vendor.js size | 13.9 MB | 4.4 MB
app.js size | 8.7 MB | 4.1 MB
vendor.css size | 200 KB | 194 KB
app.css size | 293 KB | 271 KB

Many of the file changes are due to small path updates and some minor restructuring. Full compatibility should be retained for the existing Make and npm targets.

Note: In order to leverage Webpack's dev server, `templates/ui/index.html` is generated from `client/src/index.template.html`. 

To test out this change:

* Remove `node_modules`
* `npm i` (from `awx/ui`)
* Use one of the following:
  * `npm run dev` for dev build
  * `npm run watch` for continuous dev (@ `http://localhost:3000`)
... Or if you prefer the make targets from the project root:
  * `make ui-devel`
  * `make ui-docker`

### CODE REVIEW

**Review by wwitzel3 — APPROVED** [review]
LGTM and tested successfully using:

    make clean-ui
    make ui-devel

**Comment by jakemcdermott** [comment]
I gave this a whirl by running:

```
make clean-ui
npm --prefix awx/ui install
npm --prefix awx/ui run watch
```

From there I changed various files to check out the syncing behavior and everything seems to be working smoothly. 👍

**Comment by gconsidine** [comment]
Cool, thanks for taking a look guys. I want to take another stab at resolving the extraneous `/` in the static file paths this morning before bringing this one in.

**Comment by mabashian** [comment]
Followed the same steps that @jakemcdermott outlined and everything seems to be working as expected.

**Review by jaredevantabor — APPROVED** [review]
Nice work! This will help speed up development and it's nice to see the misdirection in the build process become more straightforward. 🌮 👍

**Pull request merged**
