### PR TITLE
Make sure project updates run in default EE

### PR DESCRIPTION
**Pull request by AlanCoding**
replaces https://github.com/shanemcd/awx/pull/27 because base branch moved

### CODE REVIEW

**Comment by AlanCoding** [comment]
I rebuilt the UI, and navigated around. I'm not seeing any console errors.

It looks like we have not yet hooked up the fields for JT / project

@nixocio, does that sound right to you? Can you anticipate any fallout from removing this field from the API?

**Review by jbradberry — APPROVED** [review]
Still looks good to me, but per my comment elsewhere, we need to make sure that the UI also loses this field for Projects.

**Comment by AlanCoding** [comment]
I can't find it anywhere in the UI, navigating to the project form, neither field is present. It looks like the UI has only added the execution environments list so-far.

**Comment by nixocio** [comment]
hey @AlanCoding, that seems right.

**Comment by nixocio** [comment]
Also we are tracking the work related to EE and UI on this issue, https://github.com/ansible/awx/issues/7884, if we are missing something, please file an issue.

**Pull request merged**
