### PR TITLE
Disabled undefined variable "scm_full_checkout"

### PR DESCRIPTION
**Pull request by 1it**
##### SUMMARY
Fixed the galaxy requirements install task.
Disabled the undefined variable "scm_full_checkout" on task 'fetch galaxy roles from requirements.yml'. 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
awx: 1.0.1.144
```

##### ADDITIONAL INFORMATION
Before:
```
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
changed: [localhost]

TASK [update project using git and accept hostkey] *****************************
skipping: [localhost]

TASK [Set the git repository version] ******************************************
skipping: [localhost]

TASK [update project using git] ************************************************
changed: [localhost]

TASK [Set the git repository version] ******************************************
ok: [localhost]

TASK [update project using hg] *************************************************
skipping: [localhost]

TASK [Set the hg repository version] *******************************************
skipping: [localhost]

TASK [update project using svn] ************************************************
skipping: [localhost]

TASK [Set the svn repository version] ******************************************
skipping: [localhost]

TASK [update project using svn with auth] **************************************
skipping: [localhost]

TASK [Set the svn repository version] ******************************************
skipping: [localhost]

TASK [Ensure the project directory is present] *********************************
skipping: [localhost]

TASK [Fetch Insights Playbook(s)] **********************************************
skipping: [localhost]

TASK [Save Insights Version] ***************************************************
skipping: [localhost]

TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
skipping: [localhost]

TASK [parse subversion version string properly] ********************************
skipping: [localhost]

TASK [parse hg version string properly] ****************************************
skipping: [localhost]

TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version ca1cca4426d3a7acb34f56d9724ba03b46ec2e3d"
}

TASK [Write Repository Version] ************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=0   
```

After:
```
Using /etc/ansible/ansible.cfg as config file

PLAY [all] *********************************************************************

TASK [delete project directory before update] **********************************
skipping: [localhost]

TASK [update project using git and accept hostkey] *****************************
skipping: [localhost]

TASK [Set the git repository version] ******************************************
skipping: [localhost]

TASK [update project using git] ************************************************
changed: [localhost]

TASK [Set the git repository version] ******************************************
ok: [localhost]

TASK [update project using hg] *************************************************
skipping: [localhost]

TASK [Set the hg repository version] *******************************************
skipping: [localhost]

TASK [update project using svn] ************************************************
skipping: [localhost]

TASK [Set the svn repository version] ******************************************
skipping: [localhost]

TASK [update project using svn with auth] **************************************
skipping: [localhost]

TASK [Set the svn repository version] ******************************************
skipping: [localhost]

TASK [Ensure the project directory is present] *********************************
skipping: [localhost]

TASK [Fetch Insights Playbook(s)] **********************************************
skipping: [localhost]

TASK [Save Insights Version] ***************************************************
skipping: [localhost]

TASK [detect requirements.yml] *************************************************
ok: [localhost]

TASK [fetch galaxy roles from requirements.yml] ********************************
changed: [localhost]

TASK [parse subversion version string properly] ********************************
skipping: [localhost]

TASK [parse hg version string properly] ****************************************
skipping: [localhost]

TASK [Repository Version] ******************************************************
ok: [localhost] => {
    "msg": "Repository Version 3f44f8baac8df94e640b3609b3ad452c7d68f1e5"
}

TASK [Write Repository Version] ************************************************
changed: [localhost]

PLAY RECAP *********************************************************************
localhost                  : ok=6    changed=3    unreachable=0    failed=0   
```

### CODE REVIEW

**Comment by wenottingham** [comment]
That's not how it's supposed to work - scm_full_checkout is set when the project is checked out before running jobs - that's when roles are checked out.

What is the issue you're seeing?

**Comment by 1it** [comment]
@wenottingham I see that galaxy requirements installation/update task not working with that variable, at all.

**Comment by wenottingham** [comment]
What's the error / playbook output?

**Comment by 1it** [comment]
@wenottingham I attached the logs and screenshots to initial message.

**Comment by wenottingham** [comment]
Right, that's the project update that merely grabs the revision to use. 

What does it do for the project update that actually checks out the source to use? You can get to it by clicking on the green circle icon next to the project from the job output screen.

**Comment by matburt** [comment]
ping ^

To reiterate what @wenottingham said... the `Project Update` that you are linking to... which is the update triggered from the project screen is responsible, primarily, for grabbing a revision of the source tree.

The one that @wenottingham is talking about... that runs when the job runs is what is responsible for actually making sure that the files are available.

**Comment by 1it** [comment]
Ok, now I understand. It was not clear enough to me, why this task (install the requirements) isn't working when I try to manually update the project.
Sorry for the misunderstanding.
Thank you guys @wenottingham @matburt

**Pull request closed without merging**
