### PR TITLE
Fix up request tower ps script

### LINKED ISSUE #9434: request_tower_configuration.ps1 problem windows 2012 and 2016
We have to limit this because of limited volunteer time to respond to issues! -->

##### ISSUE TYPE
 - Bug Report

##### SUMMARY
`request_tower_configuration.ps1` doesn't run on windows 2012 and 2016

##### ENVIRONMENT
* AWX version: 17.0.1
* AWX install method: ansible tower
* Ansible version:  2.9.15
* Operating System: Red Hat Enterprise Linux release 8.3 (Ootpa)
* Web Browser: Firefox 85.0.1

##### STEPS TO REPRODUCE

1. download  the latest version of request_tower_configuration.ps1
https://github.com/ansible/awx/blob/devel/tools/scripts/request_tower_configuration.ps1

2. Execute Powershell
3. Set Execution policy to Unrestricted (ref http://go.microsoft.com/fwlink/?LinkID=135170 )
$ `Set-ExecutionPolicy -ExecutionPolicy Unrestricted`
(confirm yes at the request)
```
PS C:\Users\Administrator> Set-ExecutionPolicy -ExecutionPolicy Unrestricted

Execution Policy Change
The execution policy helps protect you from scripts that you do not trust. Changing the execution policy might expose you to the security risks described in the about_Execution_Policies help topic at http://go.microsoft.com/fwlink/?LinkID=135170. Do you want to
change the execution policy?
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "N"): a
```
4. Execute request_tower_configuration.ps1
`$ C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c fc951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
`
5. Get Powershell version with
`$ (Get-Host).Version
`

##### EXPECTED RESULTS

Like windows 2019
```
PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c f c951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
403 received... retrying in 1 minute (Attempt 1)
PS C:\Users\Administrator> 

```

##### ACTUAL RESULTS

- Windows 2012 - Powershell version (5.1.14409.1018)
```

Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c fc951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
C:\Users\Administrator\Desktop\request_tower_configuration.ps1 : The property 'StatusCode' cannot be found on this
object. Verify that the property exists.
At line:1 char:1
+ C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s htt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [request_tower_configuration.ps1], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,request_tower_configuration.ps1

PS C:\Users\Administrator>
```
- Windows 2016 - Powershell version (5.1.14393.3866)

```
Windows PowerShell
Copyright (C) 2016 Microsoft Corporation. All rights reserved.

PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s https://10.0.121.63 -k -c f c951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
C:\Users\Administrator\Desktop\request_tower_configuration.ps1 : The property 'StatusCode' cannot be found on this object. Verify that the property exists.
At line:1 char:1
+ C:\Users\Administrator\Desktop\request_tower_configuration.ps1 -s htt ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [request_tower_configuration.ps1], PropertyNotFoundException
    + FullyQualifiedErrorId : PropertyNotFoundStrict,request_tower_configuration.ps1

PS C:\Users\Administrator>

```
##### ADDITIONAL INFORMATION

It runs without errors when run without arguments:
```
PS C:\Users\Administrator> C:\Users\Administrator\Desktop\request_tower_configuration.ps1
Request server configuration from Ansible Tower

Usage:
    Execution using positional parameters:
    request_tower_configuration.ps1 https://example.towerhost.net 44d7507f2ead49af5fca80aa18fd24bc 38

    Ignore self-signed certificates using named parameters:
    request_tower_configuration.ps1 -k -s https://example.towerhost.local -c 44d7507f2ead49af5fca80aa18fd24bc -t 38

    Execution using optional extra_vars:
    request_tower_configuration.ps1 https://example.towerhost.net 44d7507f2ead49af5fca80aa18fd24bc 38 '{ key: value, dic
t: { key: value }}'

Options:
    -help, -h                                Show this message
    -tower_url, -s                           Tower server (e.g. https://<server address>[:server port]) (required)
    -insecure, -k                            Allow insecure SSL connections and transfers
    -host_config_key, -c <host config key>   Host config key (required)
    -job_template_id, -t <job template id>   Job template ID (required)
    -extra_vars, -e [<extra vars>]           Extra variables
```

### PR DESCRIPTION
**Pull request by jborean93**
##### SUMMARY
Fixes the `request_tower_configuration.ps1` script with the following:

* Added PowerShell 6+ support, can now run on Linux
* Removes the uneeded strict and ErrorActionPreference settings which could impact the global settings
* Enables TLS 1.2 support on Windows PowerShell
* Fixes `-insecure` handling for certificates
  * Works across ps versions
  * Original didn't actually work (at least in my testing)
  * Hopefully doesn't impact the global state
* Fixes IE not loaded error on Windows PowerShell when running on a new profile
* Changes the encoding to UTF-8 (no BOM) and made it executable
  * Can now be invoked on Linux like `./request_tower_configuration.ps1 ...`
  * There are no non-ASCII chars in the script so this won't matter on Windows

Fixes https://github.com/ansible/awx/issues/9434

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Tools

##### AWX VERSION
```
N/A
```

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
@jborean93

Wow, thanks for fixing this up for us.  However.



I know nothing about PowerShell 😂

So I'm fine merging this given that we know it's broken now, but I also have _no idea_ if this new approach is correct either 😄

**Comment by ryanpetrello** [comment]
This might be the type of PR @ghjm would be willing to give a glance at and lend some review feedback (if any is necessary) 😉

**Comment by jborean93** [comment]
@ryanpetrello no worries. I didn’t actually have a tower instance to test with but I just targeted `https://httpbin.org/status/200` (with a slightly modified get call) to simulate the behaviour around the various http calls and what tower could return. It worked fine for the various platforms I worked on but I can’t guarantee it is completely bug free. Happy to fix up any future bugs that may arise because of these changes.

**Comment by ghjm** [comment]
> This might be the type of PR @ghjm would be willing to give a glance at and lend some review feedback (if any is necessary) 😉

Then again, it might not be.  I don't have anything set up that uses provisioning callbacks, and @jborean93's PowerShell is clearly better than mine.

**Comment by lucab85** [comment]
I confirm that with #9673 solves issue #9434.
I was able to test the reproducer on Windows 2012 and Windows 2016 machines against Ansible Tower and this is the output after #9673:
```
C:\Users\Administrator\Desktop\request_tower_configuration_9673.ps1 -s https://10.0.121.63 -k -c fc951820-04eb-4a27-9c9c-d9a1c01f48ff -t 42
400 (BadRequest) received...  retrying in 1 minute (Attempt 1)
```
The connection was successful after the first try on Windows 2012 and Windows 2016 machines.

**Pull request merged**
