### PR TITLE
Reduce duplicate fetches after saving inventory group

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Reduces the number of duplicate requests when saving inventory group.

Addresses part of #10655

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by nixocio — APPROVED** [review]

**Comment by akus062381** [comment]
@keithjgrant - upon testing this- when I access the groups tab inside of an inventory, click Add, create the group and click Save, I see this: (all the 1/ are the inventory, and all the 2/ are the new group
image


When accessing the groups tab inside of a Host, clicking Associate, selecting a Group, and then from the list, editing that group- I see this upon saving the edit: (the 1/ is the inventory GET requests and the 2/ is the group GET requests (all except for the first 2/, which is PATCH)
image

**Comment by keithjgrant** [comment]
See comment at https://github.com/ansible/awx/issues/10655#issuecomment-993762092

There's a deeper issue here to dig into, so this PR does not fix everything. But I think as long as these changes are an improvement on devel, we should look to merge

**Comment by akus062381** [comment]
testing on 12/20:

Creating a group inside the groups tab of an inventory:
image

Associating a group to a host on the groups tab inside of a host:
Confirmed as fixed. (yay)

Creating a schedule inside of a workflow job template:
image

Associating a team to a user:
confirmed as fixed

**Comment by akus062381** [comment]
since two outstanding issues have been fixed on this PR, i propose we merge this and continue fixing the issue in a subsequent PR. @keithjgrant ? @nixocio ?

**Comment by nixocio** [comment]
@akus062381 I agree. Lets make sure that no other regression was added.  I just triggered the e2e test run.

**Comment by akus062381** [comment]
@keithjgrant please rebase and then we can merge

**Comment by akus062381** [comment]
@nixocio are you able to rebase this branch? I think that is the reason for the failures

**Comment by nixocio** [comment]
@akus062381 I just triggered the tests again - PR was rebased.

**Review by akus062381 — APPROVED** [review]

**Pull request merged**
