### PR TITLE
cli: add the ability to specify a token description w/ `awx login`

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/6122

### CODE REVIEW

**Comment by ryanpetrello** [comment]
```shell
~ awx login --description "Ryan Made This Token"
{
     "token": "KaTJYPYZHrLEK7Wfn6jlxldv1U4J5G"
}
~ awx login
{
     "token": "2ldHxTRtD79u8n8UKxLYICzlcdA31Y"
}
~ awx tokens list | jq '.results[].description'
"Ryan Made This Token"
"AWX CLI"
```

**Review by rooftopcellist — APPROVED** [review]
This makes sense and is a good addition.  Thanks!

**Review by beeankha — APPROVED** [review]
🚀

**Review by jbradberry — APPROVED** [review]
hm, cool

**Pull request merged**
