### PR TITLE
 Add tooltips to inventory sync status icons on Inventory List

### PR DESCRIPTION
**Pull request by nixocio**
See: https://github.com/ansible/awx/issues/7676

image

image

### CODE REVIEW

**Comment by unlikelyzero** [comment]
This will require some additional coverage and we may not have existing examples of generating the different inventory sync states via awxkit

**Comment by nixocio** [comment]
@unlikelyzero, I still working on this one. It is a WIP PR.

**Review by jakemcdermott — APPROVED** [review]

**Comment by unlikelyzero** [comment]
@jakemcdermott can you help us understand the various states that this icon would reflect?

**Comment by tiagodread** [comment]
@nixocio hey, could you rebase this one?

**Comment by nixocio** [comment]
> @nixocio hey, could you rebase this one?

@tiagodread , I will follow up about this one. Mainly in how to address this one with the newly added tables work.

**Comment by unlikelyzero** [comment]
@keithjgrant and @nixocio do we want to implement this as-is or wait for lists (which will change this PR drastically)

**Comment by tiagodread** [comment]
@nixocio any update in this PR?

**Comment by nixocio** [comment]
@tiagodread, we are re-evaluating if this work still relevant with the introduction of tables.

**Comment by nixocio** [comment]
Closing this one. It was replaced by https://github.com/ansible/awx/pull/9170 using the newly added tables work.

**Pull request closed without merging**
