### PR TITLE
Enable source variables for Azure inventory

### PR DESCRIPTION
**Pull request by paneu**
##### SUMMARY

Enable source variables to be set for Azure Resouce Manager Inventory Sources within azure_rm.ini. This is mostly copied and adapted from the other inventory sources that have this enabled already.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

  - UI

##### AWX VERSION

```
awx: 1.0.6.6
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by matburt — APPROVED** [review]

**Review by jaredevantabor — APPROVED** [review]

**Comment by ryanpetrello** [comment]
It would be awesome to have unit test coverage for this code, even if it just meant updating this existing test:

https://github.com/ansible/tower/blob/devel/awx/main/tests/unit/test_tasks.py#L1863

You could assign `source_vars` here:
https://github.com/ansible/tower/blob/devel/awx/main/tests/unit/test_tasks.py#L1881
```python
self.instance.source_vars = '{"foo": "bar"}'
```

And then make assertions about the contents of the generated `.cfg` file here:
https://github.com/ansible/tower/blob/devel/awx/main/tests/unit/test_tasks.py#L1897

The easiest way to run these tests is exec'ing into the container and running `make test_unit`:

```shell
~ docker exec -it <container-name> bash
[root@awx /]# make test_unit
```

**Comment by paneu** [comment]
I have extended the unit test as you explained. Let me know if this is the way you intended.

**Comment by ryanpetrello** [comment]
@paneu do you mind rebasing `devel` against your branch so we can run the latest unit tests?  It looks like your branch was started in mid May.

```shell
~ git remote add upstream git@github.com:ansible/awx.git
~ git fetch upstream
~ git rebase upstream/devel
~ git push -f origin azure-rm-inv-variables
```

**Comment by paneu** [comment]
@ryanpetrello Done

**Comment by ryanpetrello** [comment]
@paneu I'm poking around to see if I can figure out what's up w/ the CI failures.

**Comment by ryanpetrello** [comment]
@paneu sorry about this - mind another rebase?  We've just resolved the unrelated CI failure: https://github.com/ansible/awx/pull/2019

**Comment by paneu** [comment]
@ryanpetrello No worries, thanks for having a look at this PR. The tests have run now, although there are still some test failures left it seems.

**Comment by ryanpetrello** [comment]
@paneu yep, those failures are unrelated to your PR (I'm about to fix them, too), so I'm happy merging this.  Thanks for contributing it!

**Comment by jomeier** [comment]
Hi,

I tagged all my VMs with the tag:

type:cluster

I tried to list only this VMs with the source variables. But whatever I put into the source variable field, it has no effect. Always all resources are loaded into the inventory.

This is what I entered in the source variable input field in the UI:
```
AZURE_TAGS:
  type:cluster
```

If I copy the azure_rm.py script into the inventory script feature of AWX, everything works as expected with the code above.

AWX 1.0.6.23

**Comment by paneu** [comment]
@jomeier I think you might have to quote the string to avoid any amiguity, like this:
```
AZURE_TAGS: 'type:cluster'
```
Have you tried it this way?

**Pull request merged**
