### PR TITLE
Add timeout & slice count to the job field whitelist.

### PR DESCRIPTION
**Pull request by wenottingham**
##### SUMMARY

Allow them to be set by JT admins even if they can't access the project/inventory/creds.

### CODE REVIEW

**Comment by wenottingham** [comment]
Note... currently testing.

**Comment by wenottingham** [comment]
See https://github.com/ansible/awx/issues/2798

**Review by ryanpetrello — APPROVED** [review]
If this seems to fix the issue(s) in question, I'm 👍 on merging this.

**Review by AlanCoding — APPROVED** [review]
frankly not worried about testing this

**Comment by ryanpetrello** [comment]
I'm fine with merging this PR as-is; I just want an answer about whether it _solves_ the related issues (or if there's more to them).

@wenottingham if you test it and those fields become editable, I'm good to `mergeit`.

**Comment by wenottingham** [comment]
Tested in dev env - works. Changing inventory still yields -EPERM as expected.

**Pull request merged**
