### PR TITLE
fix french typos

### PR DESCRIPTION
**Pull request by aperigault**
##### SUMMARY
fix typos in french translation for settings screens

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
19.3.0
```

### CODE REVIEW

**Comment by shanemcd** [comment]
@rooftopcellist I think these will need to be fixed in whatever translation service we use these days. Can you confirm?

**Comment by rooftopcellist** [comment]
Yes, before merging, these changes need to approved by our translation team.  Once approved, we have the option of merging them here, and they will be marked as fuzzy strings to be confirmed again when we send out the next batch of strings.  I am waiting to hear back from our translators on this one.

**Review by rooftopcellist — APPROVED** [review]

**Comment by rooftopcellist** [comment]
recheck

**Comment by rooftopcellist** [comment]
@aperigault Do you mind force pushing to this branch?  It looks like what happened is the awx-operator check was added after the last CI run on this PR.  Pushing again will change the commit hash and kick off CI again with the new check.  Sorry for the inconvenience.

**Comment by aperigault** [comment]
Hi @rooftopcellist I rebased my branch and force pushed.

**Comment by rooftopcellist** [comment]
Thanks @aperigault !

**Pull request merged**
