### PR TITLE
Fix collection sanity

### PR DESCRIPTION
**Pull request by thedoubl3j**
##### SUMMARY

related #5465 

##### ISSUE TYPE

 
 - Bugfix Pull Request

##### COMPONENT NAME

 - API

##### AWX VERSION

```
NA
```

##### ADDITIONAL INFORMATION

```
make test_collection_sanity 
Running sanity test 'use-compat-six' with Python 3.7
Running sanity test 'validate-modules' with Python 3.7
ERROR: Found 3 validate-modules issue(s) which need to be resolved:
ERROR: plugins/modules/tower_job_template.py:0:0: doc-required-mismatch: Argument 'job_type' in argument_spec is not required, but is documented as being required
ERROR: plugins/modules/tower_project.py:0:0: doc-required-mismatch: Argument 'name' in argument_spec is not required, but is documented as being required
ERROR: plugins/modules/tower_role.py:0:0: doc-required-mismatch: Argument 'role' in argument_spec is not required, but is documented as being required

```
after 
```
make test_collection_sanity
Running sanity test 'use-argspec-type-path' with Python 3.7
Running sanity test 'use-compat-six' with Python 3.7
Running sanity test 'validate-modules' with Python 3.7
Running sanity test 'yamllint' with Python 3.7
(devel_ansible) [thedoubl3j@localhost awx]
```

### CODE REVIEW

**Comment by thedoubl3j** [comment]
fixing commit history right quick

**Review by AlanCoding — APPROVED** [review]

**Review by AlanCoding — CHANGES_REQUESTED** [review]
Sorry got this wrong at first

Instead of this, we should make job_type not required (API defaults to "run")

and squashing commits would be good

**Comment by thedoubl3j** [comment]
@AlanCoding roger that, will pull that out and squash either this evening or next week

**Review by AlanCoding — APPROVED** [review]

**Comment by AlanCoding** [comment]
regate

**Comment by AlanCoding** [comment]
regate

**Comment by AlanCoding** [comment]
regate

**Comment by AlanCoding** [comment]
recheck

**Comment by AlanCoding** [comment]
regate

**Pull request merged**
