### PR TITLE
Enable saving button on disabled Auth providers

### LINKED ISSUE #88: External AUTH Providers - Can't Save configuration form without changing the dropdown
The external AUTH providers for LDAP, RADIUS, SAML, and TACACS+ all have the Save button grayed out and disabled. I cannot save their config. I know the footer UI is in the way, but if you zoom out you can access the buttons. The other external providers like OAuth2 and Github work just fine. 

I didn't think there were any dependencies for those services?

* AWX version: 1.0.0.312
* Ansible version:  2.3.1
* Operating System: RHEL 7
* Web Browser: Chrome and Firefox

image

### PR DESCRIPTION
**Pull request by Zokormazo**
Enables saving button on LDAP, RADIUS, SAML and TACACS+ Auth proviers

Signed-off-by: Julen Landa Alustiza <julen@zokormazo.info>

##### SUMMARY
The enterprise license check has no sense here so I replaced it with enable like in the rest of the auth providers.

Fixes #88

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
awx: 1.0.0.386

### CODE REVIEW

**Review by matburt — CHANGES_REQUESTED** [review]
This is not going to work, we still do need to support our license types in the downstream Tower project. What needs to happen is for this to also act as enabled if the license type is `open` (which is what the stub license produces) see: https://github.com/ansible/awx/blob/devel/awx/main/utils/common.py#L182-L186

**Comment by Zokormazo** [comment]
The ConfigurationService is using the LICENSE attribute returned by `/api/v2/settings/all` to populate $scope.license_type and is empty:

settings

So there is an api issue too.

`/api/v2/config` returns `license_info.features.enterprise_auth` and `license_info.features.ldap values`:

config

won't be better using those specific values instead of license_type on auth provider's ngDisabled boolean statement?

What is the correct way? should we fix `/api/v2/settings/all` to return license info, or license info should be retrieved from `/api/v2/config` ? the disabled/enabled check should be done against `license_type` or against `license_info.features.enterprise_auth` and/or `license_info.features.ldap` ?

**Comment by Zokormazo** [comment]
PR updated with a fix suggestion.

The patch uses `license_info.features.ldap` & `license_info.features.enterprise_auth` values from `/api/v2/config` to enable saving buttons for auth providers

**Comment by matburt** [comment]
I think we've got this already fixed up here: https://github.com/ansible/awx/commit/64415872a0550bd982c7d2df53a6edfb1debc5b5

**Comment by jlmitch5** [comment]
@Zokormazo I'm reopening your pr, but have a slightly altered way for you to go about things if you wouldn't mind making these changes.  I was going to fix this downstream in Tower and let in flow back up when that is merged in, but it really has no point to be in Tower as I initially thought (when the user doesn't "have" a license in Tower, it just redirects the user to the license page until they enter one).


Instead of checking on the features of the config, you can use the fact that the LICENSE in the settings/all endpoint returns an empty object for AWX.

```
if (key === "LICENSE") {
                                    if (_.isEmpty(data[key])) {
                                        $scope.license_type = "open";
                                    } else {
                                        $scope.license_type = data[key].license_type;
                                    }
                                }
```

then, in the various form configs conditionally show taking into account this new open license type.  For example:

```
ngDisabled: "license_type !== 'enterprise' && license_type !== 'open' || configuration_radius_template_form.$invalid || configuration_radius_template_form.$pending"
```

I believe that should work without causing any disturbance to the way Tower checks for things.

**Comment by jlmitch5** [comment]
o wait hmm...somehow my changes were pulled into AWX already? investigating

**Comment by jlmitch5** [comment]
ah @matburt had just merged our Tower branch back into AWX, so the change is in AWX now https://github.com/ansible/awx/commit/37487b2427046c0055270be9daf65aab2450cff6

I'm sorry about all the confusing @Zokormazo!  Bear with me as I get used to this new open source dev process :).  Would you mind pulling in the latest changes to see if your issue is resolved?  It should be.

**Comment by Zokormazo** [comment]
Yep, it works on awx since I tested some minutes ago with the 3.2.0 merge,
althrought I don't know if its suitable for downstream.

I'll make the changes ASAP.

Now I'm curious about the config endpoint values. What purpose has the
license.features.enterprise_auth and license.features.ldap values if they
aren't used for auth provider configuration?

2017 ira. 18 18:14 erabiltzaileak hau idatzi du ("jlmitch5" <
notifications@github.com>):

**Comment by jlmitch5** [comment]
well actually at this point, i think we're good to go without needing a pr (sorry for the confusion!)

**Comment by jlmitch5** [comment]
but good point, are you on the ansible-awx IRC channel @Zokormazo?

**Comment by Zokormazo** [comment]
Yep, jlanda, althought I'm not at home right now and I can't reply you :P

**Comment by jlmitch5** [comment]
heh cool, ping jlmitch5/jtabor on there sometime and we can have a larger discussion about this.  tbh, your solution might be better than what I have.  @jaredevantabor is the one who worked on some of the conditional feature stuff, so he's probably got some good insight into that behavior that I don't really.

And again, sorry for sending you on the wild goose chase with this...we definitely appreciate your contributions and your help thus far has been _super_ valuable!

**Comment by Zokormazo** [comment]
My solution will work with an eventual new license type, called "foo" that has enterprise_feature activated and ldap deactivated for example

On the other side it uses two api endpoint and it needs some rework on the populated = true mark since it's marked just on the then() part of a async fetch while actually the other one could be not resolved yet.

Anyway, I'll contact you asap on irc

**Pull request closed without merging**
