### PR TITLE
Support Google credentials on Terraform credentials type

### PR DESCRIPTION
**Pull request by abikouo**
##### SUMMARY

Terraform configuration for [gcs](https://developer.hashicorp.com/terraform/language/settings/backends/gcs) backend requires a path to a credentials file. It is not possible to combine credentials in an inventory source, so there needs to be a way to get the credentials file for GCE into the Terraform credential plugin.
This PR add a new attribute to the Terraform credential plugin which allows to push GCE credentials file.

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME
Terraform backend configuration Secret management

##### AWX VERSION

```
24.1.1.dev12+g35608421f2
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by chrismeyersfsu — APPROVED** [review]

**Comment by chrismeyersfsu** [comment]
Hey @abikouo this PR looks good, but there is a failing test. Can you have a look at it and fix it up?

**Comment by abikouo** [comment]
> Hey @abikouo this PR looks good, but there is a failing test. Can you have a look at it and fix it up?

@chrismeyersfsu I am currently trying to fix tests. Thanks

**Comment by abikouo** [comment]
@chrismeyersfsu the tests have been fixed, for the `api-schema` and `api-swagger` broken tests, theses are not related to this PR (they are already broken in the `devel` branch)

**Comment by abikouo** [comment]
@chrismeyersfsu CI is ok now, could you please merge this?

**Review by thedoubl3j — APPROVED** [review]
Looks good and looks like CI is happy now, @chrismeyersfsu you mind finishing you review and merging.

**Review by chrismeyersfsu — APPROVED** [review]

**Pull request merged**
