### PR TITLE
Add pexpect to awx images

### PR DESCRIPTION
**Pull request by tha80**
##### SUMMARY
This Pull Requests add the "pexpect" package to the AWX container images, as it is needed for roles using the expect module.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
- Installer

##### AWX VERSION
7.0.0

### CODE REVIEW

**Comment by AlanCoding** [comment]
This is already in the container image inside the default virtual environment, could your problem also be resolved to setting the `ansible_python_interpreter` to that of the default Ansible venv?

**Comment by ryanpetrello** [comment]
Agreed with @AlanCoding; if your goal is to use `pexpect` in playbooks that AWX runs, this isn't the way to do it (see: https://github.com/ansible/awx)

**Comment by tha80** [comment]
Hey @AlanCoding,

thanks for the hint, but probably I don't completely get it.

I am currently trying to run a playbook in AWX which uses the expect module. But this playbook fails with the following message:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named pexpect
384
fatal: [*********** -> localhost]: FAILED! => {"changed": false, "msg": "Failed to import the required Python library (pexpect) on awx's Python /usr/bin/python2. Please read module documentation and install in the appropriate location"}
```

The virtual env that was used is: "/var/lib/awx/venv/ansible".

I haven't installed this awx instance, but as fas as I know it used the default approach of running awx in docker containers.

I looked into the awx_tasks container and saw that pexpect is available in the "/var/lib/awx/venv/awx" environment.

Isn't "/var/lib/awx/venv/ansible" the default virtual env in the awx_task container? How can I change it? 

Thanks for your help

**Comment by ryanpetrello** [comment]
@tha80 apologies, I linked to the wrong document above: https://github.com/ansible/awx/blob/devel/docs/custom_virtualenvs.md

This document explains how to set up custom virtualenvs with _additional_ dependencies beyond what we bundle in the default virtualenv (like pexpect, in your case).

**Comment by kladiv** [comment]
+1 if possible to include in default AWX ansible venv. This module could be very useful.

**Comment by AlanCoding** [comment]
The AWX ansible venv has been removed, replaced by execution environments. I have filed an issue in awx-ee (the default execution environment) to replace this discussion.

**Pull request closed without merging**
