### PR TITLE
Update useBrandName

### PR DESCRIPTION
**Pull request by nixocio**
Update useBrandName and its usage.

It was verified on downstream if the this solution was as per issue
described.

See:https://github.com/ansible/awx/issues/10775

### CODE REVIEW

**Comment by nixocio** [comment]
image
image
image

**Review by jakemcdermott — APPROVED** [review]

**Review by AlexSCorey — APPROVED** [review]
This looks good to me.  Confirm that changes are reflected properly on a production build also.

**Comment by tiagodread** [comment]
Settings and About modal looks fine.

AdHocDetailsStep.js is not showing the brand by the first time, just after any interaction

https://user-images.githubusercontent.com/12464858/129252636-ca9066d5-6037-4286-8382-839987e5ecdb.mp4

Screenshot from 2021-08-12 15-56-54

ManualSubForm.js is not showing the brand by the first time, just after any interaction (click)


https://user-images.githubusercontent.com/12464858/129253365-b900cc3f-ef11-455c-9100-b77b69e84b31.mp4

**Review by tiagodread — APPROVED** [review]
All fixed, there is only one unit test failing

**Pull request merged**
