### PR TITLE
Upgrades pf deps to latest

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
Also adds ability to click on row items in order to select them rather than having to click on checkboxes/radio buttons.

row_select

### CODE REVIEW

**Review by jakemcdermott — COMMENTED** [review]
The dependency changes look good to me. 

Many related list views don't have selectable rows, e.g the `access` and `teams` tabs.  The row-click effect should be disabled there.

**Comment by mabashian** [comment]
@jakemcdermott yea I can look in to that.  It seems like the default pf behavior is to highlight the row on selection even if it doesn't have an action.  See https://patternfly-react.surge.sh/patternfly-4/documentation/react/components/datalist#basic.  @trahman73 any thoughts on this one?  We're talking about rows that don't have checkboxes or radio's (the access list for example).

**Review by jakemcdermott — APPROVED** [review]
@mabashian 
> It seems like the default pf behavior is to highlight the row on selection even if it doesn't have an action.

Interesting. Well, the code changes look good to me. Merge when ready.

**Comment by trahman73** [comment]
@mabashian It feels odd to have a list be selectable that doesn't have any actions, but let's go with the default behavior until this is addressed from the PatternFly side.

**Comment by mabashian** [comment]
Totally agree that it's weird - something we should bring up with them.  Maybe they have a reason for that behavior.

**Pull request merged**
