### PR TITLE
Run setup install before continuing the documentation

### PR DESCRIPTION
**Pull request by naisanza**
##### SUMMARY

Otherwise when running the ansible playbook, the setup will hang during build-image setup.

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
GNU Make 4.1
Built for x86_64-pc-linux-gnu
```

### CODE REVIEW

**Comment by matburt** [comment]
This isn't necessary and will just literally install the awx package on your local system.

These tasks in the playbook are responsible for doing this in the image: https://github.com/ansible/awx/blob/devel/installer/image_build/tasks/main.yml#L50-L75

Is the installer hanging or just taking a while?

**Comment by naisanza** [comment]
@matburt it hangs indefinitely, restarting the playbook still hangs.

As soon as I ran `setup.py install`, afterwards it never hangs

**Comment by naisanza** [comment]
Here's the playbook I used for preparing AWX

https://github.com/naisanza/antsable/blob/master/playbooks/ansible_awx.yml

**Comment by matburt** [comment]
I can't reproduce this locally with our standalone playbook. Do you happen to know why it's hung?

**Comment by naisanza** [comment]
Is there an ansible-playbook command to write out all the debug logs to?

**Comment by naisanza** [comment]
In a new Ubuntu 16.04 server kvm, with python-minimal installed, it still stalls at `image_build : Build base web image`


```
TASK [image_build : State ansible repo] 
changed: [localhost -> localhost]

TASK [image_build : State ansible repo key] 
changed: [localhost -> localhost]

TASK [image_build : Build base web image] 
```

**Pull request closed without merging**
