### PR TITLE
Adopt changes to AWX_ISOLATION_SHOW_PATHS for trust store

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Porting downstream changes of @shanemcd 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

### CODE REVIEW

**Comment by AlanCoding** [comment]
Would replace https://github.com/ansible/awx/pull/11812, not yet sure if this is the right thing to do.

**Review by shanemcd — APPROVED** [review]

**Review by shanemcd — CHANGES_REQUESTED** [review]
Actually wait. I think this will break the development environment.

**Comment by shanemcd** [comment]
Yeah, I get:

```
Error: mounting overlay failed "/usr/share/pki/": chown /var/lib/awx/.local/share/containers/storage/overlay-containers/ba7243af6a0b1510caaffcf1e848721ec384513532009fc63487bc803fdea0bf/userdata/overlay/3107658967/upper: invalid argument
```

I think we just want this in `production.py`.

**Review by shanemcd — APPROVED** [review]

**Comment by AlanCoding** [comment]
This still leaves us needing to sync up other branches with the production / development settings. I'm not sure how yet, still thinking on it.

**Pull request merged**
