### PR TITLE
Adding CSRF Validation for schemas

### PR DESCRIPTION
**Pull request by brsanche**
##### SUMMARY
This PR is for adding the validation for the CSRF Origin since it should be `schema://addresses`.

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - API
 - UI

##### AWX VERSION

```
AAP 2.4.6 installation:

# awx-manage --version
4.5.2
```

##### ADDITIONAL INFORMATION

```
This is to prevent issues while adding wrong origins other than `schema://addresses`.
```

### CODE REVIEW

**Review by jbradberry — CHANGES_REQUESTED** [review]
It would be good for this to be closer in behavior to the existing Django check for this.  Perhaps even somehow make use of the existing code.

https://github.com/django/django/blob/main/django/core/checks/compatibility/django_4_0.py

**Comment by chrismeyersfsu** [comment]
https://github.com/ansible/awx/blob/devel/awx/main/tests/functional/api/test_settings.py <-- good place to add tests.

**Comment by brsanche** [comment]
> It would be good for this to be closer in behavior to the existing Django check for this. Perhaps even somehow make use of the existing code.
> 
> https://github.com/django/django/blob/main/django/core/checks/compatibility/django_4_0.py

Let me know if it looks good now. 

CC: @jbradberry @chrismeyersfsu

**Review by chrismeyersfsu — APPROVED** [review]

**Comment by chrismeyersfsu** [comment]
@brsanche the overall structure is looking good on this PR but a basic use case is failing. You can see a failure in the CI here, but that is pretty confusing. Instead, to observe and recreate the failure, try using this feature like this:

### Steps to Recreate
* Go to http://localhost:8013/api/v2/settings/system/
* click PATCH with a payload of  `{}`

### Actual
```
KeyError at /api/v2/settings/system/
'CSRF_TRUSTED_ORIGINS'
...
```

### Expected
200 or 301 (I forget the exact expected http code, but not a 500)


Other payloads to try:

Try permutations of the below
```
{
    "CSRF_TRUSTED_ORIGINS": [
        "hello",
        "bye",
        "https:/google.com"
    ]
}
```

This should clear the setting.
```
{
    "CSRF_TRUSTED_ORIGINS": []
}
```

**Comment by brsanche** [comment]
Hey @chrismeyersfsu , sorry for the delay was on PTO.

So, I added a check now to ensure that `CSRF_TRUSTED_ORIGINS` is present before accessing it, it looks good on my tests now via API.

Let me know how it looks for you now.

Thanks!

**Comment by fosterseth** [comment]
@brsanche I think api-test is failing due to linting error
```
would reformat /awx_devel/awx/main/conf.py
```

can you run `make black` in your awx directory?

**Review by fosterseth — APPROVED** [review]

**Comment by brsanche** [comment]
> @brsanche I think api-test is failing due to linting error
> 
> ```
> would reformat /awx_devel/awx/main/conf.py
> ```
> 
> can you run `make black` in your awx directory?

Hey @fosterseth , yep, that was it. 

The `make black` also fixed another file `awx/main/migrations/0190_alter_inventorysource_source_and_more.py` but just removed a blank line, if it's a problem I can remove it from this PR.

**Review by jbradberry — APPROVED** [review]

**Pull request merged**
