### PR TITLE
fix a bug that breaks inventory update stdout when used in a workflow

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/4920
related: https://github.com/ansible/awx/pull/4731

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]

**Review by kdelee — APPROVED** [review]

**Comment by ryanpetrello** [comment]
I'm closing this temporarily until Zuul gets happy.

**Comment by kdelee** [comment]
@ryanpetrello going to re-open this

**Comment by ryanpetrello** [comment]
Sorry about that @kdelee I missed this.

**Comment by ryanpetrello** [comment]
I'm ready to merge it whenever you are.

**Pull request merged**
