### PR TITLE
Upgrade pip from v7.1.2 (from August 2015) to v9.0.1

### PR DESCRIPTION
**Pull request by cclauss**
https://pip.pypa.io/en/stable/news/

### CODE REVIEW

**Comment by wenottingham** [comment]
What's the rationale for not using the system version - is something breaking as of now?

**Comment by cclauss** [comment]
This is a series of PRs about trying to get to compatibility with both Python 2 and Python 3...  At the URL above there are the multitude of pip changes over the past 2.5 years.  Many of these changes are about making sure that pip works smoothly both Python releases.

**Comment by wenottingham** [comment]
Makes sense. It's just that our build environment for our images is CentOS 7, and I'm leery to do unbounded upgrades to it that could affect reproducibility.

cc @shanemcd

**Comment by shanemcd** [comment]
Not sure upgrading pip here really makes a difference since our tests run inside of a container?

**Comment by shanemcd** [comment]
> This is a series of PRs about trying to get to compatibility with both Python 2 and Python 3...

@cclauss have you discussed this effort with anyone on the AWX team? If not you should pop into our IRC channel or start a thread on the mailing list.

**Pull request closed without merging**
