### PR TITLE
Upgrade our UI packaging for NodeJS 10.

### PR DESCRIPTION
**Pull request by kialam**
##### SUMMARY
- Update README.md
- Bump certain dependencies to fix vulnerabilities. Exclude dependency bumps that would cause breaking changes.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI
 - Installer

##### AWX VERSION

```
awx: 4.0.0
```

##### ADDITIONAL INFORMATION
Running `npm-audit` reveals one critical vulnerability tied to our `nightwatch` library. However, if we were to upgrade `nightwatch` in order to fix this it could potentially cause breaking changes. @unlikelyzero @elyezer what are your thoughts on how to address this?
```
# Run  npm install --save-dev nightwatch@1.1.10  to resolve 6 vulnerabilities
SEMVER WARNING: Recommended action is a potentially breaking change
┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Low           │ Regular Expression Denial of Service                         │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ debug                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nightwatch [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nightwatch > mocha-nightwatch > debug                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/534                       │
└───────────────┴──────────────────────────────────────────────────────────────┘


┌───────────────┬──────────────────────────────────────────────────────────────┐
│ Critical      │ Command Injection                                            │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Package       │ growl                                                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Dependency of │ nightwatch [dev]                                             │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ Path          │ nightwatch > mocha-nightwatch > growl                        │
├───────────────┼──────────────────────────────────────────────────────────────┤
│ More info     │ https://nodesecurity.io/advisories/146                       │
└───────────────┴──────────────────────────────────────────────────────────────┘
```

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@kialam , @dsesami has done some work in this area. We will have to work diligently to get the tests running and may need some dev cycles to help

**Comment by mabashian** [comment]
Note that if/when this merges https://github.com/ansible/awx/pull/3891 can probably just be closed since this also upgrades jquery

**Review by dsesami — APPROVED** [review]
:smile: excellent

**Comment by jakemcdermott** [comment]
yay

**Review by jakemcdermott — APPROVED** [review]
yay

**Pull request merged**
