### PR TITLE
Update empty survey list

### PR DESCRIPTION
**Pull request by nixocio**
Update empty survey list to be as the remaining lists.

Survey endpoint does not allow search.

Survey empty list with the changes.

image

An example of another empty list.

image

See: https://github.com/ansible/awx/issues/10942

### CODE REVIEW

**Comment by tiagodread** [comment]
@akus062381 @InnocentK this will potentially break some e2e tests

**Review by AlexSCorey — APPROVED** [review]
Looks good to me!

**Comment by InnocentK** [comment]
> @akus062381 @InnocentK this will potentially break some e2e tests
Resolved: https://dashboard.cypress.io/projects/ui2mq7/runs/9494/overview

**Review by InnocentK — APPROVED** [review]
Looks good

**Pull request merged**
