### PR TITLE
related #3778 Change postgresql version to 11.2

### PR DESCRIPTION
**Pull request by joseorpa**
##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```


##### ADDITIONAL INFORMATION
<!---
Include additional information to help people understand the change here.
For bugs that don't have a linked bug report, a step-by-step reproduction
of the problem is helpful.
  -->

<!--- Paste verbatim command output below, e.g. before and after your change -->
```
awx: 4.0.0
```

### CODE REVIEW

**Review by matburt — CHANGES_REQUESTED** [review]
We need to make sure *all* of the development compose files are updated, for example:

https://github.com/ansible/awx/blob/devel/tools/docker-compose-cluster.yml

Along with the kubernetes and openshift deployments. We *should* check to see what the upgrade behavior is on production AWX deployments.

**Comment by joseorpa** [comment]
I have changed all the docker-compose files and also the postgresql-persistent.yaml template. I've also set the version to 10, because 11 is not ready yet.

**Comment by matburt** [comment]
Wasn't 11.2 released as stable last month?

Can we also see if the config this is based on has been updated? https://github.com/ansible/awx/blob/devel/installer/roles/kubernetes/templates/postgresql-persistent.yml.j2

**Comment by joseorpa** [comment]
We have available postgresql:11.2 in DockerHub, but we just have registry.access.redhat.com/rhscl/postgresql-10-rhel7
The Kubernetes template uses registry.access.redhat.com/rhscl/postgresql-96-rhel7 
There should be some changes about RBAC with the image in DockerHub.
The documentation on postgresql-persistent is updated up to postgresql v10.

**Review by joseorpa — COMMENTED** [review]
Changes requested are done to the latest version available for Openshift.

**Comment by joseorpa** [comment]
I will do another pull request when all postgresql templates are available.

**Pull request closed without merging**
