### PR TITLE
Make AWX compatible with Helm 3.x

### PR DESCRIPTION
**Pull request by bhundven**
##### SUMMARY
In issue #5371, an incompatibility with older Helm 2.x (using tiller)
was found.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

##### AWX VERSION
```
awx: 9.1.1
```
##### ADDITIONAL INFORMATION
Future installs will require Helm 3.x.
Tested with Helm 3.0.2.

Signed-off-by: Bryan Hundven <bryanhundven@gmail.com>

### CODE REVIEW

**Comment by shanemcd** [comment]
Hello, thanks for this PR! I have been on vacation for the past 2 weeks and am currently catching up on other things, but will circle back to this in the coming days. I'll merge once I have a chance to verify it.

**Comment by bhundven** [comment]
Cool, the multiple tests are from rebasing to keep the PR up to date. I'm also still testing locally.

**Review by matburt — APPROVED** [review]

**Comment by bhundven** [comment]
I didn't think about this until I did a few more tests, but would you like me to add another task in that kubernetes block to remove the tempfile after helm applies?

**Comment by shanemcd** [comment]
Up to you - I don't think we clean up other temp files we create so.. meh. One thing I did notice though, should we remove `tiller_namespace` from the default inventory file?

**Comment by shanemcd** [comment]
I ran into this on my first attempt:

```
Error: no repositories found. You must add one before updating
```

After reading the docs, it seems like this is intentional and running this is required on a fresh install:

```
$ helm repo add stable https://kubernetes-charts.storage.googleapis.com
```

It seems like re-running this command multiple times works ok. Should we consider adding it before we run `helm repo update`?

Other than that, this worked for me. Thanks again for the contribution.

**Comment by bhundven** [comment]
I pushed two changes to fix the issues you found, thanks!

**Comment by bhundven** [comment]
I also opted to remove the tempfile.

**Comment by bhundven** [comment]
I think the check for a984e5d is stuck

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
