### PR TITLE
Remove mix usage of hooks and HOC for router

### PR DESCRIPTION
**Pull request by nixocio**
There were a few cases that hooks and HOC were being used at the same on
a certain component. Remove HOC from those ones.

### CODE REVIEW

**Comment by nixocio** [comment]
I already ran e2e tests 🟢

**Review by jakemcdermott — APPROVED** [review]
Looks great - by using hooks instead of the HOCs, our component tests get a little easier to initialize and the code is more consistent.

**Comment by tiagodread** [comment]
@nixocio  could you rebase this one?

**Comment by nixocio** [comment]
e2e tests triggered.

**Comment by nixocio** [comment]
@akus062381 ran the tests once more and 🟢 . Merging this one.

**Pull request merged**
