### PR TITLE
Replace deprecated -U option by --become-user

### PR DESCRIPTION
**Pull request by aperigault**
##### SUMMARY
Replace deprecated ansible -U option by --become-user

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

##### AWX VERSION

```
1.0.4.0
```

### CODE REVIEW

**Review by ryanpetrello — CHANGES_REQUESTED** [review]
Are these actually equivalent?  `ansible -h` suggests that `-U` is analogous to `--sudo-user`:

```
-U SUDO_USER, --sudo-user=SUDO_USER
                        desired sudo user (default=root) (deprecated, use
                        become)
```

**Comment by aperigault** [comment]
As you can read in your comment ``ansible -h`` says: ``(deprecated, use become)`` so i use become.

**Comment by ryanpetrello** [comment]
giphy

**Review by ryanpetrello — APPROVED** [review]
(apologies, it's been one of those sorts of days)

**Pull request merged**
