### PR TITLE
add additional settings sub navigation

### PR DESCRIPTION
**Pull request by jlmitch5**
link #2326 

changes:
- adds settings sub pane with settings view links
- makes the root /#/settings route a card view of these same settings view links
- updates scroll to be full page as opposed to independent of main viewport (necessary for the submenu pane to scroll.  confirmed with @trahman73 on the ux)
- all styling should conform to our BEM convention used in awx/ui/lib and use variables for colors
- show/hide done on the JS side based on how the submenu pane is position off of the sidenav itself, rather than the side nav item (also necessary for the pane to correctly position on scroll)

### CODE REVIEW

**Comment by marshmalien** [comment]
Looks awesome! 🎉 

settings

**Review by marshmalien — APPROVED** [review]

**Review by dsesami — APPROVED** [review]
Looks good!

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
Once we rebase `devel` into this, and @unlikelyzero is happy with it, I'd say this is ready for `mergeit`.

**Comment by unlikelyzero** [comment]
blocked on https://github.com/ansible/awx/issues/2436

**Comment by jlmitch5** [comment]
This api issue resulted from fixing up the config/auth json fields https://github.com/ansible/awx/issues/2446

**Comment by jlmitch5** [comment]
based on @chrismeyersfsu feedback on 2446, the fields work correctly when the json has the root default key.

**Comment by shanemcd** [comment]
recheck

**Pull request merged**
