### PR TITLE
Add a leading plus to the refspec

### PR DESCRIPTION
**Pull request by AlanCoding**
Speculative patch based on https://github.com/ansible/awx/issues/9371#issuecomment-888002348

### CODE REVIEW

**Comment by AlanCoding** [comment]
Reported to not solve the issue, interest is waning

**Comment by junrrein** [comment]
Sorry for commenting on a closed MR.

I would like to ask: is there a reason for AWX having a default refspec that is different from Git's default?  
I couldn't find an explanation for this either at the code level (i.e. comments) or at the commit level (with `git blame`).

The reason I'm asking is that in my org we are hitting the referenced issue, and the ops team would like to know the reason for AWX's default. In other words, if there are any (negative) consequences of changing the refspec to allow non-fast-forward updates on `git fetch`.

**Comment by AlanCoding** [comment]
I'll be happy to revisit if I can get a test case that it will fix. I failed to develop one myself.

**Comment by junrrein** [comment]
Thanks. I will try to create a reproducible test case and get back to you.

**Pull request closed without merging**
