### PR TITLE
Disable resource profiling if cgexec fails

### PR DESCRIPTION
**Pull request by jladdjr**
Currently, when a job executes on a container and resource profiling is enabled, the job fails with:

image

This PR adds a check before running a job that will ensure the `ansible-runner` cgroup exists and awx has the proper permissions to run a process inside the cgroup.

Verified fix by running jobs in dev environment with / without the `ansible-runner` cgroup present. Job runs successfully in both cases, only enables resource profiling when the cgroup is present, and emits a (warning-level) log message when resource profiling is disabled due to the cgroup being absent.

### CODE REVIEW

**Review by one-t — APPROVED** [review]

**Review by ryanpetrello — COMMENTED** [review]
I'm not sure I agree with this (I don't think the error in the issue screenshot is unreasonable, and I think if you turn this off and something is misconfigured, it's better to fail fast and explicitly, not just run the job and log a warning that the user may not notice.).  Is this only something that happens when tasks execute in a container?

**Review by ryanpetrello — CHANGES_REQUESTED** [review]
See prior comment.

**Comment by jladdjr** [comment]
> Is this only something that happens when tasks execute in a container?

@ryanpetrello - yes, only if the execution node is a container. If the current behavior is considered okay, will go ahead and close this. 👍 

---

_If we do decide to look into this later, wanted to note that..._

one gap in the this PR that I thought of after the fact is that it checks if the _current host_ can run a process in the `ansible-runner` cgroup. This is actually the wrong check if the current host isn't where the job will actually be executed, which is the case with 1) container groups and 2) isolated instances. So, if we were to pick up this work again, we'd need to first check to see if the current host is going to execute the job or if one of those other two cases applies, and then check if make the `cgexec` check happen _wherever the execution environment is_.

**Comment by wenottingham** [comment]
@jladdjr please file a bug on this, we still need to track this

**Pull request closed without merging**
