### PR TITLE
add inventory host groups list and host groups lists

### PR DESCRIPTION
**Pull request by jlmitch5**
link https://github.com/ansible/awx/issues/5908

this is just the list part...associate and disassociate will come in follow up PRs.

### CODE REVIEW

**Comment by mabashian** [comment]
I think this looks really good @jlmitch5.

I did notice this one console error when I navigate to the list from the host details:

Screen Shot 2020-03-31 at 10 27 39 AM

It doesn't seem to matter how many items are in the list (at first I thought it was because the list was empty).

The other thing I noticed was with the group type filter.  I'm not sure that we want/need it on this particular groups list.  I'm also not sure that it's functioning as expected.  I associated a single group with the host and then checked out the filter:

rootAllGroups

In this case I think I'd expect to see the group in both root and all groups.  I'd be inclined to just remove this filter option though but let me know your thoughts @jlmitch5

**Comment by jlmitch5** [comment]
Thanks for the review @mabashian 

I've updated the host groups/inv host groups list to useRequest (which fixes the mount error).

I've also removed the group type filter from these views.  I noticed that there's an issue with the filter we are using as well, which I've filed for fixing outside of this pr https://github.com/ansible/awx/issues/6503

**Review by mabashian — APPROVED** [review]

**Comment by jlmitch5** [comment]
after talking with @unlikelyzero we're gonna merge this and then work on the tests after it's in devel

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
:middle_finger:  :middle_finger:  :middle_finger:  recheck :middle_finger:  :middle_finger:  :middle_finger:

**Pull request merged**
