### PR TITLE
Add support for notification template copy and advanced search

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #7879 

Copy:

copy

Search:

advanced_search

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by nixocio — APPROVED** [review]
I got this code locally, changes seem to be working as expected.

**Comment by tiagodread** [comment]
@mabashian found this items:

- [ ] If the copy button was clicked twice before the first request finish the user see:

image

- [ ] Advanced search for type doesn’t work:

image

- [ ] (Not related to this PR) The user can hit the test button many times while the notification test is still running

**Comment by mabashian** [comment]
@tiagodread 

> If the copy button was clicked twice before the first request finish the user see:

Good catch, this actually applies to all the copy buttons in the app but they all share the same component so the fix here should apply to all.

> Advanced search for type doesn’t work

This looks like an API bug to me.  I filed this issue: https://github.com/ansible/awx/issues/8919.  The field that you're searching on isn't actually the field you wan though.  You want to be searching on `notification_type`.  `type` is a field with only one possible value right now: `notification_template`.  Im not quite sure what the function of this field is.

notif_search

> (Not related to this PR) The user can hit the test button many times while the notification test is still running

I fixed this

**Comment by mabashian** [comment]
OK @tiagodread i think this is ready for another look

**Review by tiagodread — APPROVED** [review]
Verified that the user can now copy notifications and it keep working on different places like 

```
templates
credentials
projects
inventories
notifications

```

Tests covered by 5804

**Pull request merged**
