### PR TITLE
Add Expand button to variables fields

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Adds expand button to variables fields and details. Clicking it opens the code editor & YAML/JSON toggles in a large modal

Addresses #8031 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2021-03-15 at 11 16 03 AM
Screen Shot 2021-03-15 at 11 16 09 AM

### CODE REVIEW

**Review by nixocio — APPROVED** [review]
💯

**Comment by one-t** [comment]
This looks great to me. I've added stubs to come back to when we address testability in general for the ace editor.

**Review by one-t — APPROVED** [review]

**Comment by unlikelyzero** [comment]
@keithjgrant do you mind adding ouiaIDs to these components?

**Comment by one-t** [comment]
Hey, Keith- I was working on a visual test and realized we need a couple more OUIA IDs for this one.

- close button for modal
- YAML and JSON buttons (preferably different between the expanded modal and the details/edit page)

edit: We can probably catch those in the other editor PRs.

**Pull request merged**
