### PR TITLE
Revert 9b95cc27c4840140996a036223e2909a30953b95.

### PR DESCRIPTION
**Pull request by wenottingham**
We do not want to create a new setting for a on-Tower-host global collection path at this time.

### CODE REVIEW

**Review by ryanpetrello — COMMENTED** [review]
I'm fine with just telling people to use `/usr/share/ansible/collections` if it gives @AlanCoding and @elyezer what they need 🤷‍♂

**Comment by AlanCoding** [comment]
yes, we are testing `/usr/share/ansible/collections` as a drop-in replacement, and will approve this after confirming it works.

**Review by AlanCoding — APPROVED** [review]
We should still wait until the A.M. before merging

**Comment by AlanCoding** [comment]
Wait, I was wrong about my testing. This is more difficult than it looks.

https://github.com/ansible/test-playbooks/blob/master/invoke_x.yml#L6

using module names like `tower_organization` fail to detect when the wrong version of the modules are being used. I will attempt a patch with a fully qualified module name, which should correctly tell me if the tests are using the proper collection.

**Review by AlanCoding — CHANGES_REQUESTED** [review]
I fixed my testing and it seems that this is not working. Not yet sure of the root cause, I might need some help to get this sorted out.

**Comment by AlanCoding** [comment]
correctly putting in the fully qualified collection name leaves me with the known error

```
task path: /tmp/awx_339_hdyznl3w/project/invoke_x.yml:23
fatal: [localhost]: FAILED! => {
    "reason": "no action detected in task. This often indicates a misspelled module name, or incorrect module path.\\n\\nThe error appears to be in '/tmp/invoke_x_include_0fee72ec-6cf9-5f8f-a6e5-35b960982bda.yml': line 1, column 3, but may\\nbe elsewhere in the file depending on the exact syntax problem.\\n\\nThe offending line appears to be:\\n\\n\\n- name: \\"invoke_arbitrary_module\\"\\n  ^ here\\n"
}
```

**Comment by AlanCoding** [comment]
After installing ansible-tower-cli to the Ansible venv, running this manually inside the server container seems to work.

```
ansible-playbook --connection=local -i localhost, invoke_x.yml -e ansible_python_interpreter=/venv/ansible/bin/python
```

But playbooks running basically this same command do not work.

**Comment by AlanCoding** [comment]
Okay here's the problem.

https://github.com/ansible/awx/blob/b9960f9bfe0ccea1d82d568de7ddcde003d4d356/awx/main/tasks.py#L1468-L1475

The collections from `requirements.yml` file are added to the listing via this environment variable. When doing so, no deference to the Ansible core default was adhered to. Logical, since the defaults were already squashed by the feature which you are reverting here.

So... for job runs that have collections specified in requirements files

 - is it expected that those job runs can use collections _both_ from the requirement files and in the `/usr/share` location?
 - are you cool if we hard code the Ansible defaults to handle this case? Because I don't see any other option unless we do some serious bubblewrap gymnastics to map the awx user collections as a writable location.

But I'm getting ahead of myself. After hacking out that bit of code which squashes the defaults, I discover a completely novel bug.

```
The full traceback is:
Traceback (most recent call last):
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 145, in run
    res = self._execute()
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 664, in _execute
    result = self._handler.run(task_vars=variables)
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 809, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 203, in _configure_module
    environment=final_environment)
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/executor/module_common.py", line 1015, in modify_module
    with open(module_path, 'rb') as f:
IOError: [Errno 13] Permission denied: u'/usr/share/ansible/collections/ansible_collections/chrismeyersfsu/tower_modules/plugins/modules/tower_organization.py'

fatal: [localhost]: FAILED! => {
    "msg": "Unexpected failure during module execution.", 
    "stdout": ""
}
```

If Ansible core wants to modify the global collection location, I can't do anything about that. My current reading is that would have to be raised as an issue in core.

**Comment by AlanCoding** [comment]
Sorry, having some Ansible versioning problems. Here is the traceback with line numbers updated to current Ansible core `devel`, 

https://github.com/ansible/ansible/blob/531e0560cb28114d5474851d9615ae2e42c96034/lib/ansible/plugins/action/__init__.py#L178

```
Traceback (most recent call last):
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 146, in run
    res = self._execute()
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/executor/task_executor.py", line 650, in _execute
    result = self._handler.run(task_vars=variables)
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/plugins/action/normal.py", line 46, in run
    result = merge_hash(result, self._execute_module(task_vars=task_vars, wrap_async=wrap_async))
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 796, in _execute_module
    (module_style, shebang, module_data, module_path) = self._configure_module(module_name=module_name, module_args=module_args, task_vars=task_vars)
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/plugins/action/__init__.py", line 190, in _configure_module
    environment=final_environment)
  File "/venv/python2_tower_modules/lib/python2.7/site-packages/ansible/executor/module_common.py", line 1250, in modify_module
    with open(module_path, 'rb') as f:
IOError: [Errno 13] Permission denied: u'/usr/share/ansible/collections/ansible_collections/chrismeyersfsu/tower_modules/plugins/modules/tower_organization.py'
```

**Comment by AlanCoding** [comment]
Filed https://github.com/ansible/ansible/issues/61778

**Comment by AlanCoding** [comment]
I verified that collections installed (and chmod' correctly) to the `/usr/share` folder can be used in job runs now.

This PR can be made to work if the following diff is applied.

```diff
diff --git a/awx/main/tasks.py b/awx/main/tasks.py
index e8f671ee9e..0d1357cfaa 100644
--- a/awx/main/tasks.py
+++ b/awx/main/tasks.py
@@ -1474,12 +1474,14 @@ class RunJob(BaseTask):
             if authorize:
                 env['ANSIBLE_NET_AUTH_PASS'] = network_cred.get_input('authorize_password', default='')
 
-        for env_key, folder in (
-                ('ANSIBLE_COLLECTIONS_PATHS', 'requirements_collections'),
-                ('ANSIBLE_ROLES_PATH', 'requirements_roles')):
-            paths = []
+        for env_key, folder, default in (
+                ('ANSIBLE_COLLECTIONS_PATHS', 'requirements_collections', '~/.ansible/collections:/usr/share/ansible/collections'),
+                ('ANSIBLE_ROLES_PATH', 'requirements_roles', '~/.ansible/roles:/usr/share/ansible/roles:/etc/ansible/roles')):
+            paths = default.split(':')
             if env_key in env:
-                paths.append(env[env_key])
+                for path in env[env_key].split(':'):
+                    if path not in paths:
+                        paths.append(env[env_key])
             paths.append(os.path.join(private_data_dir, folder))
             env[env_key] = os.pathsep.join(paths)
```

I verified that we can get our tests working with that as well.

If you don't like the hard coded defaults, then you can mention that issue I filed in Ansible core in a comment.

**Review by AlanCoding — CHANGES_REQUESTED** [review]
See diff I provided so that this will not break things.

**Comment by wenottingham** [comment]
Sorry, messed up my base devel branch. Please go to https://github.com/ansible/awx/pull/4656

**Pull request closed without merging**
