### PR TITLE
Remove old UI

### PR DESCRIPTION
**Pull request by TheRealHaoLiu**
##### ISSUE TYPE

 - Breaking Change 

##### COMPONENT NAME

 - API
 - UI
 - Docs
 - Other

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by fosterseth** [comment]
`npm install -g n && n 16.13.1 && npm install -g npm@8.5.0 && dnf remove -y nodejs`

we could replace this with requirements to build new UI (nodejs >= 18, npm > 10)

**Comment by fosterseth** [comment]
pulled down branch and tested, it works

**Review by fosterseth — APPROVED** [review]

**Review by pb82 — APPROVED** [review]
After running `make clean/ui ui` I was able to log into the new UI in the docker compose environment :+1:

**Comment by AlanCoding** [comment]
Replaced by https://github.com/ansible/awx/pull/15409?

**Comment by fosterseth** [comment]
reminder to incorporate change for this diff https://github.com/ansible/awx/pull/15456

i.e. sso should redirect to ui:index if we rename ui_next to ui

**Pull request merged**
