### PR TITLE
Fix bug with association on creation

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
This is needed to make https://github.com/ansible/awx/issues/5177 fully functional.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
9.3.0
```

##### ADDITIONAL INFORMATION
related to a few other things going on.

### CODE REVIEW

**Review by beeankha — APPROVED** [review]
Tested locally, everything works! My only nitpick is, please change the docstring description of the `groups:` parameter in the `tower_group.py` module from `- List of groups that should be nested inside in this group.` to `- List of groups that should be nested inside of this group.` (or we can do that in a separate PR)

**Comment by AlanCoding** [comment]
@beeankha you made the point elsewhere that this related field should have been named `children` instead of `groups`, and I strongly agree. Do you think it would be best to add that into this PR?

**Comment by beeankha** [comment]
> @beeankha you made the point elsewhere that this related field should have been named `children` instead of `groups`, and I strongly agree. Do you think it would be best to add that into this PR?

Nope, it's fine to leave it as-is (with `children` as the related field)

**Review by squidboylan — APPROVED** [review]

**Comment by AlanCoding** [comment]
regate

**Pull request merged**
