### PR TITLE
Server-side generation of private SSH keys

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
This is a new feature proposal. If you look at an example of getting started with AWX:

https://groups.google.com/d/msg/awx-project/wXU5IjsX2jA/aGeCuz-QBwAJ

> For the reasons Ben mentioned, it's important to practice good key management processes - we recommend that users generate a new private key specific to their awx installation and not use existing/shared keys.

This allows users to go one step further by avoiding the need to ever have the private key in their possession, telling the server to generate it on its own.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

UI work will be necessary, and this has not yet been done. My proposal is that the UI insert a button in these cases to say "server-side generation", and when clicked, it fills in the box with the $generate$ keyword and parameters with default values.

##### AWX VERSION

```
1.0.7-7
```

##### ADDITIONAL INFORMATION
For notions of robustness / security, see an existing precedent for generation of `AWX_ISOLATED_PRIVATE_KEY`, @ryanpetrello implemented this using the same library and algorithm employed here.

https://github.com/ansible/awx/blob/d8c4f118c23fde9f59f38334974381264d22f120/awx/main/management/commands/generate_isolated_key.py

The backend, as far as I understand, is OpenSSL.

Also important to note - this feature will begin displaying public keys for SSH keys that were previously added manually.

As one final note, it might make more sense to include info about the generator parameters in the OPTIONS instead of summary_fields, but I'd like to address that as the UI technical elements are addressed.

### CODE REVIEW

**Comment by ryanpetrello** [comment]
I'm skeptical about putting this in awx for a few reasons.  The main reason is that I don't think the concern is the **process** of getting a private key **into** awx.  My guess is that people who are concerned about putting their private key into awx is the worry that it might be **stored** insecurely and vulnerable to leaking and compromising their infrastructure.

My other concern is that this is going to evolve into something that supports _much_ of:

```
usage: ssh-keygen [-q] [-b bits] [-t dsa | ecdsa | ed25519 | rsa]
                  [-N new_passphrase] [-C comment] [-f output_keyfile]
       ssh-keygen -p [-P old_passphrase] [-N new_passphrase] [-f keyfile]
       ssh-keygen -i [-m key_format] [-f input_keyfile]
       ssh-keygen -e [-m key_format] [-f input_keyfile]
       ssh-keygen -y [-f input_keyfile]
       ssh-keygen -c [-P passphrase] [-C comment] [-f keyfile]
       ssh-keygen -l [-v] [-E fingerprint_hash] [-f input_keyfile]
       ssh-keygen -B [-f input_keyfile]
       ssh-keygen -D pkcs11
       ssh-keygen -F hostname [-f known_hosts_file] [-l]
       ssh-keygen -H [-f known_hosts_file]
       ssh-keygen -R hostname [-f known_hosts_file]
       ssh-keygen -r hostname [-f input_keyfile] [-g]
       ssh-keygen -G output_file [-v] [-b bits] [-M memory] [-S start_point]
       ssh-keygen -T output_file -f input_file [-v] [-a rounds] [-J num_lines]
                  [-j start_line] [-K checkpt] [-W generator]
       ssh-keygen -s ca_key -I certificate_identity [-h] [-U]
                  [-D pkcs11_provider] [-n principals] [-O option]
                  [-V validity_interval] [-z serial_number] file ...
       ssh-keygen -L [-f input_keyfile]
       ssh-keygen -A
       ssh-keygen -k -f krl_file [-u] [-s ca_public] [-z version_number]
                  file ...
       ssh-keygen -Q -f krl_file file ...
```

...to satisfy our broad user base (and I don't want to have to maintain that).

**Comment by wenottingham** [comment]
This is an old old RFE.

In terms of ssh-keygen knobs, I'm in favor of not having them... if you're using this, you get our presumably secure defaults.

**Review by ryanpetrello — CHANGES_REQUESTED** [review]
I don't care for the special `$generate$` in terms of implementation; I feel like this is an RFE, and if we want to add this feature, we should scope out a nicer API and plan out a nice UI interaction.

**Comment by ryanpetrello** [comment]
I think a nice approach to this problem might be a button/mechanism in the UI that creates an SSH credential and pops up a dialog w/ the public key value.

**Pull request closed without merging**
