### PR TITLE
Change dockerfile to use postgresql96

### LINKED ISSUE #977: pg_dump included in awx_task/awx_web is old 9.2.23 incompatible
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - Installer

##### SUMMARY
Unable to dump postgres database because of a missing option.

The version of pg_dump on awx_task and awx_web is 9.2.23. There version with the postgres container is 9.6.6.

9.6.6 has a --dbname option which is missing from the 9.2.23 

##### ENVIRONMENT
* AWX version: 1.0.1.173
* AWX install method: docker on linux
* Ansible version:  2.4.2
* Operating System: RHEL 7.4
* Web Browser: Chrome

##### STEPS TO REPRODUCE

Create a playbook with task to backup db (using the settings obtained via awx-manage command)

``
- name: Perform a PostgreSQL dump.
  shell: "pg_dump --clean --create --host='{{ tower_db_settings.default.HOST }}' --port={{ tower_db_settings.default.PORT }} --username='{{ tower_db_settings.default.USER  }}' --dbname='{{ tower_db_settings.default.NAME }}' > tower.db"
  args:
    chdir: '{{ backup_tmp.rstrip("/") }}/{{ now }}/'
  environment:
    PGPASSWORD: "{{ tower_db_settings.default.PASSWORD }}"
  no_log: True
``

##### EXPECTED RESULTS

Backup to be dumped, no errors

##### ACTUAL RESULTS

fatal: [awx_task]: FAILED! => {"changed": true, "cmd": "pg_dump --clean --create --host='postgres' --port=5432 --username='awx' --dbname='awx' > tower.db", "delta": "0:00:00.248242", "end": "2018-01-12 13:57:38.853204", "msg": "non-zero return code", "rc": 1, "start": "2018-01-12 13:57:38.604962", "stderr": "pg_dump: unrecognized option '--dbname=awx'\nTry \"pg_dump --help\" for more information.", "stderr_lines": ["pg_dump: unrecognized option '--dbname=awx'", "Try \"pg_dump --help\" for more information."], "stdout": "", "stdout_lines": []}

### PR DESCRIPTION
**Pull request by Klaas-**
Fixes ansible/awx#977
currently the image uses 9.2 from base. This change should enable it to use the 9.6 binaries.

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
2.1.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by Klaas-** [comment]
see https://wiki.postgresql.org/wiki/YUM_Installation for rational behind the change

**Comment by Klaas-** [comment]
I can not properly test this in my environment because EPEL is blocked in my proxy... :D

**Comment by matburt** [comment]
It might be worth it to bump this up to PG10.  I'll point out that we'll also need to make any relevant change to the dev environment also: https://github.com/ansible/awx/tree/devel/tools/docker-compose

**Comment by Klaas-** [comment]
@matburt I've changed what we discussed on irc. This change is to postgresql96, I'll give pg10 a try in a second PR in the near future.

**Comment by matburt** [comment]
We'll need to wait for someone who has some time to verify this. Regardless, we'll probably hold this PR until after the holidays to keep from disrupting anyone's dev environments. You should know that PG10 is something we're  targeting really soon... it's likely we'll just end up closing this PR at some point in January.

**Comment by ryanpetrello** [comment]
Closing this as well - the next upgrade we're planning here will be to Postgres 10, and all that entails regarding a viable, tested upgrade path for existing installs.

**Comment by Klaas-** [comment]
@ryanpetrello this would fix the docker images to use the current default postgres96 until you actually use postgres10

**Comment by matburt** [comment]
We'd just like to hold off on making any changes to this until we're ready to move up to pg10 to minimize impact.

**Pull request closed without merging**
