### PR TITLE
bump version 11.2.0

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Review by beeankha — APPROVED** [review]
🚀

**Review by jladdjr — APPROVED** [review]

**Review by rebeccahhh — APPROVED** [review]

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by dnguyen9** [comment]
@ryanpetrello Will we have a tag for 11.2.0 ?

**Comment by shanemcd** [comment]
@dnguyen9 It's pretty typical to bump the version prior to cutting a release. The tag will be published when it goes live.

**Pull request merged**
