### PR TITLE
Add project manual subform

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
* Add Manual SCM Type subform
* Add test coverage for manual subform
* Add playbook directory and project base path to Project Details
* Pull project_base_dir and project_local_paths from Config Context

_Manual SubForm Demo_
manual

_Warning Alert_
Screen Shot 2019-11-05 at 10 00 28 PM

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
awx: 9.0.1
```

### CODE REVIEW

**Comment by shanemcd** [comment]
@jakemcdermott's fix for these flakey tests landed this morning. Try to rebase.

**Comment by mabashian** [comment]
A couple of notes:

1) I think this field needs to be required:

Screen Shot 2019-11-11 at 1 08 00 PM

Attempting to submit the form without it results in a 400 error from the API.

2) There are a couple of console errors being thrown when the form loads:

```Warning: Failed prop type: The prop `value` is marked as required in `AnsibleSelect`, but its value is `null`.```

and 

```Warning: `value` prop on `select` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.```

which I think both stem from setting the default `local_path` to `null` ([link](https://github.com/ansible/awx/pull/5272/files#diff-ac7a78c1191b3b1f26d50ed67793d2a0R186)).

Do you recall needing to set that field to `null` as opposed to `''`?  I _think_ an empty string would be OK in this case but would need to investigate.

**Comment by marshmalien** [comment]
I don't recall why it was set to `null`, but setting it to `' '` resolves the console error. Will update the PR.

**Review by mabashian — APPROVED** [review]
Nice! 👍

**Pull request merged**
