### PR TITLE
Adds eu-north-1, eu-west-3, ap-east-1, and me-south-1.

### PR DESCRIPTION
**Pull request by deepy**
Signed-off-by: Alex Nordlund <deep.alexander@gmail.com>

##### SUMMARY
Adds eu-north-1, eu-west-3, ap-east-1, and me-south-1 regions.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]

**Comment by AlanCoding** [comment]
recheck

**Comment by wenottingham** [comment]
This won't work with the ec2 inventory, see https://github.com/ansible/awx/issues/2115

**Comment by AlanCoding** [comment]
Sorry, @wenottingham is right, this requires some associated work with the dependency. Attempting to close to avoid confusion on this.

**Comment by deepy** [comment]
How tough would #2115 be?
I might be able to give that a try

**Comment by AlanCoding** [comment]
The best of my understanding of what needs to be done:

We have instructions on upgrading dependencies in the README here.

https://github.com/ansible/awx/tree/devel/requirements

This is concerned with the AWX virtual environment. The "source" requirements are in `requirements.in` in that folder. That needs to have boto swapped with boto3. Then that file compiles to `requirements.txt`. Even if you can't get this step right I can come in and do it later, and you can test by manually uninstalling & reinstalling stuff (first do `. /venv/awx/bin/activate`). Then the call patterns in the code need to be changed, depending on how boto3 works, plus this diff you already did.

**Comment by wenottingham** [comment]
It also involves moving the ec2 inventory source to use the ansible plugin instead of the included script, which is a larger feature.

**Comment by deepy** [comment]
@wenottingham can these be done separately? Is it ok to start with awx or should the inventory source be first?

**Comment by deepy** [comment]
@wenottingham is it ok to do those separately? Can I start with the boto -> boto3 and then later attempt moving the ec2 inventory source to the ansible plugin?

**Comment by wenottingham** [comment]
The inventory source needs done first - otherwise this work will just add options that won't actually be used properly.

**Pull request closed without merging**
