### PR TITLE
Update inventory file 

### PR DESCRIPTION
**Pull request by shaynecm**
##### SUMMARY

upgrade ansible_python_interpreter to use python3 for the localhost setting by default,

##### ISSUE TYPE

 - Feature Pull Request
 - Bugfix Pull Request
 - Docs Pull Request

##### COMPONENT NAME

 - API
 - UI
 - Installer

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
Might be smart to add "Python 3.6+" to https://github.com/ansible/awx/blob/devel/INSTALL.md#prerequisites

**Review by ryanpetrello — COMMENTED** [review]
Also, let's make this `/usr/bin/env python3`

**Comment by shaynecm** [comment]
I have added Python 3.6+ to the pre-requisites and updated to be python 3 as suggested

**Comment by TristanCacqueray** [comment]
Oops we dropped ansible-new by mistake, we'll recheck once this is fixed.

**Comment by TristanCacqueray** [comment]
recheck

**Pull request merged**
