### PR TITLE
Make sure that the resolved EE gets attached to new workflow jobs

### PR DESCRIPTION
**Pull request by jbradberry**
##### SUMMARY
Make sure that the resolved EE gets attached to new workflow jobs.  This is solely for future reference and UI consistency, since workflows are not actually executed in EE images.

related #10399 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

### CODE REVIEW

**Comment by jbradberry** [comment]
recheck

**Comment by jbradberry** [comment]
recheck

**Comment by jbradberry** [comment]
recheck

**Comment by AlanCoding** [comment]
Would this result in the `default_environment` from the organization of the WFJT overriding the EE set directly on JTs in the WFJT?

That seems like wrong behavior.

**Comment by jbradberry** [comment]
@AlanCoding no, it wouldn't.  Or at least it shouldn't.

**Comment by jbradberry** [comment]
I've double-checked, this does not cause the behavior that you were worrying about.

Setup:
- "Demo Job Template", explicit EE = "AWX EE 0.3.0"
- "Workflow Template", contains one node that points to "Demo Job Template", no explicit EE
- "Second-Order Workflow Template", contains one node that points to "Workflow Template", explicit EE = "Foo"

Result:
Screenshot_2021-06-11 AWX

**Comment by jbradberry** [comment]
If the explicit EE is unset on "Demo Job Template", all three jobs correctly wind up with EE "Foo" used.

**Comment by jbradberry** [comment]
To be clearer, the workflow job isn't part of the resolver hierarchy, it's the workflow job template (and only when the EE is explicitly set on the workflow template).

**Comment by AlanCoding** [comment]
What about

 - "Demo Job Template", no explicit EE
 - "Workflow Template", contains one node that points to "Demo Job Template", no explicit EE, in "foo" organization
 - The "foo" organization has a "foo-org-EE"

Launch the "Workflow Template", would it run with "foo-org-EE"?

> To be clearer, the workflow job isn't part of the resolver hierarchy, it's the workflow job template (and only when the EE is explicitly set on the workflow template).

Yeah, I would like that the WFJT organization doesn't come into play. If this is the intention (just that workflow job gets EE from its respective WFJT) then can you just add `execution_environment` to this list?

https://github.com/ansible/awx/blob/3063073395143a019ad0918e397ab7a30f740c82/awx/main/models/workflow.py#L385-L391

These are fields copied over from the WFJT to the workflow job on launch.

**Comment by jbradberry** [comment]
> Launch the "Workflow Template", would it run with "foo-org-EE"?

That's pretty unambiguously 'yes'.  But to confirm:

Screenshot_2021-06-11 AWX(1)

**Comment by jbradberry** [comment]
> Yeah, I would like that the WFJT organization doesn't come into play. If this is the intention (just that workflow job gets EE from its respective WFJT) then can you just add `execution_environment` to this list?

I'm having a bit of trouble parsing what you actually mean by this.  Let's chat.

**Comment by jbradberry** [comment]
Based on https://github.com/ansible/awx/issues/10399#issuecomment-859828641, it seems like this isn't the direction to go in.  Closing.

**Pull request closed without merging**
