### PR TITLE
Fix initialization race in awx_display_callback.

### PR DESCRIPTION
**Pull request by dw**
##### SUMMARY

When thread A and B compete to execute set_local() for the first time, no synchronization occurs on creation of the threading.local() object, resulting in an easy to hit sequence like:

```
  add_local():
    A: if not hasattr(self, '_local')
    B: if not hasattr(self, '_local')
    A: self._local = threading.local()
    A: self._local._ctx = {}
    B: self._local = threading.local()  # new TLS key! A's _ctx discarded
    B: self._local._ctx = {}

  remove_local():
    B: self._local._ctx.pop(key, None)  # succeeds
    A: self._local._ctx.pop(key, None)  # AttributeError
```

The fix is simple: local() object construction is not magically thread safe, only attribute and `__dict__` access are thread-safe. So move local() construction to the (single-threaded) EventContext constructor.

This is easily triggered by Mitogen running with -vvv, where multiple threads can generate display.*() calls.

See: https://github.com/dw/mitogen/issues/400

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - Display Callback

##### AWX VERSION

``devel``

##### ADDITIONAL INFORMATION

To reproduce:

1. Configure Mitogen
2. Run job with -vvv
3. Notice job crashes with AttributeError.

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Hey @dw,

Thanks for digging in on a really hairy issue like this and providing a PR.  We're actually in the process of extracting awx's playbook execution into a separate standalone library, https://github.com/ansible/ansible-runner, which awx itself will import and use.  We'll likely address this type of issue in ansible-runner as we continue migrating towards it.

I'll reopen an issue over there that references this pull request.

**Comment by dw** [comment]
Looks like the PR can be reapplied as-is to ansible-runner. Should I open a duplicate PR there? What about this one? Is it needed?

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/ansible-runner/issues/168

**Comment by ryanpetrello** [comment]
@dw re-opening a PR over there would be greatly appreciated - thanks for you help :)

**Pull request closed without merging**
