### PR TITLE
[usage-collection] Add Host Metrics table

### PR DESCRIPTION
**Pull request by ZitaNemeckova**
##### SUMMARY

Fixes https://issues.redhat.com/browse/AA-1613 and https://issues.redhat.com/browse/AA-1573

- New nav bar item Host Metrics
- Page with table
- Depends on https://github.com/ansible/awx/pull/13560 and https://github.com/ansible/awx/pull/13624
- Deleted items do no show
- Only visible for `superadmin` and `auditor` with correct subscription
Screenshot 2023-02-23 at 15 19 23

##### TODO

- [x]  partial filtering by hostname
- [x] select row/select all 
- [x] + action delete
- [x] The new UI sections should be available to a sysadmin/auditor role

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Comment by h-kataria** [comment]
@ZitaNemeckova is this ready for review?

**Comment by ZitaNemeckova** [comment]
@h-kataria I think it's ready for review.

**Review by vidyanambiar — APPROVED** [review]
lgtm!

**Comment by vidyanambiar** [comment]
@ZitaNemeckova A heads up - it looks like one of the unit tests (src/screens/HostMetrics/HostMetrics.test.js) is failing on the PR check

**Comment by ZitaNemeckova** [comment]
@vidyanambiar Thanks for the review. I fixed the tests.

**Pull request merged**
