### PR TITLE
Upgrades pf deps to latest

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
Survey preview tests were failing because we weren't providing options as children to match up with the selected fields.  I'm not sure if this is a bug upstream but it seemed reasonable to address it in the way I did.  The field _is_ always disabled but it doesn't hurt to render the relevant options.

##### ISSUE TYPE
 - Task

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
lgtm. if the unit tests pass and qe is happy, I am happy :+1:

**Comment by jakemcdermott** [comment]
cc @dsesami @unlikelyzero @appuk

**Review by dsesami — APPROVED** [review]
no weird regressions, looks good.

**Review by appuk — APPROVED** [review]
no major changes found in visual diff 👍

**Comment by mabashian** [comment]
regate

**Pull request merged**
