### PR TITLE
[WIP] Remove job isolation from management command logic

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Fixes bug with inventory update isolation

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
3.3.0
```

##### ADDITIONAL INFORMATION
Job isolation for inventory updates is already performed by the dispatcher task code. There is no need to do it here, and it breaks everything whenever something changes.

I thought I saw this done in the PR https://github.com/ansible/awx/pull/3041, but I think it was removed from that diff.

### CODE REVIEW

**Comment by ryanpetrello** [comment]
What about people who run `awx-manage inventory_import` by hand?

**Comment by AlanCoding** [comment]
this will turn off job isolation for them, the status of support for that is a good question of @wenottingham

**Comment by wenottingham** [comment]
> What about people who run `awx-manage inventory_import` by hand?

... they are already in a shell on the system with awx-level privileges?

**Comment by ryanpetrello** [comment]
> they are already in a shell on the system with awx-level privileges?

Okay, @wenottingham convinced me.

**Review by ryanpetrello — APPROVED** [review]

**Comment by AlanCoding** [comment]
I have another approach in progress

https://github.com/ansible/awx/compare/devel...AlanCoding:isolate_venv

sorry for that churn, this was a clunky process.

**Pull request closed without merging**
