### PR TITLE
allow nginx config extension

### PR DESCRIPTION
**Pull request by droopy4096**
##### SUMMARY

Extending nginx configuration to allow some flexibility. For example - when AWX is being accessed both directly and via LB callback URLs will be broken with default setup, but extending nginx.conf to have set_real_ip_from and real_ip_header resolves the issue. 

related #1952

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```
awx: 1.0.6.16
```

##### ADDITIONAL INFORMATION

this PR adds ability to optionally include additional configuration files by nginx so that end-users to not have to modify code from the project but rather modify inventory and maintain separate nginx configuration file.

### CODE REVIEW

**Comment by droopy4096** [comment]
checks are failing in django which is unrelated to changes in PR

**Review by matburt — APPROVED** [review]

**Comment by shanemcd** [comment]
@droopy4096 Thanks for this. Can you resolve the conflicts? Will merge after that.

**Comment by droopy4096** [comment]
I'm away from computers at the moment. will look into it after Aug 6

**Review by matburt — DISMISSED** [review]
fix conflicts

**Comment by droopy4096** [comment]
fixed conflicts

**Comment by shanemcd** [comment]
recheck

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
