### PR TITLE
fixes selinux permissions for awx data.

### PR DESCRIPTION
**Pull request by ikke-t**
fixes issue #2036 and  #1896

##### SUMMARY
Ansilbe docker module attaches volumes without setting selinux labels right. Probably will hit docker compose too, but I haven't tried. This fixes the above issues on Fedora 28, likely on any RHEL.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

##### AWX VERSION
latest

### CODE REVIEW

**Comment by shanemcd** [comment]
Can you also update this in the `docker-compose.yml.j2` jinja template?

**Comment by matburt** [comment]
@ikke-t ^^ respond to feedback?

**Comment by ikke-t** [comment]
Sorry @shanemcd and @matburt , the notification mail for your comment had slipped past my eyes. I made the change in template now too.

I was wondering what do options ':z' and ':Z' do on non selinux machines? Do they just get ignored? Docker is odd in the sense that it doesn't allow to put 'rwz', or 'roz', but just ':z'.

**Comment by ryanpetrello** [comment]
@ikke-t sorry for the delay on this one - do you mind taking another look and rebasing?  Looks like we're almost there.

**Comment by ikke-t** [comment]
Hi, rebased.

**Review by shanemcd — APPROVED** [review]

**Comment by shanemcd** [comment]
Thank you!

**Comment by geislermatt** [comment]
My hostconfig.json shows rw and not z - What file do I fix for the z option after it's install?
{"Binds":["/var/lib/awx/projects:/var/lib/awx/projects:rw"],

**Pull request merged**
