### PR TITLE
Avoid prop reference error when recreating survey

### PR DESCRIPTION
**Pull request by jakemcdermott**
##### SUMMARY
For #9370 

The survey object is undefined when recreating a survey after deleting it. Add optional chaining on survey fields to avoid prop reference error.

### CODE REVIEW

**Review by nixocio — APPROVED** [review]

**Comment by nixocio** [comment]
Note: When I was reviewing another PR I saw this error of `spec` null before on Firefox,  I was not able to see the same on chrome.

I triggered an e2e test run.

**Comment by mabashian** [comment]
@jakemcdermott looks like this one needs a rebase so quality can give this a go

**Comment by akus062381** [comment]
@jakemcdermott I tested this- just one thing I found- otherwise working great!

When adding a survey question, consider adding error handling for the following scenario:
Create a survey question in the question box. 
Add an answer variable name.
In answer type, choose Float.
In default answer, type 2.
Click Save.
Here is what the user sees:
image

**Comment by akus062381** [comment]
> @jakemcdermott I tested this- just one thing I found- otherwise working great!
> 
> When adding a survey question, consider adding error handling for the following scenario:
> Create a survey question in the question box.
> Add an answer variable name.
> In answer type, choose Float.
> In default answer, type 2.
> Click Save.
> Here is what the user sees:
> image

This is a known issue, see https://github.com/ansible/awx/issues/8460

**Comment by akus062381** [comment]
Issue is fixed! QE thumbs up

**Pull request merged**
