### PR TITLE
Add Sparkline to templates list

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #4225 

This PR adds two new components

1. The Sparkline - this component takes in an array of jobs and spits out a series of status icons
2. The Job Status Icon - this component takes in a job and renders based on the status of the job.  Optionally, a tooltip and/or link can be passed through to this component.  In the case of the Sparkline we want both but in other places where we show a single status icon we may not want either of those two things.

sparkline

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

I'm particularly interested in hearing feedback on the styled components in the Job Status Icon component.  If anyone's got better or more concise ways of doing that I'd be happy to refactor.

### CODE REVIEW

**Review by jlmitch5 — APPROVED** [review]
Code looks great!

**Comment by mabashian** [comment]
@trahman73 one thing that John brought up while reviewing this was the scenario where we show an exclamation point `!` inside the old job status circle to indicate a failed job.  Is that something that we need to carry over to this new status component?

**Comment by trahman73** [comment]
@mabashian @jlmitch5 We don't need to worry about the ! icon for this sparkline component as we show status as a box with one of two possible options:
top - green = success
bottom - red = fail
We should also have a text alternative tooltip for each status for screen readers and also if the user needs further clarification.

**Comment by mabashian** [comment]
Yea - we do have those tooltips.  @trahman73 sounds good.

**Pull request merged**
