### PR TITLE
Add Credential List 

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
Issue: https://github.com/ansible/awx/issues/5273

* Add credential list and credential list item components
* Add unit tests
* Create shared mock credential json object for unit tests
* This PR shows the default delete modal. In the future, we plan to discuss how to handle multi-delete when there are dependent resource counts. Created an issue here: https://github.com/ansible/awx/issues/5546
* Add Credential Add form placeholder

Screen Shot 2019-12-18 at 4 54 33 PM

#### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 9.1.0
```

##### ADDITIONAL INFORMATION
We decided to remove the *Owners* column. The same information can be gleaned through the Credential Access tab or through User / Team Permissions.

### CODE REVIEW

**Comment by dsesami** [comment]
Some notes:

- Having more than 20 items, then deleting a few of them while on the second page results in a 404, rather than a redirect to the first page.
Screenshot from 2019-12-19 11-57-00

- Deleting some credentials, then trying to do a second deletion, results in the previous deletion's list of credentials still being included. This results in a failure to delete the already-deleted credentials. I don't know if this is related, but when this error happens, the credential count fails to update.

**Comment by marshmalien** [comment]
@dsesami https://github.com/ansible/awx/pull/5542#issuecomment-567575413 Reopened Issue: https://github.com/ansible/awx/issues/4239

**Comment by marshmalien** [comment]
> Deleting some credentials, then trying to do a second deletion, results in the previous deletion's list of credentials still being included. This results in a failure to delete the already-deleted credentials. I don't know if this is related, but when this error happens, the credential count fails to update.

Pushing up a change to address this. We need to reset the selected state after a successful delete. Good find!

**Review by dsesami — APPROVED** [review]
Both issues are handled, the redirect is handled in a different issue, while multi-delete works great now. :+1:

**Review by jlmitch5 — APPROVED** [review]
Looks good!

**Review by mabashian — APPROVED** [review]
lgtm 🎉

**Pull request merged**
