### PR TITLE
added search for visualizer nodes

### PR DESCRIPTION
**Pull request by dsesami**
##### SUMMARY
Updated the workflow visualizer tests to use the searchbar, so that items hidden in pagination can be clicked.

##### COMPONENT NAME
 - UI

##### AWX VERSION
AWX 2.0.1-99-g110c5a8e8

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@dsesami lgtm. Which PR broke this?

**Comment by dsesami** [comment]
@unlikelyzero broke in Jenkins Test Tower E2E when it had too many projects and got shoved to page 2

**Comment by unlikelyzero** [comment]
@dsesami I mean which dev change was made to break the E2E test or is this just making the test more specific

**Comment by dsesami** [comment]
@unlikelyzero as far as i can tell this is just making this more specific. It seems to have been dependent on the state of the testbed, I can't track down the exact moment it broke

**Review by unlikelyzero — APPROVED** [review]

**Pull request merged**
