### PR TITLE
Add expanded row content to job list

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
#4977 

Add the following details to expanded section:
* Job Template
* Workflow Job Template
* Source Workflow Job
* Project
* Execution Environment

Screen Shot 2021-04-16 at 3 20 10 PM

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Comment by nixocio** [comment]
recheck

**Comment by nixocio** [comment]
I triggered an e2e test run.

**Comment by nixocio** [comment]
regate

**Review by nixocio — APPROVED** [review]

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Review by tiagodread — APPROVED** [review]
e2e tests are green, improved the assert of `can expand and collapse a row` in 6244

**Pull request merged**
