### PR TITLE
Move jt/wfjt created/modified details to the end right before the full width details

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #5683 

Screen Shot 2020-11-23 at 2 37 42 PM
Screen Shot 2020-11-23 at 2 20 57 PM

I also moved the Options detail in WorkflowJobTemplateDetail.jsx to come after the webhook details.  This makes it consistent with JobTemplateDetail.jsx.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

@unlikelyzero @tiagodread I assume this will cause a break in the visual tests

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by unlikelyzero** [comment]
Since this impacts all details views, we'll need to ensure that the e2e tests are green and the visual tests pass.

**Comment by unlikelyzero** [comment]
This will just need some visual test changes. If we don't have visual tests for this view, let's add them now

**Comment by tiagodread** [comment]
@mabashian we are not displaying `Created` and `Last Modified` data for some details page, I went through all details page checking the API response, and here is the list:

- Jobs: has data but not displayed
- notification templates: has data but not displayed
- applications: has data but not displayed

**Comment by mabashian** [comment]
@tiagodread 

Screen Shot 2021-01-04 at 3 20 25 PM
Screen Shot 2021-01-04 at 3 16 19 PM
Screen Shot 2021-01-04 at 3 13 17 PM

Including the user in the detail depends on whether its available via the api.  In some cases it is not.

**Review by tiagodread — APPROVED** [review]
Added visual tests in 5829

**Pull request merged**
