### PR TITLE
Fix automation analytics link in license page

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
Fix broken link to automation analytics docs on the licensing page. 

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Review by AlexSCorey — APPROVED** [review]

**Review by vidyanambiar — APPROVED** [review]
lgtm!

**Comment by jay-steurer** [comment]
Reviewing.

**Comment by jay-steurer** [comment]
@marshmalien could you rebase your PR? Thanks!

**Comment by mabashian** [comment]
@jay-steurer I just rebased this one

**Review by jay-steurer — APPROVED** [review]

**Comment by jay-steurer** [comment]
Verified by QE. Merging it

**Pull request merged**
