### PR TITLE
Adding Project Based Navigation of Job Templates

### PR DESCRIPTION
**Pull request by jaredevantabor**
##### SUMMARY
This adds a Job Templates tab onto the Project form that gives
the user the ability to see all the job templates using a project.
Clicking the add button on this list will take the user to the job
template form with the project field auto-filled with the project.

relates to https://github.com/ansible/awx/issues/72

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION
```
awx: 1.0.1.94
```

##### ADDITIONAL INFORMATION
image

image

### CODE REVIEW

**Comment by trahman73** [comment]
@jaredevantabor We might want to change the tab label from Job Templates to Templates as we show both Job and Workflow templates on this list.  I also have Templates as the last item on the tabs if that matters.
image

**Comment by wenottingham** [comment]
How does showing workflow templates work when they could conceivably have job templates from different projects?

**Comment by mabashian** [comment]
Yea the add button makes mixing workflows and JT's here kind of weird to me.  In this specific case the relationship between projects and workflows is achieved through a JT and I think that's tripping me up.  If we do want to display that information to the user could we just add another tab for workflows?  

Side note: If we're doing this I guess you could argue that we could add a Workflows tab to the job template details to show which workflows use that particular job template.

**Comment by jaredevantabor** [comment]
I moved the JOB TEMPLATES tab so that it matches the mockups. @trahman73 

>How does showing workflow templates work when they could conceivably have job templates from different projects? 

This is basically why I went with just Job Templates instead of both JT's and WFJT's. 

We could take this as far as we wanted, showing Inventories -> JT's, or cred's -> All-the-things, I'll defer to @wenottingham to instruct us on when/where he'd like us to add those.

**Comment by mabashian** [comment]
Not sure if this is related to your PR but I did notice this extra empty icon on the JT list:

screen shot 2017-10-25 at 3 21 03 pm

Not quite sure what icon that's supposed to be - cancel maybe?

Other than that I think this looks good.  Haven't looked at the test failures but if the UI suite looks good then I think this is good to go.  I'm going to request changes for that extra icon but we can chat about that if we need to.

**Review by mabashian — CHANGES_REQUESTED** [review]
Extra empty icon on Projects->Job Templates

**Review by mabashian — APPROVED** [review]

**Comment by simfarm** [comment]
@jaredevantabor @mabashian Great coordination and thinking here guys.

:100:

**Pull request merged**
