### PR TITLE
Fix image build - powertools repo ref changed

### PR DESCRIPTION
**Pull request by rooftopcellist**
##### SUMMARY
Fix borked awx image build.  

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - Installer

##### ADDITIONAL INFORMATION

Context: failed linting jobs on PR - https://ansible.softwarefactory-project.io/logs/70/8770/f2a6aacd7c97ea0157003bc0465bb50a00fd99ee/check/awx-api-lint/28e191d/job-output.txt.gz

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by ghost** [comment]
This looks like the issue I'm getting when trying to install AWX on CentOS 7 using docker.
I'm using the same installation method I have previously used for older versions, last version I tried before this was 11.2.0.
I'm trying to make a fresh install on a new system and have tried version 11.2.0, 13.0.0, 14.0.0 & 15.0.0 but I get the same error (pasted below) with all of these on the [image_build : Build base awx image] stage of the AWX installation.

I'm getting the same PowerTools and UTF errors:
- Error: No matching repo to modify: PowerTools
- Failed to set locale, defaulting to C.UTF-8

Is there an ETA when this will be fixed as currently I'm unable to install any version of AWX?

Thanks


AWX installer failure output:

fatal: [localhost]: FAILED! => {"changed": false, "msg": "Error building awx - code: 1, message: The command '/bin/sh -c dnf -y update &&     dnf -y install epel-release 'dnf-command(config-manager)' &&     dnf module -y enable 'postgresql:10' &&     dnf config-manager --set-enabled PowerTools &&     dnf -y install ansible     gcc     gcc-c++     git-core     glibc-langpack-en     libcurl-devel     libffi-devel     libtool-ltdl-devel     make     nodejs     nss     openldap-devel     patch     @postgresql:10     postgresql-devel     python3-devel     python3-pip     python3-psycopg2     python3-setuptools     swig     unzip     xmlsec1-devel     xmlsec1-openssl-devel' returned a non-zero code: 1, logs: ['Step 1/50 : ARG VENV_BASE=\"/var/lib/awx/venv\"', '\\n', 'Step 2/50 : ARG COLLECTION_BASE=\"/var/lib/awx/vendor/awx_ansible_collections\"', '\\n', 'Step 3/50 : FROM centos:8 as builder', '\\n', ' ---> 300e315adb2f\\n', 'Step 4/50 : ARG VENV_BASE', '\\n', ' ---> Using cache\\n', ' ---> 169aeef5c18c\\n', 'Step 5/50 : ARG COLLECTION_BASE', '\\n', ' ---> Using cache\\n', ' ---> 1b07b7442efb\\n', 'Step 6/50 : ENV LANG en_US.UTF-8', '\\n', ' ---> Using cache\\n', ' ---> 0a7c29b61bef\\n', 'Step 7/50 : ENV LANGUAGE en_US:en', '\\n', ' ---> Using cache\\n', ' ---> cc35e6a13504\\n', 'Step 8/50 : ENV LC_ALL en_US.UTF-8', '\\n', ' ---> Using cache\\n', ' ---> 0bc8d2ffbe2e\\n', 'Step 9/50 : USER root', '\\n', ' ---> Using cache\\n', ' ---> 96f4d16c43ce\\n', \"Step 10/50 : RUN dnf -y update &&     dnf -y install epel-release 'dnf-command(config-manager)' &&     dnf module -y enable 'postgresql:10' &&     dnf config-manager --set-enabled PowerTools &&     dnf -y install ansible     gcc     gcc-c++     git-core     glibc-langpack-en     libcurl-devel     libffi-devel     libtool-ltdl-devel     make     nodejs     nss     openldap-devel     patch     @postgresql:10     postgresql-devel     python3-devel     python3-pip     python3-psycopg2     python3-setuptools     swig     unzip     xmlsec1-devel     xmlsec1-openssl-devel\", '\\n', ' ---> Running in f64ef2decc40\\n', '\\x1b[91m/bin/sh: warning: setlocale: LC_ALL: cannot change locale (en_US.UTF-8)\\n\\x1b[0m', 'CentOS Linux 8 - AppStream                       13 MB/s | 6.3 MB     00:00    \\n', 'CentOS Linux 8 - BaseOS                          12 MB/s | 2.3 MB     00:00    \\n', 'CentOS Linux 8 - Extras                          28 kB/s | 8.6 kB     00:00    \\n', 'Dependencies resolved.\\n', 'Nothing to do.\\n', 'Complete!\\n', '\\x1b[91mFailed to set locale, defaulting to C.UTF-8\\n\\x1b[0m', 'Last metadata expiration check: 0:00:02 ago on Tue Jan  5 16:11:32 2021.\\n', 'Dependencies resolved.\\n', '================================================================================\\n Package                       Arch        Version            Repository   Size\\n================================================================================\\nInstalling:\\n dnf-plugins-core              noarch      4.0.17-5.el8       baseos       66 k\\n epel-release                  noarch      8-8.el8            extras       23 k\\nInstalling dependencies:\\n python3-dateutil              noarch      1:2.6.1-6.el8      baseos      251 k\\n python3-dnf-plugins-core      noarch      4.0.17-5.el8       baseos      221 k\\n python3-six                   noarch      1.11.0-8.el8       baseos       38 k\\n\\nTransaction Summary\\n================================================================================\\nInstall  5 Packages\\n\\n', 'Total download size: 599 k\\n', 'Installed size: 1.4 M\\n', 'Downloading Packages:\\n', '(1/5): dnf-plugins-core-4.0.17-5.el8.noarch.rpm 1.7 MB/s |  66 kB     00:00    \\n', '(2/5): python3-six-1.11.0-8.el8.noarch.rpm      7.2 MB/s |  38 kB     00:00    \\n', '(3/5): python3-dateutil-2.6.1-6.el8.noarch.rpm  5.3 MB/s | 251 kB     00:00    \\n', '(4/5): python3-dnf-plugins-core-4.0.17-5.el8.no 4.6 MB/s | 221 kB     00:00    \\n', '(5/5): epel-release-8-8.el8.noarch.rpm          656 kB/s |  23 kB     00:00    \\n', '--------------------------------------------------------------------------------\\n', 'Total                                           808 kB/s | 599 kB     00:00     \\n', '\\x1b[91mwarning: /var/cache/dnf/baseos-f6a80ba95cf937f2/packages/dnf-plugins-core-4.0.17-5.el8.noarch.rpm: Header V3 RSA/SHA256 Signature, key ID 8483c65d: NOKEY\\n\\x1b[0m', 'CentOS Linux 8 - BaseOS                         1.6 MB/s | 1.6 kB     00:00    \\n', '\\x1b[91mFailed to set locale, defaulting to C.UTF-8\\nImporting GPG key 0x8483C65D:\\n Userid     : \"CentOS (CentOS Official Signing Key) <security@centos.org>\"\\n Fingerprint: 99DB 70FA E1D7 CE22 7FB6 4882 05B5 55B3 8483 C65D\\n From       : /etc/pki/rpm-gpg/RPM-GPG-KEY-centosofficial\\n\\x1b[0m', 'Key imported successfully\\n', 'Running transaction check\\n', 'Transaction check succeeded.\\nRunning transaction test\\n', 'Transaction test succeeded.\\n', 'Running transaction\\n', '  Preparing        :                                                        1/1', ' \\n  Installing       : python3-six-1.11.0-8.el8.noarch                        1/5', ' \\n  Installing       : python3-dateutil-1:2.6.1-6.el8.noarch                  2/5', ' \\n  Installing       : python3-dnf-plugins-core-4.0.17-5.el8.noarch           3/5', ' \\n  Installing       : dnf-plugins-core-4.0.17-5.el8.noarch                   4/5', ' \\n  Installing       : epel-release-8-8.el8.noarch                            5/5', ' \\n  Running scriptlet: epel-release-8-8.el8.noarch                            5/5', ' \\n  Verifying        : dnf-plugins-core-4.0.17-5.el8.noarch                   1/5', ' \\n  Verifying        : python3-dateutil-1:2.6.1-6.el8.noarch                  2/5 \\n  Verifying        : python3-dnf-plugins-core-4.0.17-5.el8.noarch           3/5', ' \\n  Verifying        : python3-six-1.11.0-8.el8.noarch                        4/5 \\n  Verifying        : epel-release-8-8.el8.noarch                            5/5', ' \\n\\nInstalled:\\n  dnf-plugins-core-4.0.17-5.el8.noarch                                          \\n  epel-release-8-8.el8.noarch                                                   \\n  python3-dateutil-1:2.6.1-6.el8.noarch                                         \\n  python3-dnf-plugins-core-4.0.17-5.el8.noarch                                  \\n  python3-six-1.11.0-8.el8.noarch                                               \\n\\n', 'Complete!\\n', 'Extra Packages for Enterprise Linux Modular 8 - 676 kB/s | 527 kB     00:00    \\n', 'Extra Packages for Enterprise Linux 8 - x86_64   11 MB/s | 8.7 MB     00:00    \\n', 'Dependencies resolved.\\n', '================================================================================\\n Package           Architecture     Version             Repository         Size\\n================================================================================\\nEnabling module streams:\\n postgresql                         10                                         \\n\\nTransaction Summary\\n================================================================================\\n\\n', 'Complete!\\n', '\\x1b[91mFailed to set locale, defaulting to C.UTF-8\\n\\x1b[0m', '\\x1b[91mFailed to set locale, defaulting to C.UTF-8\\nError: No matching repo to modify: PowerTools.\\n\\x1b[0m', 'Removing intermediate container f64ef2decc40\\n']"}

**Comment by ryanpetrello** [comment]
> Is there an ETA when this will be fixed as currently I'm unable to install any version of AWX?

Hey @OwainWin,

This commit will be in the next official release we cut.  I don't have an ETA at the moment, but I'd probably expect something likely in the coming weeks.

**Comment by ghost** [comment]
Thanks Ryan.
In the meantime is there a file that I can manually change to be able to install AWX?

Best regards

Owain

**Comment by ryanpetrello** [comment]
Yes, the one in this pull request:

https://github.com/ansible/awx/pull/8775/files

**Comment by ghost** [comment]
Thanks I'll give that a try.

**Pull request merged**
