### PR TITLE
Add alt text for image directives in credential_types.rst

### LINKED ISSUE #14501: [DOCS] Add alt-text codeblock to Images for Userguide: credential_types.rst
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.
- [X] I am **NOT** reporting a (potential) security vulnerability. (These should be emailed to `security@ansible.com` instead.)

### Bug Summary

We need to add alt-text to images for accessibility purposes. See the syntax in the Expected Results below.

### AWX version

latest

### Select the relevant components

- [ ] UI
- [ ] UI (tech preview)
- [ ] API
- [X] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

kubernetes

### Modifications

no

### Ansible version

_No response_

### Operating system

_No response_

### Web browser

_No response_

### Steps to reproduce

1. Clone the AWX repo.
2. Navigate to the source files for the User Guide in GitHub at: https://github.com/ansible/awx/tree/devel/docs/docsite/rst/userguide (locally they should reside in ``/Users/you/awx/docs/docsite/rst/userguide``).
3. Open the credential_types.rst file to edit it. Search all image directives and place the `:alt:` code block beneath it. See syntax in Expected Results below.
4. Commit the changes, open a PR.

### Expected results

The following codeblock added to each image with its specific descriptors filled in: 
```
.. image:: ../common/images/image-filename.png
   :alt: Phrase that describes image

```
or

```   
|Resource - alt text describing image|

.. |Resource - alt text describing image| image:: ../common/images/image-filename.png
   :alt: Phrase that describes image

```
### Actual results
Some images don't have the alt text info in them.

### Additional information
Example from Credentials section of the User Guide:

```
Add Team Permissions
^^^^^^^^^^^^^^^^^^^^^^

To add permissions to a Team:

1. Click the **Add** button, which opens the Add Permissions Wizard.

.. image:: ../common/images/teams-users-add-permissions-form.png 
   :alt: Add Permissions Form

```

### PR DESCRIPTION
**Pull request by kishan3**
Fixes #14501

##### SUMMARY

Add alt text for image directives in credential_types.rst

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Docs

### CODE REVIEW

**Comment by kishan3** [comment]
Hi @tvo318 can you please check my PRs if anything required?

**Comment by oraNod** [comment]
Hi @kishan3 Thanks for the contribution!

Can you please amend your final commit to do the DCO signoff per the [Contributor's Guide guidelines](https://ansible.readthedocs.io/projects/awx/en/latest/contributor/work_items.html#things-to-know-prior-to-submitting-revisions)?

1. ``git commit --signoff``
2. Push to your branch

**Comment by kishan3** [comment]
Hi @tvo318 @oraNod I updated PR with signoff commit.

**Review by tvo318 — APPROVED** [review]
Thanks for your contribution, @kishan3 🎉  I made some revisions to the alt text and approved this PR so we can push it through!

**Pull request merged**
