### PR TITLE
Bump timeout for unit-tests

### PR DESCRIPTION
**Pull request by nixocio**
Bump timeout for unit-tests.

### CODE REVIEW

**Comment by mabashian** [comment]
recheck

**Comment by mabashian** [comment]
recheck

**Comment by mabashian** [comment]
recheck

**Comment by mabashian** [comment]
recheck

**Comment by nixocio** [comment]
recheck

**Review by mabashian — APPROVED** [review]

**Comment by nixocio** [comment]
This change is a workaround as we try to better understand the reason for these timeouts.

**Pull request merged**
