### PR TITLE
Pass new ansible-runner parameters to reduce number of artifacts we don't need on file system

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Connect https://github.com/ansible/awx/issues/11356

Direct follow-up from https://github.com/ansible/ansible-runner/pull/937 and https://github.com/ansible/ansible-runner/pull/939

This has not been tested. At all. Once I verify functionality I will make it non-draft.

##### ISSUE TYPE
 - Feature Pull Request
 - Bugfix Pull Request

##### COMPONENT NAME
 - API

### CODE REVIEW

**Comment by AlanCoding** [comment]
Now I'm testing in conjunction with https://github.com/ansible/ansible-runner/pull/943

**Comment by AlanCoding** [comment]
That's working as intended. I'll mark this as non-draft whenever the ansible-runner PR merges.

**Comment by AlanCoding** [comment]
I rebuilt the image and ran the demo job template with cleanup turned off, it produces this:

```
$ docker exec -it tools_receptor_1 tree /tmp/awx_694_yhrvjvsf
/tmp/awx_694_yhrvjvsf
├── artifacts
│   └── 694
│       ├── ansible_version.txt
│       ├── collections.json
│       ├── command
│       ├── env.list
│       ├── job_events
│       ├── rc
│       └── status
├── cp
├── env
│   ├── cmdline
│   ├── envvars
│   ├── extravars
│   ├── passwords
│   ├── settings
│   └── ssh_key
├── inventory
│   └── hosts
└── project
    ├── hello_world.yml
    └── README.md

7 directories, 15 files

$ docker exec -it tools_awx_1 tree /tmp/awx_694_yhrvjvsf
/tmp/awx_694_yhrvjvsf
├── artifacts
│   └── 694
│       ├── ansible_version.txt
│       ├── collections.json
│       ├── command
│       ├── env.list
│       ├── job_events
│       ├── rc
│       └── status
├── cp
├── env
│   ├── cmdline
│   ├── envvars
│   ├── extravars
│   ├── passwords
│   ├── settings
│   └── ssh_key
├── inventory
│   └── hosts
└── project
    ├── hello_world.yml
    └── README.md

7 directories, 15 files
```

This is a pretty good reflection of the intent. The structures match, not as much unnecessary stuff being written.

**Comment by AlanCoding** [comment]
There's still a problem here, because we get things from the artifact directory after a run has completed. With this work, that has obviously moved. This affects inventory, facts, and other stuff.

**Comment by AlanCoding** [comment]
that should be wrapped up with the last commit, kicking off more tests now.

**Review by amolgautam25 — APPROVED** [review]

**Comment by AlanCoding** [comment]
I discovered an unexpected test failure related to this. This is where my latest commit is coming from - it deletes the artifacts folder after it has been sent so that we can detect cases where the fact cache was cleared.

Looking further at this, I went down the rabbit hole which was https://github.com/ansible/awx/issues/11560, and I have a pretty good idea of some followup bug fixes and improvements.

I also believe that AWX `devel` branch is very broken with the ansible-runner `devel` branch to the extent that facts are not even saved (because process takes ident, and everything gets confused).

I believe this PR should work as good as current `devel` branch with the latest commit, and I have restarted tests to confirm.

**Review by jbradberry — APPROVED** [review]

**Review by shanemcd — APPROVED** [review]

**Pull request merged**
