### PR TITLE
Remove two unused parent relationships from JobEvent model

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
These are no longer supported. Since there is no way for users to even get these populated with the correct data, there is no longer any argument for keeping them around.

https://github.com/ansible/awx/pull/5618

https://github.com/ansible/awx/pull/5618#discussion_r364841910

> This method was dead code that nothing was calling. I can't see any evidence of its use since ~2014.

https://github.com/ansible/awx/pull/5618#discussion_r364852325

> Looks like it got turned off as default behavior years ago - 🤷‍♂

(setting to turn it back on was removed)

https://github.com/ansible/awx/pull/3800

> I would like to delete the job event children relationship, but do that separately from this. This PR is to restore functionality to this endpoint.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - API

##### AWX VERSION
```
9.1.1
```

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by ryanpetrello** [comment]
If you don't mind, please hold off on merging this until I get https://github.com/ansible/awx/pull/5448 in (soon) 😄

**Comment by AlanCoding** [comment]
Oh sure, I'm not 100% finished with testing this. When I am I will squash commits and the 2 migrations.

**Review by ryanpetrello — APPROVED** [review]
Assuming integration looks good, I'm fine with this 👍

**Comment by AlanCoding** [comment]
Finished triaging results, I'm good to merge this, @matburt any concerns from you?

**Comment by matburt** [comment]
Sorry I missed this last week, it looks good by me.

**Pull request merged**
