### PR TITLE
removed unused analytics metrics

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Review by benthomasson — APPROVED** [review]
LGTM

**Comment by ryanpetrello** [comment]
```
bash-4.4$ tar zxvf 00000000-0000-0000-0000-000000000000_2020-11-11-170445+0000_0.tar.gz
./
./unified_jobs_table.csv
./manifest.json
./config.json
./workflow_job_template_node_table.csv
./instance_info.json
./query_info.json
./workflow_job_node_table.csv
./unified_job_template_table.csv
./events_table.csv
```

cc @Ladas @benthomasson

**Comment by Ladas** [comment]
@ryanpetrello awesome, we should backport to at least 3.7 @wenottingham ?

**Comment by wenottingham** [comment]
NO.

**Pull request merged**
