### PR TITLE
Add polling interval argument for --monitor/--wait

### PR DESCRIPTION
**Pull request by hluk**
##### SUMMARY

Adds `--poll-interval` CLI flag indicating the interval between API calls when `--monitor` or `--wait` are used.

The default value is set to 2000ms (instead of the previous 250ms) to avoid overwhelming the server in case client does not set the interval explicitly.

The logs retrieval will be less smooth (unless user overrides the interval) but it makes the job monitoring much less likely to fail by overloading the server (which can respond for example with 502 Bad Request status code).

The minimum allowed value is 250ms.

related #14064

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - CLI

##### AWX VERSION

```
awx: 22.3.1.dev19+g1bd7770c30
```

##### ADDITIONAL INFORMATION

Monitoring jobs with a default small polling interval (which was 250 ms) causes server to get overloaded (assuming there are many clients) and in turn the monitoring process fails after it gets unexpected response from the server (for example with 502 Bad Request status code).

### CODE REVIEW

**Review by dangoncalves — COMMENTED** [review]
IMHO it would be worth to have poll_interval in second instead of millisecond

**Comment by hluk** [comment]
> IMHO it would be worth to have poll_interval in second instead of millisecond

Yeah, that would be more consistent with the units used by the other arguments.

Is it OK to make the argument value type `float` instead of `int`? Value `0.25` would be the minimum, `2.0` the default.

**Comment by dangoncalves** [comment]
I understand your POV, but it would be better if we accept both float and int.
Minimum and default are fine for me.

**Comment by hluk** [comment]
> I understand your POV, but it would be better if we accept both float and int.

I've changed the unit to seconds and the type to `float`. This accepts integers on command line as well - i.e. `--poll-interval=2` would be parsed as `2.0`.

**Review by dangoncalves — APPROVED** [review]

**Comment by hluk** [comment]
I'm closing this in favor of #14068.

**Pull request closed without merging**
