### PR TITLE
fix a formatting bug re: required arguments in the CLI

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by kdelee** [comment]
LGTM, still need to address some missing ones but this is big improvement
```
awx users create --help
usage: awx users create [-h] --username TEXT [--first_name TEXT]
                        [--last_name TEXT] [--email TEXT]
                        [--is_superuser BOOLEAN] [--is_system_auditor BOOLEAN]
                        [--password TEXT] [--last_login LAST_LOGIN]

required arguments:
  --username TEXT       [REQUIRED] Required. 150 characters or fewer. Letters,
                        digits and @/./+/-/_ only.

optional arguments:
  -h, --help            show this help message and exit
  --first_name TEXT
  --last_name TEXT
  --email TEXT
  --is_superuser BOOLEAN
                        Designates that this user has all permissions without
                        explicitly assigning them.
  --is_system_auditor BOOLEAN
  --password TEXT       Write-only field used to change the password.
  --last_login LAST_LOGIN

awx users create: the following arguments are required: --username
```

**Review by kdelee — APPROVED** [review]
:shipit:

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/awx/issues/4560

**Review by kdelee — APPROVED** [review]
works for me! thanks

**Comment by kdelee** [comment]
> Build failed.
> 
> * [awx-api-lint ](https://ansible.softwarefactory-project.io/logs/62/4562/67dcc84200a154b38a121e9315a4a7ec71848f7f/check/awx-api-lint/0822353/) : SUCCESS in 4m 55s
> * awx-ui-lint  : RETRY_LIMIT in 3s
> * awx-ui-next-lint  : RETRY_LIMIT in 4s
> * awx-api  : RETRY_LIMIT in 4s
> * [awx-ui ](https://ansible.softwarefactory-project.io/logs/62/4562/67dcc84200a154b38a121e9315a4a7ec71848f7f/check/awx-ui/ab35e08/) : FAILURE in 6m 19s
> * awx-ui-next  : RETRY_LIMIT in 4s
> * [awx-swagger ](https://ansible.softwarefactory-project.io/logs/62/4562/67dcc84200a154b38a121e9315a4a7ec71848f7f/check/awx-swagger/90d6264/) : SUCCESS in 11m 58s
> * awx-detect-schema-change  : RETRY_LIMIT in 3s (non-voting)

zuul angry :angry:

**Comment by ryanpetrello** [comment]
recheck

**Comment by kdelee** [comment]
This actually closes https://github.com/ansible/awx/issues/4569 NOT https://github.com/ansible/awx/issues/4560 <-- that one has additional component of not having password

**Pull request merged**
