### PR TITLE
Update Frequency of Collection for Automation Analytics

### PR DESCRIPTION
**Pull request by rooftopcellist**
##### SUMMARY

Addresses these Issues:
* https://github.com/ansible/tower/issues/3781
* https://github.com/ansible/tower/issues/3729

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
Seems pretty reasonable.

**Review by benthomasson — APPROVED** [review]

**Comment by ryanpetrello** [comment]
regate

**Comment by rooftopcellist** [comment]
regate

**Comment by ryanpetrello** [comment]
recheck

**Pull request merged**
