### PR TITLE
Only allow legal/logical match types in advanced search

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Limits the match type options in Advanced Search based on the selected search key:
- iexact, contains, and icontains matching only allowed on string fields
- startswith and endswith options removed when searching on datetime fields
- greater than/less then options removed when searching a json field

As far as I can tell, invalid `icontains` searches were the only ones that actually resulted in errors from the API, but since some of these other methods didn't really seem to make sense to me, I removed options that seemed nonsensical or not useful (I'm open to suggestions on any changes here)

Addresses #7834, #9222

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI
 
##### ADDITIONAL INFORMATION
This change involved restructuring the `searchableKeys` prop from an array of strings to an array of objects, each containing the search key and its data type. I added a util function to make it easier to extract this from the ACTIONS response and updated everywhere that did this work to use the new util

### CODE REVIEW

**Comment by nixocio** [comment]
hello @keithjgrant, goob job on this PR.

~I spent some time with this code, and I noticed this one.~

image

~Is that a case that we want to avoid with your changes?~

I was not able to reproduce this behavior again.

**Comment by keithjgrant** [comment]
@nixocio good catch. I'll take a look

**Review by nixocio — APPROVED** [review]

**Comment by akus062381** [comment]
I am adding the needs_test label because I feel UI-QE should verify these changes.

**Comment by akus062381** [comment]
@keithjgrant question- I noticed that the "elapsed" field had lookup type options that the date/time fields did not. I know that elasped is only time, but I wanted to make sure this was your intention?

**Comment by keithjgrant** [comment]
@akus062381 Yes, that was my intention. I make the decision purely based on the `type` the API expects for a field. Since "elapsed" is type "decimal" some of the filters that don't make sense for dates might still make sense for filtering on elapsed # of seconds

**Review by akus062381 — APPROVED** [review]

**Pull request merged**
