### PR TITLE
allows all WFJT  tabs to properly route to workflow visualizer

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
The addresses #4523.  This add a fix so that all tabs are able to route to the Workflow visualizer.  

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
7.0.0
```
##### ADDITIONAL INFORMATION
Tabs

### CODE REVIEW

**Review by marshmalien — APPROVED** [review]
Tested this out locally by clicking the `Missing Job Templates found in the Workflow Editor` link from the Permissions, Notifications, Completed Jobs, and Schedules tabs. Routes to the correct workflow editor 👍

**Comment by mabashian** [comment]
Nice!

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
regate

**Pull request merged**
