### PR TITLE
Remove tower-cli from Zuul CI for AWX collection

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
https://github.com/ansible/awx/issues/5145 is almost finished, so ready to turn this off.

##### ISSUE TYPE
 - Feature Pull Request

##### AWX VERSION
```
10.0.0
```

### CODE REVIEW

**Comment by AlanCoding** [comment]
recheck

**Review by ryanpetrello — APPROVED** [review]

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
Apologies for the noise, going to use this PR for Zuul debugging.

**Pull request merged**
