### PR TITLE
remove the `new_in_<version>` in API doc gen

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/73

related comments at https://github.com/ansible/awx/issues/73#issuecomment-364166740

### CODE REVIEW

**Comment by wenottingham** [comment]
What is the actual strategy we'd use for marking things?

**Comment by ryanpetrello** [comment]
@wenottingham none; see https://github.com/ansible/awx/issues/73#issuecomment-364166740

The idea is that we would compare diffs of OpenAPI specs between releases and generate per-release changelogs.  Whatever the case, these labels are currently out of date and inaccurate for awx.

**Review by matburt — APPROVED** [review]

**Comment by wenottingham** [comment]
As long as we commit to doing that, OK.

**Review by cchurch — APPROVED** [review]
'Bout damn time 😂

**Pull request merged**
