### PR TITLE
The python 3.6 package seems to already make this symlink

### PR DESCRIPTION
**Pull request by matburt**
```
[root@045499f99bbf /]# yum whatprovides /usr/bin/python3                                                                                                                                 
python34u-3.4.8-1.ius.centos7.x86_64 : Version 3 of the Python programming language aka Python 3000                                                                                      
Repo        : ius                                                                                                                                                                        
python36-3.6.6-5.el7.x86_64 : Interpreter of the Python programming language                                                                                                             
Repo        : epel                                                                                                                                                                       
python36-3.6.6-5.el7.x86_64 : Interpreter of the Python programming language                                                                                                             
Repo        : epel
```

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by matburt** [comment]
recheck

**Comment by ryanpetrello** [comment]
regate

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
replaced by https://github.com/ansible/awx/pull/3626

**Pull request closed without merging**
