### PR TITLE
Remove text about confirming launch-time passwords.

### PR DESCRIPTION
**Pull request by wenottingham**
We haven't required double-entry for a long time now.

### CODE REVIEW

**Comment by wenottingham** [comment]
I tried to dig out when we changed this behavior and failed.

**Review by AlanCoding — APPROVED** [review]
this change must have been ancient

**Comment by mabashian** [comment]
I don't think we want the manual changes to the .pot and .po files.  Those should get updated via our automated processes the next time strings are aggregated.

**Comment by wenottingham** [comment]
po/pot changes removed.

**Review by ryanpetrello — APPROVED** [review]

**Pull request merged**
