### PR TITLE
Pre-lingui upgrade 

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
In preparation for a Ling ui upgrade I am auditing our files that use withI18n looking for those files that still use React classes.  Where it makes sense to move those over to hook I am doing so. This is the first PR doing that.  This will be followed by at least 1 or 2 more PRs doing this.  No functionality has changed.

12/15/2020 ran e2e tests on this PR and everything passed
##### ISSUE TYPE
- Preparation PR

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by nixocio** [comment]
I would suggest to run e2e tests to verify that no regression was added.

**Comment by AlexSCorey** [comment]
> I would suggest to run e2e tests to verify that no regression was added.

yep that's the plan.  Pipeline are down right now but I'm trying to run them locally.  When I get 👍  from that Ill mark this PR for needs review

**Comment by unlikelyzero** [comment]
@AlexSCorey we didn't find any other teams using a i18n linter or linting strategy. The closest we got was https://www.npmjs.com/package/i18next-pseudo which is being run by the openshift/console project to check i18n of strings pre-merge

**Review by jakemcdermott — APPROVED** [review]
LGTM - This is basically just a refactor for some of our components. All unit, functional, and e2e test results look good

**Review by jlmitch5 — APPROVED** [review]
looking good!

**Comment by unlikelyzero** [comment]
@tiagodread and I met with @AlexSCorey and noticed that the inventory lookup field did not appear as 'enabled' on Edit forms. Will need to investigate further and apply mergeit if not related to the changes in this PR

**Comment by unlikelyzero** [comment]
@AlexSCorey i'm seeing hundreds of API requests on edit pages. I think that's why the visual tests were failing: the inventory lookups never stop firing
Screen Shot 2020-12-15 at 7 50 30 PM

**Review by unlikelyzero — DISMISSED** [review]
something is blowing up the edit forms. We need to take a hard look at this one when you get back from break. 
https://share.getcloudapp.com/kpuN6LlN

**Comment by jakemcdermott** [comment]
Very nice find @unlikelyzero! - looks like we have a misconfigured hook somewhere in the form. We'll just have to address this once folks are back before merging.

**Comment by jakemcdermott** [comment]
Note: I decided to just fix this: https://github.com/ansible/awx/pull/8706/commits/5cb580be7a5cc72c43115126c10ec269e98802ae

**Comment by jakemcdermott** [comment]
regate

**Pull request merged**
