### PR TITLE
Added more context to subscription details and rearrange the order of some of the fields

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
Adds static help text to subscription details depending on status.  Moved a number of compliance related fields up to the beginning of the details view.  See the original issue for more details.

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by keithjgrant** [comment]
I'm curious what the thinking is on using static help text here when we use Popovers in all other Details. (There is certainly an accessibility argument for using static text everywhere.) `<Detail>` has a `helpText` prop that uses a Popover... I'm wondering if we should use that

**Comment by mabashian** [comment]
@keithjgrant - Yea I'll defer to @ffirg but I think the idea is to put something right in the users face.  If we put this in a tooltip/popover it might be too subtle.

**Review by AlexSCorey — APPROVED** [review]
This looks good to me.

**Comment by AlexSCorey** [comment]
Is there an issue tracking this work?

**Review by InnocentK — APPROVED** [review]
Looks good! (ignore the failing tests above--those are unrelated to these changes)

**Pull request merged**
