### PR TITLE
update social-auth-core to address a GitHub API deprecation

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/5970
see: https://github.com/python-social-auth/social-core/pull/428

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]

**Comment by ryanpetrello** [comment]
Github Organization SSO seems to work for me with this PR:

```
bash-4.4$ awx-python
Python 3.6.8 (default, Nov 21 2019, 19:31:34)
[GCC 8.3.1 20190507 (Red Hat 8.3.1-4)] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import social_core
>>> social_core.__version__
'3.3.0'
```

image

image

image

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
Ugh.

The latest `social-auth-core` brings in https://pypi.org/project/Unidecode/1.1.1/ as a dependency, which is GPLv2.

🤕 

cc @wenottingham

**Comment by ryanpetrello** [comment]
Okay, it looks like the package author is open to fixing this:

https://github.com/python-social-auth/social-core/issues/449#issuecomment-603868350

Once a new version is released that addresses this, I'll update this PR to pin the *new* version.

**Comment by omab** [comment]
@ryanpetrello, a new version of `python-social-auth` was just released, version `3.3.1` with the corresponding fix to this issue.

**Comment by ryanpetrello** [comment]
Amazing.

**Thank you** @omab!

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
