### PR TITLE
Add a message to the resulting login dialog when a user explicitly logs out.

### PR DESCRIPTION
**Pull request by wenottingham**
##### ADDITIONAL INFORMATION

Warning: javascripting-by-cargo-cult.

### CODE REVIEW

**Comment by Spredzy** [comment]
recheck

**Review by jlmitch5 — APPROVED** [review]
looks good

**Comment by ryanpetrello** [comment]
@unlikelyzero @jladdjr @Spredzy this seems like a pretty low-impact improvement; you comfortable w/ us merging this?

**Comment by unlikelyzero** [comment]
Can you detail how it is tested?

**Comment by ryanpetrello** [comment]
I've only tested/confirmed it by hand in the Docker install environment:

kapture 2018-11-20 at 12 07 18

If you're _not_ comfortable with us merging this, that's fine - let's just detail here what we need to be comfortable with a merge.

**Review by jakemcdermott — APPROVED** [review]
code changes lgtm, no surprises on the e2e 👍 

I think this looks merge-able.

**Comment by unlikelyzero** [comment]
Can we test the following scenarios:
- Auto logout message when custom warning messages are configured
- Auto logout message when customer images are used

**Comment by jakemcdermott** [comment]
@unlikelyzero let us know what you find!

**Comment by ryanpetrello** [comment]
@unlikelyzero this seems to work for me using a custom login message and logo:

kapture 2018-11-27 at 9 58 26

I'm going to go ahead and merge this one.

**Comment by unlikelyzero** [comment]
:thumbs-up:

**Pull request merged**
