### PR TITLE
Modernize types of WFJT module

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Proposed fix for https://github.com/ansible/awx/issues/6167

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - AWX collection

##### AWX VERSION
```
9.2.0
```

##### ADDITIONAL INFORMATION
I actually have manual testing for this.

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  tasks:
    - name: delete a workflow job template
      awx.awx.tower_workflow_template:
        name: issue-workflow5
        organization: Default
        state: absent

    - name: Create a workflow job template
      awx.awx.tower_workflow_template:
        name: issue-workflow5
        description: created by Ansible Playbook
        organization: Default
        survey_enabled: false
        allow_simultaneous: no
        schema: "{{ lookup('file', '{{ playbook_dir }}/schema.json') }}"
        # schema:
        #   - job_template: Demo Job Template
        # extra_vars:
        #   var1: val1
        #   var2:
        #     var21: val21
        #     var22: val22
        #   var3:
        #     - var4
        #     - var5
        #   var6:
        #     - var7: val7
        #     - var8: val8
        #       var9: val9
      register: new_workflow

    - debug: var=new_workflow
```

with both versions of schema it works.

I produced the schema via

```
tower-cli workflow schema 202 --format=json > sanity/schema.json
```

This is what is documented in the example, so that's good to have.

### CODE REVIEW

**Comment by AlanCoding** [comment]
I put up https://github.com/ansible/ansible/pull/68151 to justify my change in integration tests.

**Comment by AlanCoding** [comment]
@kedark3 I'm happy with this fix as it is now, and I believe it should fix the issue you reported.

@squidboylan wanted to ask if you had any other issues with it too

**Comment by kedark3** [comment]
@AlanCoding I appreciate your team's quick turnaround. What would be the best way to pull these fixes in? Do I have to start using upstream ansible vs the one that RH Repo's would provide?

**Review by beeankha — APPROVED** [review]
The changes here all make sense, thanks for doing this work @AlanCoding !

**Comment by AlanCoding** [comment]
@kedark3 You need Ansible 2.9. If you have that (or more recent), you should be able to use this content.

There are various ways to install, but however it happens, you want the contents in this `awx_collection` folder copied into your local folder `~/.ansible/collections/ansible_collections/awx/awx`. You can copy them outright. We have several targets in the top-level Makefile for this repo that do variations of that. So a quick job could look like:

```
mkdir -p ~/.ansible/collections/ansible_collections/awx
rm -rf ~/.ansible/collections/ansible_collections/awx/awx
git clone --single-branch --depth=1 --branch wfjt_vars https://github.com/AlanCoding/awx.git
cp -Ra awx/awx_collection ~/.ansible/collections/ansible_collections/awx
```

The other thing you need are playbook changes, which can be done at the play level like:

```yaml
---
- hosts: localhost
  gather_facts: false
  connection: local
  collections:
    - awx.awx
  tasks:
```

This tells us to use modules in the collection, as opposed to `tower_workflow_template` as it existed in Ansible 2.9.

**Comment by kedark3** [comment]
@AlanCoding thanks for the comment. It seems like it will be non-standard(aka from your fork) install until new release of awx collections comes out, right? Is there a release scheduled?

**Comment by AlanCoding** [comment]
Well we went ahead and merged it, but I believe that it just missed the 9.3.0 release. You could still try the development version of the collection at any time with slightly simplified instructions.

```
mkdir -p ~/.ansible/collections/ansible_collections/awx
rm -rf ~/.ansible/collections/ansible_collections/awx/awx
git clone --depth=1 https://github.com/awx/awx.git
cp -Ra awx/awx_collection ~/.ansible/collections/ansible_collections/awx
```

**Comment by kedark3** [comment]
@AlanCoding Thanks. Seems like release cadence is monthly once.

**Pull request merged**
