### PR TITLE
docs: update execution_nodes.md to follow changes for receptor_collection

### PR DESCRIPTION
**Pull request by kurokobo**
##### SUMMARY

related #14247

Update `execution_nodes.md` to follow following changes:

- Copr repository is no longer used in new receptor collection
- ~~`receptor_dependencies` in `group_vars/all.yml` has been updated as `python3-pip` in this feature branch, and this causes error on RHEL 8 based OS since it's too old and causes error during Ansible Runner installation.~~ (edit: will be fixed on the collection side by https://github.com/ansible/receptor-collection/pull/47)

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Docs

##### AWX VERSION

```
# feature_hop-node branch
awx: 22.5.1.dev43+g7df570e9cd
```

##### ADDITIONAL INFORMATION

I'm sending this PR against `feature_hop-node` branch, since `requirements.yml` ~~and `group_vars/all.yml`~~ is updated on only in this branch.
The `devel` branch doesn't have the related issue, since its `requirements.yml` points old collection ~~and `group_vars/all.yml`~~ has old value.

### CODE REVIEW

**Comment by thedoubl3j** [comment]
related https://github.com/ansible/receptor-collection/pull/47

**Comment by kurokobo** [comment]
@thedoubl3j 
Thanks for informing me, I didn't realize that there is a PR to fix dependency issue by collection side.
I have updated this PR here to just remove paragraph about Copr.

**Comment by kurokobo** [comment]
@thedoubl3j @fosterseth 
Just to inform, I've rebased this with the latest `feature_hop-node` branch.

**Comment by fosterseth** [comment]
cherry picked commit into the main hop node branch https://github.com/ansible/awx/pull/13904/commits
thank you!

**Pull request closed without merging**
