### PR TITLE
added OIDC tab to auth settings

### PR DESCRIPTION
**Pull request by emargolin**
##### SUMMARY
Added an OpenID Connect button in the Settings > Authorization section.

Screen Shot 2020-07-08 at 12 45 00 PM

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Hey @emargolin,

Did you mean to open this?

It looks like it has some private hostnames/usernames in it.

**Comment by emargolin** [comment]
Hi Ryan,

Yes! I meant to make a pull request with some changes onto my branch, but
didn't mean to keep the private hostnames. Should I make any changes?

Thanks,
Elena

**Review by emargolin — COMMENTED** [review]
Took out private hostnames.

**Comment by wenottingham** [comment]
Hi -

Outside of any accidental changes to the inventory file, this isn't something we'd ever accept like this. We're not going to add UI code for features that aren't actually in AWX; this would need to be pared with a backend implementation.

**Comment by ryanpetrello** [comment]
Hey @emargolin,

What @wenottingham said.  This JavaScript code looks like a step in the right direction _if there were_ an official backend generic OIDC implementation to match - but that's the part that's missing for us to consider merging something like this.  @wenottingham, @matburt and I spoke with Suresh Kumar earlier today - before anything like this could land in AWX in an _official_ supported capacity, it would require support in the underlying Python libraries (namely `python-social-auth`) that AWX relies on.

This pull request doesn't look wrong as a necessary step in the direction of official support, but it's also probably premature.

**Pull request closed without merging**
