### PR TITLE
Issue #11284: restore missing null default for limit of workflow job …

### PR DESCRIPTION
**Pull request by johnmillertech**
…template.

See: https://github.com/ansible/awx/issues/11284

### CODE REVIEW

**Comment by nixocio** [comment]
@johnmillertech , thank you for your PR. 

There was a unit-test failing due to some warnings related to `TextInput` on the `WorkflowJobTemplateForm`. Basically with initial value set to `null` the value of the `TextInput` was set to null and that  was raising the error. 

```  bash
console.error
    Warning: `value` prop on `input` should not be null. Consider using an empty string to clear the component or `undefined` for uncontrolled components.
        at input
```

I worked in another solution.  See patch below, I manually tested, and unit-tests are passing with this patch. Please, let me know if this patch works for you. If that is a solution, please, update your PR.

This patch basically modifies the value of limit to `null` if is an empty string when adding or editing that form. Display as empty string - but sends to the API as `null`.

@keithjgrant any suggestions here?



```patch

diff --git a/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.js b/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.js
index c8a11308dd..7d96fda714 100644
--- a/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.js
+++ b/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.js
@@ -23,11 +23,13 @@ function WorkflowJobTemplateAdd() {
       organization,
       webhook_credential,
       webhook_key,
+      limit,
       ...templatePayload
     } = values;
     templatePayload.inventory = inventory?.id;
     templatePayload.organization = organization?.id;
     templatePayload.webhook_credential = webhook_credential?.id;
+    templatePayload.limit = limit === '' ? null : limit;
     const organizationId =
       organization?.id || inventory?.summary_fields?.organization.id;
     try {
diff --git a/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.js b/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.js
index 2d2d83f403..a6cb0e1969 100644
--- a/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.js
+++ b/awx/ui/src/screens/Template/WorkflowJobTemplateAdd/WorkflowJobTemplateAdd.test.js
@@ -113,7 +113,7 @@ describe('<WorkflowJobTemplateAdd/>', () => {
       description: '',
       extra_vars: '---',
       inventory: undefined,
-      limit: '',
+      limit: null,
       organization: undefined,
       scm_branch: '',
       webhook_credential: undefined,
diff --git a/awx/ui/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.js b/awx/ui/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.js
index d3ab8fb43f..0815f69685 100644
--- a/awx/ui/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.js
+++ b/awx/ui/src/screens/Template/WorkflowJobTemplateEdit/WorkflowJobTemplateEdit.js
@@ -22,11 +22,13 @@ function WorkflowJobTemplateEdit({ template }) {
       organization,
       webhook_credential,
       webhook_key,
+      limit,
       ...templatePayload
     } = values;
     templatePayload.inventory = inventory?.id || null;
     templatePayload.organization = organization?.id || null;
     templatePayload.webhook_credential = webhook_credential?.id || null;
+    templatePayload.limit = limit === '' ? null : limit;
 
     const formOrgId =
       organization?.id || inventory?.summary_fields?.organization.id || null;


```

**Review by nixocio — CHANGES_REQUESTED** [review]
See: https://github.com/ansible/awx/pull/11477#issuecomment-999837841

**Comment by keithjgrant** [comment]
@nixocio that looks good to me!

**Comment by nixocio** [comment]
Closing this one in favor https://github.com/ansible/awx/pull/11522, since I could not push to the fork that initiate this PR. 
Thanks @johnmillertech

**Pull request closed without merging**
