### PR TITLE
adding iputils

### PR DESCRIPTION
**Pull request by wolfsoldier47**
##### SUMMARY
- Add iputils

##### ISSUE TYPE
- Docs Fix or other nominal change

##### COMPONENT NAME
 - Other

### CODE REVIEW

**Comment by fosterseth** [comment]
@shanemcd what are your thoughts on including `iputils` into the awx image?

**Comment by wolfsoldier47** [comment]
@fosterseth it will be a good idea to have a direct ping and tracepath command available in the development container at least so the user can check the interconnectivity within docker to docker and to the docker host too.

**Comment by djyasin** [comment]
Hello,
Thank you for your contribution. At this time we would prefer not to add iputils into the container. For now, one way of achieving this is to start a sidecar container with these utilities.

Alternatively, we could consider putting iputils in a new image called `awx_debug`. Our GitHub workflows could be updated to build this image alongside the standard AWX image. If you wanted to update this PR to go more in that direction then we would certainly consider the changes there. 

Thank you again for your time!

-AWX Team

**Comment by wolfsoldier47** [comment]
> Hello, Thank you for your contribution. At this time we would prefer not to add iputils into the container. For now, one way of achieving this is to start a sidecar container with these utilities.
> 
> Alternatively, we could consider putting iputils in a new image called `awx_debug`. Our GitHub workflows could be updated to build this image alongside the standard AWX image. If you wanted to update this PR to go more in that direction then we would certainly consider the changes there.
> 
> Thank you again for your time!
> 
> -AWX Team

Allright then you may take it to awx_debug maybe if you feel oright about adding it to the container then surely you may add it.

**Review by dmzoneill — APPROVED** [review]

**Pull request merged**
