### PR TITLE
Remove undefined prop from SelectedList call

### PR DESCRIPTION
**Pull request by nixocio**
Remove undefined prop from `SelectedList` call.

### CODE REVIEW

**Comment by nixocio** [comment]
See: https://github.com/ansible/awx/blob/d2acd157833543182b8a9d8aee8963e0a5c6df8b/awx/ui_next/src/components/SelectedList/SelectedList.jsx#L19

**Review by jakemcdermott — APPROVED** [review]

**Comment by nixocio** [comment]
regate

**Comment by TristanCacqueray** [comment]
recheck

**Comment by TristanCacqueray** [comment]
The post failure was fixed by https://github.com/ansible/zuul-config/pull/92

**Pull request merged**
