### PR TITLE
Show only member users for organization

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY
Currently we display the `access_list` while trying to view the Users for an Organization. This change restricts them to only Member users and shows first name and last name instead of user role.

Before

Screenshot from 2019-04-15 16-57-41

After

image

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 4.0.0
```

### CODE REVIEW

**Comment by AlanCoding** [comment]
I think we would need to get rid of the roles column, and maybe we would need to add user-related columns, like first name and last name

**Comment by ghost** [comment]
A couple questions:

1. Are we on a consensus regarding what type of users we want to list (i.e. just members), and in that case, should we rename the USERS tab to MEMBERS? 

2. What should we display instead of ROLE column?

**Comment by ryanpetrello** [comment]
@wenottingham can you weigh in on this?

**Comment by wenottingham** [comment]
If we were to change the users tab to only show members (which I believe does make some sense) we should probably change the rest of the list from ROLE to firstname/lastname or similar.

**Comment by ryanpetrello** [comment]
@wenottingham how do you feel about the screenshots in the issue description _now_ (@vismay-golwala just pushed a change).

**Comment by wenottingham** [comment]
That could work for me. cc @jlmitch5 as to how this would work with awx-pf and if we would want to adjust there.

**Comment by ryanpetrello** [comment]
@jlmitch5 or @mabashian one of you have time to review this code?

**Review by mabashian — APPROVED** [review]
lgtm

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
