### PR TITLE
[wip] Add max concurrent jobs per container group

### PR DESCRIPTION
**Pull request by kdelee**
See https://github.com/ansible/awx/issues/12288
Tests are passing except one that is encountering more queries than expected.

TODO:
  * add tests
  * investigate additional queries
  * ensure validation is working in serializer so we don't set this on regular instance groups
  * add ui for setting the Max Concurrent Jobs

QUESTIONS:
  * we could probably have this on the model, but hide it in the api/ui for everything but container groups. Consider if we want to do that.

##### SUMMARY

Specifically for container groups, there are 2 pain points. 

* First, if there is control capacity, there is no way to throttle how many jobs get launched into a container group. 
* The second pain point is that it is useless to have 2 or more container groups assigned to a resource, because each container group has no limit on how many jobs we will launch into it, as long as we have control capacity.
 
By introducing a max number of concurrent jobs for a container group, we mitigate both pain points. It will now be possible to put in information so that your first 50 jobs will go to one container group, and the following 50 to a different container group, or simply to wait until there were less than $max_concurrent_jobs running on a container group to launch the next job.

related #12288
##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - API
 - UI

### CODE REVIEW

**Comment by fosterseth** [comment]
my gut instinct on this

1. worried about introducing yet another piece of logic to the task manager system, especially one that overlaps in functionality with another feature we have (capacity)
2. is there any way to leverage our notion of capacity for container groups?
   - maybe make capacity user-defined for CG, and just default to something reasonable
3.  if we don't do 2, what if we just round-robin the task assignment for an IG that consists of > 1 container group? That way both get filled up evenly

I might be missing some vital info here so forgive me if my suggestions make no sense :)

**Comment by kdelee** [comment]
The overlap concern is valid. One thing we could do is like with policy_instance_percentage not being exposed on container groups etc, not expose this on regular instance groups, and not consider this field for any regular instance group, and only look at it for container groups.

The idea of setting max_forks on a container group and tracking how many forks are being used by jobs on a container group is interesting and I think worth further discussion. This feature when used with container groups is pretty cut and dry "only launch X jobs with Y pod spec". This other proposal is more dynamic, where we don't know what max number of jobs launched with Y pod spec will be, it will depend on the task_impact of the jobs.

I don't like the round-robin thing though, because that is only one pain point. The other pain point addressed by this is simply overloading a container group because we have no notion of max capacity of a container group.

**Comment by AlanCoding** [comment]
Yeah, I also just kind of don't get why we would use the number of jobs metric here, as opposed to forks like we do in every other case.

Doing a schema change to add a field to instance groups is unavoidable given the problem, I would just like it to be a little more like a straightforward extension of the current system. It's true that we're using two different logic systems for the 2 types of instance groups, but it's the same model either way. I would advocate that we look at the new field as a _more restrictive_ capacity limit above and beyond what the instance capacity is. So to schedule a job, it needs to be on an instance group _and_ an instance with sufficient spare capacity. Who knows, maybe someone would like to use this for ordinary instance groups?

Say you have a cluster where the database is the limitation, not the hardware. Anyway, you're sharing the hardware with other apps, so the health check measurements aren't really useful to start with. Maybe you want to put a capacity limit on the default instance group, just to keep database usage below a certain value. That's not exactly possible tweaking individual instance capacities. Maybe just expose it for all instance groups and save yourself from writing additional exceptions?

**Comment by kdelee** [comment]
For container groups my thought to go with max jobs was that each job gets a certain amount of CPU/memory requested per pod, doesn't matter how many forks/the task impact of the job. E.g. if you have 100 jobs with forks set to 1, we will attempt to schedule 100 pods if max_forks is set to 100 -- even if your namespace only actually has resources to satisfy the requests of 50 pods.

So its easier to map pod spec --> max # of pods your container group could sustain, and its something the administrator of tower would have more control over vs. the forks on the individual job templates, because the person setting up the container group likely knows how to access the kubernetes/openshift cluster namespace and can know "I can have X number of pods with this set of resource requests in this namespace" and configure it all on the container group. With max_forks its really a guessing game for the person setting up the container group how many forks the jobs assigned to it will consume.

Honestly I think we could actually implement both :smiling_imp: but I think that scares @fosterseth as far as making things complicated

**Comment by kdelee** [comment]
closing in favor of  #13099 ...even if we don't decide to do both, I've added more tests/refactor over there so I'll just work off of that branch

**Pull request closed without merging**
