### PR TITLE
Rename managed_by_tower & other tower references

### PR DESCRIPTION
**Pull request by rooftopcellist**
##### SUMMARY

Renaming Tower to Controller in various places.  

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API
 - UI

### CODE REVIEW

**Review by tiagodread — APPROVED** [review]

**Comment by AlanCoding** [comment]
recheck

**Review by AlanCoding — APPROVED** [review]

**Comment by rooftopcellist** [comment]
It was the concur/controller cred defaults ordering test failure @AlanCoding .  It should be fixed on this CI run.

**Review by rebeccahhh — APPROVED** [review]

**Review by amolgautam25 — APPROVED** [review]

**Comment by rooftopcellist** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by rooftopcellist** [comment]
recheck

**Pull request closed without merging**
