### PR TITLE
Add all github category setting edit forms

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
Issue: #8288
This PR adds the following github category forms:
* Default `/settings/github/default/edit`
* Organization `/settings/github/organization/edit`
* Team `/settings/github/team/edit`
Screen Shot 2020-12-04 at 3 55 47 PM

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Comment by mabashian** [comment]
@unlikelyzero just realizing that we'll need to get this merged in order to finish work on https://github.com/ansible/awx/pull/6106.

**Comment by unlikelyzero** [comment]
@mabashian ok i'll do it first thing tomorrow (cc @marshmalien )

**Comment by unlikelyzero** [comment]
@marshmalien this is ready to go and is covered by https://github.com/ansible/tower-qa/pull/5845

The only ask is that we change the data-cy attributes to data-ouia-id's if possible

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/5845

**Pull request merged**
