### PR TITLE
Fix lookup plugins sanity

### LINKED ISSUE #12674: awx_collection sanity test fail with python3.9
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

attempting to run `ansible-test sanity` on awx_collection failed

### AWX version

awx: 21.4.1.dev61+gd2217bc61d.d20220817

### Select the relevant components

- [ ] UI
- [ ] API
- [ ] Docs
- [X] Collection
- [ ] CLI
- [ ] Other

### Installation method

N/A

### Modifications

no

### Ansible version

_No response_

### Operating system

_No response_

### Web browser

_No response_

### Steps to reproduce

- build and install `awx` collection with `make install_collection`
- cd into `~/.ansible/collections/ansible_collections/awx/awx`
- run `ansible-test sanity -v --color --docker --coverage --python=3.9`
- sanity test fail 

### Expected results

sanity test pass

### Actual results

sanity test fail with 
```
ERROR: The 1 sanity test(s) listed below (out of 32) failed. See error output above for details.
import --python 3.9

ERROR: Found 2 import issue(s) on python 3.9 which need to be resolved:
ERROR: plugins/lookup/schedule_rrule.py:103:0: traceback: NameError: name 'rrule' is not defined
ERROR: plugins/lookup/schedule_rruleset.py:139:0: traceback: AnsibleError: No module named 'pytz'
```

### Additional information

full log
```
➜  awx ansible-test sanity -v --color --docker --coverage --python=3.9
WARNING: Ignoring tests in "test/" in favor of "tests/".
Run command: docker images quay.io/ansible/default-test-container:3.2.2 --format '{{json .}}'
Run command: docker pull quay.io/ansible/default-test-container:3.2.2
3.2.2: Pulling from ansible/default-test-container
f22ccc0b8772: Pull complete
3cf8fb62ba5f: Pull complete
e80c964ece6a: Pull complete
9b09b8205c21: Pull complete
94a33eccd491: Pull complete
879fb3e00b48: Pull complete
a0fc60deec6d: Pull complete
0146914f596b: Pull complete
9861c35d69c7: Pull complete
254f498a83b4: Pull complete
07d99b38b30c: Pull complete
877d947e7190: Pull complete
221a70eb8225: Pull complete
1f03a775bcfe: Pull complete
37c3d6fe9239: Pull complete
d3f2e2cd796c: Pull complete
18023419ec23: Pull complete
bdc09117b685: Pull complete
be718274d1e7: Pull complete
031103dcf998: Pull complete
893b245223d5: Pull complete
4bf1d8500b9d: Pull complete
a1eb9fa897b8: Pull complete
2f7a5dab24fc: Pull complete
083e7c7a2ba4: Pull complete
80df48ea52f6: Pull complete
ec8466ad84d0: Pull complete
b8091cecfc7a: Pull complete
0bf6ed029087: Pull complete
6b97690d348a: Pull complete
6a22c91b2e72: Pull complete
f5b2cdff9e2d: Pull complete
Digest: sha256:02521efb6ca14d6b75f234fd3a66b4b3d273d545912b377baebe7dc1ccefe83a
Status: Downloaded newer image for quay.io/ansible/default-test-container:3.2.2
quay.io/ansible/default-test-container:3.2.2
Scanning collection root: /Users/liuhao/.ansible/collections/ansible_collections
Run command: git ls-files -z --cached --others --exclude-standard
Run command: git ls-files -z --deleted
Run command: git submodule status --recursive
Including collection: aapqa.openstack (32 files)
Including collection: amazon.aws (601 files)
Including collection: awx.awx (169 files)
Including collection: community.aws (1402 files)
Including collection: community.kubernetes (89 files)
Including collection: community.okd (58 files)
Including collection: kubernetes.core (172 files)
Run command: git ls-files -z --cached --others --exclude-standard
Run command: git ls-files -z --deleted
Run command: git submodule status --recursive
Including collection: ocmplus.cm (84 files)
Including collection: playbook.integrity (15 files)
Run command: git ls-files -z --cached --others --exclude-standard
Run command: git ls-files -z --deleted
Run command: git submodule status --recursive
Including collection: stolostron.core (84 files)
Creating a payload archive containing 3446 files...
Created a 4521547 byte payload archive containing 3446 files in 1 seconds.
Assuming Docker is available on localhost.
Run command: docker run --detach --volume /sys/fs/cgroup:/sys/fs/cgroup:ro --privileged=false --security-opt seccomp=unconfined --volume /var/run/docker.sock ...
Run command: docker exec -i 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 /bin/sh
Run command: docker exec -i 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 dd of=/root/test.tgz bs=65536
Run command: docker exec 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 tar oxzf /root/test.tgz -C /root
Run command: docker exec 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/aw ...
WARNING: Ignoring tests in "test/" in favor of "tests/".
Running sanity test 'action-plugin-docs' with Python 3.9
Read 0 sanity test ignore line(s) for Ansible 2.11 from: tests/sanity/ignore-2.11.txt
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check coverage -c /root/ansible/test/lib ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/yamlcheck.py
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/action-plugin-docs.py
Running sanity test 'ansible-doc' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Injecting "/tmp/python-xgxdc5bt-ansible/python" as a execv wrapper for the "/usr/bin/python3.9" interpreter.
Run command: ansible-doc -t inventory awx.awx.controller
Run command: ansible-doc -t inventory --json awx.awx.controller
Run command: ansible-doc -t lookup awx.awx.controller_api awx.awx.schedule_rrule awx.awx.schedule_rruleset
Run command: ansible-doc -t lookup --json awx.awx.controller_api awx.awx.schedule_rrule awx.awx.schedule_rruleset
Run command: ansible-doc -t module awx.awx.ad_hoc_command awx.awx.ad_hoc_command_cancel awx.awx.ad_hoc_command_wait awx.awx.application awx.awx.controller_me ...
Run command: ansible-doc -t module --json awx.awx.ad_hoc_command awx.awx.ad_hoc_command_cancel awx.awx.ad_hoc_command_wait awx.awx.application awx.awx.contro ...
Running sanity test 'changelog' with Python 3.9
No tests applicable.
Running sanity test 'compile' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/compile/compile.py
Running sanity test 'empty-init' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/empty-init.py
Running sanity test 'future-import-boilerplate' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/future-import-boilerplate.py
Running sanity test 'ignores'
Running sanity test 'import' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/virtualenvcheck.py
Run command: /usr/bin/python3.9 -m venv /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39
Created Python 3.9 virtual environment using "venv": /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39/bin/python /root/ansible/test/lib/ansible_test/_data/quiet_pip.py ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39/bin/python /root/ansible/test/lib/ansible_test/_data/quiet_pip.py ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39/bin/python /root/ansible/test/lib/ansible_test/_data/quiet_pip.py ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39/bin/python /root/ansible/test/lib/ansible_test/_data/quiet_pip.py ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39/bin/python /root/ansible/test/lib/ansible_test/_data/quiet_pip.py ...
Run command: importer.py
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/virtualenvcheck.py
Run command: /usr/bin/python3.9 -m venv /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfc ...
Created Python 3.9 virtual environment using "venv": /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8db49f04fa29b
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Detected OpenSSL version 1.1.1 under Python 3.9.
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Collecting cryptography<3.4
  Downloading cryptography-3.3.2-cp36-abi3-manylinux2010_x86_64.whl (2.6 MB)
Collecting cffi!=1.14.4
  Downloading cffi-1.15.1-cp39-cp39-manylinux_2_17_x86_64.manylinux2014_x86_64.whl (441 kB)
Collecting six>=1.4.1
  Downloading six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pycparser
  Downloading pycparser-2.21-py2.py3-none-any.whl (118 kB)
Installing collected packages: pycparser, cffi, six, cryptography
Successfully installed cffi-1.15.1 cryptography-3.3.2 pycparser-2.21 six-1.16.0
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: /root/ansible_collections/awx/awx/tests/output/.tmp/sanity/import/minimal-py39-requirements-8b83ca76b13364be2f9e02cfcf77dd0bd86a1921ca9e121049d8 ...
Run command: importer.py
ERROR: Found 2 import issue(s) on python 3.9 which need to be resolved:
ERROR: plugins/lookup/schedule_rrule.py:103:0: traceback: NameError: name 'rrule' is not defined
ERROR: plugins/lookup/schedule_rruleset.py:139:0: traceback: AnsibleError: No module named 'pytz'
See documentation for help: https://docs.ansible.com/ansible/2.11/dev_guide/testing/sanity/import.html
Running sanity test 'line-endings' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/line-endings.py
Running sanity test 'metaclass-boilerplate' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/metaclass-boilerplate.py
Running sanity test 'no-assert' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-assert.py
Running sanity test 'no-basestring' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-basestring.py
Running sanity test 'no-dict-iteritems' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-dict-iteritems.py
Running sanity test 'no-dict-iterkeys' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-dict-iterkeys.py
Running sanity test 'no-dict-itervalues' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-dict-itervalues.py
Running sanity test 'no-get-exception' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-get-exception.py
Running sanity test 'no-illegal-filenames' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-illegal-filenames.py
Running sanity test 'no-main-display' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-main-display.py
Running sanity test 'no-smart-quotes' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-smart-quotes.py
Running sanity test 'no-unicode-literals' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/no-unicode-literals.py
Running sanity test 'pep8' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 -m pycodestyle --max-line-length 160 --config /dev/null --ignore E402,E741,W503,W504 plugins/doc_fragments/auth.py plugins/do ...
Running sanity test 'pslint'
No tests applicable.
Running sanity test 'pylint' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/collection_detail.py /root/ansible_collections/awx/awx
Checking 33 file(s) in context "collection" with config: /root/ansible/test/lib/ansible_test/_data/sanity/pylint/config/collection.cfg
Run command: /usr/bin/python3.9 -m pylint --jobs 0 --reports n --max-line-length 160 --max-complexity 20 --rcfile /root/ansible/test/lib/ansible_test/_data/s ...
Checking 3 file(s) in context "module_utils" with config: /root/ansible/test/lib/ansible_test/_data/sanity/pylint/config/collection.cfg
Run command: /usr/bin/python3.9 -m pylint --jobs 0 --reports n --max-line-length 160 --max-complexity 20 --rcfile /root/ansible/test/lib/ansible_test/_data/s ...
Checking 41 file(s) in context "modules" with config: /root/ansible/test/lib/ansible_test/_data/sanity/pylint/config/collection.cfg
Run command: /usr/bin/python3.9 -m pylint --jobs 0 --reports n --max-line-length 160 --max-complexity 20 --rcfile /root/ansible/test/lib/ansible_test/_data/s ...
Running sanity test 'replace-urlopen' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/replace-urlopen.py
Running sanity test 'runtime-metadata' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/runtime-metadata.py
Running sanity test 'shebang' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/shebang.py
Running sanity test 'shellcheck'
No tests applicable.
Running sanity test 'symlinks' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/symlinks.py
Running sanity test 'use-argspec-type-path' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/use-argspec-type-path.py
Running sanity test 'use-compat-six' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/code-smell/use-compat-six.py
Running sanity test 'validate-modules' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/collection_detail.py /root/ansible_collections/awx/awx
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/validate-modules/validate-modules --format json --arg-spec plugins/modules/a ...
Running sanity test 'yamllint' with Python 3.9
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py install --disable-pip-version-check -r /root/ansible/test/lib/ansible_ ...
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/quiet_pip.py check --disable-pip-version-check
Run command: /usr/bin/python3.9 /root/ansible/test/lib/ansible_test/_data/sanity/yamllint/yamllinter.py
ERROR: The 1 sanity test(s) listed below (out of 32) failed. See error output above for details.
import --python 3.9
Run command: docker exec 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 tar czf /root/output.tgz --exclude .tmp -C /root/ansible_collection ...
Run command: docker exec -i 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 dd if=/root/output.tgz bs=65536
Run command: tar oxzf /var/folders/tw/5y6lxkh11rv5pfcmjwt1d1fm0000gn/T/ansible-result-firpvt9a.tgz -C /Users/liuhao/.ansible/collections/ansible_collections/ ...
Run command: docker rm -f 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22
ERROR: Command "docker exec 7fee2ef6abe2087d424523b7642ee5270c76c804aa8f99834e1a6ba2193a6c22 /usr/bin/env ANSIBLE_TEST_CONTENT_ROOT=/root/ansible_collections/awx/awx LC_ALL=en_US.UTF-8 /usr/bin/python3.9 /root/ansible/bin/ansible-test sanity -v --coverage --python=3.9 --metadata tests/output/.tmp/metadata-7omv_d5f.json --truncate 162 --redact --color yes --requirements --coverage-label docker-default" returned exit status 1.
```

### PR DESCRIPTION
**Pull request by thedoubl3j**
##### SUMMARY

Fixes #12674 

`NameErrror`
The changes from class to instance variables addressed the issue of the NameError. This change directly stems from how ansible wants to test imports. Why this popped up for python 3.8 later I am not sure of. (kudos to @maxamillion for the help on discovering that). They are moved in both as once the pytz issue was fixed, it was able to continue and find that error in rruleset as well. 

`No module named 'pytz'`
while this:
```
except ImportError as imp_exc:
    raise_from(AnsibleError('{0}'.format(imp_exc)), imp_exc)
```
is technically correct, it will always throw that error in a sanity suite run as the requirements are not installed (pytz being one of them) so I changed it to match the pattern that is recommended in [docs](https://docs.ansible.com/ansible/latest/dev_guide/testing/sanity/import.html#import).

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - Collection

##### AWX VERSION

```
[thedoubl3j@localhost awx]$ make VERSION
awx: 21.5.1.dev434+g3ca14c43bb

```

##### ADDITIONAL INFORMATION

```
before:
ERROR: plugins/lookup/schedule_rrule.py:109:0: traceback: NameError: name 'rrule' is not defined
ERROR: plugins/lookup/schedule_rruleset.py:139:0: traceback: AnsibleError: No module named 'pytz'
```

```
after:
errors resolved
```

### CODE REVIEW

**Comment by thedoubl3j** [comment]
while I was fixing these issues, a new issue popped up around distutils being deprecated. the ignore files included will suppress those failures until we find a replacement. I will open a separate issue to track the progress on that.

**Comment by sean-m-sullivan** [comment]
This doesn't fix the name error, its changing lookup to name, example of the fix
https://github.com/redhat-cop/controller_configuration/pull/434/files#diff-a22bb89c00e700ac603e8c9ba76dea2d1310d5c036ec4da04654c9e41723ba43

I came across this a few days ago.
But it looks fixed due to the ignore file.

Do we want to fix this in the lookup plugins now or later?

**Review by john-westcott-iv — APPROVED** [review]
This is looking good, thanks for the work!

**Review by jbradberry — APPROVED** [review]

**Comment by thedoubl3j** [comment]
ignores in place until #13278 is resolved

**Comment by thedoubl3j** [comment]
merging, all test passed. if there is any fallout, please see @fosterseth

**Pull request merged**
