### PR TITLE
Create hacking environment for awxkit command line like ansible

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY
Ansible has the following `hacking` environment to assist testing for developers. I think it would be nice if we have a similar environment for `awxkit`.

Reference: https://docs.ansible.com/ansible/latest/dev_guide/developing_modules_general.html#environment-setup

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - awxkit

##### AWX VERSION
```
devel
```

##### ADDITIONAL INFORMATION
This `hacking/env-setup` is based on the Ansible hacking environment.

### CODE REVIEW

**Comment by saito-hideki** [comment]
recheck

**Comment by AlanCoding** [comment]
What does this do that simply running `pip install -e awxkit` (from the root of the checkout) not do?

**Comment by saito-hideki** [comment]
@AlanCoding thank you for your advice!
`pip install -e awxkit` worked perfectly! But I thought that using env-setup to change the path without `pip install -e awxkit` will avoid affecting the outside of repository root.

**Review by ryanpetrello — CHANGES_REQUESTED** [review]
I think it would be better to just rely on existing tools in the Python ecosystem for this (like `virtualenv`), and just installing `awxkit` manually as @AlanCoding suggested.

**Comment by saito-hideki** [comment]
Hi @ryanpetrello @AlanCoding 
Thank you for your suggestion. I have understood the best practice to test awxkit.
There is a better way to test awxkit, so I'll close this PR.

**Pull request closed without merging**
