### PR TITLE
record a start time for WorkflowApproval jobs

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/6202

### CODE REVIEW

**Comment by ryanpetrello** [comment]
cc @Ladas

**Comment by ryanpetrello** [comment]
before/after:

image

**Comment by AlanCoding** [comment]
would this have roughly the same value as `created`?

**Comment by ryanpetrello** [comment]
@AlanCoding probably, yes.  The problem is that `elapsed` is based on `finished - started`.

**Comment by ryanpetrello** [comment]
@AlanCoding I could change it to:

```diff
diff --git a/awx/main/models/workflow.py b/awx/main/models/workflow.py
index a3aaf8e6e2..d7bf84fd0a 100644
--- a/awx/main/models/workflow.py
+++ b/awx/main/models/workflow.py
@@ -751,7 +751,7 @@ class WorkflowApproval(UnifiedJob, JobNotificationMixin):
     def signal_start(self, **kwargs):
         can_start = super(WorkflowApproval, self).signal_start(**kwargs)
         self.send_approval_notification('running')
-        self.started = now()
+        self.started = self.created
         self.save(update_fields=['started'])
         return can_start
```

...if you'd prefer.  I tested that, and it also works:

image

(PR updated)

**Review by Ladas — APPROVED** [review]
If `created` is close to `started` then this is great :+1: (now() is even better)

Thank you for a speedy fix :-)

**Review by AlanCoding — APPROVED** [review]

**Pull request merged**
