### PR TITLE
Add feature to add instance group

### PR DESCRIPTION
**Pull request by nixocio**
Add feature to add instance group.

See: https://github.com/ansible/awx/issues/7744

image

### CODE REVIEW

**Review by jlmitch5 — APPROVED** [review]
Code looks good! just check with Taufique/Tvo on the help text language if it is different from the old ui and you haven't already

**Comment by nixocio** [comment]
Thanks for your review @jlmitch5, text updated per feedback provided by Taufique/Tvo.

**Review by dsesami — APPROVED** [review]

**Comment by nixocio** [comment]
regate

**Comment by nixocio** [comment]
regate

**Comment by nixocio** [comment]
recheck

**Comment by dsesami** [comment]
regate

**Comment by dsesami** [comment]
recheck

**Comment by nixocio** [comment]
recheck

**Comment by nixocio** [comment]
regate

**Comment by nixocio** [comment]
regate

**Pull request merged**
