### PR TITLE
Update Patternfly to allow access to slider component

### PR DESCRIPTION
**Pull request by nixocio**
Update Patternfly to allow access to slider component

See: https://github.com/ansible/awx/issues/7777

### CODE REVIEW

**Comment by nixocio** [comment]
Running e2e tests.

**Review by jakemcdermott — APPROVED** [review]
If E2E and visuals are happy, I am happy.

**Comment by unlikelyzero** [comment]
After meeting with @nixocio , the only issue we found was that the YAML/JSON toggles were too large
Screen Shot 2021-02-10 at 9 01 40 AM

**Comment by unlikelyzero** [comment]
@nixocio were you able to fix the visual bug?
Screen Shot 2021-02-13 at 11 54 53 AM

**Comment by nixocio** [comment]
> @nixocio were you able to fix the visual bug?
> Screen Shot 2021-02-13 at 11 54 53 AM

I think so, I will verify the last visual test run. 

Verified with @unlikelyzero, failure was fixed.

**Pull request merged**
