### PR TITLE
only override django for FIPS in environments where Django is installed

### PR DESCRIPTION
**Pull request by ryanpetrello**
isolated awx installs don't have this tooling, and so they don't need this specific monkey-patch

### CODE REVIEW

**Comment by ryanpetrello** [comment]
image

**Review by Spredzy — APPROVED** [review]
Thanks @ryanpetrello for the quick fix !

**Review by rooftopcellist — APPROVED** [review]
good catch! this lgtm.

**Comment by Spredzy** [comment]
regate

**Pull request merged**
