### PR TITLE
Add dependencies to documentation to build NPM packages

### PR DESCRIPTION
**Pull request by rthill**
Replace git:// links with https:// links for people who can't access Github repositories using SSH protocol

### CODE REVIEW

**Comment by shanemcd** [comment]
@gconsidine @jlmitch5 This PR updates `npm-shrinkwrap.json`. Can you take a look?

**Comment by gconsidine** [comment]
This one ties into this issue as well: https://github.com/ansible/awx/issues/55

Thanks for the work on this one @rthill but I think the more sustainable approach here is updating `package.json` (since `npm-shrinkwrap.json` is a generated file and will get clobbered any time a dependency changes).

This syntax is supported for git dependencies in `package.json`: `git+https://isaacs@github.com/npm/npm.git`, which should resolve the issue here and in #55 

npm documentation: https://docs.npmjs.com/files/package.json

**Comment by gconsidine** [comment]
Take a look at #68 for the `package.json`-based fix. @rthill if you're able to verify it fixes your issue, that'd be fantastic.

**Comment by shanemcd** [comment]
Thanks for this, but I'm going to close this PR in favor of #49 and #104.

**Pull request closed without merging**
