### PR TITLE
Host/Inventory vars popout (code mirror)

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
"Additional variables" fields for hosts and inventories can now be expanded into a modal with a larger input area, for better readability/editability. I also added the same behavior to the host facts. related #3209 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### ADDITIONAL INFORMATION

@mabashian and I enhanced the `<at-code-mirror>` directive—it is no longer read-only. If the user clicks "expand" to open the field in a larger view, this modal view is kept in sync with the initial view. I also updated the form generator to support a "code_mirror" type input, which renders an `<at-code-mirror>`.

Affected views:

* Inventory details
* Host details
* Host facts
* Inventory: related host details
* Inventory: related host facts
* Job details (read only)

### CODE REVIEW

**Comment by keithjgrant** [comment]
This also sets things up to do the work for #3437

**Review by kialam — CHANGES_REQUESTED** [review]
Clicking outside the modal will also close it. This seems to have unexpected consequences. I'm not sure what the expected UX is if a user edits the contents of a modal and clicks outside of the modal body instead of the CLOSE or "X" button. Do we save the edited data?

host_vars

**Comment by keithjgrant** [comment]
@kialam good catch on the modal. that should be fixed now

**Review by kialam — APPROVED** [review]

**Comment by kialam** [comment]
Code looks good and manually verified that the various ways of closing the code mirror modal works as expected. Nice job!

**Pull request merged**
