### PR TITLE
Use favicon for dev and prod builds

### PR DESCRIPTION
**Pull request by jakemcdermott**

### CODE REVIEW

**Comment by jakemcdermott** [comment]
recheck

**Review by mabashian — APPROVED** [review]

**Comment by tiagodread** [comment]
@akus062381 Look at `<base_url>/favicon.ico`, run dev and prod builds

**Comment by akus062381** [comment]
I spoke with @jakemcdermott and we established that, although this is working on prod/dev builds, opening a YOLO instance directly still shows the Ansible A as the icon instead of the red hat icon. putting back into needs _devel

**Comment by jakemcdermott** [comment]
@akus062381 The issue should be resolved now. I sent some additional details your way. I believe this PR is ready for another look when you have a moment, thanks!

**Review by akus062381 — APPROVED** [review]
looks great! thanks :-)

**Pull request merged**
