### PR TITLE
Support file upload/drag and drop on credential mutliline fields

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #6113 
link #6703 

Here's upload in action:

upload

And here's the drag and drop:

dragndrop

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]

**Review by jlmitch5 — APPROVED** [review]
very nice!

**Comment by nixocio** [comment]
That is neat feature.

**Comment by unlikelyzero** [comment]
@mabashian @jlmitch5 this is our first case of os native uploading in cypress. We expect this to take a full week in terms of turnaround but it will help establish some best practices for os interaction.

**Comment by dsesami** [comment]
Is it possible to create a preventative hard limit on filesize upload? For example, if I paste the wrong file into the RSA private key field, I can successfully freeze up the UI (something like 50MB isn't recoverable and you have to kill the page and come back). It would be nice if it simply shut down the upload if it was too large before the upload itself finished.

**Comment by unlikelyzero** [comment]
@mabashian we're able to use the drag and drop field but cannot use this button upload element. Can you sync with us to go over our options?

**Comment by mabashian** [comment]
@dsesami yes we can implement a max file size.  Here's the library that the PF component is using under the hood: https://react-dropzone.js.org/#!/Dropzone

**Comment by unlikelyzero** [comment]
@mabashian Filed as https://github.com/ansible/awx/issues/8082 . As soon as we sort out the file upload problems with our test framework, this can be merged

**Comment by mabashian** [comment]
Decided to file an enhancement for the file upload size limit: https://github.com/ansible/awx/issues/8083

**Comment by unlikelyzero** [comment]
@mabashian can we get IDs added to the Save and Cancel buttons?
Screen Shot 2020-09-04 at 10 22 16 AM

**Comment by unlikelyzero** [comment]
verified via 5484

**Pull request merged**
