### PR TITLE
Adds sync button to project details page

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
Addresses #8847

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

##### ADDITIONAL INFORMATION
Screen Shot 2021-01-05 at 9 51 30 AM

### CODE REVIEW

**Review by nixocio — APPROVED** [review]
Those changes address the mentioned issue.

**Comment by nixocio** [comment]
One thing that I noticed reviewing this PR is that the user triggers an action, but it does not get any feedback about that action. Perhaps, we can file another issue to either redirect the user to the main list where we show the progress of the sync or another solution to display to the user progress of the sync.

**Comment by unlikelyzero** [comment]
@AlexSCorey I think we should add something like @nixocio is suggesting. My first thought while using this was to check the console log because I thought that it hadn't completed the operation. If that's necessary in a follow up ticket (subscribing to the websocket event), then we can just file the RFE, too.

We could also show the sync history in some way, to make it clearer that the action was performed

Would it be possible to get a unique id on this element as well?

**Comment by trahman73** [comment]
I think a toast message would fit nicely here to show the user the sync action is completed.
image
image

**Comment by unlikelyzero** [comment]
@AlexSCorey hey, I'm seeing two api requests being sent on the click event. Is it possible to reduce it to a single POST instead of the GET can_update: true -> POST ?

**Comment by unlikelyzero** [comment]
covered by https://github.com/ansible/tower-qa/pull/5832

**Pull request merged**
