### PR TITLE
Updates to a given inventory should happen serially

### PR DESCRIPTION
**Pull request by jladdjr**
We need to ensure inventory updates for the same inventory happen serially.

Basic sanity test shows syncs happening serially. Need to follow-up with more tests to make sure there aren't any side-effects.

Note: Thought this might address https://github.com/ansible/awx/issues/5571, but I'm still seeing that issue w/ this fix.

### CODE REVIEW

**Comment by AlanCoding** [comment]
I think we should develop some means of testing, but I agree this should fix some issues.

**Review by AlanCoding — APPROVED** [review]
Confirmed that this fixes issue, not the issue you intended, but a bug nonetheless

**Comment by jladdjr** [comment]
rebased, going to run this through some tests to make sure this still looks good

**Comment by jladdjr** [comment]
The tests I ran for this are just about wrapped up. So far, I haven't seen anything come up that suggests this would introduce any regressions.

**Comment by jladdjr** [comment]
Tests finished. Again, I'm not seeing any signs of a regression. 

Think this is good-to-go. cc @ryanpetrello @AlanCoding

**Pull request merged**
