### PR TITLE
Add minor update to strings

### PR DESCRIPTION
**Pull request by nixocio**
Add minor update to strings. And adjust the usage of `toTitleCase` to
dynamic strings.

### CODE REVIEW

**Review by AlexSCorey — APPROVED** [review]
LGTM

**Comment by mabashian** [comment]
@unlikelyzero @tiagodread This seems like something we could just yolok and merge

**Comment by unlikelyzero** [comment]
@mabashian yes unfortunately with the way our tests work, minor changes to text have huge impact on our tests and locators. This will require pairing with a QE to update all the changes

**Comment by nixocio** [comment]
In this particular case I just removed the usage of the `toTitleCase` for non dynamic strings, the string displayed on the screen is the same as before.

**Comment by unlikelyzero** [comment]
@nixocio if the tests are green, 🚢

**Comment by nixocio** [comment]
I ran e2e tests, and those changes did not add a regression.

**Pull request merged**
