### PR TITLE
Upgrade pip and setuptools

### PR DESCRIPTION
**Pull request by AlanCoding**
connect https://github.com/ansible/awx/issues/3968

### CODE REVIEW

**Review by Spredzy — APPROVED** [review]
LGTM

**Comment by AlanCoding** [comment]
Previous friction we hit on this: https://github.com/ansible/awx/pull/3702

Ping @ryanpetrello and @shanemcd because we expect some difficulty from this.

**Comment by ryanpetrello** [comment]
@AlanCoding is there anything scary lurking here, or are you just waiting to see if any test failures fall out of this applied to a nightly?

**Comment by AlanCoding** [comment]
regate

**Pull request merged**
