### PR TITLE
chore: adjust some fr translations

### PR DESCRIPTION
**Pull request by lerminou**
##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
19.3.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by Spredzy — APPROVED** [review]
French content is correct. LGTM.

Merci pour la contrib et les corrections.

**Comment by tiagodread** [comment]
@lerminou thanks for fixing this, could you rebase this PR in order to get it merged?

**Comment by lerminou** [comment]
@tiagodread  I rebased the PR

**Comment by AlexSCorey** [comment]
not a priority.

**Comment by fosterseth** [comment]
@mabashian can we safely close this one? my understanding is that translations will be handled from the translation team

**Comment by dmzoneill** [comment]
closing

**Pull request closed without merging**
