### PR TITLE
Implements AWS SNS notification support for webhook

### LINKED ISSUE #15183: Add support for AWS SNS(Simple Notification Service) notifications
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Feature type

New Feature

### Feature Summary

Simple Notification Service is an AWS service that offers a messaging solution within AWS. Several resources can subscribe to topics and receive published messages and it is a commonly used service to integrate with other AWS services.
AWX already has extensive support for different notification types, such as Slack and Pagerduty. It might be a nice addition to add support for AWS SNS.

### Select the relevant components

- [X] UI
- [X] API
- [X] Docs
- [X] Collection
- [X] CLI
- [ ] Other

### Steps to reproduce

It must be possible to:

- Create a new notification template with the type `AWS SNS`
- with required SNS Topic ARN, AWS Region fields
- enter optional Access Key ID, Access Key Secret, Session Token field
- When notification with this field is sent, a SNS message must be published.

### Current results

Currently it is not possible to create notification templates with AWS SNS type. 

### Sugested feature result

A notification with this type must:
- must use optional Access Key ID, Access Key Secret, Session Token fields to authenticate or default to AWS SDK default chain 
- be published to the defined SNS topic
- SNS event message field must contain a json body with job/workflow details,(existing Webhook data structure looks ideal)

### Additional information

_No response_

### PR DESCRIPTION
**Pull request by ethemcemozkan**
##### SUMMARY
closes https://github.com/ansible/awx/issues/15183.

Support for AWS SNS notifications. SNS is a widespread service that is used to integrate with other AWS services(EG lambdas).  This support would unlock use cases like triggering lambda functions, especially when AWX is deployed on EKS. 

**Decisions:**

1. Data Structure
I preferred using the same structure as Webhook for message body data because it contains all job details. For now, I directly linked to Webhook to avoid duplication, but I am open to suggestions.
2. AWS authentication
To support non-AWS native environments, I added configuration options for AWS secret key, ID, and session tokens. When entered, these values are supplied to the underlining boto3 SNS client. If not entered, it falls back to the default authentication chain to support the native AWS environment.  Properly configured EKS pods are created with temporary credentials that the default authentication chain can pick automatically.

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - API
 - UI

##### AWX VERSION

```
awx: 0.1.dev33966+g94be22a
```

##### ADDITIONAL INFORMATION

Implementation for https://github.com/ansible/awx/issues/15183.

```

```

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
Wow @ethemcemozkan amazing PR! thanks for the contribution

**Comment by TheRealHaoLiu** [comment]
CI failure due to recent ansible 2.17 release and podman 5 release. Rebasing the PR to pick up CI fixes

**Comment by ethemcemozkan** [comment]
@TheRealHaoLiu Thanks for yourquick reply, let me know if you have additions or fixes I have to make for builds

**Review by jbradberry — APPROVED** [review]

**Comment by ethemcemozkan** [comment]
@jbradberry and @TheRealHaoLiu thanks for the approvals, I can fix the SNS test case, but if you can help me with the api-schema and the RBAC test failures, that would be great.

**Comment by TheRealHaoLiu** [comment]
push a commit up to fix UI lint error  lets see if anything else fails

**Comment by TheRealHaoLiu** [comment]
api-schema failure is expected since this PR does introduce a new notification type and it won't block the PR

**Comment by TheRealHaoLiu** [comment]
btw before we merge this PR (once the CI runs green) can you squash the PR and provide a good commit message? it will make it prettier in our git history. Thanks~

**Comment by TheRealHaoLiu** [comment]
cool the RBAC failure went away its just the failure in `awx/main/tests/unit/notifications/test_awssns.py` now

**Comment by ethemcemozkan** [comment]
@TheRealHaoLiu yeap my upstream merge took care of that, the latest commit should also take care of my test case issue. Could you approve latest CI jobs?

**Comment by TheRealHaoLiu** [comment]
Fantastic, thanks @ethemcemozkan, I enabled auto-merge once the CI pass it should be merged. Again thank you for this awesome feature contribution!

**Comment by TheRealHaoLiu** [comment]
If you would like to share a short video demo of this feature we would be honored to inclue it on our YouTube channel and in our next AWX community meeting

**Comment by TheRealHaoLiu** [comment]
Push up an additional commit to fix liniting failure

**Comment by ethemcemozkan** [comment]
@TheRealHaoLiu thanks for merging it. I would like to create a short video but can you send an example for me?

**Comment by TheRealHaoLiu** [comment]
@ethemcemozkan check out our community YouTube channel on https://www.youtube.com/@ansible-awx

**Pull request merged**
