### PR TITLE
Add an initial check and gate job configuration for zuul

### PR DESCRIPTION
**Pull request by matburt**
Depends-On: https://github.com/ansible/zuul-jobs/pull/20

### CODE REVIEW

**Comment by ryanpetrello** [comment]
happy-tears

**Comment by matburt** [comment]
recheck

**Comment by Spredzy** [comment]
@matburt Tox failing because its using python 3 rather than python 2

```bash
spredzy@bordeaux ~/Projects/github.com/Spredzy/ansible/awx [devel *]
± % python3 -m flake8
./awx/main/tests/functional/api/test_instance_group.py:69:67: F821 undefined name 'xrange'
./awx/main/tests/functional/api/test_instance_group.py:70:89: F821 undefined name 'xrange'
./awx/main/tests/functional/api/test_instance_group.py:76:73: F821 undefined name 'xrange'
./awx/main/tests/functional/api/test_instance_group.py:77:95: F821 undefined name 'xrange'
./awx/main/utils/common.py:389:55: F821 undefined name 'long'

spredzy@bordeaux ~/Projects/github.com/Spredzy/ansible/awx [devel *]
± % python2 -m flake8

spredzy@bordeaux ~/Projects/github.com/Spredzy/ansible/awx [devel *]
± % 
```

**Comment by matburt** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by matburt** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Review by ryanpetrello — APPROVED** [review]

**Review by shanemcd — APPROVED** [review]

**Review by jakemcdermott — APPROVED** [review]

**Comment by matburt** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Comment by Spredzy** [comment]
recheck

**Pull request merged**
