### PR TITLE
cli: make --help work properly for custom commands

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/4559

### CODE REVIEW

**Comment by kdelee** [comment]
WORKS for:
`awx config --help`
`awx login --help`

Still not working for:
 `awx metrics --help`
`awx ping --help`
`awx me --help`

**Comment by ryanpetrello** [comment]
@kdelee try now

**Comment by kdelee** [comment]
Works for me!

User needing help might be mad at this:
```
awx config --help
usage: awx config [-h]

optional arguments:
  -h, --help  show this help message and exit
``` 
but it will leave us open to adding more descriptive text in future.

**Review by kdelee — APPROVED** [review]
Works for me, thanks!

**Comment by ryanpetrello** [comment]
> User needing help might be mad at this:

@kdelee not much we'll be able to do about that beyond e.g., https://github.com/ansible/awx/issues/4575

**Pull request merged**
