### PR TITLE
Apply celery rollback changes to kubernetes configmap

### PR DESCRIPTION
**Pull request by matburt**
related #1424

### CODE REVIEW

**Comment by shanemcd** [comment]
Looks like a few more things need to be copied over here:

- https://github.com/ansible/awx/commit/5918fa5573e3e67cabb28d32c9f1f6c9cb5a5cab#diff-908738d8ec3dd38385d70d4f642ac06d
- https://github.com/ansible/awx/commit/148baf76749afac309ad4ae38871b4220de19928#diff-908738d8ec3dd38385d70d4f642ac06d
- https://github.com/ansible/awx/commit/9436e8ae25904cb81c0848cbea439d3f6ce3554a#diff-908738d8ec3dd38385d70d4f642ac06d

**Comment by matburt** [comment]
We really need to have this role unified

**Review by shanemcd — APPROVED** [review]

**Comment by Cryptophobia** [comment]
Can we get a new docker image after this fix? Latest is broken.

**Comment by shanemcd** [comment]
@Cryptophobia What is broken? These changes might require a redeploy, but these files arent in the images themselves.

**Comment by matburt** [comment]
As @shanemcd the only fixes needed were in the installer... so pulling new code should be all that's necessary.

**Comment by Cryptophobia** [comment]
I am still getting Internal Server Errors even after adding fixes on the configmaps and the deployment object.

**Pull request merged**
