### PR TITLE
fix a bug that prevents deletion of workflow approval records

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/8305

### CODE REVIEW

**Comment by ryanpetrello** [comment]
```wx_1       | 2020-10-01 19:17:11,140 ERROR    django.request Internal Server Error: /api/v2/workflow_approvals/3/
awx_1       | Traceback (most recent call last):
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/exception.py", line 34, in inner
awx_1       |     response = get_response(request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 115, in _get_response
awx_1       |     response = self.process_exception_by_middleware(e, request)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/core/handlers/base.py", line 113, in _get_response
awx_1       |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1       |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1       |     return func(*args, **kwds)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/decorators/csrf.py", line 54, in wrapped_view
awx_1       |     return view_func(*args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/django/views/generic/base.py", line 71, in view
awx_1       |     return self.dispatch(request, *args, **kwargs)
awx_1       |   File "./awx/api/generics.py", line 328, in dispatch
awx_1       |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 505, in dispatch
awx_1       |     response = self.handle_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 465, in handle_exception
awx_1       |     self.raise_uncaught_exception(exc)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 476, in raise_uncaught_exception
awx_1       |     raise exc
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/views.py", line 502, in dispatch
awx_1       |     response = handler(request, *args, **kwargs)
awx_1       |   File "/venv/awx/lib/python3.6/site-packages/rest_framework/generics.py", line 217, in delete
awx_1       |     return self.destroy(request, *args, **kwargs)
awx_1       |   File "./awx/api/views/mixin.py", line 52, in destroy
awx_1       |     elif not obj.event_processing_finished:
awx_1       |   File "./awx/main/models/unified_jobs.py", line 1004, in event_processing_finished
awx_1       |     event_qs = self.get_event_queryset()
awx_1       |   File "./awx/main/models/unified_jobs.py", line 994, in get_event_queryset
awx_1       |     return self.event_class.objects.filter(**{self.event_parent_key: self.id})
awx_1       | AttributeError: 'NoneType' object has no attribute 'objects'
awx_1       | 172.18.0.1 DELETE /api/v2/workflow_approvals/3/ - HTTP/1.1 500```

**Review by mabashian — APPROVED** [review]
🎉

**Comment by ryanpetrello** [comment]
recheck

**Review by beeankha — APPROVED** [review]

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Pull request merged**
