### PR TITLE
Prefer installer defaults over user-defined global EEs

### PR DESCRIPTION
**Pull request by AlanCoding**
The installer knows better than the user

### CODE REVIEW

**Review by jbradberry — APPROVED** [review]
I wonder if we should use the name field instead, but sure.

**Comment by AlanCoding** [comment]
You know, we should also add `organization=None, managed_by_tower=False` to this filter.

**Review by beeankha — APPROVED** [review]

**Review by kdelee — APPROVED** [review]
This is good...we can't know that it is still around, but if it is, we prefer it

**Comment by AlanCoding** [comment]
As kind of a followup to this, I filed https://github.com/ansible/awx/issues/10442. That's not something for the near-term, but as we manage multiple versions in future releases this will become more important.

ping @wenottingham

**Comment by AlanCoding** [comment]
saw that a release was in progress https://github.com/ansible/awx/pull/10441

**Pull request merged**
