### PR TITLE
awx/ui: minor fix on Update on Project Update description

### PR DESCRIPTION
**Pull request by falcon78921**
##### SUMMARY

In the Inventory Source settings, one of the update options is titled
`Update on Project Change`. However, the tooltip is titled
`Update on Project Update`. Looking at the overall AWX codebase, I think
the definitions are fitted more towards `Update on Project Update`.

Here's an example:

~~~
                    name: 'update_on_project_update',
                    label: i18n._('Update on Project Update'),
                    type: 'checkbox',
                    ngShow: "source.value === 'scm'",
                    awPopOver: "<p>" + i18n._("After every project update where the SCM revision changes, " +
                                "refresh the inventory from the selected source before executing job tasks. " +
                                "This is intended for static content, like the Ansible inventory .ini file format.") + "</p>",
                    dataTitle: i18n._('Update on Project Update'),
                    dataContainer: 'body',
                    dataPlacement: 'right',
                    ngDisabled: '!(inventory_source_obj.summary_fields.user_capabilities.edit || canAdd)'
                }]
            },
~~~

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 6.0.0
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by jakemcdermott** [comment]
`Update on Project Update` is worded a little awkwardly. Personally I think `Update on Project Change` is slightly better in this regard.

> Looking at the overall AWX codebase, I think the definitions are fitted more towards

I do see what you mean here. That said, the purpose of these descriptions _isn't_ to strictly align with the conventions used by developers in the source code - they exist to be helpful to people using awx. Can you please explain how this change will result in descriptions that are more helpful or less confusing to end users?

**Review by jakemcdermott — CHANGES_REQUESTED** [review]
This doesn't really improve the helpfulness of the descriptions from my POV. I'm thinking we probably  want to close this but I'd like to wait and see if @falcon78921 can provide some more details / context.

**Comment by jakemcdermott** [comment]
@falcon78921 Actually, I think I see the value to this rewording. `Update on Project Update` is slightly less ambiguous than `Update on Project Change` - that's because project _change_ might be interpreted as _any_ change (like its fields). This makes sense to me :+1:

**Review by jakemcdermott — COMMENTED** [review]
https://github.com/ansible/awx/pull/4283#issuecomment-509299957

**Review by jakemcdermott — APPROVED** [review]

**Comment by falcon78921** [comment]
@jakemcdermott Thanks! :)

**Pull request merged**
