### PR TITLE
Fix misalignment checkbox final build

### PR DESCRIPTION
**Pull request by nixocio**
Fix misalignment checkbox final build on Organization Lookup.

See: https://github.com/ansible/awx/issues/9433

### CODE REVIEW

**Comment by nixocio** [comment]
~Currently running visual tests.~

**Comment by tiagodread** [comment]
We need to add a visual test to cover this component

**Review by AlexSCorey — APPROVED** [review]
Well done!

**Comment by jakemcdermott** [comment]
If there's a difference between the in-memory dev server builds and the production bundle, it is a concern. We'll want to figure out the underlying cause.

**Comment by jakemcdermott** [comment]
it may be a local caching issue, or we may need to regenerate a `package-lock.json` file

**Review by tiagodread — APPROVED** [review]
We noticed that we have a test that covers the Organization modal on inventories.

**Comment by nixocio** [comment]
> If there's a difference between the in-memory dev server builds and the production bundle, it is a concern. We'll want to figure out the underlying cause.

I agree. Let's find out the root of problem, before we merge this PR.

**Review by jakemcdermott — CHANGES_REQUESTED** [review]
https://github.com/ansible/awx/pull/9435#issuecomment-789165897

**Comment by jakemcdermott** [comment]
Note: The discrepancy between devel and prod builds should be addressed by: https://github.com/ansible/awx/pull/9649

Once that's ready, tested, and merged I believe this PR will be ready for another look.

**Comment by akus062381** [comment]
We have coverage for this. Once up to date, this can be merged. Test already exists.

**Comment by jakemcdermott** [comment]
:sparkles: https://github.com/ansible/awx/pull/9649

**Comment by mabashian** [comment]
@nixocio mind rebasing this one?  @jakemcdermott have the changes here addressed your concerns?

**Review by jakemcdermott — APPROVED** [review]

**Comment by mabashian** [comment]
@tiagodread once this conflict gets resolved are we good to merge this one or did you want to take another look?

**Comment by nixocio** [comment]
PR rebased.

**Comment by tiagodread** [comment]
@nixocio Looks like there is no space between the radio component and the text?

image

**Comment by nixocio** [comment]
Updated @tiagodread.

Build

image

Dev server

image

**Review by tiagodread — APPROVED** [review]

**Pull request merged**
