### PR TITLE
Add support of update_on_project_update in inventory_source

### PR DESCRIPTION
**Pull request by Sispheor**
##### SUMMARY
The flag `update_on_project_update  `was missing from `inventory_source `module.

Api ref: https://docs.ansible.com/ansible-tower/latest/html/towerapi/api_ref.html#/Inventories/Inventories_inventories_inventory_sources_create

##### ISSUE TYPE
New or Enhanced Feature

##### COMPONENT NAME
 - Collection

### CODE REVIEW

**Comment by Sispheor** [comment]
Pr updated.

- PR body updated
- Flag added to the E2E test

**Review by sean-m-sullivan — APPROVED** [review]
This matches the API, LGTM

**Review by john-westcott-iv — APPROVED** [review]

**Review by john-westcott-iv — CHANGES_REQUESTED** [review]
Update on project update was actually removed from the API in https://github.com/ansible/awx/commit/052223389239392b32877a9798b5056a0048e049

**Comment by john-westcott-iv** [comment]
Thank you so much for your contribution, it really means a lot to us. After further investigation, it looks like `update_on_project_update` was a field in the modules for quite some time but was recently removed in June of this year from the API and also the collection. At this time we don't want to add the parameter back in because the version of the collection should match the version of the API it was released with. Please let us know if you have a different opinion about this. If not, we will close this PR.

**Comment by Sispheor** [comment]
Indeed it has been removed... And so this PR is not needed.
The new behavior based only on "update_no_launch" is not very good but I guess that we'll have to live with it.

Thanks for your time anyway guys. I close this one.

**Pull request closed without merging**
