### PR TITLE
add inventory name and id to meta vars

### LINKED ISSUE #4269: Ability to add AWX Inventory name as a variable in playbook
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

Per a customer's request, they would like to query the name of the Inventory utilized as a variable and use that variable in a playbook.

~~~
---
- name: Test connectivity
  hosts: all

  tasks:
    - name: Run hostname command
      command: hostname
    - name: Run Inventory Name
      command: echo {{ inventory_name }}
~~~

### PR DESCRIPTION
**Pull request by jainnikhil30**
##### SUMMARY

Fixes #4269 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]
Seems pretty reasonable, @AlanCoding what do you think?

**Comment by AlanCoding** [comment]
I do have a _little_ bit of hesitation about the location of this code, since it's in the `UnifiedJob` model. It's very non-obvious, but the properties like `created_by` and schedule are all properties of the base model. Inventory is actually a property of the derived `Job` model instead, so for cases like system jobs, there is no inventory field. So we should confirm that things like system jobs and ad hoc commands work fine with this patch. Alternatively, we could move this code to the `Job` and/or `AdHocCommand` class (although I see how this makes the argument for it being a base model parameter in the first place).

But it'll probably work as-is, I'm just going to run more tests.

Also, this needs a docs marker for after it merges.

**Comment by jainnikhil30** [comment]
@AlanCoding 

Thanks for taking look at this.

I did launch a few ad-hoc commands and system jobs with this change and they seems to have worked fine.

I will create a separate docs issues for this, once this gets merged.

**Review by AlanCoding — APPROVED** [review]

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
