### PR TITLE
Updated ovirt4 dynamic inventory script.

### PR DESCRIPTION
**Pull request by rmkraus**
##### SUMMARY
Pulling in the new ovirt4 dynamic inventory script that will be pulled in ansible/ansible#57824

This fixes a bug with the current implementation of ovirt4 that causes the inventory sync to fail if a VM exists in RHV/OVirt that is powered off. 

##### ISSUE TYPE
- Bugfix

##### COMPONENT NAME
- Dynamic Inventory
- ovirt4

##### AWX VERSION
```
awx: 4.0.0
```

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Hey @rmkraus,

Looks like https://github.com/ansible/ansible/pull/57824 is merged.  Let me know if/when this PR is ready for review and I'll take a peek.

**Comment by ryanpetrello** [comment]
Confirmed that the diff matches when I pull `ovirt4.py` from ansible's `HEAD` commit.

**Review by ryanpetrello — APPROVED** [review]

**Comment by rmkraus** [comment]
@ryanpetrello - Everything should be good to go on my end.

**Comment by ryanpetrello** [comment]
Thanks for the legwork on this, @rmkraus.

I'm going to merge it shortly.

**Comment by rmkraus** [comment]
👍

**Comment by ryanpetrello** [comment]
related: https://github.com/ansible/awx/issues/4138

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
