### PR TITLE
Expand and Collapse Jobs List

### PR DESCRIPTION
**Pull request by kialam**
##### SUMMARY

Link #2984
This PR adds a list toolbar component that allows the user to expand or collapse the Jobs list.
expand_collapse

The new list toolbar contains the following attributes that you can pass it:

- `isCollapsed`: flag used to set active class on selected view. Boolean.
- `sortOnly`: flag used to either show or hide the `EXPANDED` and `COMPACT` buttons if a list view is sort-only. Boolean.
- `onExpand`: method to handle when the EXPANDED button is clicked.
- `onCollapse`: method to handle with the COMPACT button is clicked.

Incidentally, the My View page also now displays this new Jobs list correctly:
screen shot 2019-01-23 at 1 33 07 pm

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
awx: 3.0.0
```

### CODE REVIEW

**Comment by mabashian** [comment]
We probably want to hide this toolbar if there are no items in the list initially:

screen shot 2019-01-23 at 2 28 24 pm

not sure what to do when the user searches:
screen shot 2019-01-23 at 2 31 19 pm

ping @trahman73

**Comment by mabashian** [comment]
Other than ^^ this looks good to me

**Comment by trahman73** [comment]
@mabashian Yes, agree we should hide the toolbar if no resources exist. We should also hide the toolbar if the search filter has zero results. All other cases, the toolbar should be visible. Also want to add that the default state should be COMPACT if it already isn't.

**Review by mabashian — APPROVED** [review]

**Comment by ryanpetrello** [comment]
regate

**Pull request merged**
