### PR TITLE
Filling job_explanation field if an exception occurred during the job execution

### PR DESCRIPTION
**Pull request by x0r3ax3ax**
##### SUMMARY

The job_explanation field is filled if an exception occurred during the job execution

#10364 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - API

##### AWX VERSION

```
19.2.2
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by AlanCoding** [comment]
The outer context already has exception handling

https://github.com/ansible/awx/blob/9af9e9a4e4b05531ff076733a79883630ba46db3/awx/main/tasks.py#L1422-L1427

I don't want this block to be re-implemented for the receptor job class. The `result_traceback` is also the most appropriate place for the data to go. If you thought that `job_explanation` should also be filled in for traceback cases (from `str(e)`), we could manage that.

It doesn't look like this would help with issues like https://github.com/ansible/awx/issues/10213 either.

**Comment by x0r3ax3ax** [comment]
> The outer context already has exception handling
> 
> https://github.com/ansible/awx/blob/9af9e9a4e4b05531ff076733a79883630ba46db3/awx/main/tasks.py#L1422-L1427
> 
> I don't want this block to be re-implemented for the receptor job class. The `result_traceback` is also the most appropriate place for the data to go. If you thought that `job_explanation` should also be filled in for traceback cases (from `str(e)`), we could manage that.
> 
> It doesn't look like this would help with issues like #10213 either.

Hi!
Yes you are right. The current solution is bad. I will move the filling of job_explanation to the part you provided.

As for issue #10213, I was unable to reproduce that problem. In my case i get a traceback like this
```python
Traceback (most recent call last):
  File "/awx_devel/awx/main/tasks.py", line 1406, in run
    res = receptor_job.run()
  File "/awx_devel/awx/main/tasks.py", line 2936, in run
    return self._run_internal(receptor_ctl)
  File "/awx_devel/awx/main/tasks.py", line 3005, in _run_internal
    raise RuntimeError(detail)
RuntimeError: Stream error running pod: context canceled
```
Please, could you send me an ansible-playbook with the task you are running on the mail specified in my profile?

**Comment by AlanCoding** [comment]
I'll leave a note that I need to re-test that issue, thanks for the info.

**Comment by AlanCoding** [comment]
With the recent push, I don't think it would expose any new information, and the UI will get mixed up about which to show between the two fields.

**Pull request closed without merging**
