### PR TITLE
add organization column notification template list

### PR DESCRIPTION
**Pull request by erezo9**
##### SUMMARY
Adding the option to view organization from the notification template list

##### ISSUE TYPE
- New or Enhanced Feature

##### COMPONENT NAME
 - UI

##### AWX VERSION
22.2.1.dev19+ge434b1e.d20230515

##### ADDITIONAL INFORMATION
Before change
image

After Change
image

### CODE REVIEW

**Comment by fosterseth** [comment]
@tvo318 if merged, would have docs impact

**Comment by fosterseth** [comment]
@mabashian thoughts on this change?

**Review by mabashian — APPROVED** [review]
lgtm

**Comment by erezo9** [comment]
@fosterseth anything i need to do to make this pr merged after the approval?

**Comment by fosterseth** [comment]
we need the CI to pass

you may need to rebase on devel

**Comment by erezo9** [comment]
@fosterseth I have updated my branch, needs approval to run again

**Comment by erezo9** [comment]
@fosterseth should i add organization to the NotificationTemplateListItem.test.js?
also i dont really understand why to ui lint is failing

**Comment by erezo9** [comment]
@fosterseth should be good with the test, I ran prettier and fixed the ui test and checked it locally - if approved the checks will run again

**Comment by erezo9** [comment]
@fosterseth @mabashian can you re approve this so the ci will run again please?

**Comment by erezo9** [comment]
@fosterseth @mabashian this needs to be approved again and set to auto-merge 
the pipeline succeded but i needed to merge devel again to my branch for it to be merged

**Comment by erezo9** [comment]
@mabashian can this be merged now?

**Pull request merged**
