### PR TITLE
Add support for installing AWX from official images

### PR DESCRIPTION
**Pull request by matburt**
* New options in the inventory file
* Add defaults to some variables

### CODE REVIEW

**Comment by chouseknecht** [comment]
@matburt

So far LGTM. I deployed the official images using local docker and remote docker. No problems to report.

My only comment is that we probably need to mention the new variables, `dockerhub_base` and `dockerhub_version`, in the INSTALL doc. We should explain what they do, and explain that unsetting `docker_base` is the way to trigger a local image build.

At the meetup last night, there were a couple people interested in performing a custom build. One person in particular was interested in using a different Linux distro, so pointing out that a local build is possible, and the Dockerfiles are there, if you want them, is probably a useful thing.

**Comment by matburt** [comment]
Yep absolutely... definitely need to have some information in the install docs

**Comment by chrismeyersfsu** [comment]
Docker path works for me 👍

**Comment by chrismeyersfsu** [comment]
minishift ran into a timeout on the first try.

image

Scaled the pods down to 0 and then back up to 1, that worked.

**Review by chrismeyersfsu — APPROVED** [review]

**Pull request merged**
