### PR TITLE
Add extra step to confirm edition of login redirect URL

### LINKED ISSUE #10613: Add modal to confirm update of LOGIN_REDIRECT_OVERRIDE on the settings
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Add modal to confirm update of LOGIN_REDIRECT_OVERRIDE on the settings.

image

Giving the user a change to confirm that updated URL is sane.

Similar UX was used here: https://github.com/ansible/awx/pull/10102/commits/3b5641c41b44198ee459f3bd5c4353aa59735a9d

### PR DESCRIPTION
**Pull request by nixocio**
Add extra step to allow edition of login redirect URL

image

image

image

closes: https://github.com/ansible/awx/issues/10613

### CODE REVIEW

**Comment by tiagodread** [comment]
@nixocio could you rebase this one?

**Comment by AlexSCorey** [comment]
Looks like when the modal is open the text field behind it, where the user just clicked disappears.  I would expect that field to not disappear when the modal is open.
redirect

**Comment by nixocio** [comment]
> Looks like when the modal is open the text field behind it, where the user just clicked disappears. I would expect that field to not disappear when the modal is open.
> redirect

@AlexSCorey good find. Updated.

image

**Review by jakemcdermott — APPROVED** [review]

**Comment by akus062381** [comment]
This branch needs a rebase before I am able to test. I pinged @nixocio

**Review by akus062381 — APPROVED** [review]

**Pull request merged**
