### PR TITLE
Added relnotes for 23.0.0

### PR DESCRIPTION
**Pull request by tvo318**
##### SUMMARY
Adds release notes for 23.0.0 based on https://github.com/ansible/awx/releases/tag/23.0.0

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - Docs
 
##### AWX VERSION

```
23.0.0
```

### CODE REVIEW

**Comment by tvo318** [comment]
@oraNod - please, can you review this also? Thanks!

**Review by oraNod — APPROVED** [review]
LGTM. Thanks @tvo318

**Comment by AlanCoding** [comment]
Certainly no issues from me, but this appears to be a new process, and I want to make sure we make things as easy as possible for the future.

Shouldn't this be the same as what's shown here?

https://github.com/ansible/awx/releases/tag/23.0.0

We annotate tags (in the AWX release process) with a lightly sanitized history of commit messages. This is why we have tried to push for better summaries in PR titles (which will be the message after squashing). So I just want to ask if there's something here that should be hooked into that release process.

**Comment by tvo318** [comment]
@AlanCoding - The relnotes are the same as what you linked, but not verbatim. In addition to grammar, spelling, wordsmithing, etc., I've clarified some of them so they are more descriptive what the change was for so readers don't have to cross check in the PR itself to find out.
Having said that, we could either have one of the following processes:
- Have better PR summaries before auto-gen of the relnotes and not rewrite them (developers only)
- Not auto-generate the relnotes and have it done during this process instead (writer only)
- Cleanup PR summaries before auto-gen and not have official release notes (writer only)
- Have both - raw auto-gen list and official relnotes - the way we did it here (writer only)

**Review by AlanCoding — APPROVED** [review]

**Pull request merged**
