### PR TITLE
Switch default job panel to output

### PR DESCRIPTION
**Pull request by jakemcdermott**
##### SUMMARY
https://github.com/ansible/awx/issues/4973

### CODE REVIEW

**Review by marshmalien — APPROVED** [review]

**Comment by mabashian** [comment]
@jakemcdermott - can we change https://github.com/ansible/awx/blob/devel/awx/ui_next/src/components/LaunchButton/LaunchButton.jsx#L98 as well?

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
rs

**Pull request merged**
