### PR TITLE
[4362] git version is old and does not work with x509 certificates

### LINKED ISSUE #4362: git version is old and does not work with x509 certificates
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
If we need to use the git options sslCert, sslKey and sslCAInfo with git 1.8 and centos7 we get:

NSS: client certificate not found (nickname not specified)

##### ENVIRONMENT
* AWX version: 6.1.0
* AWX install method: docker
* Ansible version:  2.8.2
* Operating System: centos7
* Web Browser: Chrome

##### STEPS TO REPRODUCE

 1- docker run ansible/awx_task:latest  bash
 2- setup gitconfig to use sslCert (so that x509 handshake is needed)
 3- export GIT_CURL_VERBOSE=1
 4 - git clone <git server that needs x509 tls certificate as handshake>
##### EXPECTED RESULTS

git clone works

##### ACTUAL RESULTS

NSS: client certificate not found (nickname not specified)
Cloning into 'repo'...
* About to connect() to someServer port 443 (#0)
*   Trying someServer
* Connected to someServer (xxxxx) port 443 (#0)
* Initializing NSS with certpath: sql:/etc/pki/nssdb
*   CAfile: /etc/pki/tls/certs/ca-bundle.crt
  CApath: none
* NSS: client certificate not found (nickname not specified)
* NSS error -12227 (SSL_ERROR_HANDSHAKE_FAILURE_ALERT)
* SSL peer was unable to negotiate an acceptable set of security parameters.
* Closing connection 0

##### ADDITIONAL INFORMATION

Upgrade from git version fixes the problem

### PR DESCRIPTION
**Pull request by jomach**
* upgrade from git on containers

##### SUMMARY
Fixes #4362 
Upgrade of the git version

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

##### AWX VERSION
```
awx: 6.1.0
```

### CODE REVIEW

**Comment by jomach** [comment]
can we merge this?

**Review by shanemcd — CHANGES_REQUESTED** [review]
Hi @jomach - thanks for the PR. I think I am fine with the proposed change (we will need to run it through downstream testing) but I have one piece of feedback in terms of formatting / organization. In the Dockerfiles you have modified, please move `https://centos7.iuscommunity.org/ius-release.rpm` up to the same place where we install `epel-release` ie:

```
yum install epel-release https://centos7.iuscommunity.org/ius-release.rpm
```

Then move `git2u git2u-core` into the alphabetized list of dependencies. Once this happens I'll merge this in. Thank you!

**Comment by jomach** [comment]
@shanemcd I think I addressed the issues that you mentioned. Once you merge it when does the new image gets to docker hub ?

**Comment by jomach** [comment]
@shanemcd  I don't know why this got a timeout. Can you help?

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
@jomach do you mind rebasing this into a single commit so we don't pollute the commit history?

**Comment by jomach** [comment]
@ryanpetrello done.

**Comment by ryanpetrello** [comment]
@shanemcd you happy with this?

**Review by ryanpetrello — APPROVED** [review]

**Review by shanemcd — APPROVED** [review]

**Comment by jomach** [comment]
@ryanpetrello  @shanemcd  when is a new release planned ? I would like to use my fix...

**Comment by jomach** [comment]
when do we release a new version ? I need this fix :)

**Comment by ryanpetrello** [comment]
Hey @jomach,

We just released a new version of AWX (7.0.0) yesterday with this fix.

**Pull request merged**
