### PR TITLE
Create single source of truth for outgoing Docs link URLs

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Adds a utility function to generate links to the correct version of documentation and updates/adds a number of docs links throughout the app.

Addresses #8428 

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
lgtm!

@keithjgrant When you get a moment, would you please rebase this pr w/ latest devel?

**Comment by unlikelyzero** [comment]
@keithjgrant Missing the 'Help' on the top header/navbar

Responsive advancedsearch layout
Screen Shot 2021-04-05 at 10 19 39 PM

Workflow Viz - Workflow Node
Screen Shot 2021-04-05 at 10 21 22 PM

**Comment by keithjgrant** [comment]
I've updated all links to ansible tower docs to point to the relevant version. There are a few links to ansible core docs which I left hard-coded to point to the latest version of docs, since we don't know from the config which version is relevant

**Comment by unlikelyzero** [comment]
Added some post-merge tests to the issue. Just need a unit test or two methinks https://github.com/ansible/awx/issues/8428#issuecomment-814319367

**Pull request merged**
