### PR TITLE
Added some Doc for FREEipa

### PR DESCRIPTION
**Pull request by Numblesix**
##### SUMMARY
Added docs for FREEipa Users
 

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME
 - UI

##### AWX VERSION

```
'2.0.1'
```

##### ADDITIONAL INFORMATION
Basically this pr is a summary/copy of the information shared in issue #876

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
@Numblesix if you'll rebase this change with `devel`, I'll approve and merge it.  Thanks!

**Comment by shanemcd** [comment]
regate

**Comment by ryanpetrello** [comment]
regate

**Comment by Spredzy** [comment]
regate

**Pull request merged**
