### PR TITLE
Use variables to set rabbitmq host and port

### PR DESCRIPTION
**Pull request by kumy**

### CODE REVIEW

**Review by shanemcd — APPROVED** [review]

**Comment by ryanpetrello** [comment]
@kumy do you mind rebasing and updating this PR?

**Comment by kumy** [comment]
@ryanpetrello will try tomorrow

**Comment by kumy** [comment]
@ryanpetrello do you mind merging this PR? I don't wish to rebase it every months ;)

**Comment by ryanpetrello** [comment]
Apologies @kumy,

This is a fairly fast-moving bit of our codebase and the timing keeps causing conflicts.  I'll give this another shot at a merge now.

**Pull request merged**
