### PR TITLE
[WIP] Add bindep.txt file for zuul jobs

### PR DESCRIPTION
**Pull request by pabelanger**
##### SUMMARY
Manage OS level dependencies using bindep for zuul.ansible.com

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - testing

##### AWX VERSION
n/a

##### ADDITIONAL INFORMATION

### CODE REVIEW

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now df81923058d4c44cb319a81952b38d527c195801

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now 23388967b778c3c65dd45f2957c209aae9882de2

**Comment by pabelanger** [comment]
Looks like we cannot merge this until we migrate from sf.io, this is because they are using containers, which don't allow sudo permissions.  This is okay for now, since we can do cross-project testing

**Comment by pabelanger** [comment]
Pull-request updated, HEAD is now db212220e982cda1fc1e87ed4a0320ebc2b4ab5d

**Comment by TristanCacqueray** [comment]
Note that these jobs are not using softwarefactory-project.io containers, they are running on the static host provided by the AWX team.

**Pull request closed without merging**
