### PR TITLE
WIP: remove schedule-related computed fields on UnifiedJobTemplate

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/3912
context: https://github.com/ansible/awx/issues/3912#issuecomment-493474475

### CODE REVIEW

**Comment by wenottingham** [comment]
If this changes the filterable nature of these fields, it may be worth a relnote.

**Comment by AlanCoding** [comment]
Right now I'm still getting

```python
awx_1        |   File "./awx/main/models/unified_jobs.py", line 243, in next_schedule
awx_1        |     return Schedule.objects.filter(enabled=True, unified_job_template=self, next_run__isnull=False).order_by('-next_run').first()
awx_1        | NameError: name 'Schedule' is not defined
```

**Comment by AlanCoding** [comment]
I added the migration and now get

```python
awx_1        | Traceback (most recent call last):
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/core/handlers/exception.py", line 41, in inner
awx_1        |     response = get_response(request)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
awx_1        |     response = self.process_exception_by_middleware(e, request)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
awx_1        |     response = wrapped_callback(request, *callback_args, **callback_kwargs)
awx_1        |   File "/usr/lib64/python3.6/contextlib.py", line 52, in inner
awx_1        |     return func(*args, **kwds)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/views/decorators/csrf.py", line 58, in wrapped_view
awx_1        |     return view_func(*args, **kwargs)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/django/views/generic/base.py", line 68, in view
awx_1        |     return self.dispatch(request, *args, **kwargs)
awx_1        |   File "./awx/api/generics.py", line 334, in dispatch
awx_1        |     return super(APIView, self).dispatch(request, *args, **kwargs)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 494, in dispatch
awx_1        |     response = self.handle_exception(exc)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 454, in handle_exception
awx_1        |     self.raise_uncaught_exception(exc)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 491, in dispatch
awx_1        |     response = handler(request, *args, **kwargs)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/views.py", line 505, in options
awx_1        |     data = self.metadata_class().determine_metadata(request, self)
awx_1        |   File "./awx/api/metadata.py", line 198, in determine_metadata
awx_1        |     metadata = super(Metadata, self).determine_metadata(request, view)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/metadata.py", line 65, in determine_metadata
awx_1        |     metadata['description'] = view.get_view_description()
awx_1        |   File "./awx/api/generics.py", line 273, in get_view_description
awx_1        |     return func(self.__class__, getattr(self, '_request', None), html)
awx_1        |   File "./awx/api/generics.py", line 146, in get_view_description
awx_1        |     desc = cls().get_description(request, html=html)
awx_1        |   File "./awx/api/generics.py", line 289, in get_description
awx_1        |     context = self.get_description_context()
awx_1        |   File "./awx/api/generics.py", line 419, in get_description_context
awx_1        |     d = super(ListAPIView, self).get_description_context()
awx_1        |   File "./awx/api/generics.py", line 397, in get_description_context
awx_1        |     d[key] = self.metadata_class().get_serializer_info(serializer, method=method)
awx_1        |   File "./awx/api/metadata.py", line 132, in get_serializer_info
awx_1        |     super(Metadata, self).get_serializer_info(serializer),
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/metadata.py", line 112, in get_serializer_info
awx_1        |     for field_name, field in serializer.fields.items()
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/serializers.py", line 363, in fields
awx_1        |     for key, value in self.get_fields().items():
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/serializers.py", line 997, in get_fields
awx_1        |     field_names = self.get_field_names(declared_fields, info)
awx_1        |   File "/venv/awx/lib64/python3.6/site-packages/rest_framework/serializers.py", line 1098, in get_field_names
awx_1        |     serializer_class=self.__class__.__name__
awx_1        | AssertionError: The field 'next_job_run' was declared on serializer UnifiedJobTemplateSerializer, but has not been included in the 'fields' option.
```

this is on an OPTIONS request

**Comment by ryanpetrello** [comment]
I want to think about this some more before we decide to remove it.  Maybe we can make it faster.

**Comment by AlanCoding** [comment]
An option we can talk about is to make the JT save less expensive. If you're seeing a 100x performance improvement gain with this change (as mentioned in your comment in the issue), then either something _really_ bad is happening in signals, or I just don't understand what's happening.

Some optimizations which are available:

https://github.com/ansible/awx/pull/3883/files#diff-840aee1d09c364211891211e2a4cef7eR482

https://github.com/ansible/awx/compare/devel...AlanCoding:rbac_signal_optimization?expand=1
(this one may still need some additional rigor)

There are plenty more which are very easy to find, once the steps to reproduce the slowdown are produced.

**Comment by AlanCoding** [comment]
I inspected this computation by inserting it into a view and using the Django debug toolbar:

```diff
diff --git a/awx/main/models/schedules.py b/awx/main/models/schedules.py
index d78b78cb41..ce98b122b6 100644
--- a/awx/main/models/schedules.py
+++ b/awx/main/models/schedules.py
@@ -228,6 +228,7 @@ class Schedule(PrimordialModel, LaunchTimeConfig):
         return job_kwargs
 
     def update_computed_fields(self):
+        changed = False
         future_rs = Schedule.rrulestr(self.rrule)
         next_run_actual = future_rs.after(now())
 
@@ -237,7 +238,10 @@ class Schedule(PrimordialModel, LaunchTimeConfig):
                 next_run_actual = future_rs.after(next_run_actual)
             next_run_actual = next_run_actual.astimezone(pytz.utc)
 
+        if self.next_run != next_run_actual:
+            changed = True
         self.next_run = next_run_actual
+        old_dtstart, old_dtend = (self.dtstart, self.dtend)
         try:
             self.dtstart = future_rs[0].astimezone(pytz.utc)
         except IndexError:
@@ -248,9 +252,13 @@ class Schedule(PrimordialModel, LaunchTimeConfig):
                 self.dtend = future_rs[-1].astimezone(pytz.utc)
             except IndexError:
                 self.dtend = None
+        if self.dtstart != old_dtstart or self.dtend != old_dtend:
+            changed = True
         emit_channel_notification('schedules-changed', dict(id=self.id, group_name='schedules'))
-        with ignore_inventory_computed_fields():
-            self.unified_job_template.update_computed_fields()
+        if changed and self.enabled:
+            with ignore_inventory_computed_fields():
+                self.unified_job_template.update_computed_fields()
+        return changed
 
     def save(self, *args, **kwargs):
         self.update_computed_fields()
diff --git a/awx/main/models/unified_jobs.py b/awx/main/models/unified_jobs.py
index ed63cb6dde..44fcf485cb 100644
--- a/awx/main/models/unified_jobs.py
+++ b/awx/main/models/unified_jobs.py
@@ -254,9 +254,10 @@ class UnifiedJobTemplate(PolymorphicModel, CommonModelNameNotUnique, Notificatio
     def update_computed_fields(self):
         Schedule = self._meta.get_field('schedules').related_model
         related_schedules = Schedule.objects.filter(enabled=True, unified_job_template=self, next_run__isnull=False).order_by('-next_run')
-        if related_schedules.exists():
-            self.next_schedule = related_schedules[0]
-            self.next_job_run = related_schedules[0].next_run
+        next_sch = related_schedules.first()
+        if next_sch and (self.next_schedule_id != next_sch.pk or self.next_job_run != next_sch.next_run):
+            self.next_schedule = next_sch
+            self.next_job_run = next_sch.next_run
             self.save(update_fields=['next_schedule', 'next_job_run'])
 
     def save(self, *args, **kwargs):
diff --git a/awx/main/tasks.py b/awx/main/tasks.py
index d0caa8d527..5920842eb0 100644
--- a/awx/main/tasks.py
+++ b/awx/main/tasks.py
@@ -104,12 +104,13 @@ class InvalidVirtualenvError(Exception):
 def dispatch_startup():
     startup_logger = logging.getLogger('awx.main.tasks')
     startup_logger.info("Syncing Schedules")
+    from awx.main.signals import disable_activity_stream
     for sch in Schedule.objects.all():
         try:
-            sch.update_computed_fields()
-            from awx.main.signals import disable_activity_stream
-            with disable_activity_stream():
-                sch.save()
+            changed = sch.update_computed_fields()
+            if changed:
+                with disable_activity_stream():
+                    sch.save()
         except Exception:
             logger.exception("Failed to rebuild schedule {}.".format(sch))
```

Is the general direction I would favor. This gets it down from about 6 SELECTs and 2 UPDATEs per schedule to 1 SELECT and 0-1 UPDATEs per schedule.

The fact that we update `next_run` to _disabled_ schedules isn't a performance problem, that's a _bug_. It just also happens to create a major performance problem.

**Comment by ryanpetrello** [comment]
@AlanCoding I like this diff - will you turn it into a new PR?

**Comment by AlanCoding** [comment]
Yes, I'll do that, but I'm also going to investigate some test cases:

 - not updating next_run for disabled schedules
 - (speculative) check if the computed fields updates modified time, and assert some sane behaviors in the test/functional/models/test_schedules.py file, probably

I'm still fidgeting around with some stuff with the debug toolbar, but I'll get there soon enough.

**Pull request closed without merging**
