### PR TITLE
Add SAML and UI setting edit forms

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
Issues: https://github.com/ansible/awx/issues/8295 https://github.com/ansible/awx/issues/8297

This PR adds the SAML and UI setting edit forms

Screen Shot 2020-12-04 at 2 18 15 PM
Screen Shot 2020-12-04 at 2 17 10 PM

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@marshmalien we noticed that the SAML Service Provider Public Certificate field might need some restructuring. In the current form it looks like this when used with a cert
image (5)

**Comment by unlikelyzero** [comment]
@rooftopcellist from the bug bash comments: is this more in line with what you'd like to see in the settings details layout?

**Review by jakemcdermott — APPROVED** [review]

**Comment by therealmacjeezy** [comment]
Any idea on when this pull request will be rolled into the next release?

**Comment by zachrd** [comment]
Hello, is there any update as to the status of the PR.

**Comment by zachrd** [comment]
> 
> 
> Any idea on when this pull request will be rolled into the next release?

I am also inquiring as to the status of this PR.

**Comment by ryanpetrello** [comment]
@zachrd,

The status of this PR is that it’s open and unmerged 😄.

This PR will be part of an awx release shortly after it’s reviewed, tested, and merged.  Sometimes that takes a little while.  If you’d like, follow the issue (in the sidebar) and you’ll get a notification when it merges.

**Comment by unlikelyzero** [comment]
@one-t note: https://github.com/ansible/tower/issues/4696

**Comment by one-t** [comment]
This looks good, we have a PR up for some additional tests, and that will be merged tomorrow most likely.

**Comment by one-t** [comment]
regate

**Pull request merged**
