### PR TITLE
[docs] Update OpenShift doc section to clarify #3116

### PR DESCRIPTION
**Pull request by kimausloos**
Signed-off-by: Kim Ausloos <kim.ausloos@cegeka.be>

##### SUMMARY
I've updated the install documentation because there is no mention of the requirement mentioned in #3116. If this text would have been present, it would have saved me some time...

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION
None

##### ADDITIONAL INFORMATION
None

### CODE REVIEW

**Comment by ryanpetrello** [comment]
@matburt how do you feel about this?

**Review by ryanpetrello — APPROVED** [review]

**Comment by matburt** [comment]
I actually agree with mentioning this, but we should make it a seperate bullet point in that section and justify why this is needed... otherwise it looks bad on us.

The reason this is needed is due to the privilege seperation protection that we get from bubblewrap, and bubblerwrap requiring the chroot privilege.

**Comment by kimausloos** [comment]
@matburt To be honest I'm not sure why this would make the project look badly, I just see it as a requirement of the setup. If the tone is suggesting so, please tell because that's not what I was trying to achieve.

Anyhow, I'll update the PR and mention it's a requirement for bubblewrap.

**Review by matburt — APPROVED** [review]

**Comment by matburt** [comment]
recheck

**Comment by kimausloos** [comment]
I noticed merge failed, so I did a rebase and pushed everything. I didn't notice sooner, sorry.

**Comment by matburt** [comment]
regate

**Pull request merged**
