### PR TITLE
Remove limit on `limit` field.

### PR DESCRIPTION
**Pull request by wenottingham**
This allows 'relaunch-on-failed' on an arbitrary number of failed hosts.

### CODE REVIEW

**Comment by wenottingham** [comment]
For https://github.com/ansible/awx/issues/2144.

Obligatory:

the limit does not exist

**Comment by ryanpetrello** [comment]
Before:

```
                 Table "public.main_jobtemplate"
          Column           |          Type           | Modifiers
---------------------------+-------------------------+-----------
 unifiedjobtemplate_ptr_id | integer                 | not null
 job_type                  | character varying(64)   | not null
 playbook                  | character varying(1024) | not null
 forks                     | integer                 | not null
 limit                     | character varying(1024) | not null

                 Table "public.main_job"
       Column       |          Type           | Modifiers
--------------------+-------------------------+-----------
 unifiedjob_ptr_id  | integer                 | not null
 job_type           | character varying(64)   | not null
 playbook           | character varying(1024) | not null
 forks              | integer                 | not null
 limit              | character varying(1024) | not null
```

image

After:

```
                 Table "public.main_jobtemplate"
          Column           |          Type           | Modifiers
---------------------------+-------------------------+-----------
 unifiedjobtemplate_ptr_id | integer                 | not null
 job_type                  | character varying(64)   | not null
 playbook                  | character varying(1024) | not null
 forks                     | integer                 | not null
 limit                     | text                    | not null

                 Table "public.main_job"
       Column       |          Type           | Modifiers
--------------------+-------------------------+-----------
 unifiedjob_ptr_id  | integer                 | not null
 job_type           | character varying(64)   | not null
 playbook           | character varying(1024) | not null
 forks              | integer                 | not null
 limit              | text                    | not null
```

**Comment by ryanpetrello** [comment]
@mabashian @kialam do I recall something on the front end enforcing this old 1024 value?

**Review by ryanpetrello — APPROVED** [review]

**Comment by kialam** [comment]
@ryanpetrello AFAIK there is no client-side form validation for the `limit` field on the Job Templates page: https://github.com/ansible/awx/blob/devel/awx/ui/client/src/templates/job_templates/job-template.form.js#L155-L168

**Comment by krentiken** [comment]
Hi.
I updated AWX to version 3.0.1, however the limit of 1024 characters remained for ad_hoc commands.
Do you plan to remove the restriction?

<picture>
  <source media="(min-width: 650px)" srcset="img_pink_flowers.jpg">
  <source media="(min-width: 465px)" srcset="img_white_flower.jpg">
  Flowers
</picture>

**Comment by chrismeyersfsu** [comment]
image

**Comment by ryanpetrello** [comment]
see: https://github.com/ansible/awx/pull/3225

**Pull request merged**
