### PR TITLE
Use more modern version of OpenShift client

### PR DESCRIPTION
**Pull request by svenstaro**
##### SUMMARY
3.9 is pretty old by now. 3.11 is the current stable version.

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

### CODE REVIEW

**Comment by svenstaro** [comment]
I don't think the build failures are related.

**Comment by shanemcd** [comment]
Hello and thanks for the patch. I will test this out, but may need a few days before I get to it.

**Review by shanemcd — APPROVED** [review]
Thanks for this.

**Comment by shanemcd** [comment]
recheck

**Pull request merged**
