### PR TITLE
Free up persistent db connection in heartbeet service

### PR DESCRIPTION
**Pull request by jessicamack**
##### SUMMARY

related #13952

Use existing db connection instead of creating a new one and close the connection one the message has been sent.

##### ISSUE TYPE

 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME

 - API

##### AWX VERSION

```
awx: 22.1.1
```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by AlanCoding** [comment]
If I check out this branch, I still see an open connection from the heatbeet.

```
bash-5.1$ echo "select pid,application_name, state from pg_stat_activity;" | awx-manage dbshell
 pid |             application_name              | state  
-----+-------------------------------------------+--------
  30 |                                           | 
  32 |                                           | 
  46 | awx-144-heartbeet-awx_1                   | idle
  48 | awx-146-rsyslog_configurer_listener-awx_1 | idle
  49 | awx-146-rsyslog_configurer-awx_1          | idle
  54 | awx-142-wsrelay-awx_1                     | idle
  51 | awx-150-cache_clear_listener-awx_1        | idle
  52 | awx-137-dispatcher_listener-awx_1         | idle
 588 | awx-875-dispatcher_worker-awx_1           | idle
 175 | awx-138-callback_receiver-awx_1           | idle
 597 | awx-260-dispatcher_periodic-awx_1         | idle
 598 | awx-889-dispatcher_worker-awx_1           | idle
 589 | awx-881-dispatcher_worker-awx_1           | idle
 591 | awx-887-dispatcher_worker-awx_1           | idle
 599 | awx-883-dispatcher_worker-awx_1           | idle
 600 | psql                                      | active
  28 |                                           | 
  27 |                                           | 
  29 |                                           | 
(19 rows)
```

You could get rid of this too by `from django.db import connection` and then `connection.close()` in the loop after the message is sent.

**Comment by jessicamack** [comment]
@AlanCoding The service should only be using existing connections now so I'm looking into why it's showing as a dedicated connection still. Would we still want to close the connection if we're using an existing one that should be released afterward?

**Comment by relrod** [comment]
> The service should only be using existing connections now

The service is running independently from everything else, so it has no existing connection to share (it's not running in wsgi or anything). It needs its own connection. The goal is just to not have it hold on to that connection in between messages for no reason.


> Would we still want to close the connection if we're using an existing one that should be released afterward?

I think if you keep `new_connection=True`, it should do what you want. When we exit the context manager, it will automatically close the connection.

**Comment by AlanCoding** [comment]
> The service should only be using existing connections now so I'm looking into why it's showing as a dedicated connection still. Would we still want to close the connection if we're using an existing one that should be released afterward?

As to the question of "should", the setting `BROADCAST_WEBSOCKET_BEACON_FROM_WEB_RATE_SECONDS` makes the period 15 seconds. For a comparison point, look at uWSGI, it frequently closes connections not being used by its workers, which is why we rarely see it in the connection list, I believe.

**Pull request closed without merging**
