### PR TITLE
Installer: increase nginx worker_processes

### PR DESCRIPTION
**Pull request by Exordian**
##### SUMMARY

uwsgi is running with 5 processes. only one nginx worker is a bottleneck and leads to http 502 errors on real setups

##### COMPONENT NAME

 - Installer

### CODE REVIEW

**Comment by matburt** [comment]
I haven't seen this in any real setups... can you explain how much volume you are putting through it and the console errors that lead to the 502?

**Comment by shanemcd** [comment]
Maybe we just make this a template / variable?

**Comment by matburt** [comment]
I think that would be better.

**Review by shanemcd — CHANGES_REQUESTED** [review]
We don't want to make this the default. Please make this a template with a variable that defaults to 1.

**Comment by schue30** [comment]
why are you not using `worker_processes  auto` here?
nginx will scale the worker processes based on the autodetected number of cpu cores.

http://nginx.org/en/docs/ngx_core_module.html#worker_processes

**Comment by shanemcd** [comment]
That might make sense if it is the only thing running on the underlying host. In container-based environments that’s almost never going to be the case. Again, it should be a variable so you can set it to whatever your heart desires.

**Comment by matburt** [comment]
ping @Exordian ... the comments need to be addressed and this branch needs to be re-based.

**Comment by matburt** [comment]
`auto` worker processes could be good here given it attempts to autodetect what would be optimal based on # of cores and disks available.

**Comment by matburt** [comment]
superceded by #1251

**Pull request closed without merging**
