### PR TITLE
WIP: specify --forks on isolated health check calls

### PR DESCRIPTION
**Pull request by ryanpetrello**
this requires ansible-runner 1.3.2

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Please don't merge until this makes it into a stable runner release (likely 1.3.2):

https://github.com/ansible/ansible-runner/pull/241

**Comment by ryanpetrello** [comment]
image

**Comment by ryanpetrello** [comment]
recheck

**Review by AlanCoding — APPROVED** [review]
If this doesn't cause runner to error, I don't see any harm in merging it now

**Comment by ryanpetrello** [comment]
> If this doesn't cause runner to error, I don't see any harm in merging it now

That's why I'm not ready to merge yet, this forks argument doesn't exist in `ansible_runner.interface.run` in 1.3.1 😄

**Pull request merged**
