### PR TITLE
added buildah and podman build support

### PR DESCRIPTION
**Pull request by ghost**
##### SUMMARY

Changed the installer to allow for buildah and podman based builds. Tried to have as little code duplication as possible. To achieve that got rid of the docker module based steps and went towards a variable driven approach (comparable with the oc vs. kubectl things). 

I am allowing to inject extra build parms for the container build because I figured that in some scenarios you want to specify some extra stuff. In my case, I want to specify `--format docker` with the builds because I am testing with k3s and OpenShift 3.11. Both do not understand the OCI manifests. 

related #8969 

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by shanemcd** [comment]
Hello! Thanks for opening this. I'll try to play around with it sometime this week. Can you just take a look at the test failures in the comment above and try to fix those up? https://ansible.softwarefactory-project.io/logs/79/9079/834201620f4f5827b15cb0184866ba82fe88f9a3/check/awx-api-lint/6ccfeae/job-output.txt.gz

```
2021-01-13 22:07:44.053513 | static | linters run-test: commands[1] | yamllint -s .
2021-01-13 22:07:46.569372 | static | ./installer/roles/image_build/defaults/main.yml
2021-01-13 22:07:46.569545 | static |   12:1      error    too many blank lines (1 > 0)  (empty-lines)
2021-01-13 22:07:46.569568 | static |
2021-01-13 22:07:46.569636 | static | ./installer/roles/image_build/tasks/main.yml
2021-01-13 22:07:46.569716 | static |   30:12     error    trailing spaces  (trailing-spaces)
2021-01-13 22:07:46.569795 | static |   32:10     error    trailing spaces  (trailing-spaces)
2021-01-13 22:07:46.569901 | static |   33:7      error    wrong indentation: expected 4 but found 6  (indentation)
2021-01-13 22:07:46.570155 | static |   33:44     error    trailing spaces  (trailing-spaces)
2021-01-13 22:07:46.570297 | static |   34:7      error    wrong indentation: expected 4 but found 6  (indentation)
2021-01-13 22:07:46.570394 | static |   35:7      error    wrong indentation: expected 4 but found 6  (indentation)
2021-01-13 22:07:46.570409 | static |
2021-01-13 22:07:46.570469 | static | ./installer/roles/image_push/tasks/main.yml
2021-01-13 22:07:46.570543 | static |   10:90     error    trailing spaces  (trailing-spaces)
2021-01-13 22:07:46.570635 | static |   11:18     warning  truthy value should be one of [false, true]  (truthy)
```

**Comment by ghost** [comment]
@shanemcd, just out of curiosity. Have you had a chance to test this?

**Comment by ryanpetrello** [comment]
@it-baschtler sorry for the delay on reviewing this PR - we've in the process of replacing the k8s installer in `devel` (https://groups.google.com/g/awx-project/c/47MjWSUQaOc/m/bCjSDn0eBQAJ https://github.com/ansible/awx/tree/devel/tools/docker-compose) and thus the next major release of AWX with an operator (https://github.com/ansible/awx-operator), so I suspect this PR is obsolete now.

**Comment by ghost** [comment]
@ryanpetrello well, it depends. I haven't read up on the links you posted (which I will). And I certainly need to read up some of the details on how operators are developed.

This PR, however, is more about building custom images rather than the actual installation of AWX. But let me explain a bit on what I need to achieve. It's only two things, really: 
1. It needs to run an Air-Gapped Environment
2. It needs to run reliably

For my use cases I need to load collections from galaxy. I am currently doing this at build time of the awx image. That works lovely. This PR gives the chance to run the build with something else than docker, which I can't do because we are running on RHEL which ships a docker version that is not capable of multi stage builds.

I am certainly willing to put in some extra effort to preserve the possibility of building and pushing without docker and fit that into the new installer structure.

**Comment by ghost** [comment]
@ryanpetrello So, I have been looking around in the devel branch, the operator and the links you have posted earlier. What I have learned:

1. The Operator allows to specify my own image source using the `tower_image: myorg/my-custom-awx` configuration
2. The build of the AWX Image is in the playbook `awx/tools/ansible/build.yml` plus there is a role for the dockerfile creation.

If I put my changes into the image_build and image_push roles of devel, would that have a chance to be accepted as a PR?

**Comment by ryanpetrello** [comment]
@it-baschtler,

Thanks for understanding - I know this recent change is a little disruptive for folks with unmerged PRs.

Yep, I think adapting this PR's support (to the relocated roles) for _optionally_ building and pushing images with buildah/podman (instead of Docker) would be reasonable.

**Comment by ghost** [comment]
@ryanpetrello No worries. 
I was able to copy and past pretty much all of the playooks to the new location and tested succesfully on my local system with all 3 build tools. I put it in a way, that if you don't specify another tool everything defaults to docker. I put that into PR #9578. I would suggest to close #9079 and would be hoping that we get #9578 into awx instead ;-)

Oh, btw. I did write a blog post on running awx in an airgapped environment (with the old installer) my plan is to do the same thing for the new installer. I do write that in german. If there is interest, however, I would be OK with translating that to english and to share that.

**Comment by ghost** [comment]
#9578 is taking care of this

**Pull request closed without merging**
