### PR TITLE
Add controller_node to job details page

### PR DESCRIPTION
**Pull request by nixocio**
Add controller_node to job details page. Modify serializers to make
controller_node available to the UI.

See: https://github.com/ansible/awx/issues/11196
Also: https://github.com/ansible/awx/issues/12132

image

### CODE REVIEW

**Comment by AlanCoding** [comment]
Looks like the API test failure just requires updating the test.

**Review by AlanCoding — APPROVED** [review]

**Comment by AlanCoding** [comment]
FYI, your screenshot doesn't seem to show the controller_node.

And the awx-operator failure is obviously github's fault here.

**Comment by nixocio** [comment]
hey @keithjgrant, do you have any more comments?

**Review by AlexSCorey — APPROVED** [review]
Looks good to me

**Pull request merged**
