### PR TITLE
Addresses bug where advanced search by groups wasn't working on host list

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
link #10400 

OK so this got a bit more complicated than I wanted it to but I think on the whole this is a nice improvement.  In the initial bug report it was noted that we were ignoring the `or`/`not` operators when searching on a related key (in this case it was groups).  We were also ignoring the modifier at the end (icontains, exact, startswith, etc).  Since we were always defaulting to `__search` for these types of keys this was actually valid.  The API doesn't like us attempting to do something like `?or__groups__search=foo` or `?groups__search__icontains` because they aren't valid.  So, I changed the UX a little bit.  A user can still do a fuzzy search on a related key but the prefix is disabled in this case:

Screen Shot 2021-06-10 at 2 10 02 PM

I changed the third dropdown (specifically for related keys) to contain the following options: `search`, `id`, `name__icontains` which I think would be the three most general cases.  `id` and `name__icontains` do allow for prefixing (`or`, `not`, `and`).

This should make searching on related keys a little bit easier and a little bit more flexible since name and id weren't possible in the UI before.

Once place where this is a little different is the host filter in the smart inventory form.  Using `__search` currently throws an error when the user attempts to save.  I believe this is an API bug and will file it as such but for now I prevent users from attempting to use `__search` by removing it as an option for this particular list.  When this bug gets fixed in the API we can remove this logic.

I also noticed that there was a bug where `or__` search terms were being converted to `and` when using the Smart Inventory button on the host list so I fixed that.

Here's the fix in action:

host_search

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by mabashian** [comment]
recheck

**Review by nixocio — APPROVED** [review]
💯 This PR looks great.

**Comment by tiagodread** [comment]
Running e2e

**Comment by nixocio** [comment]
> Running e2e

I forgot to mention that I also triggered an e2e test run. @tiagodread

**Review by tiagodread — APPROVED** [review]
Verified that:

- basic search filters works
- advanced search type `and/or/not` works for `default `keys
- advanced search type `and/or/not` works for `related_search_fields` keys when `lookup type` is `name__icontains` or `id`
- type is disabled and tooltip ins displayed if fuzzy search is enabled in `related_search_fields` keys
- smart inv button is disabled and contains help text in tolltip if the fuzzy search is enabled 
- smart inv can be created using or operator in hosts list or in smart inv form

**Pull request merged**
