### PR TITLE
[constructed-inventory] Revert hack to get Ansible core devel

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
This will be needed before merge of constructed inventory.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - API

### CODE REVIEW

**Review by CFSNM — APPROVED** [review]

**Review by TheRealHaoLiu — APPROVED** [review]

**Comment by AlanCoding** [comment]
We can merge once https://github.com/ansible/awx-ee/pull/192#event-8810070955 is in place

**Review by relrod — APPROVED** [review]

**Comment by relrod** [comment]
I'm fine with merging this at any time now, we have new `latest` builds from awx-ee `devel` now.

**Comment by AlanCoding** [comment]
testing this branch, if it works I'll merge in a minute

**Comment by AlanCoding** [comment]
Pulled `quay.io/ansible/awx-ee:latest`, reports being updated 6 hours ago, which is expected to have the fix.

**Comment by AlanCoding** [comment]
testing is looking good

**Pull request merged**
