### PR TITLE
 Add updates related to smart inventories

### PR DESCRIPTION
**Pull request by nixocio**
Add updates related to smart inventories.

* Add popover for `Smart host filter`.
* Rename `Host filter` to `Smart host filter` per mockup.
* Add inventory as part of dynamic host filter.

See: https://github.com/ansible/awx/issues/8581
Also: https://github.com/ansible/awx/issues/8548

image

image

### CODE REVIEW

**Comment by nixocio** [comment]
I also ran e2e for this PR. Currently evaluating failures.

**Comment by tiagodread** [comment]
We are missing popover for `Instance Groups` field and the popover text of `Variables` field is different from old/ui_next.

**Review by tiagodread — APPROVED** [review]

**Comment by nixocio** [comment]
Thanks for your feedback @marshmalien, I will update accordingly.

**Review by marshmalien — APPROVED** [review]
Looks great!

**Comment by unlikelyzero** [comment]
@nixocio this is covered by https://github.com/ansible/tower-qa/pull/5727

**Pull request merged**
