### PR TITLE
Allow lookup modals to refresh when opened.

### PR DESCRIPTION
**Pull request by kialam**
##### SUMMARY

Related #10093 

##### ISSUE TYPE

 - Feature Pull Request
 
##### COMPONENT NAME

 - UI

### CODE REVIEW

**Comment by AlexSCorey** [comment]
This looks good so far.  My only question is, are we still fetching the lookup data when the page loads in addition to when the user clicks to open the look up?

**Comment by kialam** [comment]
Some of them yes because they require the field to be auto populated with the selected org, cred, etc.

**Review by nixocio — APPROVED** [review]
@kialam I like the simplicity of this solution. I got the code locally, and work as expected. Great job.

**Comment by jay-steurer** [comment]
Tested and approved.

**Pull request merged**
