### PR TITLE
Renders Command Module in job detail view and improves Ad Hoc Commands execution permissions

### LINKED ISSUE #10440: Ad hoc command details does not show the module name
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Launch an ad hoc command that runs the ping module. View the details in the UI.

Screenshot from 2021-06-14 10-48-57

At first, I was confused, because I thought I ran the "ping" module, not the "command" or "shell" modules. Then I see that the UI's meaning is that it was an ad hoc _command_.

However, the page gives no indication anywhere that I ran the "ping" module.

It should also probably show the module arguments. If I run a command that does `echo "Hello world"`, then I need to know:

 - that I ran the `command` module
 - the args passed to it (so I know why it printed "Hello world")

Otherwise, there's nothing to connect this job entry with the function of what actually happened.

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This closes #10440 and #8660.

On the job details view we now render the command module name, and the arguments.  We also remove the run command button for user that do not have permission to launch a ad hoc command. 

##### ISSUE TYPE
-enhancement

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by nixocio — APPROVED** [review]

**Comment by nixocio** [comment]
e2e tests triggered.

**Review by akus062381 — APPROVED** [review]

**Comment by tiagodread** [comment]
recheck

**Comment by tiagodread** [comment]
@AlexSCorey could you rebase this one?

**Comment by akus062381** [comment]
verified

**Pull request merged**
