### PR TITLE
[WIP] Replace shallow clone with shutil copy with .git exclusion

### PR DESCRIPTION
**Pull request by AlanCoding**
##### SUMMARY
Experimental idea for some tech debt cleanup / simplification.

##### COMPONENT NAME
 - API

##### AWX VERSION
```
12.0.0
```

### CODE REVIEW

**Comment by ryanpetrello** [comment]
@AlanCoding do we still need this?  I see it referenced in https://github.com/ansible/awx/pull/7643

**Comment by AlanCoding** [comment]
no, it's not a part of that, but the latest idea I was throwing around was to expand this, using the new caching mechanisms, and thus remove the `GitPython` dependency entirely.

**Comment by AlanCoding** [comment]
This has now collected 4 issues, which could probably all be consolidated into a single work item - to update and complete this.

There were significant conflicts introduced with the merge of https://github.com/ansible/awx/pull/7643, but those are generally moving in the same code design pattern. Nonetheless, the conflict is so large I think one would just have to start over and redo this.

**Comment by AlanCoding** [comment]
Closing because this is tracked in an issue now.

**Pull request closed without merging**
