### PR TITLE
Fix issues with prop types that were causing errors to be logged during tests

### PR DESCRIPTION
**Pull request by mabashian**
##### SUMMARY
Noticed several errors being logged while the tests ran that had to do with prop types.  This PR should clean that up.

```
 PASS  src/screens/Template/shared/JobTemplateForm.test.jsx (23.988s)
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: The prop `fieldId` is marked as required in `FieldWithPrompt`, but its value is `undefined`.
          in FieldWithPrompt (created by I18n)
          in I18n (created by WithI18n)
          in WithI18n (at InventoryLookup.jsx:78)
          in InventoryLookup (created by Context.Consumer)
          in withRouter(InventoryLookup) (created by I18n)
          in I18n (created by WithI18n)
          in WithI18n (at JobTemplateForm.jsx:241)
          in div (created by FormGroup)
          in div (created by FormGroup)
          in FormGroup (at JobTemplateForm.jsx:230)
          in div (created by Context.Consumer)
          in StyledComponent (created by styled.div)
          in styled.div (at JobTemplateForm.jsx:194)
          in form (created by Form)
          in Form (at JobTemplateForm.jsx:193)
          in JobTemplateForm (created by Formik)
          in Formik (created by WithFormik(JobTemplateForm))
          in WithFormik(JobTemplateForm) (created by I18n)
          in I18n (created by WithI18n)
          in WithI18n (at JobTemplateForm.test.jsx:142)
          in Router (created by MemoryRouter)
          in MemoryRouter (at enzymeHelpers.jsx:96)
          in Wrap (created by WrapperComponent)
          in WrapperComponent
```

```
 PASS  src/components/AdHocCommands/AdHocDetailsStep.test.jsx
  ● Console

    console.error node_modules/prop-types/checkPropTypes.js:20
      Warning: Failed prop type: Invalid prop `moduleOptions[0]` of type `array` supplied to `AdHocDetailsStep`, expected `object`.
          in AdHocDetailsStep (created by I18n)
          in I18n (created by WithI18n)
          in WithI18n (at AdHocDetailsStep.test.jsx:44)
          in Formik (at AdHocDetailsStep.test.jsx:43)
          in Router (created by MemoryRouter)
          in MemoryRouter (at enzymeHelpers.jsx:96)
          in Wrap (created by WrapperComponent)
          in WrapperComponent
```

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by unlikelyzero** [comment]
@mabashian do you mind running yolok?

**Comment by mabashian** [comment]
@unlikelyzero sure, just kicked it off

**Review by jakemcdermott — APPROVED** [review]

**Comment by jakemcdermott** [comment]
regate

**Comment by jakemcdermott** [comment]
regate

**Pull request merged**
