### PR TITLE
Fixes a bug with ResourceAccess Add

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
This addresses #9456 and #9466 

The user can now properly add roles to a resource.  
##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Review by nixocio — APPROVED** [review]
Got this code locally, issue seems to be fixed. Goob job @AlexSCorey

**Comment by akus062381** [comment]
@AlexSCorey I will reach out to you on this

**Comment by akus062381** [comment]
@AlexSCorey, I checked your code. Everything is working except for the save button on a credential- refer to https://github.com/ansible/awx/issues/9456
But the check box issue is all fixed!

**Comment by akus062381** [comment]
everything looks good!

**Review by jakemcdermott — APPROVED** [review]

**Pull request merged**
