### PR TITLE
add a minimal framework for generating analytics/metrics

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by ryanpetrello** [comment]
recheck

**Review by rooftopcellist — APPROVED** [review]
lgtm

**Comment by rooftopcellist** [comment]
mergit

**Comment by ryanpetrello** [comment]
@rooftopcellist is going to continue work on this in his branch.

**Comment by one-t** [comment]
@rooftopcellist @ryanpetrello is that this one? https://github.com/ansible/awx/tree/analytics

**Comment by ryanpetrello** [comment]
@one-t I'd say whatever @rooftopcellist names the branch on _his_ remote, that's probably where he'll be doing the work, because that's the remote that'll turn into a PR eventually.

Maybe here?  https://github.com/rooftopcellist/awx/tree/analytics

**Comment by one-t** [comment]
🤦‍♂️ I don't know why I missed that when I looked at his fork. Thanks!

**Comment by rooftopcellist** [comment]
@one-t I am working out of this branch: https://github.com/ansible/awx/tree/analytics

**Pull request closed without merging**
