### PR TITLE
properly serialize external logs that contain decimal.Decimal objects

### PR DESCRIPTION
**Pull request by ryanpetrello**
image

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Just a log aggregator bug I noticed while looking at some other stuff.

**Comment by AlanCoding** [comment]
With this, could we get rid of the `format_timestamp` method already in this file? Like, plop the record time, created, and modified in the data as they are.

**Comment by ryanpetrello** [comment]
@AlanCoding I don't think so?  Those values are `datetime.datetime` objects, not `decimal.Decimal`.

**Comment by ryanpetrello** [comment]
Oh, I see what you mean, would the Django encoder just "do the right thing".

**Comment by ryanpetrello** [comment]
@AlanCoding 

No, it looks like the `DjangoJSONEncoder` coerces `datetime` objects to epoch integers, not `.isoformat()`:

image

**Comment by ryanpetrello** [comment]
Good call, @AlanCoding I've updated the PR and it seems to work:

image

**Comment by ryanpetrello** [comment]
image

**Review by rooftopcellist — APPROVED** [review]
lgtm

**Pull request merged**
