### PR TITLE
fix workflow url

### PR DESCRIPTION
**Pull request by djj106**
Signed-off-by: djj106 <djj106@gmail.com>

##### SUMMARY

Fix workflow url 

##### ISSUE TYPE

 - Bugfix Pull Request

##### COMPONENT NAME

 - API
 - UI

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by djj106** [comment]
https://github.com/ansible/awx/issues/9162

**Review by jakemcdermott — APPROVED** [review]
Good find, @ djj106. Thanks!

**Review by ryanpetrello — APPROVED** [review]
Thanks @djj106!

**Comment by kdelee** [comment]
taking off api label, api has been updated to use correct route in UI

Thanks!

**Comment by kdelee** [comment]
oops, meant to do this on the issue

**Pull request merged**
