### PR TITLE
feat: add token description column

### PR DESCRIPTION
**Pull request by Tioborto**
##### SUMMARY

- Add "description" column to user token list page
- Correction on french vocabulary

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by Tioborto** [comment]
Hello, 
I propose to you to add a new column in user token list page. 
I've just a problem with array headers style. How to correct it ? 
image

**Review by akus062381 — APPROVED** [review]

**Review by nixocio — CHANGES_REQUESTED** [review]
> Hello, I propose to you to add a new column in user token list page. I've just a problem with array headers style. How to correct it ? image

@Tioborto, Thanks for your PR.

On the `HeaderRow.js` - Modify

```
const Th = styled(PFTh)`
  --pf-c-table--cell--Overflow: initial;
  --pf-c-table--cell--MaxWidth: none;
`;
```

I believe that should fix the header overlapping that you described.

**Comment by Tioborto** [comment]
Indeed, thank you @nixocio. It works and fix header row style

**Comment by nixocio** [comment]
hey @Tioborto, thanks for updating that. Would you mind adding a different PR to address the translations? In case we need to revert, etc.

**Review by nixocio — APPROVED** [review]

**Pull request merged**
