### PR TITLE
Use a docker volume for the dev env db

### PR DESCRIPTION
**Pull request by shanemcd**

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
recheck

**Comment by jakemcdermott** [comment]
:eyes:

**Comment by jakemcdermott** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by jakemcdermott** [comment]
:eyes:

**Comment by jakemcdermott** [comment]
recheck

**Pull request merged**
