### PR TITLE
Upgrade lingui-cli to 2.9.2

### PR DESCRIPTION
**Pull request by jakemcdermott**
##### SUMMARY
Upgrade vulnerable dependencies

Screenshot from 2020-09-18 12-58-25

### CODE REVIEW

**Comment by unlikelyzero** [comment]
🟢

**Review by unlikelyzero — APPROVED** [review]
passes e2e

**Comment by unlikelyzero** [comment]
regate

**Comment by unlikelyzero** [comment]
recheck

**Comment by unlikelyzero** [comment]
regate

**Comment by unlikelyzero** [comment]
regate

**Comment by jakemcdermott** [comment]
recheck

**Comment by unlikelyzero** [comment]
regate

**Pull request merged**
