### PR TITLE
Define a DEFAULT_QUEUE_NAME

### PR DESCRIPTION
**Pull request by Spredzy**

### CODE REVIEW

**Comment by Spredzy** [comment]
recheck

**Review by rooftopcellist — APPROVED** [review]
LGTM

**Review by beeankha — APPROVED** [review]

**Comment by shanemcd** [comment]
This will most likely be replaced by https://github.com/ansible/awx/pull/10324

**Comment by Spredzy** [comment]
Closing in favor of prev mentionned PR

**Pull request closed without merging**
