### PR TITLE
Fix a few typos in awx/ui

### PR DESCRIPTION
**Pull request by altmas5**
##### SUMMARY

Remove consecutive occurrences of 'the'

##### ISSUE TYPE

 - Docs Pull Request

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Comment by jakemcdermott** [comment]
recheck

**Comment by jakemcdermott** [comment]
recheck

**Review by jakemcdermott — APPROVED** [review]
lgtm - thanks

**Comment by altmas5** [comment]
> lgtm - thanks

You're welcome!

**Pull request merged**
