### PR TITLE
[WIP] Avoid recursion in group computed fields

### LINKED ISSUE #1641: Computed fields suffers from same scaling problems with dense groups
##### ISSUE TYPE
 - Bug Report

##### COMPONENT NAME
 - API

##### SUMMARY
Inventory script with 500 hosts, 27 groups, and 351 group-group relationships reaches scaling limit of AWX.

##### ENVIRONMENT
* AWX version: 1.0.4-318
* AWX install method: docker for mac
* Ansible version:  relevant for 2.6/2.7
* Operating System:
* Web Browser:

##### STEPS TO REPRODUCE

Ansible core cannot yet handle these numbers, but a fix for that is in progress - https://github.com/ansible/ansible/pull/37141. If that fix lands, then Ansible will be able to handle inventories that AWX cannot.

In order to get around the temporarily limitation of core make this change

```
--- a/awx/main/management/commands/inventory_import.py
+++ b/awx/main/management/commands/inventory_import.py
@@ -90,6 +90,7 @@ class AnsibleInventoryLoader(object):
         return env
 
     def get_base_args(self):
+        return [self.source]
```

Next, create an inventory source that syncs from

https://github.com/AlanCoding/Ansible-inventory-file-examples/blob/master/scripts/connections/hosts/dag_max.py

set source variables

```yaml
NUMBER_HOSTS: 1000
```

##### EXPECTED RESULTS

Script expected to run with 10k hosts.

##### ACTUAL RESULTS

500 takes too long for me to wait, but limit varies based on your own patience.

thousands of hosts approach "heat death of the universe" slow.

### PR DESCRIPTION
**Pull request by AlanCoding**
Fixes https://github.com/ansible/awx/issues/1641

Dug back up from https://github.com/ansible/awx/pull/1628

Found that this will import the example with `NUMBER_HOSTS: 2000`, but I'm sure it goes farther.

I can add back in unit tests from the old PR as well, but this requires getting the fixtures and such in as well.

### CODE REVIEW

**Comment by AlanCoding** [comment]
This morning I ran the 10,000 case while eating breakfast.

```
2018-03-22 11:24:24,579 WARNING  awx.main.commands.inventory_import finished running the command itself
2018-03-22 11:24:24,586 WARNING  awx.main.commands.inventory_import Processing JSON output...
2018-03-22 11:24:24,586 WARNING  awx.main.commands.inventory_import finished processing
2018-03-22 11:24:26,064 WARNING  awx.main.commands.inventory_import loading into database...
2018-03-22 11:24:26,453 WARNING  awx.main.commands.inventory_import group updates took 471 queries for 140 groups
/venv/awx/lib/python2.7/site-packages/django/db/backends/base/base.py:151: UserWarning: Limit for query logging exceeded, only the last 9000 queries will be returned.
  "will be returned.".format(self.queries_log.maxlen))
2018-03-22 11:25:05,225 WARNING  awx.main.commands.inventory_import host updates took 8524 queries for 10000 hosts
2018-03-22 11:25:07,613 WARNING  awx.main.commands.inventory_import Group-group updates took 0 queries for 9730 group-group relationships
2018-03-22 11:25:10,576 WARNING  awx.main.commands.inventory_import Group-host updates took 0 queries for 10000 group-host relationships
2018-03-22 11:25:10,577 DEBUG    awx.main.models.inventory Going to update inventory computed fields
2018-03-22 11:26:29,902 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, taking 79.33
2018-03-22 11:26:29,903 WARNING  awx.main.commands.inventory_import update computed fields took 0 queries
2018-03-22 11:26:29,908 WARNING  awx.main.commands.inventory_import Inventory import completed for sdf in 125.5s
2018-03-22 11:26:30,419 WARNING  awx.main.commands.inventory_import Inventory import required 8995 queries taking 9.770s
```

The import works fine, although the query logger maxes out. To get a reference no-op case, I invoked computed fields again from the shell.

```
awx_1        | 2018-03-22 11:36:06,527 DEBUG    awx.main.models.inventory Going to update inventory computed fields
awx_1        | 2018-03-22 11:36:14,415 DEBUG    awx.main.models.inventory Finished updating inventory computed fields, taking 7.89
```

This stabilizes out at nearly 8 seconds. The initial time of 125 isn't unreasonable (although why it needs to run twice is another matter), when you consider that it has to loop over groups and hosts in order to update them, and that puts us in the 10k range. There's no hope for optimization there, but the no-op case does seem like it takes too long for undiscovered reasons.

Consider, `get_existing_group_computed_fields` takes 0.003 seconds to run. The no-op case should be fast (actually, I think I will have a commit coming for this in a second)

To test that this logic is right, this example is actually pretty good because I know that its group structure is a maximum density DAG, as I print the total number of groups (inside of a group), I can see it increase monotonically.

https://gist.github.com/AlanCoding/8ec7a6ec4d390362895957d179bfcb68

**Comment by AlanCoding** [comment]
Pushed a commit to fix that 10 s time for the no-op case. Now when I remove a host from a group it runs in 0.33 seconds. @ryanpetrello I think this is a good metric for what we can ultimately achieve with inventory computed fields.

...granted, current `devel` run time for this case is essentially "never".

**Review by ryanpetrello — COMMENTED** [review]
This is some pretty non-trivial code to be changing this late in the cycle, so I'd def. like to see some sort of tests if we're going to merge this.

**Comment by AlanCoding** [comment]
There are tests here https://github.com/ansible/awx/pull/1628 and https://github.com/ansible/ansible/pull/37141 (because some of the code I outright copied over)

The problem is how we down-select the tests without also creating an inordinate amount of database objects. The transaction tests I had took a solid minute to run. Some of them can be done as unit tests, and I will see about building those out.

**Comment by wwitzel3** [comment]
@AlanCoding this is something that I would like to get in to master early if we are going to do it.

**Review by wwitzel3 — APPROVED** [review]
I couldn't see anything about this that I didn't like. I like the use of chain.

**Comment by ryanpetrello** [comment]
@AlanCoding are the tests from 
https://github.com/ansible/awx/pull/1642#issuecomment-375307622 (or something equivalent) something we can bring over?

**Comment by AlanCoding** [comment]
yes, this shouldn't be a problem, really, I just need to apply some of those things here in functional tests. These are on my agenda, I can close them and then re-open later. Also, there's a great new test suite which would be great to run against this after a rebase.

**Comment by AlanCoding** [comment]
Related for inventory _imports_ of the problematic structure: https://github.com/ansible/ansible/pull/48598

**Pull request closed without merging**
