### PR TITLE
Fix server error using 2 creds of same type

### PR DESCRIPTION
**Pull request by AlanCoding**

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
regate

**Comment by Spredzy** [comment]
recheck

**Comment by AlanCoding** [comment]
regate

**Comment by AlanCoding** [comment]
recheck

**Comment by AlanCoding** [comment]
regate

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
regate

**Comment by ryanpetrello** [comment]
recheck

**Pull request merged**
