### PR TITLE
Docs: change Getting started EE guide reference to point to the relevant location

### PR DESCRIPTION
**Pull request by Andersson007**
##### SUMMARY
Docs: change Getting started EE guide reference to point to the relevant location. The stuff was moved yesterday.
The old one currently refers to a 404 page

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - Docs

##### AWX VERSION

```
n/a
```

### CODE REVIEW

**Comment by Andersson007** [comment]
ready for review

**Review by tvo318 — APPROVED** [review]
LGTM. Thanks!

**Comment by Andersson007** [comment]
@tvo318 CI is green

**Review by thedoubl3j — APPROVED** [review]

**Comment by Andersson007** [comment]
@tvo318 @thedoubl3j thanks for reviewing and merging!

**Pull request merged**
