### PR TITLE
Extend launched by details to handle scheduled JTs and WFJTs

### PR DESCRIPTION
**Pull request by marshmalien**
##### SUMMARY
Issue: https://github.com/ansible/awx/issues/5057

Launched By detail should link to the schedule that launched the job. 

Screen Shot 2021-01-14 at 11 41 49 AM

##### ISSUE TYPE

 - Enhancement Pull Request

##### COMPONENT NAME

 - UI

### CODE REVIEW

**Review by nixocio — APPROVED** [review]

**Comment by tiagodread** [comment]
@mabashian could you rebase this PR?

**Comment by unlikelyzero** [comment]
https://github.com/ansible/awx/pull/9201 is API rework blocking this PR

**Comment by unlikelyzero** [comment]
@marshmalien the associated API work is now merged and this is ready for re-review

**Comment by mabashian** [comment]
@marshmalien it seems like this just needs to be rebased and then we can test and merge?

**Comment by akus062381** [comment]
@marshmalien I tested this manually- all good! nice job!

**Review by akus062381 — APPROVED** [review]

**Pull request merged**
