### PR TITLE
Convert JobList to PaginatedTable

### PR DESCRIPTION
**Pull request by keithjgrant**
##### SUMMARY
Converts JobList component to use PaginatedTable. I also added the expandable content rows while I was in there

addresses #6189

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - UI

Screen Shot 2020-12-23 at 2 34 21 PM

### CODE REVIEW

**Review by nixocio — APPROVED** [review]

**Review by jakemcdermott — APPROVED** [review]

**Comment by tiagodread** [comment]
Hey @keithjgrant I've verified that the user can:

- navigate to job details
- relaunch a job
- use the basic and advanced search
- delete a single or some finished jobs
- cancel a single or some running jobs
- sort jobs by name, status, type, start time and finish time 
- change the number of job items on the list
- paginate through job items 
- expand/collapse the row
- The loading state component is displayed

Responsive tests against:
1024x768 and 1920x1080 

**Considerations:**
Are we going to cover these `launched` by and `Project` sorting options?
image

If the user selects a running/pending and a successful job the delete button is enabled and trying to delete both:

image

Are these data `Started Time` and `Finish Time` on the <thead> and `expandable-row`  the same data or they are duplicate?

image

Could you add a data-ouia-component-id (when available) or IDs on:
```
<table> 
<thead> <button> for each sorting option (Name, Status, Start time...)
<tr> expanded with something similar to the original row, like `expanded-job-row-8` 
```

**Comment by keithjgrant** [comment]
> Are we going to cover these `launched` by and `Project` sorting options?

At this point we don't have plans for additional sorting options beyond the column headers, but it's worth revisiting at some point to bring them back in an enhancement (it would take a bit of UI we haven't mocked up or worked through yet)

> If the user selects a running/pending and a successful job the delete button is enabled and trying to delete both:
> 
> image

It looks like this is the current behavior in devel as well. Can you file an issue and we can deal with it separately from this PR?

> Are these data `Started Time` and `Finish Time` on the and `expandable-row` the same data or they are duplicate?
> 
> image

Yeah, these are duplicated from the non-expanded row. Though that's probably not necessary... Thoughts on this @trahman73 ?

> Could you add a data-ouia-component-id (when available) or IDs on:
> 
> ```
> <table> 
> <thead> <button> for each sorting option (Name, Status, Start time...)
> <tr> expanded with something similar to the original row, like `expanded-job-row-8` 
> ```

👍🏻

**Comment by tiagodread** [comment]
Hey @keithjgrant look

Steps to reproduce:
1 click on the checkbox to select all rows

select all

On the checkbox row the aria-label is incorrect, "Select all rows":

image

**Review by tiagodread — APPROVED** [review]
Great job, added a PR to fix some broken tests and add more coverage about the list here https://github.com/ansible/tower-qa/pull/5909

**Pull request merged**
