### PR TITLE
Add organization to EE details page

### PR DESCRIPTION
**Pull request by nixocio**
Add organization to EE details page.

See: https://github.com/ansible/awx/issues/9432

image

### CODE REVIEW

**Comment by nixocio** [comment]
recheck

**Comment by nixocio** [comment]
regate

**Comment by tiagodread** [comment]
recheck

**Review by AlexSCorey — APPROVED** [review]
Look good

**Review by tiagodread — APPROVED** [review]
Also improved the assertion on ui tests, we can merge this PR once the zuul results are 🟢

**Comment by jakemcdermott** [comment]
recheck

**Review by jakemcdermott — APPROVED** [review]

**Pull request merged**
