### PR TITLE
prevent manual updates at POST /api/v2/inventory_sources/N/update/

### PR DESCRIPTION
**Pull request by ryanpetrello**
see: https://github.com/ansible/awx/issues/6309

### CODE REVIEW

**Comment by ryanpetrello** [comment]
@AlanCoding @matburt part of me wants to make this required at the model level (currently, it's not, it just defaults to an empty string), but given that it's been that way since...2013...I'm a little nervous that doing so would break some arcane inventory nuance I'm unaware of.  You two have any thoughts?

**Comment by wenottingham** [comment]
Artifact of when sources were tied to groups?

**Comment by ryanpetrello** [comment]
@wenottingham https://github.com/ansible/awx/blob/devel/awx/main/models/inventory.py#L824 ?

**Comment by ryanpetrello** [comment]
Yea, @wenottingham @AlanCoding are "manual" inventory sources even a thing anymore now that we don't tie syncs to groups (cc @chrismeyersfsu since I think he knows some history here as well ; I think this pre-dates me).

**Comment by wenottingham** [comment]
> @wenottingham https://github.com/ansible/awx/blob/devel/awx/main/models/inventory.py#L824 ?

I feel like that's related to some awx-manage inventory_import use case, but I honestly don't know for sure.

**Comment by ryanpetrello** [comment]
@wenottingham yea, I think _just_ changing the serializer is probably the safest route here unless @AlanCoding has any other feedback.

**Comment by ryanpetrello** [comment]
@AlanCoding @wenottingham @matburt I think I like this better (uploaded):

```diff
diff --git a/awx/main/models/inventory.py b/awx/main/models/inventory.py
index d94b428581..3ff6545f25 100644
--- a/awx/main/models/inventory.py
+++ b/awx/main/models/inventory.py
@@ -1345,6 +1345,12 @@ class InventorySource(UnifiedJobTemplate, InventorySourceOptions, CustomVirtualE
     def get_absolute_url(self, request=None):
         return reverse('api:inventory_source_detail', kwargs={'pk': self.pk}, request=request)

+    @property
+    def can_update(self):
+        if self.source == '':
+            return False
+        return super(InventorySource, self).can_update
+
     def _can_update(self):
         if self.source == 'custom':
             return bool(self.source_script)
```

image

If you visit `/api/v2/inventories/update_inventory_sources/`, it doesn't show manual ones, and `POST`ing to that endpoint *only* launches non-manual sources (there's code to skip them in the view, it looks like)

https://github.com/ansible/awx/blob/daa9282790ca9c3f4fedfdd9fdf0251bba663824/awx/api/views/__init__.py#L2035

**Comment by matburt** [comment]
This looks good to me.

**Review by matburt — APPROVED** [review]

**Comment by AlanCoding** [comment]
This won't prevent _creating_ manual inventory sources, will it?

**Comment by ryanpetrello** [comment]
@AlanCoding nope, just _launching_ them at `/api/v2/inventory_sources/N/update/`.

**Pull request merged**
