### PR TITLE
Added support for aarch64

### PR DESCRIPTION
**Pull request by fsbano**
##### SUMMARY

Dockerfile changed to work on aarch64 platform

```
> tini-arm64 
> git2u-core -> git
> NodeJS -> Epel Repo
> YUM INSTALL ADD freetype freetype-devel libpng libpng-devel
```
##### ISSUE TYPE
I was not working on arm64

##### COMPONENT NAME
 - Installer

##### AWX VERSION
```
awx: devel
```

##### ADDITIONAL INFORMATION
Added support for arm64 platform

### CODE REVIEW

**Review by fsbano — COMMENTED** [review]
Added

**Comment by dmsimard** [comment]
recheck

**Comment by fsbano** [comment]
> recheck
Verified

**Comment by fsbano** [comment]
> recheck

Verified

**Comment by wenottingham** [comment]
>  >  recheck
> Verified

The 'recheck' is a comment for the CI system. Humans can ignore it.

**Comment by dmsimard** [comment]
Yes, sorry, this was me testing something but it was around the time of the github outage.. my comments didn't work but it looks like github unpiled everything that didn't work...

**Comment by fsbano** [comment]
Will the merge be done?

**Comment by wenottingham** [comment]
Is there a way this could be merged into as much of a single dockerfile as possible? I would greatly greatly prefer not to have to copy the same changes to each file every time.

**Review by wenottingham — CHANGES_REQUESTED** [review]
Please do this by parameterizing arch to the original dockerfile and conditionalizing things accordingly.

**Comment by fsbano** [comment]
I'll work on the single file then

Thank you very much

**Comment by fsbano** [comment]
The original Dockerfile file is making use of the nodejs that have no build for aarch64 I changed to use the nodejs of the epel repository however it is using version 6.

> RUN curl --silent --location https://rpm.nodesource.com/setup_8.x | bash -

Is there any dependency for version 8?

Best Regards,
Fábio Sbano

**Comment by fsbano** [comment]
https://github.com/nodesource/distributions

```
Enterprise Linux based distributions
Available architectures:

NodeSource will continue to maintain the following architectures and may add additional 
ones in the future.
- i386 (32-bit) — not available for all distros and not available for Node.js 10 and later
- x86_64 (64-bit)

Supported Red Hat® Enterprise Linux® versions:
- RHEL 6 (64-bit)
- RHEL 7 (64-bit)
```
I built the binary for aarch64

[root @ hermes aarch64] # ls -1
nodejs-8.4.0-1nodesource.el7.aarch64.rpm
nodejs-debuginfo-8.4.0-1nodesource.el7.aarch64.rpm
nodejs-devel-8.4.0-1nodesource.el7.aarch64.rpm
[root @ hermes aarch64] #

it's better, right?

**Comment by wenottingham** [comment]
Re: dependency, yes, node8/npm6 is a dependency.

**Comment by fsbano** [comment]
> Re: dependency, yes, node8/npm6 is a dependency.

I built the binary for aarch64

[root @ hermes aarch64] # ls -1
nodejs-8.4.0-1nodesource.el7.aarch64.rpm
nodejs-debuginfo-8.4.0-1nodesource.el7.aarch64.rpm
nodejs-devel-8.4.0-1nodesource.el7.aarch64.rpm
[root @ hermes aarch64] #

but i I need to change the source https://rpm.nodesource.com/setup_8.x to support aarch64. I hope this request is approved for https://github.com/nodesource

Best Regards,
Fábio Sbano

**Comment by fsbano** [comment]
wenottingham,

Is it mandatory to be the postgresql 9.4 client?

> http://download.postgresql.org/pub/repos/yum/9.4/redhat/rhel-6-x86_64/pgdg-centos94-9.4-3.noarch.rpm

I am using 
```
[root@awx /]# rpm -qa | grep postgre
postgresql-devel-9.2.24-1.el7_5.aarch64
postgresql-libs-9.2.24-1.el7_5.aarch64
postgresql-9.2.24-1.el7_5.aarch64
[root@awx /]# 
```
Best  Regards,
Fábio Sbano

**Comment by matburt** [comment]
Yes, don't drop it back to 9.2... in the near future we'll move to pg 10 and then it'll be *really* out of date.

**Comment by vielmetti** [comment]
Here's a set of searches for a most recent PostgreSQL version, @fsbano  -

https://rpmfind.net/linux/rpm2html/search.php?query=postgresql

Looks like the Fedora RPMs have more current versions than the CentOS ones.

**Comment by fsbano** [comment]
> Yes, don't drop it back to 9.2... in the near future we'll move to pg 10 and then it'll be _really_ out of date.

I can see that postgresql-96 is only being used for python-psycopg2 and contains native version 9.2 installed (awx) but the database image postgresql-server-96 is being used in another container.

Work is in progress. It may be best to build the binary for version 10.

jaguar:aarch64 fsbano$ ls -1
nodejs-8.4.0-1nodesource.el7.aarch64.rpm
nodejs-debuginfo-8.4.0-1nodesource.el7.aarch64.rpm
nodejs-devel-8.4.0-1nodesource.el7.aarch64.rpm
postgresql96-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-contrib-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-debuginfo-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-devel-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-docs-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-libs-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-plperl-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-plpython-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-pltcl-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-server-9.6.10-1PGDG.el7.aarch64.rpm
postgresql96-test-9.6.10-1PGDG.el7.aarch64.rpm
python-psycopg2-2.7.5-1.el7.aarch64.rpm
python-psycopg2-debug-2.7.5-1.el7.aarch64.rpm
python-psycopg2-debuginfo-2.7.5-1.el7.aarch64.rpm
python-psycopg2-doc-2.7.5-1.el7.aarch64.rpm
python2-psycopg2-tests-2.7.5-1.el7.aarch64.rpm
jaguar:aarch64 fsbano$ 

I have another problem the nodesource did not accept my pull request -> https://github.com/nodesource/distributions/pull/743

Best Regards,
Fábio Sbano

**Comment by vielmetti** [comment]
@fsbano 

Is there an open PR for the PostgreSQL components you are missing? I am not sure what repo would need to be changed to add those arm64 builds.

**Comment by matburt** [comment]
I have an overarching concern with this PR in that it's not linked up in any way to our build infrastructure and there's no specific internal testing that we can do to validate that it works continuously during our release process.

This seems like it would be better served as an external project from AWX proper.

**Comment by fsbano** [comment]
> I have an overarching concern with this PR in that it's not linked up in any way to our build infrastructure and there's no specific internal testing that we can do to validate that it works continuously during our release process.
> 
> This seems like it would be better served as an external project from AWX proper.

rpm package was created in version 10 postgresql :-)
- https://github.com/fsbano/postgresql10

Will the Docker external database image be re-created?

I see that currently awx_web exists 9.2 (client) and 9.6 (client)

Best Regards,
Fábio Sbano

**Comment by fsbano** [comment]
Unfortunately there is no community interest in the aarch64 platform

 - PostgreSQL (RHSCL)
 - NodeJS

Thank you all,
Fábio Sbano

**Comment by lemmy04** [comment]
can someone please reopen this, with the newer pi models the interest might be there now...

**Comment by kevindurb** [comment]
#7051

**Comment by geerlingguy** [comment]
@lemmy04 - Please see #7051, and hopefully we'll see a little renewed interest, for the following reasons:

  1. Pi 4 8 GB and Raspberry Pi OS 64-bit were introduced last month, making the Pi more competent for a heavy app like AWX.
  2. Postgres and Nodejs now have ARM64 arch builds in Docker Hub at least (its easier to do multi-arch builds now)
  3. Apple Silicon is ARM64 and if we want AWX to run in Docker for Mac on newer Macs, it will need to be built for ARM64 as well as X86.

**Comment by nullr0ute** [comment]
And actually the most interesting in the context of this the AWS Graviton series of aarch64 VMs/bare metal.

**Pull request closed without merging**
