### PR TITLE
Consolidate scl enable calls

### PR DESCRIPTION
**Pull request by shanemcd**

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
rebuild

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Review by rooftopcellist — APPROVED** [review]

**Comment by shanemcd** [comment]
recheck

**Pull request merged**
