### PR TITLE
Modify UI building process for development environment to cover I18N static contents

### PR DESCRIPTION
**Pull request by saito-hideki**
##### SUMMARY

For a development environment, if we want to generate language files like `awx/locale/ja/LC_MESSAGES/django.mo`,  we need to exec `make languages` before `make ui-devel`.
If the building process of those files have finished before `ui-devel` target, `*.mo` and `<LANG>.json` files will be copied to the static contents directory by `collectstatic`.

##### ISSUE TYPE
 - Feature Pull Request

##### COMPONENT NAME
 - Installer

##### ADDITIONAL INFORMATION
None

### CODE REVIEW

**Comment by saito-hideki** [comment]
recheck

**Review by ryanpetrello — COMMENTED** [review]
@mabashian @jakemcdermott you have any opinions on this?  Seems pretty reasonable to me.

**Review by jakemcdermott — CHANGES_REQUESTED** [review]
This will cause the `PUPPETEER_SKIP_CHROMIUM_DOWNLOAD` flag to get incorrectly set to `1` for `make ui-devel` builds. We only want to skip the chromium download for `make ui_release` builds.


```
~/projects/awx$ make ui-devel
PUPPETEER_SKIP_CHROMIUM_DOWNLOAD=1 npm --unsafe-perm --prefix awx/ui ci --no-save awx/ui
```

@saito-hideki you're welcome to optimize the `devel` make targets but for this you'll need to find a way to make sure the language deps get built without preventing the chromium download for devel builds.

**Review by jakemcdermott — APPROVED** [review]
@saito-hideki - ~working now fafter a `make clean`, actually.  :man_shrugging: LGTM. thanks.~

*edit:* actually, I have some reproduction steps for what I mentioned here: https://github.com/ansible/awx/pull/4271#pullrequestreview-259643229

Starting with a checkout of devel, you should be able to run:

```
make clean-ui
make ui-devel
make ui-test-ci
```

With the Makefile changes in this PR, I'm seeing that the tests will fail to run - I'm assuming this is from the puppeteer chromium download being skipped. When I undo the changes and try the above steps again, the tests run without issue.

**Review by jakemcdermott — CHANGES_REQUESTED** [review]
see https://github.com/ansible/awx/pull/4271#pullrequestreview-259643229

**Pull request closed without merging**
