### PR TITLE
Updates Several UI dependencies

### PR DESCRIPTION
**Pull request by AlexSCorey**
##### SUMMARY
updates d3, ansi-t0-html, has-ansi, httml-entities, sanitize-html, styled-components

##### ISSUE TYPE
-depdency upgrades

##### COMPONENT NAME
 - UI

### CODE REVIEW

**Comment by AlexSCorey** [comment]
e2e triggered

**Comment by AlexSCorey** [comment]
visual tests triggered

**Review by nixocio — CHANGES_REQUESTED** [review]
@AlexSCorey overall changes look good.

We need to run prettier to fix CI.

```bash
npm run prettier
modified:   src/screens/Dashboard/shared/LineChart.jsx
```

**Comment by nixocio** [comment]
regate

**Comment by AlexSCorey** [comment]
closing in favor of https://github.com/ansible/awx/pull/10662

**Pull request closed without merging**
