### PR TITLE
properly support deprecated `Authorization: Token xyz`

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Looks like the swagger build in Shippable timed out 🤷‍♂️

**Comment by rooftopcellist** [comment]
@ryanpetrello it looks like the `Authorization: Token` syntax works with as many spaces between Token and the token value as the user wants.  

```
curl -k -H 'Authorization: Token       Cl3lPEA8XLS06OSYDHUFEtDqylcZdg' https://localhost:8043/api/v2/config/

curl -k -H 'Authorization: Token Cl3lPEA8XLS06OSYDHUFEtDqylcZdg' https://localhost:8043/api/v2/config/
```

A small nitpick is that the `Authorization: Bearer` syntax _only_ works with one space, and the error message doesn't give a clear indication as to why.  

```
christianadams$ curl -k -H 'Authorization: Bearer  Cl3lPEA8XLS06OSYDHUFEtDqylcZdg' https://localhost:8043/api/v2/config/
{"detail":"Authentication credentials were not provided. To establish a login session, visit /api/login/."}
```

**Comment by ryanpetrello** [comment]
@rooftopcellist yea, my goal here is to just provide backwards compatibility w/ pre-3.3.0 (which we currently don't seem to have).  If users discover that extra spaces are allowed in `Authorization: Token`, then 🤷‍♂️ (in my opinion), because this code is just meant as a temporary shim that we're throwing away in the near future (likely 3.4 or 3.5).

**Review by rooftopcellist — APPROVED** [review]
I agree, tests pass locally for me.  lgtm!

**Pull request merged**
