### PR TITLE
Add peers management and hop options on UI

### PR DESCRIPTION
**Pull request by tanganellilore**
##### SUMMARY
This PR add some enhancement on some areas that will be useful also for hop node.

- new "peer" api using InstanceLink for add/remove links beetween nodes
- Add/remove buttons on peer instance tab to add/remove links beetween peer
- integrate hop funcitionality  on UI to add also hop node

##### ISSUE TYPE

 - New or Enhanced Feature

##### COMPONENT NAME

 - API
 - UI

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Comment by tanganellilore** [comment]
@fosterseth fyi, I updated with your last commit related rename of peers_from_control_nodes

**Comment by fosterseth** [comment]
thanks for the live demo

todo:
- api calls can go through the /api/v2/instances/ endpoint by patching the "peers" field, instead of the api/v2/peers view
- Add peer association / disassociation box on the instance creation page
- Save button on the instance edit page (so that peers_from_control_nodes is not triggering write_receptor_config too easily)
- node type editable for existing execution/hop nodes (but not control nodes)

**Comment by tanganellilore** [comment]
Hi @fosterseth i will use this PR, that we will colse in next future, as "traking".

First PR with backend api released on https://github.com/ansible/awx/pull/13916.
After this approval i will move to UI part with all features discussed today.

Thanks

**Comment by tanganellilore** [comment]
close in favour of UI PR https://github.com/ansible/awx/pull/13922

**Pull request closed without merging**
