### PR TITLE
Add some Chinese Translations

### PR DESCRIPTION
**Pull request by weidongkl**
##### SUMMARY

Add some Chinese Translations

##### COMPONENT NAME

 - UI

##### AWX VERSION

```

```

##### ADDITIONAL INFORMATION

```

```

### CODE REVIEW

**Review by AlexSCorey — APPROVED** [review]
Based on google translate, these translations are accurate.

**Comment by weidongkl** [comment]
> Based on google translate, these translations are accurate.

Thanks

**Comment by weidongkl** [comment]
Can this PR merge？

**Comment by AlexSCorey** [comment]
@weidongkl please rebase this PR to trigger the checks again.

**Comment by nnguyenrh** [comment]
@weidongkl 

Lines 2687 - 2688:
```
msgid ""
"Enter one Slack channel per line. The pound symbol (#)\n"
"is required for channels."
msgstr "每行输入一个 Slack 频道。频道不需要输入 # 号。"
```

英文沒錯的話翻譯該不該說 「频道需要输入 # 号」？
Chinese currently says "The pound symbol is not required for channels".

**Comment by qiwangrh** [comment]
The Chinese translation in this PR look good based on the current English messages. We might need revisit its Chinese translation after https://github.com/ansible/awx/issues/12752 is fixed.

**Review by qiwangrh — APPROVED** [review]

**Comment by AlexSCorey** [comment]
Does not need QE

**Comment by AlexSCorey** [comment]
No UI QE needed

**Pull request closed without merging**
