### PR TITLE
CyberArk Central Credential Provider Lookup custom Web Service ID & update branding

### LINKED ISSUE #10545: Update CyberArk AIM credentials lookup plugin
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY
Update AIM credentials lookup plugin to allow entering complete URL to the API.
Currently it requires BaseURL and after that adds hard-coded values:
request_url = urljoin(url, '/'.join(['AIMWebService', 'api', 'Accounts']))

If you are using something else than AIMWebService you will not be able to make it work.

Add a descriptions or tool-tip to the URL field in the GUI

image

### LINKED ISSUE #13122: Update CyberArk AIM Central Credential Provider branding
### Please confirm the following

- [X] I agree to follow this project's [code of conduct](https://docs.ansible.com/ansible/latest/community/code_of_conduct.html).
- [X] I have checked the [current issues](https://github.com/ansible/awx/issues) for duplicates.
- [X] I understand that AWX is open source software provided for free and that I might not receive a timely response.

### Bug Summary

Currently, the CyberArk CCP external secrets management system credential plugin is named `CyberArk AIM Central Credential Provider Lookup` and should no longer have `AIM` within the name to match current CyberArk branding.

### AWX version

21.7.0

### Select the relevant components

- [X] UI
- [X] API
- [ ] Docs
- [ ] Collection
- [ ] CLI
- [ ] Other

### Installation method

docker development environment

### Modifications

no

### Ansible version

2.13.5

### Operating system

Ubuntu 22.04.1 LTS

### Web browser

_No response_

### Steps to reproduce

View the CyberArk AIM Central Credential Provider Lookup in Credentials.

### Expected results

Should be `CyberArk Central Credential Provider Lookup`

### Actual results

Is `CyberArk AIM Central Credential Provider Lookup`

### Additional information

PR is prepared and will be submitted shortly.

### PR DESCRIPTION
**Pull request by infamousjoeg**
##### SUMMARY
Fixes #13122 & fixes #10545. Updates name from `CyberArk AIM Central Credential Provider Lookup` to `CyberArk Central Credential Provider Lookup`.  Removes references to `AIM`.  Adds the ability to set a different CCP Web Service ID than the default `AIMWebService`.

##### ISSUE TYPE
 - Bug, Docs Fix or other nominal change

##### COMPONENT NAME
 - API
 - UI

##### AWX VERSION
```
awx: 0.1.dev32524+g2cc971a.d20221026
```

##### ADDITIONAL INFORMATION
n/a

### CODE REVIEW

**Comment by TheRealHaoLiu** [comment]
Hi @infamousjoeg thank you for your contribution!

are you on Ansible chat https://matrix.to/#/#awx:ansible.com 
we would love to hang out and chat with you about CyberArk integration 

also it would be wonderful if you can provide some instruction on how you have tested this feature (both regression and the new functionality)

PS: I'm actually wearing a CyberArk t-shirt right now, the one with "stolen secrets sink starships

PPS: there might be a rare IRL angry spuds plushy for you and your college if you job the AWX chatroom and collaborate with us

**Comment by infamousjoeg** [comment]
I am already in #ansible-awx on IRC. If I remember correctly, it is linked with Matrix. Should I move over to Matrix instead?

**Review by AlexSCorey — APPROVED** [review]
This is good to go from a UI perspective.  It looks like all the places in the UI code that need a name change have gotten it in this PR.  Well done and thanks for the contribution!

**Review by CFSNM — APPROVED** [review]

**Comment by branic** [comment]
@infamousjoeg The commits in this PR are the same as in #13121 and the changes you discussed on office hours this morning are not here.

**Comment by CFSNM** [comment]
@branic It was my fault. Git played me a bad trick and the changes here https://github.com/ansible/awx/pull/13121 were merged in this PR. I just solved the incidence and this PR is back to the correct state. My apologies @infamousjoeg

**Review by fosterseth — APPROVED** [review]

**Comment by infamousjoeg** [comment]
Fixed the merge conflicts.  Should be good to go now.

**Review by CFSNM — APPROVED** [review]

**Review by Zokormazo — APPROVED** [review]

**Pull request merged**
