### PR TITLE
Remove unused project field

### PR DESCRIPTION
**Pull request by AlanCoding**
Fixes https://github.com/ansible/awx/issues/1892

### CODE REVIEW

**Review by wwitzel3 — DISMISSED** [review]
Update the migration so it can merge cleanly and this LGTM.

**Comment by AlanCoding** [comment]
this should be added to the CHANGELOG too

**Comment by AlanCoding** [comment]
Ping @wenottingham about API versioning strategy.

This is a battle we will have to fight in other places soon as well. Note: job template `credential` field is deprecated, and the plan is to remove it without introducing a v3 API.

Removing this field may be a better test case. It was a read-only field, and we know that it was implemented wrong, so it never served any purpose for any client, unless that client was mistaken. As a matter of case law, removing this field is establishing that it's still okay to remove fields without a new API version.

**Comment by wenottingham** [comment]
cc @matburt. I'm generally OK with it, but curious about other opinions.

**Comment by ryanpetrello** [comment]
Casting my vote: let's please not introduce an `/api/v3/` for this.  If a lesser-known API field has a nuanced bug, let's just deprecate (it looks like we already did this) and remove it (let's do this).

**Review by matburt — APPROVED** [review]
For fields like this I'm okay with removing them after a deprecation period. `v3` will be a larger discussion.

**Comment by matburt** [comment]
needs rebase, though!

**Comment by ryanpetrello** [comment]
Agreed, once this is rebased, I say let's merge it.

**Comment by AlanCoding** [comment]
Roger that.

A new PR that sets out to follow a similar pattern as this: https://github.com/ansible/awx/pull/2591

Both of these are following a field deprecation schedule, where the OPTIONS announce them as deprecated, and then after some amount of grace time, they are yanked out of the schema.

**Comment by AlanCoding** [comment]
added to changelog.

**Pull request merged**
