### PR TITLE
Replace RabbitMQ w/ Redis

### PR DESCRIPTION
**Pull request by chrismeyersfsu**
related to https://github.com/ansible/awx/issues/5443

3 use cases for RabbitMQ:
1. websockets
2. dispatcher (message broker)
3. ansible events --> database

-----

1. This PR upgrades to channels 2 (async interface). Redis operate independently of each other (*NO* clusters or master/slave). Instead, we distribute the `group_send()` event to all tower nodes to be replayed (think RPC). User websocket <--> group subscription is maintained _only_ on the local redis. This is perfect in the case of an AWX node fail. Websocket clients already have to reconnect to a different AWX node in case of a failure; thus, there is no reason to propagate websocket group membership between AWX nodes.

2. Redis is temporarily being used as an AMQP message broker. All towers point to a single redis instance. If that AWX node goes down then the whole system fails. We plan on replacing this with a postgres message broker. We can do this because our traffic need is very low.

3. Ansible events are pushed into RabbitMQ for distributed processing of events to the database. The reason we distribute the events is because our writing to postgres is synchronous. We spawn multiple threads in the callback receiver to allow concurrent writes to postgres but there is a high overhead to those threads. With this PR, those Ansible events are pushed into the single Redis and all nodes pop from that Redis and process events. We plan on replacing this architecture with an async postgres writing. With this in place, we shouldn't need to distribute events. At this point we will utilize Redis as a local-only IPC + cache for Ansible events.

---

### CODE REVIEW

**Comment by wenottingham** [comment]
> Websocket clients already have to reconnect to a different AWX node in case of a failure; thus, there is no reason to propagate websocket group membership between AWX nodes.

How does this work in a loadbalancer or DNS-RR environment?

**Comment by chrismeyersfsu** [comment]
It's the same problem that we have today. Presumably users will have their load balancer setup to detect the health of the tower nodes behind it.

**Comment by wenottingham** [comment]
> It's the same problem that we have today. Presumably users will have their load balancer setup to detect the health of the tower nodes behind it.

No, I mean in the case of a loadbalancer, your requests could silently be redirected to different nodes, so wouldn't you lose websocket groups when that happens?

**Comment by chrismeyersfsu** [comment]
Websocket connections are persistent. Once established they stay with that tower node. We don't support any kind of session migration today and we won't support one in this new proposal.

If we were to support such a thing we could store the user <--> group relationship in postgres; per user-session.

**Comment by bouluad** [comment]
Hello
I have a question about replacing Rabbit by redis, that's mean Redis is the final solution ? 
What is exactly the role of Redis ? 
is it better to get into production with an infrastructure like that (with Redis) or wait ?

**Comment by ryanpetrello** [comment]
> What is exactly the role of Redis ?

Please see the detailed issue description above that explains this: https://github.com/ansible/awx/pull/5441#issue-348957149

> is it better to get into production with an infrastructure like that (with Redis) or wait ?

We won't be able to answer this question for you (it will depend on your comfort level and familiarity with managing and deploying open source software in production environments).

AWX is open source software, and it's constantly evolving.  Our official stance is that AWX is not production-hardened software.  We anticipate that for the foreseeable future, AWX will make use of redis in some fashion; it is unlikely that we'll return to RabbitMQ.

**Pull request closed without merging**
