### PR TITLE
Modifying AWX collection to allow connection to IPv6 hosts.

### PR DESCRIPTION
**Pull request by konono**
##### SUMMARY
resolve verification in controller_api.py does not support AWX IPv6 single stack installation's.
related #11450

##### ISSUE TYPE
 - New or Enhanced Feature

##### COMPONENT NAME
 - Collection

##### ADDITIONAL INFORMATION

Playbook sample
```
---
- name: 'Create project'
  awx.awx.tower_project:
    name: 'Foo'
    tower_host: 'fd00:2001::1/64'
    tower_username: 'username'
    tower_password: 'password'
    organization: 'Default'
    state: present
```

Behavior before change
```
TASK [create_project : Create project]　********************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "msg": "Unable to resolve tower_host ([Errno -2] Name or service not known): [fd00"}
```

Behavior after change
```
TASK [create_project : Create project] *************************************************************************************************************************************************************************************
ok: [localhost]
```

### CODE REVIEW

**Comment by john-westcott-iv** [comment]
We have been using PR titles for release notes. Could you change your title to be more descriptive like: `Modifying AWX collection to allow connection to IPv6 hosts`?

**Comment by john-westcott-iv** [comment]
We will need to think about if/how we are going to do an integration test with an IPv6 host to ensure we don't get a regression here.

**Review by john-westcott-iv — APPROVED** [review]

**Comment by jay-steurer** [comment]
Hi, @konono. Could you rebase your commit? Thanks!

**Comment by konono** [comment]
Hi, @jay-steurer . I rebased my commits. Please check it. Thanks!

**Pull request merged**
