### PR TITLE
Update migration page

### PR DESCRIPTION
**Pull request by nixocio**
Update migration to add styling. Also, use django template and context
to inject variables into the migration page.

See: https://github.com/ansible/awx/issues/8355

Screen Shot 2021-01-20 at 4 25 18 PM

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
lgtm!

**Comment by nixocio** [comment]
I also had to vendor the fonts. PR updated.

**Review by jakemcdermott — APPROVED** [review]

**Comment by nixocio** [comment]
I am getting a failure when collecting static files on e2e tests. Working on it.

**Comment by jakemcdermott** [comment]
LOADING

**Review by jakemcdermott — APPROVED** [review]

**Pull request merged**
