### PR TITLE
merge a variety of downstream bug fixes

### PR DESCRIPTION
**Pull request by ryanpetrello**

### CODE REVIEW

**Review by AlanCoding — APPROVED** [review]

**Review by matburt — APPROVED** [review]

**Review by beeankha — APPROVED** [review]
🚀

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by ryanpetrello** [comment]
recheck

**Comment by shanemcd** [comment]
recheck

**Pull request merged**
