### PR TITLE
resolving installation folder issues related to #3551

### PR DESCRIPTION
**Pull request by mrwiora**
##### SUMMARY
resolving the topic covered in/related #3551 

##### ISSUE TYPE
 - Bugfix Pull Request

##### COMPONENT NAME
 - Installer

### CODE REVIEW

**Review by shanemcd — CHANGES_REQUESTED** [review]
`/opt` is not going to be a writable location for a lot of our users. We would probably accept a PR that adds magic around detecting where it should write to, but we're not going to change this to a non-functional default.

**Comment by mrwiora** [comment]
hi @shanemcd,

where you thinking about something like this? I've implemented a simple way of fallback mechanism. Optionally I could add a third way (always), which is used when even the home directory is not available.

Cheers,
// Matthias

**Comment by LaurentDumont** [comment]
I think we could use Ansible built-in `var=lookup('env','HOME')` which would point to the home of the user the playbook is currently running with.

Using a separate file to point to the `~` is a bit cumbersome.

**Comment by mrwiora** [comment]
@LaurentDumont I would fully agree with you regarding the extra file - but I found no other way to overwrite the variable inplace (vars: is not accepted in either way). Any other logic would be additional work and extra logic - while the current solutions brings up an error during the installation and therefore will be noticed by the user for sure:

image

I've added a note to the inventory file.
IMHO any solution would be better than the current situation that the files are written to a destionation where they don't survive a reboot...

**Comment by mrwiora** [comment]
well - no chance to get that in?

**Comment by mwiora** [comment]
I have to re-fork this issue and will open a new PR comming from a dedicated feature-branch.

**Comment by mrwiora** [comment]
PR has been accidently wasted by myself as I've been continuing to work on the same fork - but the main branch.... recreating

**Comment by mrwiora** [comment]
created #4877, closing this one

**Pull request closed without merging**
