### PR TITLE
 Update how ui tests are invoked on CI

### PR DESCRIPTION
**Pull request by nixocio**
Update how ui tests are invoked on CI as an attempt to speed up test
run.

### CODE REVIEW

**Comment by keithjgrant** [comment]
have you done any benchmarking here to see if this helps? When I did test perf work this summer, I found it worked best if I left off the maxWorkers flag and let it determine automatically -- but that was for local test runs, so it could be totally different in CI

**Comment by nixocio** [comment]
@keithjgrant I did several test runs with different combinations, let me try this one that you mentioned.

**Comment by nixocio** [comment]
@keithjgrant not setting the number of workers generated the best results so far.

image

image

**Review by AlexSCorey — APPROVED** [review]
Looks good

**Review by jakemcdermott — APPROVED** [review]

**Comment by nixocio** [comment]
Currently we are not enforcing any rule related to coverage and we can bring back if necessary.  Also, we to be mindful of the changes to code coverage with local runs. Removal of coverage on CI seems to help improve tests speed.

**Pull request merged**
