### PR TITLE
Use JEST directly for unit tests.

### PR DESCRIPTION
**Pull request by kialam**
##### SUMMARY

Screen Shot 2022-03-21 at 11 42 58 AM
This replaces our test runner that calls react scripts with Jest directly. Pros: an improvement in performance speed can be observed. Configuration is easily gleaned and modified from dedicated configuration files. Cons: more dev dependencies to install and maintain, another config file added to our root directory.

##### ISSUE TYPE

 - Feature Pull Request

##### COMPONENT NAME

 - UI

##### AWX VERSION

```
20.0.2
```

### CODE REVIEW

**Comment by AlexSCorey** [comment]
Given that react-scripts has been so difficult to bump versions I'm not opposed to offloading some work from it and the time reduction is AMAZING. However my concerns are: 

1. How might the possibly limited life span of jest play in here. 
2. How active, maintained are the new dependencies
3. Does this push us further from jest toward React testing library?

**Review by nixocio — COMMENTED** [review]
@kialam this is a great improvement.

We will need update what target from the make file we are calling on CI. Replacing 

``` yaml
          - name: ui-test-screens
            label: Run UI Screens Tests
            command: make ui-test-screens
          - name: ui-test-general
            label: Run UI General Tests
            command: make ui-test-general
```

https://github.com/ansible/awx/blob/7d04737a6522d16dd711afa72a1fccb5bdaa7b4d/.github/workflows/ci.yml#L37

To be

``` yaml
          - name: ui-test
            label: Run UI Tests
            command: make ui-test

```

https://github.com/ansible/awx/blob/7d04737a6522d16dd711afa72a1fccb5bdaa7b4d/Makefile#L405

**Comment by nixocio** [comment]
This PR seems to be fixing https://github.com/ansible/awx/issues/10678

**Review by AlexSCorey — APPROVED** [review]
I like this.  I like that we are configuring babel more directly rather than obscuring it behind react-scripts.  We should consider  updating the babel dependencies though, because I think many of them are behind.  That can be a separate pr, if you feel that makes more sense.  Good work on this!

**Comment by kialam** [comment]
Closing this in favor of more research is needed. See [here](https://github.com/ansible/awx/issues/10678#issuecomment-1106742276).

**Pull request closed without merging**
