### PR TITLE
Added some Doc for ca_trust_dir

### LINKED ISSUE #411: Provide custom CA certificate or skip-verify option for LDAP auth
##### ISSUE TYPE
 - Feature Idea

##### COMPONENT NAME
 - Installer

##### SUMMARY
I cannot use SSL encrypted LDAP authentication because I see no way to provide my CA certificate to the containers or have an option in the installer to disable certificate verification.

When logging in a certificate verification error comes up. 

It would be awesome to have a `additional_ca_certificate` or `skip_verify_ssl` variable in the insaller inventory.

##### ENVIRONMENT
* AWX version: d02221702fd680cd38068ec49597a7b627228c04
* AWX install method: docker on linux
* Ansible version:  2.3.2.0
* Operating System: Centos 7 (epel)
* Web Browser: Firefox

##### STEPS TO REPRODUCE
* Configure ansible-awx to use SSL encrypted ldap auth
* Login

##### EXPECTED RESULTS
Successful login

##### ACTUAL RESULTS
```
2017-10-12 10:06:12,414 DEBUG    django_auth_ldap Initiating TLS
2017-10-12 10:06:12,426 WARNING  django_auth_ldap Caught LDAPError while authenticating username: CONNECT_ERROR({'info': "TLS error -8172:Peer's certificate issuer has been marked as not trusted by the user.", 'desc': 'Connect error'},)
```

### PR DESCRIPTION
**Pull request by Numblesix**
##### SUMMARY
I added some Words on the variable ca_trust_dir

##### ISSUE TYPE
 - Docs Pull Request

##### COMPONENT NAME

 - Installer

##### AWX VERSION
```
'2.0.1'
```

##### ADDITIONAL INFORMATION
This should close #411 , as i guess the Documentation states some more details also the inventory now has better default

### CODE REVIEW

**Review by ryanpetrello — APPROVED** [review]

**Comment by ryanpetrello** [comment]
@Numblesix if you'll rebase this change with devel, I'll approve and merge it. Thanks!

**Comment by shanemcd** [comment]
regate

**Comment by ryanpetrello** [comment]
regate

**Comment by Numblesix** [comment]
@spredzy thanks :)!

**Pull request merged**
