### PR TITLE
add broadcast websocket status command

### PR DESCRIPTION
**Pull request by chrismeyersfsu**
wsbroadcast_stats

### CODE REVIEW

**Comment by ryanpetrello** [comment]
Fancy pants.

**Comment by ryanpetrello** [comment]
cc @gamuniz

**Review by ryanpetrello — APPROVED** [review]

**Comment by gamuniz** [comment]
Do we wanna exclude the current localhost as to not confuse any customer that happens to run this?

**Comment by chrismeyersfsu** [comment]
We do. This output is generated from being on the `awx-2` node. I added `awx` to simulate a down node and what that would look like. `awx-1` and `awx-3` are the other live nodes.

**Comment by gamuniz** [comment]
👍

**Comment by ryanpetrello** [comment]
@chrismeyersfsu can we make the `disconnected` red 😄 

```python
print("\033[91mred\033[0m")
```

image

If you feel so inclined, `92m` is green.

image

**Comment by chrismeyersfsu** [comment]
image

**Review by ryanpetrello — APPROVED** [review]
:shipit:

**Comment by chrismeyersfsu** [comment]
recheck

**Pull request merged**
