### PR TITLE
Removed forwardslash that was breaking paginated workflow node requests.

### LINKED ISSUE #4261: API Pagination broken on complex workflow visualizer
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
Line 139 on awx/ui/client/src/templates/templates.service.js contains a forward-slash in getWorkflowJobTemplateNodes that is interpreted as part of the pagesize integer (and thereby throwing an exception) when a complex workflow spans multiple pages of workflow nodes.
I think the bug may have been introduced when 'page_size=200' was added to the querystring in commit 700860e040ab7d2e944cad445f564c0822b9c45e.

##### ENVIRONMENT
* AWX version: 6.0.0
* AWX install method: docker on linux
* Ansible version:  2.8.1
* Operating System: Ubuntu 18.04
* Web Browser: Google Chrome 75.0.3770.100 64bit

##### STEPS TO REPRODUCE

1. Create a workflow with more than 200 nodes.
2. View in workflow visualiser

##### EXPECTED RESULTS

Workflow graphically rendered

##### ACTUAL RESULTS

An error is displayed and the workflow is not rendered.
"Call to /api/v2/workflow_job_templates/171/workflow_nodes/?page_size=200/&page=1 failed. GET returned status: 500. A server error has occurred."

##### ADDITIONAL INFORMATION

In theory, removing the forward-slash should fix this (and does in my own limited tests).
i.e. line 139 becomes "url += '&page=' + page;"

### PR DESCRIPTION
**Pull request by ghost**
The forward-slash in getWorkflowJobTemplateNodes was incorrectly interpreted as part of the pagesize integer (and thereby throwing an exception) when a complex workflow spanned multiple pages of workflow nodes.
Resolves: #4261
Signed-off-by: Dave Compton <sircompo@gmail.com>

##### SUMMARY
The forward-slash in getWorkflowJobTemplateNodes was incorrectly interpreted as part of the pagesize integer (and thereby throwing an exception) when a complex workflow spanned multiple pages of workflow nodes per request.

Related #4261

##### ISSUE TYPE
- Bugfix Pull Request

##### COMPONENT NAME
- UI

##### AWX VERSION
- Haven't set up a build environment for this I'm afraid. _If it's necessary please advise._

##### ADDITIONAL INFORMATION
Prior to this change, the following error is displayed if the workflow contains more than 200 nodes -
```
Call to /api/v2/workflow_job_templates/171/workflow_nodes/?page_size=200/&page=1 failed. GET returned status: 500. A server error has occurred.
```

### CODE REVIEW

**Review by jakemcdermott — APPROVED** [review]
code changes lgtm

**Review by jakemcdermott — APPROVED** [review]
@pebbledavec thanks for the contribution! We'll get this tested and merged.

**Comment by dsesami** [comment]
made a large workflow and launched this, looks great. Thanks for the fix!

**Comment by ghost** [comment]
> made a large workflow and launched this, looks great. Thanks for the fix!

My pleasure; I'm very proud to have contributed -1 character towards the project!

**Pull request merged**
